### ISSUE TITLE
Collecting metrics cause error logs

### ISSUE THREAD

**Issue by korjavin** [jaegertracing/jaeger-operator#1002]
I am getting log flooded by
```
WARNING: 2020/04/04 11:26:10 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client: \"GET /metrics HTTP/1.1\\r\\nH\""
WARNING: 2020/04/04 11:27:10 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client: \"GET /metrics HTTP/1.1\\r\\nH\"
```

If prometheus scrapping is on.

Any advice?

**Comment by objectiser** [comment]
@korjavin Are these from the operator or one of the Jaeger components? Can you provide the first part of the log (i.e. from start up) - and also information about how you install/configure your prometheus?

**Comment by korjavin** [comment]
It's from jaeger-collector
and it's because prometheus trying to collect metrics from it

**Comment by objectiser** [comment]
Can you provide the first part of the jaeger-collector's log please.

Do you use the jaeger operator to deploy the jaeger instance? If so, can you attach your CR.

What version of Jaeger operator/collector are you using?

How do you deploy and configure your prometheus server?
