### ISSUE TITLE
How to add a port to collector service

### ISSUE THREAD

**Issue by huikang** [jaegertracing/jaeger-operator#1017]
I notice that by default the operator creates the following ports for the collector' service

```
collector            ClusterIP   172.21.41.213    <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP                          69m
```

My question is that how to add 14269 to the service list because I need to check the health and metric of the collector like `curl http://localhost:14269/metrics `. The doc seems not have such example. Thanks.

**Comment by objectiser** [comment]
This was deliberate, as this port is for internal admin purposes. If you want to collect the metrics, then you can use a PodMonitor, as discussed in this article: https://developers.redhat.com/blog/2019/08/28/build-a-monitoring-infrastructure-for-your-jaeger-installation/

Alternatively you can create your own service to expose this port if you wish.
