### ISSUE TITLE
Private image registry how to config imagePullSecret

### ISSUE THREAD

**Issue by sherwinwangs** [jaegertracing/jaeger-operator#1018]
when deploy jaeger without internet,I pulled the related image to private harbor registry with login credentials, how to config the ImagePullSecret In operator or Jaeger CR.

**Comment by objectiser** [comment]
@sherwinwangs Currently this is not supported - would you be interested in contributing a PR? The image pull secrets could be added to the common spec part of the CRD, to enable the secrets to be defined either at the top level of the CRD (to be inherited by all components) or within the individual components.

**Comment by Saad-Hussain1** [comment]
@objectiser I also need this functionality and created https://github.com/jaegertracing/jaeger-operator/pull/1103 for this.

I keep running into this error with `make ensure-generate-is-noop` during the PR "basic-checks" though:
```
Build failed: a model has been changed but the generated resources aren't up to date. Run 'make generate' and update your PR.
make: *** [ensure-generate-is-noop] Error 1
##[error]Makefile:45: recipe for target 'ensure-generate-is-noop' failed
```

The command seems to work fine for me locally:
```
saad@Saads-MacBook-Pro: jaeger-operator$ pwd
/Users/saad/go/src/github.com/jaegertracing/jaeger-operator
saad@Saads-MacBook-Pro: jaeger-operator$ make generate
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [jaegertracing:[v1], kafka:[v1beta1], ] 
INFO[0019] Code-generation complete.                    
Formatting code...
pkg/client/versioned/clientset.go
pkg/client/versioned/fake/clientset_generated.go
pkg/client/versioned/fake/register.go
pkg/client/versioned/scheme/register.go
saad@Saads-MacBook-Pro: jaeger-operator$ git status
On branch add-imagePullSecrets
Your branch is up to date with 'saad/add-imagePullSecrets'.

nothing to commit, working tree clean
saad@Saads-MacBook-Pro: jaeger-operator$ make ensure-generate-is-noop
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [jaegertracing:[v1], kafka:[v1beta1], ] 
INFO[0019] Code-generation complete.                    
Formatting code...
pkg/client/versioned/clientset.go
pkg/client/versioned/fake/clientset_generated.go
pkg/client/versioned/fake/register.go
pkg/client/versioned/scheme/register.go
```

Would you happen to know what I might be missing?

**Comment by jpkrohling** [comment]
I think this has to do with the `GOPATH`. Could you please try unsetting `GOROOT` and `GOPATH`? You might need to run `make install-tools` afterwards, and use the newly installed `controller-gen`. For faster feedback, you can issue the following command directly:

```console
$ controller-gen crd paths=./pkg/apis/jaegertracing/... crd:maxDescLen=0,trivialVersions=true output:dir=./deploy/crds/
```

Once that is done, check the changes with `git diff`: the only changes should be your new field, like this:

https://github.com/jpkrohling/jaeger-operator/blob/add-imagePullSecrets/pkg/apis/jaegertracing/v1/zz_generated.openapi.go

**Comment by Saad-Hussain1** [comment]
Ah okay, that worked, thanks!

Let me know what might be needed to get this PR reviewed: https://github.com/jaegertracing/jaeger-operator/pull/1103

**Comment by Saad-Hussain1** [comment]
For anyone that comes across this in the future, see here: https://github.com/jaegertracing/documentation/pull/416/files

Namely,
> Note: If necessary, imagePullSecrets can be configured for components through their serviceAccounts (see https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-image-pull-secret-to-service-account). For the sidecar, see the [Deployment-level Configurations for Injected Sidecars](#deployment-level-configurations-for-injected-sidecars) section.

**Comment by jpkrohling** [comment]
Should this be closed? The PR has been merged, I believe we have all cases covered to get this working.
