### ISSUE TITLE
Jaeger-agent not exposing ports 6831/UDP 6832/UDP

### ISSUE THREAD

**Issue by chukynax** [jaegertracing/jaeger-operator#1020]
Trying to work with jaeger operator and hotrod demo app 

deployed simplest jaeger and apperead agent svc with no ip 
```
jaegertracing-jaeger-operator-jaeger-agent                ClusterIP   None            <none>        5775/UDP,5778/TCP,6831/UDP,6832/UDP                                                              5m54s
jaegertracing-jaeger-operator-jaeger-collector            ClusterIP   10.233.10.37    <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP                                                           5m54s
jaegertracing-jaeger-operator-jaeger-collector-headless   ClusterIP   None            <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP                                                           5m54s
jaegertracing-jaeger-operator-jaeger-query                ClusterIP   10.233.53.215   <none>        16686/TCP                                                                                        5m54s
jaegertracing-jaeger-operator-metrics                     ClusterIP   10.233.61.80    <none>        8383/TCP,8686/TCP    ```

**Comment by objectiser** [comment]
The jaeger-agent shouldn't be accessed via a service interface, as they may result in it being used over the network - as UDP is not reliable, this could lead to data loss.

Instead the agent should be used as a sidecar [via injection](https://www.jaegertracing.io/docs/1.17/operator/#auto-injecting-jaeger-agent-sidecars), [manually deployed](https://www.jaegertracing.io/docs/1.17/operator/#manually-defining-jaeger-agent-sidecars) or as a [daemonset](https://www.jaegertracing.io/docs/1.17/operator/#installing-the-agent-as-daemonset).
