### ISSUE TITLE
Update CI builds to use latest Ubuntu and Minikube

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#1021]
The CI builds run on Github actions had been using an old version of minikube (1.3.1).  PR #1019 updates that to 1.5.2, but as of April 2020 version 1.9.2 is available.  That PR also changes the Ubuntu version from ubuntu-latest (currently 18.04) back to 16.04.

These changes were required because of the following issue: https://github.com/kubernetes/kubernetes/issues/66067  There is more information on this here: https://github.com/kubernetes/kubernetes/pull/80591 and https://coredns.io/plugins/loop/#troubleshooting

Updating to the latest versions of everything will require DNS changes to the docker and/or minikube installations.

**Comment by objectiser** [comment]
Resolved by #1019

**Comment by kevinearls** [comment]
@objectiser Could you re-open this?  This is actually not covered by 1019, but is something I want to do in the future.

**Comment by objectiser** [comment]
@kevinearls Sorry :)

**Comment by jpkrohling** [comment]
Should I assign this to you, @kevinearls ?

**Comment by kevinearls** [comment]
@jpkrohling Sure
