### ISSUE TITLE
Jaeger UI - Service list is empty

### ISSUE THREAD

**Issue by ernaldobr** [jaegertracing/jaeger-operator#1028]
Hello everyone,

I´m a new Jaeger user.

On my Jaeger UI a **Service** list is empty.

The Jaeger runs on Kubernetes and jaeger-operator version is 1.16.0.

At log of **jaeger-operator** i see this:
`time="2020-04-17T18:05:45Z" level=info msg=Versions arch=amd64 identity=psc-jaeger-operator.khm-jaeger-operator jaeger=1.16.0 jaeger-operator=v1.16.0 operator-sdk=v0.12.0 os=linux version=go1.13.3
time="2020-04-17T18:06:07Z" level=info msg="Auto-detected the platform" platform=kubernetes
time="2020-04-17T18:06:07Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2020-04-17T18:06:07Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2020-04-17T18:06:07Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2020-04-17T18:06:09Z" level=warning msg="could not generate and serve custom resource metrics" error="discovering resource information failed for Jaeger in jaegertracing.io/v1: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: Unauthorized"
time="2020-04-17T18:06:15Z" level=warning msg="could not create ServiceMonitor object" error="unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: Unauthorized"`

At log of **jaeger-operator-jaeger-agent-daemonset** i see many records as same this:
`{"level":"info","ts":1587394019.8246229,"caller":"grpc/resolver_conn_wrapper.go:222","msg":"ccResolverWrapper: error parsing service config: no JSON service config provided","system":"grpc","grpc_log":true}`

Can someone help me?
Thanks.

**Comment by ernaldobr** [comment]
Sorry friends. 
I read the log more carefully and saw it:
"The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
I will adjust this and report here.

**Comment by IuriGarcia** [comment]
@ernaldobr Sorry, but , i got the same issue, tryed to create a separate new cluster-role-binding, but it has failed.
