### ISSUE TITLE
Error "The resourceVersion for the provided watch is too old"

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#103]
When the operator is running for an extended period of time, the following message is shown:

```
ERROR: logging before flag.Parse: W1109 09:42:04.207951   16079 reflector.go:341] github.com/jaegertracing/jaeger-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:91: watch of *unstructured.Unstructured ended with: unexpected object: &{map[code:410 kind:Status apiVersion:v1 metadata:map[] status:Failure message:The resourceVersion for the provided watch is too old. reason:Expired]}
```

This was seen on OpenShift but might happen with plain Kubernetes as well:

```
$ minishift status
Minishift:  Running
Profile:    istio-tutorial
OpenShift:  Running (openshift v3.10.0+349c70c-73)
DiskUsage:  23% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 2.363 GB (used by oc binary, ISO or cached images)
$ oc version
oc v3.11.0-rc.0+0cbc58b
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.155:8443
openshift v3.10.0+349c70c-73
kubernetes v1.10.0+b81c8f8
```

For those who might be experiencing this as well: please leave a comment with the output from `minikube version` + `kubectl version` (or `minishift version` + `oc version`).

**Comment by gbaufake** [comment]
Facing the same issue on https://github.com/kiali/kiali-test-mesh/pull/41

**Comment by objectiser** [comment]
@gbaufake Could you provide the details @jpkrohling mentions at the end of the initial description? Thanks.

**Comment by gbaufake** [comment]
@objectiser Updated my previous comment.

**Comment by jpkrohling** [comment]
I haven't seen this in a while. I'm closing, but feel free to reopen if this occurs again.
