### ISSUE TITLE
Change upgrade mechanism to leverage semver

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#1031]
Currently the upgrade mechanism is using a state transition approach. This means that whenever there is a new version, this table needs to be updated (as well as the `latest` pointer).

If we changed this mechanism to be based on semver, then we only need to create a list of versions where a change is required (so only update when a change is necessary).

We should also set the latest version based on the `DefaultJaeger` version that is supplied as part of the binary build.

**Comment by rubenvp8510** [comment]
I'm working on an update to 1.18 Can I work on this one too?  I think this will help to make updates  more testeable.

**Comment by objectiser** [comment]
@rubenvp8510 Its all yours.

cc @jpkrohling , in case you have any objections to the change in approach.
