### ISSUE TITLE
Put more thought on passing refs vs. value

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#104]
On the early days of the operator, it was easier to just pass references around. Unfortunately, this is not always appropriate and gives too much power to the function being called, as it can change the object in ways the caller isn't expecting.

A first thing to assess is whether we can change the places where we are using `*v1alpha1.Jaeger` to use values instead. It would mean that some functions will have its signature changed, like the `controller.normalize(*v1alpha1.Jaeger)`, so that it returns a changed normalized object instead of changing it in-place.

**Comment by jpkrohling** [comment]
Marking this as "question", as it would be good to have a discussion about it before doing any code changes.

**Comment by objectiser** [comment]
I think this sounds like a good idea.
