### ISSUE TITLE
CRDs not created on OpenShift 3.11

### ISSUE THREAD

**Issue by omertsur** [jaegertracing/jaeger-operator#1040]
I am trying to install the CRDs on my Opensfhit environment (version 3.11) and I receive the following [error](https://pastebin.com/nJ4RtNdE). I tried both from the UI and the CLI, same result.

**Comment by objectiser** [comment]
Can you provide details of which version of the Jaeger operator you are using, and how it was installed?

**Comment by omertsur** [comment]
I am using the latest jaeger operator version (1.17.1) and it is yet to be installed because I can't load the aforementioned CRDs (I followed the guide in the README, and the first step is to load the templates, with the CRD's template being the first item)

**Comment by objectiser** [comment]
Have you previously been able to install a different version of the CRD?

**Comment by omertsur** [comment]
It's the first time I tried to install said resource, I haven't tried any version prior to 1.17.1

**Comment by objectiser** [comment]
It appears to be a known issue on OpenShift 3.11, a suggestion solution can be [found here](https://github.com/datastax/labs/issues/18#issuecomment-562671178).

**Comment by omertsur** [comment]
Thanks, It seemed to solve the issue!
