### ISSUE TITLE
Run e2e tests with Jaeger OpenTelemetry collector

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#1041]
Run e2e tests with https://hub.docker.com/repository/docker/jaegertracing/jaeger-opentelemetry-collector image.

In future there will be also OpenTelemetry based ingester and agent images. Those will have to be used in tests too.

**Comment by pavolloffay** [comment]
These tests should be run as additional parallel jobs in the current CI.

**Comment by jpkrohling** [comment]
Closing, as this is not relevant anymore.
