### ISSUE TITLE
Ingress for sampling/spans from VMs

### ISSUE THREAD

**Issue by chlunde** [jaegertracing/jaeger-operator#1044]
In brownfield deployments some components might still run on VMs. It would be nice if the either the  operator could configure an ingress for sampling/spans, or at least the setup could be documented. 

For the VM side, a documented way to run jaeger-agent and configure it to point to. UDP from the agent to the collector is probably a no-go. Maybe the docs could have example systemd units for running jaeger agent with podman on a VM, or an ansible playbook.

**Comment by chlunde** [comment]
This gist from @sallyom might be very relevant: https://gist.github.com/sallyom/d2841ec66b3fe6813de2809f5fb90512

**Comment by jpkrohling** [comment]
I documented how to run the Jaeger Agent in bare metal some time ago: https://medium.com/jaegertracing/running-jaeger-agent-on-bare-metal-d1fc47d31fab . Is this what you need?

**Comment by chlunde** [comment]
Thanks for the article, it articulates better the purpose of the agent than I had seen earlier.

I haven't had time to work on implementing this yet. I think this is almost a duplicate of #1048, so I will close this issue.

My concerns/thoughts were:
* What is the most common way to implement this? I like to keep our setup close to a "best practice" when possible so having a documented setup which most users follow is nice.
* How do we best deploy/distribute and update for the agent deployed outside? Running as a container is therefore somewhat tempting.
* For a Java based process, I'm not sure if TCP vs. UDP is really something to worry about. Java based processes consume lots of RAM anyway, so the memory consumption for a slow/non-responsive TCP upstream is not really significant. I also expect the client library to have some resilience.

So, in the end I think we will probably manually set up a Route using flux, it's not an issue in our setup.
