### ISSUE TITLE
Provider "SPI"

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#106]
As part of #100, a SPI is desirable so that provider-specific features are added to Jaeger instances.

Two things that can benefit from it right now are:

- OAuth Proxy
- Routes vs. Ingress

One idea is to have a "pipeline": on a first pass, the basic objects are assembled. Then, the set of objects are passed to a provider-specific pipeline, which transforms the received objects and return a new set. This new set is then effectively passed down to the SDK.

**Comment by pavolloffay** [comment]
Closing, there was no interest in the SPI
