### ISSUE TITLE
Host Kubernetes all-in-one.yaml manifest in the operator repository

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#1064]
Jaeger operator 1.18 introduced a feature that generates k8s manifest files from the supplied CR file https://github.com/jaegertracing/jaeger-operator/#experimental-generate-kubernetes-manifest-file. 

I propose to host the generated manifest file directly in the repository - either in the examples dir or as part of the release distribution. 

The motivation for this is to fully deprecate https://github.com/jaegertracing/jaeger-kubernetes. There are still people using the all-in-one manifests, but as it is unmaintained the manifests are outdated.

**Comment by objectiser** [comment]
If it is generated, then we would need documentation (probably in this repo and the jaeger-kubernetes repo) to point to it. Instead, wouldn't it be just as easy to document the command for generating the manifest?

**Comment by pavolloffay** [comment]
The command should be already in the readme. Maybe we can just make the repository read-only and encourage users to generate the manifest they need. 

Hosting a manifest in the repository makes it easy for people to just "grab" it and deploy. To keep things simple I think we should host only the all-in-one for quick demo purposes.

**Comment by objectiser** [comment]
> Maybe we can just make the repository read-only and encourage users to generate the manifest they need.

We definitely need to be more explicit in the jaeger-kubernetes repo - so readonly +1, make the readme more explicit that the repo is no longer maintained and document the alternatives, including the helm-charts repo.

**Comment by pavolloffay** [comment]
Actually the output from generate can be piped to the `kubectl apply`

```bash
curl https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/examples/simplest.yaml | docker run --rm jaegertracing/jaeger-operator:master generate | kubectl apply -n jaeger-test -f -
```

Hence we might not need to host the manifest here. Consumers will have to install `docker`, but that is already a standard tooling :). 

I will update readme in the k8s repo and point them to the generate command in the operator.

**Comment by pavolloffay** [comment]
I am closing this for now. If somebody thinks that the manifest should be hosted please comment on this issue or create a new one.
