### ISSUE TITLE
Kubernetes:Error: no Jaeger pods found 

### ISSUE THREAD

**Issue by tanjunchen** [jaegertracing/jaeger-operator#1073]
see  https://istio.io/docs/tasks/observability/distributed-tracing/jaeger/#before-you-begin

Is there Jaeger  Pods?

```
a production environment by referencing an existing Jaeger instance, e.g. created with the operator, and then setting the --set values.global.tracer.zipkin.address=<jaeger-collector-service>.<jaeger-collector-namespace>:9411 install option.
```

How to define the jaeger-collector-service 、jaeger-collector-namespace

**Comment by objectiser** [comment]
Hi @tanjunchen , you will need to create an issue in the istio repo, as this may be a configuration issue with their installer.
