### ISSUE TITLE
Modify elasticsearch index template for spans

### ISSUE THREAD

**Issue by romil-punetha** [jaegertracing/jaeger-operator#1077]
Currently, the span template `*jaeger-spans*` has a fixed manifest. I tried updating it but saw that it restores itself after some time. There are certain optimisations mentioned in the elasticsearch website to speed up indexing speed, like increasing refresh interval (since I'm never going to search for an immediately created span). It would be good if I could define some modifications to the fields in the span template.

**Comment by pavolloffay** [comment]
> I tried updating it but saw that it restores itself after some time.
