### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by rur0** [jaegertracing/jaeger-operator#1086]
Hello, I am attempting to run jaeger operator on my 8x RPI 4 kubernetes (k3s) cluster running on ubuntu server (64 bit) and I'm getting the fun 
```standard_init_linux.go:211: exec user process caused "exec format error"``` 
error.

Is there a simple way of running jaeger operator on arm64 hardware?

thanks

**Comment by rur0** [comment]
I've added multiarch build support here https://github.com/rur0/jaeger-operator but haven't tested it yet

**Comment by rur0** [comment]
jaeger-operator compiles and runs fine on ARM64, however when the operator pulls the main jaeger image, its getting a 'exec format error.'

@jpkrohling you have mentioned that there are ARM images on the main project; would it be possible to upload them to the docker repo with multiarch support using manifests?

**Comment by jpkrohling** [comment]
I think it was done as part of https://github.com/jaegertracing/jaeger/pull/2176 . At a first glance, I couldn't find the images at Docker Hub. @pavolloffay you seem to have reviewed that PR: do you know whether ARM images should be available?

**Comment by pavolloffay** [comment]
The multiarch images are not built or published. 

The https://github.com/jaegertracing/jaeger/pull/2176 added:
* arm64 build to release archive
* refactored build for easier multiarch builds - perhaps we could do the same in the operator.

We should open a new issue in the main repo to publish multiarch images.

**Comment by yurishkuro** [comment]
I think this is fixed by https://github.com/jaegertracing/jaeger/pull/2948. Please reopen if still a problem.
