### ISSUE TITLE
can i write jaeger-ingester to an another backend like redis 

### ISSUE THREAD

**Issue by habeebshk** [jaegertracing/jaeger-operator#1090]
Hello, I am trying to install Jaeger onto my Kubernetes cluster and i would like to know if i can direct the Jaeger-ingester spans storage to an another database like Redis instead of Elasticsearch or Cassandra.

**Comment by pavolloffay** [comment]
Hi, there is no redis integration at the moment. For the support of other storage backends see https://github.com/jaegertracing/jaeger/issues/638

**Comment by nicolastakashi** [comment]
Hey, @habeebshk I just finish an implementation to store trace data on Redis Search.
You can find more information here: https://github.com/nicolastakashi/jaeger-redissearch

I still need to improve documentation and build docker images, but I'm currently testing on my dev environments to check how it goes.
