### ISSUE TITLE
Use Elasticsearch Operator 4.5

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#1098]
Use ES operator 4.5 in makefile. Note that ES manifests are no longer maintained, hence we should default to deploying the ES operator via OLM.

**Comment by jpkrohling** [comment]
Not sure OLM is something we can require for people on plain Kubernetes. I do see it as an addon for minikube, but not sure people actually use it...

**Comment by pavolloffay** [comment]
The ES operator used by Jaeger is only supported on OpenShift. 

At the moment `deploy-es-operator` target in the Makefile uses plain k8s manifest files to deploy the ES operator with all the objects https://github.com/jaegertracing/jaeger-operator/blob/master/Makefile#L188. In the version 4.5 this is not supported anymore and we should use the OLM to provision ES operator.
