### ISSUE TITLE
Update Docker image when a PR is merged

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#11]
Whenever a PR is merged, it would be good to generate a new Docker image and push to Docker Hub under the latest version tag (like, 1.6.CI_BUILD_NUM + 1.6)

**Comment by jpkrohling** [comment]
At least for this stage, it would be beneficial to have a continuous delivery of the operator. If we are able to keep backwards compatibility, I don't see a reason why not to do it :)

**Comment by jpkrohling** [comment]
> If used from a helm chart, what version of the operator would be used? latest?

No, 1.6, but we would be pushing the image to the 1.6 "stream". If we aren't satisfied with that, we just change how we publish the changes, without changing the chart.

**Comment by objectiser** [comment]
So the aim would be to have a parallel "stream" alongside the version used in the main jaeger repo?

**Comment by jpkrohling** [comment]
I'm not sure yet about how to version the operator. My first instinct would be to have the same version numbers as the image it deploys by default, so, we would indeed have a parallel stream of fixes for the operator.

Note that this is not about tagging the code.
