### ISSUE TITLE
Enable health check port to be supplied as CLI flag

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#1108]
Currently the Jaeger backend components have their own health check ports. The OpenTelemetry Collector based images use port `13133`.

Until the operator is switched over fully to use the new container images (and health check port), it would be useful to support an operator CLI flag that can override the collector and ingester health check ports, to use the OTel Col one when the OTel Col based images are being used.

**Comment by pavolloffay** [comment]
Is this necessary? The same can be achieved by overriding the HC port in the OTEL config. We already advise users to do that https://www.jaegertracing.io/docs/1.18/opentelemetry/#jaeger-operator

**Comment by objectiser** [comment]
It would be useful when the otel-collector based images are supplied via CLI flags - so that the user does not need to be aware of these specific details.

**Comment by jpkrohling** [comment]
Is the operator able to automatically detect if the operand is based on OpenTelemetry Collector?

**Comment by objectiser** [comment]
Closing, as only an issue during the transition - so not worth adding CLI flag.
