### ISSUE TITLE
Convert storage type to typed string

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#111]
The JaegerStorageSpec currently has the storage type as a string:

https://github.com/jaegertracing/jaeger-operator/blob/02ba08a3300bd2425e524098a3315e9e85c69e64/pkg/apis/io/v1alpha1/types.go#L111

It would be better to have a typed string like we have for the IngressSecurityType:

https://github.com/jaegertracing/jaeger-operator/blob/02ba08a3300bd2425e524098a3315e9e85c69e64/pkg/apis/io/v1alpha1/types.go#L8-L26

https://github.com/jaegertracing/jaeger-operator/blob/02ba08a3300bd2425e524098a3315e9e85c69e64/pkg/apis/io/v1alpha1/types.go#L83

**Comment by objectiser** [comment]
Only thing to consider is whether this would cause a problem if we have a more decoupled plugin model?

**Comment by SezalAgrawal** [comment]
Can I pick this task?

**Comment by jpkrohling** [comment]
It's yours!
