### ISSUE TITLE
How do I enable the .jaeger-compact.server-host-port 6831 for the collector in streaming strategy

### ISSUE THREAD

**Issue by huikang** [jaegertracing/jaeger-operator#1112]
Hi, is there any example to enable port 6831 in the streaming strategy? And is it possible to expose the collector service through "NodePort" as I'd like to have some external applications send trace to the collector? Thanks.

In general, I feel the documentation for configuring the operator is inadequate. Thanks.

**Comment by jpkrohling** [comment]
The port 6831 is a UDP port that is opened by the agent, not by the collector. The agent is typically deployed as either a sidecar to your pod, or as a daemonset. In general, flags can be set via the `Options` properties: 

```yaml
spec:
  collector:
    options:
      some.flag.for.the.collector.binary: value
```

Besides this specific part, what could we improve in the [official documentation](https://www.jaegertracing.io/docs/1.18/operator/)? We would love your PRs (here's the source: https://github.com/jaegertracing/documentation/blob/master/content/docs/next-release/operator.md)

**Comment by jpkrohling** [comment]
Feel free to reopen if you still have questions.

**Comment by huikang** [comment]
@jpkrohling , thanks for the clarification. So I will deploy a jaeger agent to accept trace at its port 6831. The second question in the post is about exposing the port of the collector of streaming strategy.

I am asking because the application and agent are deployed out of the k8s cluster, so I need to expose port 14250 of the collector so that it can accept traces from the agent. Is there a way to configure this? Thanks.

**Comment by jpkrohling** [comment]
The typical way of achieving this is by creating an `Ingress` resource that will expose the `-collector` service.

**Comment by huikang** [comment]
My understanding is that Ingress operates above layer 4. So will that work with the exposing port 14250 for the traffic between agent and collecot?

BTW, could you please take a look at another question at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jaeger-tracing/rNU1xKVZuGI/2yX1RfT1AgAJ

Thanks.

**Comment by jpkrohling** [comment]
> So will that work with the exposing port 14250 for the traffic between agent and collecot?

It should. But open another issue if you see a concrete problem.
