### ISSUE TITLE
Sidecar injection cannot find appropriate Jaeger instance

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1116]
When adding a Jaeger instance to the current namespace, I would expect the Operator to use that instance when injecting sidecars into deployments. Instead, the operator reports that it cannot find a suitable instance:

```console
$ kubectl apply -f deploy/examples/business-application-injected-sidecar.yaml 
deployment.apps/myapp created

$ kubectl logs deployments/jaeger-operator -n openshift-operators 
...
time="2020-07-06T12:29:16Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=myapp jaeger=jaeger jaeger-namespace=istio-system namespace=istio-system

$ kubectl delete deployment myapp
deployment.apps "myapp" deleted

$ kubectl apply -f deploy/examples/simplest.yaml 
jaeger.jaegertracing.io/simplest created

$ kubectl get jaegers
NAME       STATUS    VERSION   STRATEGY   STORAGE   AGE
simplest   Running   1.17.3    allinone   memory    8s

$ kubectl apply -f deploy/examples/business-application-injected-sidecar.yaml 
deployment.apps/myapp created

$ kubectl logs deployments/jaeger-operator -n openshift-operators
...
time="2020-07-06T12:35:30Z" level=info msg="No suitable Jaeger instances found to inject a sidecar" deployment=myapp
```

Workaround: changing the annotation value from `true` to `simplest` makes it correctly inject the sidecar:

```console
$ kubectl logs deployments/jaeger-operator -n openshift-operators
time="2020-07-06T12:39:12Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=myapp jaeger=simplest jaeger-namespace=bookinfo namespace=bookinfo
```

Environment:
```
$ oc version
Client Version: 4.4.9
Server Version: 4.4.9
Kubernetes Version: v1.17.1+912792b

$ kubectl logs deployments/jaeger-operator -n openshift-operators | head
time="2020-07-06T11:27:29Z" level=info msg=Versions arch=amd64 identity=openshift-operators.jaeger-operator jaeger=1.17.3 jaeger-operator=1.17.3.redhat6 operator-sdk=v0.15.1 os=linux version=go1.13.4
```

cc @rubenvp8510

**Comment by rubenvp8510** [comment]
Is this happening when you have two operators, one on `openshift-operators `namespace and other in the same namespace as your application? If there is only one operator this issue still happens?

**Comment by jpkrohling** [comment]
It happens also when there's only one operator. It happened to me when testing [TRACING-1300](https://issues.redhat.com/browse/TRACING-1300), but I'm sure it can be reproduced in simpler settings as well.

**Comment by rubenvp8510** [comment]
@jpkrohling Sorry my mistake, not two operators, but two instances of jaeger in different namespaces, I was able to reproduce it creating first one instance in other namespace, and then other jaeger instance in the same namespace of the app.

Those are the steps I followed:
```
oc create namespace otherns
oc apply -f  deploy/examples/simplest.yaml -n otherns
oc create namespace myapp
oc apply -f deploy/examples/simplest.yaml -n myapp
oc apply -f deploy/examples/business-application-injected-sidecar.yaml -n myapp
```

I sent a PR that should fixes this case, also added a couple of tests.

**Comment by jpkrohling** [comment]
I'll try again, but IIRC, this happened also when there was only one Jaeger instance in the cluster.
