### ISSUE TITLE
Permissions for apps/deployments is repeated

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1130]
Context: https://github.com/jaegertracing/jaeger-operator/pull/1126#discussion_r452766704

**Comment by husnialhamdani** [comment]
Hi @jpkrohling,
I interested to work on this, Could you please assign to me?

**Comment by husnialhamdani** [comment]
Hi @jpkrohling,
Is it to remove the `verbs=create` of resources `Deployment` in stated in `+kubebuilder:rbac:groups..` in the controller?
Could you please advise?

**Comment by husnialhamdani** [comment]
@iblancasa is my understanding correct? 

> Hi @jpkrohling, Is it to remove the `verbs=create` of resources `Deployment` in stated in `+kubebuilder:rbac:groups..` in the controller? Could you please advise?

**Comment by iblancasa** [comment]
> @iblancasa is my understanding correct?
> 
> > Hi @jpkrohling, Is it to remove the `verbs=create` of resources `Deployment` in stated in `+kubebuilder:rbac:groups..` in the controller? Could you please advise?

I'm not sure TBH.
