### ISSUE TITLE
`make install-tools` installs latest tools (wrong version)

### ISSUE THREAD

**Issue by chlunde** [jaegertracing/jaeger-operator#1134]
If I run `make install-tools` and `make generate`, I get a different version of controller-gen (and problably more):
```diff
--- a/deploy/crds/jaegertracing.io_jaegers_crd.yaml
+++ b/deploy/crds/jaegertracing.io_jaegers_crd.yaml
@@ -2,7 +2,7 @@ apiVersion: apiextensions.k8s.io/v1beta1
 kind: CustomResourceDefinition
 metadata:
   annotations:
-    controller-gen.kubebuilder.io/version: v0.2.4
+    controller-gen.kubebuilder.io/version: v0.3.0
```
...
```diff
@@ -600,11 +601,19 @@ spec:
                   properties:
                     limits:
                       additionalProperties:
-                        type: string
+                        anyOf:
+                        - type: integer
+                        - type: string
+                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
+                        x-kubernetes-int-or-string: true
                       type: object
```

```diff
diff --git a/pkg/client/versioned/clientset.go b/pkg/client/versioned/clientset.go
index 6850e3c7..f63063e4 100644
--- a/pkg/client/versioned/clientset.go
+++ b/pkg/client/versioned/clientset.go
@@ -44,7 +44,7 @@ func NewForConfig(c *rest.Config) (*Clientset, error) {
        configShallowCopy := *c
        if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
                if configShallowCopy.Burst <= 0 {
-                       return nil, fmt.Errorf("Burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
+                       return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
                }
                configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
        }

```

**Comment by chlunde** [comment]
# `tools.go`
```
// +build tools

// Place any runtime dependencies as imports in this file.
// Go modules will be forced to download and install them.
package tools
```

Maybe they can be added here to get them into go.mod, but the operator-sdk might have a reference how to solve this issue.

**Comment by jpkrohling** [comment]
If we add it to `tools.go`, it gets incorporated into the binary, which isn't something we want. Can't we add the version to the `go install` package argument?

https://github.com/jaegertracing/jaeger-operator/blob/82b197b68bfde3f8d0f550e11ac926f055313dc5/Makefile#L316-L324

**Comment by chlunde** [comment]
I don't think it will be part of the binary because of the +tools build tag trick, but I have never used it.

Once tried to solve this issue by adding @vX.Y.Z behind every line, but there are some issues:

* You must use `go get`, not `go install`:
  ```
  $ go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.4
  can't load package: package sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.4: can only use path@version syntax with 'go get'
   ```
* `go get` will modify `go.mod`/`go.sum`, so you must cd outside GOPATH *and* outside an existing go module. Also, since you do not have a `go.mod` you must set `GO111MODULE=on`.. so it becomes `(cd /; GO111MODULE=on go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.4)` (or some other file system path you know is not part of a go module, but /tmp is probably not safe)
* I *think* sometimes you must also split it to one tool per execution to avoid for example mixing dependency versions from tool A and tool B. That might also be an issue with tools.go actually...

At this point, I thought it I had too many hacks I had never seen anyone else use, so I thought maybe the `tools.go` alternative would be better...

**Comment by jpkrohling** [comment]
> because of the +tools build tag trick, but I have never used it.

Oh! I totally missed that. That makes perfect sense now.

**Comment by jpkrohling** [comment]
@chlunde would you like to send a PR for this?

**Comment by chlunde** [comment]
@jpkrohling sorry I need to prioritize right now :) But in general I would say switching between two operator-sdk tools is painful because when they rely on tool X and Y in different versions in $PATH
