### ISSUE TITLE
Figure out what's wrong with the CI

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1137]
The `minikube` step usually takes about a couple of minutes, but it's now getting stuck "forever", eventually getting the job killed due to a timeout somewhere.

The ticket #774139 has been opened with GitHub, but their support isn't the fastest in the world, so, we might need to figure out an alternative.

Currently, the following PRs are affected: #1136, #1133 and #1045.

**Comment by kevinearls** [comment]
@jpkrohling I saw this over the weekend: https://twitter.com/githubstatus/status/1284405893891870720

**Comment by jpkrohling** [comment]
Seems to have been fixed on Jul 18, 2020 - 11:02 UTC , and we are still experiencing this. I started #1136 again this morning and it seems to be stuck again.

**Comment by jpkrohling** [comment]
Apparently, things started working again...

**Comment by jpkrohling** [comment]
Closing, as it's now working for quite some time.
