### ISSUE TITLE
Use an HTTP(S) proxy before all Elasticsearch requests

### ISSUE THREAD

**Issue by clementlesne** [jaegertracing/jaeger-operator#1141]
Hello,

As a context, I'm working on OpenShift, and I'm trying to install the Jaeger Operator. My pods have no direct access to internet, and they need to pass across an internet proxy to communicate with others networks.

**How can I configure Jaeger with an HTTP/HTTPS proxy ?** I've been looking across all documentation and project issues but I haven't found this answer.

Usually one environment variable is sufficient.

Regards,

**Comment by jpkrohling** [comment]
I don't think we ever even thought about this case. Unless there's something at the go-level, I'd say that we don't currently support that. I'm leaving this open for two reasons:

1. to gauge interest in this feature from other people
1. perhaps there is indeed a go-level option that we can use and I don't know about?

**Comment by chlunde** [comment]
I think this _could_ be handled by allowing setting environment variables, more specifically `HTTP(S)_PROXY` and `NO_PROXY`.

This is backed by this package:
https://pkg.go.dev/golang.org/x/net/http/httpproxy#Config
