### ISSUE TITLE
jaeger operator fails to pull image for 1.17.5

### ISSUE THREAD

**Issue by daufinsyd** [jaegertracing/jaeger-operator#1143]
Hello

On openshift, the jaeger operator tried to update itself 1.17.5 provided by Red Hat but is failing to do so because of the following error:

`Failed to pull image "registry.redhat.io/distributed-tracing/jaeger-rhel7-operator@sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50": rpc error: code = Unknown desc = Error reading manifest sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50 in registry.redhat.io/distributed-tracing/jaeger-rhel7-operator: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>\nAn error occurred while processing your request.<p>\nReference&#32;&#35;132&#46;eb161002&#46;1595400530&#46;9465762\n</BODY></HTML>\n"`

I tried to pull it form a bastion but get the same error: 
`$ podman pull registry.redhat.io/distributed-tracing/jaeger-rhel7-operator@sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50 
Trying to pull registry.redhat.io/distributed-tracing/jaeger-rhel7-operator@sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50...ERRO[0004] Error pulling image ref //registry.redhat.io/distributed-tracing/jaeger-rhel7-operator@sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50: Error initializing source docker://registry.redhat.io/distributed-tracing/jaeger-rhel7-operator@sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50: Error reading manifest sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50 in registry.redhat.io/distributed-tracing/jaeger-rhel7-operator: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>\nAn error occurred while processing your request.<p>\nReference&#32;&#35;132&#46;c3161002&#46;1595401950&#46;910bdf80\n</BODY></HTML>\n"
Failed
Error: error pulling image "registry.redhat.io/distributed-tracing/jaeger-rhel7-operator@sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50": unable to pull registry.redhat.io/distributed-tracing/jaeger-rhel7-operator@sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50: unable to pull image: Error initializing source docker://registry.redhat.io/distributed-tracing/jaeger-rhel7-operator@sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50: Error reading manifest sha256:3eeed89119c20386161bc464136ccdeb98e99b2c40883f70d6cd2e6c742c0a50 in registry.redhat.io/distributed-tracing/jaeger-rhel7-operator: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>\nAn error occurred while processing your request.<p>\nReference&#32;&#35;132&#46;c3161002&#46;1595401950&#46;910bdf80\n</BODY></HTML>\n"`

Is the operator bad configured ?

Thanks
Regards
Sydney

**Comment by objectiser** [comment]
@daufinsyd Thanks for reporting this - the issue is being addressed. However, Red Hat operator issues should be raised through the Red Hat support channels as this is the open source community project repo.
