### ISSUE TITLE
How to skip hostname verification from server for wss

### ISSUE THREAD

**Issue by CVVDN-S** [jaegertracing/jaeger-operator#1145]
Hi, I'm trying wss server support with the help of libwebsocket with self signed certificate. These are the configurations done at server side.
```
if(use_ssl == 1) {
                sprintf(cert_path, "/system/bin/server_cus_cer.cer");
                sprintf(key_path, "/system/bin/server_cus_key.key");

                info.ssl_cert_filepath = cert_path;
                info.ssl_private_key_filepath = key_path;

                info.port = 443;
                info.ssl_cipher_list = NULL;
                info.options |= LWS_SERVER_OPTION_REDIRECT_HTTP_TO_HTTPS;
                info.options |= LWS_SERVER_OPTION_VALIDATE_UTF8;
        }
```
It works good with firefox, with any ssl certificates.  But in IE **Network Error 12038, The host name in the certificate is invalid or does not match** seems to appear since my device have static ips which can change according to user.
If an static ip is used for Common Name while certificate generation then it will work at first and if I change the IP, error seems to come back.

I tried the following methods:
1) tried to disable the option in IE tools, warn about the hostname mismatch
2) tried to generate wildcard certificates still no hope

Is there any options available that need to be added in Sever for this error to be rectified?

**Comment by jpkrohling** [comment]
I'm a bit confused: we don't use web sockets at all in Jaeger. Are you sure you opened this against the right project?

**Comment by CVVDN-S** [comment]
Sorry about the confusion in the project.
