### ISSUE TITLE
Jaeger Operator Generate manifest feature always creates same pod/file

### ISSUE THREAD

**Issue by sundar-cs** [jaegertracing/jaeger-operator#1150]
This is about the "(experimental) Generate Kubernetes manifest file" feature documented in the official link https://github.com/jaegertracing/jaeger-operator.

What is the role of the standard input passed into "docker run ... generate" as no matter which file is supplied as input, the pod getting generated appears to be same as the Operator's master image tag ?

(1)
_curl https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/examples/**simplest.yaml** | docker run --rm jaegertracing/jaeger-operator:master generate | kubectl apply -n jaeger-test -f -_
and then get the pod's yaml:
_kubectl get pod my-jaeger-7bdd6bfbcc-gdwmn -n jaeger-test -o yaml > jaeger-operator-**instance-simplest**.yaml.txt_

Now delete the above deployment and move onto #2 below

(2)
_curl https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/examples/**with-sampling.yaml** | docker run --rm jaegertracing/jaeger-operator:master generate | kubectl apply -n jaeger-test -f -_
and then get the pod's yaml:
_kubectl get pod my-jaeger-7bdd6bfbcc-kg74w -n jaeger-test -o yaml > jaeger-operator-**instance-with-sampling**.yaml.txt_

Now delete the above deployment and move onto #3  below

(3)
_docker run --rm jaegertracing/jaeger-operator:master generate | kubectl create -n jaeger-test -f -_
and then get the pod's yaml:
_kubectl get pod my-jaeger-7bdd6bfbcc-qbbx4 -n jaeger-test -o yaml > jaeger-operator-**no-instance**.yaml.txt_

Now delete the above deployment and compare the three generated files.
They appear to be the same (except for the pod name etc).
The same effect can be observed by directly storing the resultant yaml files (redirect the output into a file) bypassing "kubectl apply" (i.e. no need to perform the kubectl apply as such).

The output files are attached.
[jaeger-operator-instance-simplest.yaml.txt](https://github.com/jaegertracing/jaeger-operator/files/5040652/jaeger-operator-instance-simplest.yaml.txt)
[jaeger-operator-instance-with-sampling.yaml.txt](https://github.com/jaegertracing/jaeger-operator/files/5040653/jaeger-operator-instance-with-sampling.yaml.txt)
[jaeger-operator-no-instance.yaml.txt](https://github.com/jaegertracing/jaeger-operator/files/5040654/jaeger-operator-no-instance.yaml.txt)

**Comment by jpkrohling** [comment]
This is probably related to #1129, which hasn't been released yet. Are you able to try this out from the current master?

**Comment by sundar-cs** [comment]
Thank you.

Can you please elaborate because the above commands were executed from the master ?

I just did these as below and the output files are all same (i.e. bypassed kubectl and just redirected to a file).

curl https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/examples/simplest.yaml | docker run --rm jaegertracing/jaeger-operator:master generate > out1

curl https://raw.githubusercontent.com/jaegertracing/jaeger-operator//deploy/examples/with-sampling.yaml | docker run --rm jaegertracing/jaeger-operator:master generate > out2

docker run --rm jaegertracing/jaeger-operator:master generate > out3

Please let me know, Thanks.

**Comment by jpkrohling** [comment]
It might be the case that the images aren't up to date. It does work using a local version of the code for me:

```console
$ go run main.go generate --cr ./deploy/examples/simplest.yaml | fpaste
INFO[0000] Storage type not provided. Falling back to 'memory'  instance=simplest namespace=
Uploading (10.0KiB)...
https://paste.centos.org/view/1c317fcf

$ go run main.go generate --cr ./deploy/examples/simple-prod.yaml | fpaste
Uploading (17.0KiB)...
https://paste.centos.org/view/328d66e5
```

And here are the links to the resulting manifests: 
* [simplest](https://paste.centos.org/view/1c317fcf)
* [simple-prod](https://paste.centos.org/view/328d66e5)

**Comment by jpkrohling** [comment]
I just tested it with the latest operator image from Dockerhub and it also works:

```console
$ cat ./deploy/examples/simple-prod.yaml | podman run -i jaegertracing/jaeger-operator:master generate > /tmp/simple-prod.yaml
$ cat ./deploy/examples/simplest.yaml | podman run -i jaegertracing/jaeger-operator:master generate > /tmp/simplest.yaml
$ ls -l /tmp/simple*.yaml
-rw-r--r--. 1 jpkroehling wheel 14639 10. Aug 17:02 /tmp/simple-prod.yaml
-rw-r--r--. 1 jpkroehling wheel  8505 10. Aug 17:03 /tmp/simplest.yaml

```

**Comment by sundar-cs** [comment]
Yes with the above commands thru podman it works well.
Earlier with docker I did have the latest image of master and in addition had also tried removing it so that it gets it afresh which it did, but still had not made any diff.

Could it be docker versus podman issue ? If so will the documentation be updated ?

Thanks so much.

**Comment by jpkrohling** [comment]
`podman` should act exactly the same as `docker`. I use it as it's the tool that works best for me on my workstation (Fedora 32), but the documentation should be accurate for both `podman` and `docker`. I'm closing this issue, but if you feel like further action is needed on this, feel free to reopen it.

**Comment by sundar-cs** [comment]
Thank you.
I'm re-opening it just for a final observation based on your comment above that podman and docker should behave identically.

That alerted me to the fact that the documentation is missing the "i" flag (interactive) which is the crux of this somewhat confusing issue.
This explains why stdin had no effect, which in fact was the very 1st question above:
(What is the role of the standard input passed into "docker run ... generate")

I just confirmed it with the "i" flag and using docker, and it created identical output as from podman.

Maybe the documentation can be fixed so that none else re-opens this in future.
In any case thanks a lot for your help, please feel free to close it again.

**Comment by jpkrohling** [comment]
Great catch, @sundar-cs ! Would you like to open a PR to fix the readme?

**Comment by sundar-cs** [comment]
Yes sure if you would like, please let me know the procedure as my first time

**Comment by jpkrohling** [comment]
If you are familiar with Git/GitHub, the process is quite simple:

1. Fork this repository
1. Clone your repository, add this one here as `upstream`: `git remote add upstream https://github.com/jaegertracing/jaeger-operator`
1. Create a new work branch: `git checkout -b sundar-cs/issue1150`
1. Do your changes
1. Commit and sign it off: `git commit -sam "Your commit message"`
1. Push your branch: `git push`. Once you do this, there will be a link to open a new PR based on this branch

More formal instructions are here: https://github.com/jaegertracing/jaeger-operator/blob/master/CONTRIBUTING_GUIDELINES.md

Not needed for this particular change, but if you want to contribute some code as well, make sure to read this: https://github.com/jaegertracing/jaeger-operator/blob/master/CONTRIBUTING.md .

**Comment by sundar-cs** [comment]
Thank you.
I have generated the pull request, please confirm if you're able to see it.

**Comment by jpkrohling** [comment]
Thank you for your contribution, @sundar-cs!
