### ISSUE TITLE
Allow configuring the securityContext of the CassandraCreateSchema job

### ISSUE THREAD

**Issue by chgl** [jaegertracing/jaeger-operator#1166]
Currently, the CassandraCreateSchema job does not take the securityContext specified in Jaeger.spec.securityContext into account: https://github.com/jaegertracing/jaeger-operator/blob/9cde42a9ccc291545de8cfaf7a9dbebf6b15af12/pkg/storage/cassandra_dependencies.go#L129

This causes the job not to start when running in a cluster with very restrictive PSPs.

I think this could be resolved quite easily by setting the Jaeger.spec.securityContext (globally set in the Jaeger CRD) to the Job's container/pod securityContext. I could create a PR for this, although it would be the my first time writing Go 😅

**Comment by jpkrohling** [comment]
@chgl go for it! If you need any assistance, let us know.
