### ISSUE TITLE
Process dependencies in parallel

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#117]
Currently the operator works through a list of dependencies one at a time, waiting for the dependency to complete before moving onto the next.

To make the startup more efficient when multiple dependencies exist, it would be better to start them all concurrently and then wait for them all to complete.

**Comment by jpkrohling** [comment]
Somewhat related: #925

**Comment by pavolloffay** [comment]
Closing, no need for this feature. Running the dependencies in serial is preferred at the moment as it gives a clear indication how the "jobs" will be run.
