### ISSUE TITLE
APM-Server integration with Jaeger-agent: Unable to connect with APM-server on Elasticsearch

### ISSUE THREAD

**Issue by forumsheth** [jaegertracing/jaeger-operator#1183]
Hi All,
I am trying to connect my apm-server with existing jaeger agent on my Kubernetes cluster.  I have changed the backend to Elasticsearch in my jaeger configuration. And jaeger is able to connect to Elasticsearch as the logs shows: "Elasticsearch detected".
Both the apm-server and the jaeger agent are running and indices are getting created for both in elastisearch. But I am unable to set up the jaeger agent on Kibana dashboard to set up APM. 
Note: Jaeger is deployed along with Istio 1.5.1
Can anyone help what all configurations are required to do this setup?

**Comment by jpkrohling** [comment]
This is a question for the Kibana folks. If there's anything you need on our side to get a better support for Kibana, let us know but for now, I'm closing this one.
