### ISSUE TITLE
Allow for configuring the injected sidecar container's securityContext

### ISSUE THREAD

**Issue by chgl** [jaegertracing/jaeger-operator#1186]
Currently, the securityContext of the injected jaeger-agent container can not be configured, causing the agent container to fail with "container has runAsNonRoot and image will run as root" when running in a cluster with strict PSPs.

We could reuse the securityContext from the common jaeger spec (as in #1166) or add a a securityContext element to the Spec.Agent type.

In addition, a lot of headaches may be avoided by setting the the jaeger-agent container user to a non-root one by default. This should be realtively straight-forward as I don't think the jaeger-agent requires any privileges or disk access. I'd like to create a PR for this, but I can't find the jaeger-agent image's Dockerfile.

**Comment by jpkrohling** [comment]
If there's a security context for individual containers in a pod, the Jaeger Agent container should indeed use the security context from the Jaeger's CR. The fix would be somewhere around here: https://github.com/jaegertracing/jaeger-operator/blob/d94166385a596da40db494769175a675cae7ad23/pkg/inject/sidecar.go#L230-L279

And here's the Dockerfile for Jaeger Agent: https://github.com/jaegertracing/jaeger/blob/master/cmd/agent/Dockerfile

**Comment by chgl** [comment]
Sounds good! I'll create a PR to add the securityContext and will also propose to update the Dockerfile.
