### ISSUE TITLE
Rollover job created even when set to false

### ISSUE THREAD

**Issue by alexanderccc** [jaegertracing/jaeger-operator#1187]
We are trying to implement ILM with the Elasticsearch index used by jaeger. All tests were successful and it seems to work without any issue. The only problem is that we require a custom template (additional specification of the ILM policy) to be assigned to the bootstrapped index.

Because elasticsearch will handle the rollover we no longer require the rollover job so we set it to false in the operator. Even if we did this it seems that the es.use-aliases flag will still create the job and rollover the index.

**Comment by jpkrohling** [comment]
@pavolloffay would you like to take this one?

**Comment by pavolloffay** [comment]
I will have a look at this.

**Comment by pavolloffay** [comment]
@alexanderccc could you please share the Jaeger CR?

**Comment by alexanderccc** [comment]
@pavolloffay Here is the Jaeger crd

`kubectl describe crd/jaegers.jaegertracing.io


Name:         jaegers.jaegertracing.io
Namespace:    
Labels:       app=jaeger-operator
Annotations:  helm.sh/hook: crd-install
              helm.sh/hook-delete-policy: before-hook-creation
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2020-07-16T17:08:42Z
  Generation:          1
  Resource Version:    2172822
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/jaegers.jaegertracing.io
  UID:                 4aafda5a-82ae-4353-b23f-667d52d23db6
Spec:
  Additional Printer Columns:
    JSON Path:    .status.phase
    Description:  Jaeger instance's status
    Name:         Status
    Type:         string
    JSON Path:    .status.version
    Description:  Jaeger Version
    Name:         Version
    Type:         string
  Conversion:
    Strategy:  None
  Group:       jaegertracing.io
  Names:
    Kind:                   Jaeger
    List Kind:              JaegerList
    Plural:                 jaegers
    Singular:               jaeger
  Preserve Unknown Fields:  true
  Scope:                    Namespaced
  Subresources:
    Status:
  Version:  v1
  Versions:
    Name:     v1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       Jaeger
    List Kind:  JaegerList
    Plural:     jaegers
    Singular:   jaeger
  Conditions:
    Last Transition Time:  2020-07-16T17:08:42Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1
Events:  <none>`

**Comment by pavolloffay** [comment]
@alexanderccc we need CR and not CRD. Could you please provide that? You can get it via `kubectl get jaegers` and then `kubectl get jaegers <name>`. Or just paste  the yaml file you have used to create Jaeger.

**Comment by alexanderccc** [comment]
@pavolloffay sure, sorry for the misunderstanding, bellow you can find our Jaeger definition

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  annotations:
    meta.helm.sh/release-name: stg-landscape
    meta.helm.sh/release-namespace: stg
  creationTimestamp: "2020-07-16T17:15:56Z"
  generation: 8
  labels:
    app.kubernetes.io/instance: stg-landscape
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: landscape
    helm.sh/chart: landscape-3.0.1
    jaegertracing.io/operated-by: observability.jaeger-operator
  name: stg-landscape-jaeger
  namespace: stg
  resourceVersion: "27722734"
  selfLink: /apis/jaegertracing.io/v1/namespaces/stg/jaegers/stg-landscape-jaeger
  uid: 75a5049d-f23a-4875-9987-74743f6e1b49
spec:
  agent:
    config: {}
    options: {}
    resources: {}
  allInOne:
    options: {}
    resources: {}
  collector:
    config: {}
    options: {}
    resources: {}
  ingester:
    config: {}
    options: {}
    resources: {}
  ingress:
    annotations:
      kubernetes.io/ingress.class: ops
    enabled: true
    labels:
      app.kubernetes.io/instance: stg-landscape
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/part-of: landscape
      helm.sh/chart: landscape-3.0.1
    openshift: {}
    options: {}
    resources: {}
    security: none
  query:
    options:
      log-level: info
      query:
        base-path: /tracing
    resources: {}
  resources: {}
  sampling:
    options:
      default_strategy:
        param: 1
        type: const
  storage:
    cassandraCreateSchema: {}
    dependencies:
      enabled: false
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: "1"
          memory: 16Gi
      storage: {}
    esIndexCleaner:
      enabled: false
      numberOfDays: 7
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      enabled: false
      resources: {}
      schedule: 0 0 * * *
    options:
      es:
        create-index-templates: false
        index-prefix: stg
        server-urls: http://es-cluster.observability:9200
        use-aliases: true
    type: elasticsearch
  strategy: production
  ui:
    options:
      menu:
      - items:
        - label: Documentation
          url: https://www.jaegertracing.io/docs/1.18
        label: About
status:
  phase: Failed
  version: 1.18.0
```

**Comment by pavolloffay** [comment]
The `use-aliases: true` in the storage options instructs the operator to create rollover jobs. A solution might be to remove it from the storage options and instead define it in the collector and query options. See the CR below.

Do you need any of the cron jobs (init, rollover, lookback) with ILM?

Try the following configuration CR. With this configuration, the operator should not deploy rollover jobs (init, rollover, lookback) but the collector and query will use the read and write aliases.

```yaml
# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    options:
      es:
        use-aliases: true
  query:
    options:
      es:
        use-aliases: true
  storage:
    type: elasticsearch
    options:
        server-urls: http://elasticsearch:9200
```

**Comment by alexanderccc** [comment]
@pavolloffay I see, should the rest of the es config also be placed under query and collector? Like the index-prefix? What about the index-template, should that be specified under each component or just storage?

I still believe that this is a bug, even if we have the use-alias under storage if we instruct the operator to not create the rollover job shouldn't it take that into account?

I will test with this setup and come back with details.

**Comment by jpkrohling** [comment]
> should the rest of the es config also be placed under query and collector

All options defined at the .Spec.Storage level are propagated down to every component. Options defined at the component level override the ones set at the .Spec.Storage level.

Meaning: you can specify the `use-aliases` inside each component, but still have `es.server-urls`, `es.index-template` and so on at the .Spec.Storage level.

@pavolloffay could you double-check your example? I think the `.Spec.Storage.Options` node is missing the `es` part.

**Comment by alexanderccc** [comment]
Thank you guys for the workaround, I implemented the changes and it seems to work fine, the initial index creation jobs where not triggered and the rollover one as well seems to not have been triggered, we'll monitor it for a couple more days and see if anything changes and update here.

Is there anything I should keep in mind in regards to the querier when using ILM? Our current policy should move the indices across our different es node types and after a week or so they should hit cold storage where they'll be frozen. 
Will the querier face any issues when querying frozen indices?

**Comment by alexanderccc** [comment]
@pavolloffay The fix worked as expected, we didn't see any rollover job getting created. Should we consider this the permanent fix and the way to go forward or will there be a different fix for this?

**Comment by pavolloffay** [comment]
We can stick to this I will document it.
