### ISSUE TITLE
What is the best way to install Jaeger operator when we have multiple products/microservices to handle in an environment

### ISSUE THREAD

**Issue by chandu9333** [jaegertracing/jaeger-operator#1193]
What is the best way to install Jaeger operator when we have multiple products/microservices to handle in GKE cluster

Do we need to install operator for each namespace or install globally and watch all namespaces (different products namespaces) in that GKE cluster.

**Comment by jpkrohling** [comment]
Depends on your tenancy/security model, but typically, one operator per cluster is fine. You can then have one Jaeger instance per namespace if you need, or one per set of namespaces, or even only one Jaeger instance for the whole cluster as well.
