### ISSUE TITLE
Do we have any constraints that we should know or its like a standard installtion?

### ISSUE THREAD

**Issue by chandu9333** [jaegertracing/jaeger-operator#1194]

**Comment by jpkrohling** [comment]
What kind of constraints do you have in mind? As long as you have a Kubernetes-compatible cluster running, the operator should run just fine in it...

**Comment by chandu9333** [comment]
Let say, we want to install Jaeger operator and Jaeger instance in one namespace and I have a product/application which is running in other namespace which has its own role, rolebinding, service accounts. 
Is there any limitations for Jaeger operator to trace my application namespace.

**Comment by jpkrohling** [comment]
I believe your answer is in the documentation: https://www.jaegertracing.io/docs/1.19/operator/
