### ISSUE TITLE
Do we have any constraints that we should know to trace the multiple products under multiple namesapces?

### ISSUE THREAD

**Issue by chandu9333** [jaegertracing/jaeger-operator#1195]
Let say, we want to install Jaeger operator and Jaeger instance in one namespace and I have a product/application which is running in other namespace which has its own role, rolebinding, service accounts.
Is there any limitations for Jaeger operator to trace my application namespace.

**Comment by pavolloffay** [comment]
No there are not limitations. Jaeger can receive any data from any application in the cluster.
