### ISSUE TITLE
Readiness probes missing from the injected sidecar container

### ISSUE THREAD

**Issue by chgl** [jaegertracing/jaeger-operator#1202]
The injected sidecar agent currently does not set either a readiness or liveness probe. The other deployment types do: 

https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/deployment/agent.go#L156-L175

**Comment by frzifus** [comment]
Liveness probe got added here: https://github.com/jaegertracing/jaeger-operator/pull/1605
