### ISSUE TITLE
Inject the sidecard directly in Pod resources

### ISSUE THREAD

**Issue by fdimuccio** [jaegertracing/jaeger-operator#1232]
Hello,

we are using the jaeger-operator together with [kubefed](https://github.com/kubernetes-sigs/kubefed) and we are facing an reconciliation loop issue when using `sidecar.jaegertracing.io/inject` annotation. Actually the issues are two but they stem from the same root cause. If I'm not mistaken, jeager-operator modify the Deployment resource where the annotation is defined by adding the sidecar container alongside the already defined containers. If another controller is managing the Deployment (like in our case the kubefed controller) the resource will be reconciled by removing the sidecar injected by jaeger-operator, ending up in a loop where both operators modify the resource in turns.

Other systems like [istio](https://istio.io/) instead inject the sidecard directly into the Pod object (without modifying the Deployment) in this way they avoid clashing with other controllers managing the same resource. Note that also the annotation definition is moved to the Pod template definition within the Deployment `spec.template.metadata.annnotations`.

I see that there two other github issues potentially connected with this one (#171 and #750), but it's not clear to me if this change is already implied by switching to a Mutating Webhook Admission Controller.

**Comment by jpkrohling** [comment]
> it's not clear to me if this change is already implied by switching to a Mutating Webhook Admission Controller.

Yes, once we move to a webhook, we'll inject sidecars directly into pods.

**Comment by vassilvk** [comment]
Just wanted to drop in a note here too - while #171 is being worked on, an alternative non-destructive injection solution is now available through KubeMod (as [described in my comment](https://github.com/jaegertracing/jaeger-operator/issues/171#issuecomment-711422072)).
