### ISSUE TITLE
Provide kustomization.yaml for operator installation

### ISSUE THREAD

**Issue by ricochet** [jaegertracing/jaeger-operator#1235]
Benefits of providing kustomization.yaml:

- kustomize is built-in to kubectl
- works well in a gitops style pipeline
- matches direction of kube-builder and being integrated in the operator-sdk

[operator-sdk proposal to integrate kube-builder](https://github.com/operator-framework/operator-sdk/blob/627e1c65ad96c70bbe107d23eca9b3f113cc002e/proposals/kubebuilder-integration.md)

**Comment by ricochet** [comment]
A co-worker created a WIP for this a while back: https://github.com/mikeyrcamp/jaeger-operator/commit/5bdbe8a049bcc1733573f953d964ffb6d61394ab

This will have no impact on users who prefer to use plain manifests. For users who want to use kustomize, this simplifies the install and enhances the customization story for the operator. If there is an upstream base, then consumers can refer to resources in jaegar-operator as a base for their own kustomizations, e.g. setting the namespace and necessary labels.

**Comment by jpkrohling** [comment]
Is it all it needs? Nice! I'm using `kustomize` as part of the opentelemetry-operator and I like the way it works.

I think it would be a nice thing to have if we can get someone committed to maintain it in the long term. Here's a list of things we'll need in the PR:

- [ ] a Makefile target to install `kustomize`
- [ ] e2e tests, probably something based on the current smoke tests?
- [ ] documentation

**Comment by monicagangwar** [comment]
@jpkrohling can you assign it to me, i'll give it a try

**Comment by jpkrohling** [comment]
Sure, it's yours.

**Comment by tobbbles** [comment]
Did this get progressed at all? It'd be great to have a minimal kustomization to use as a [remote resource](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) for installing jaeger-operator

**Comment by elocke** [comment]
@tobbbles seconded!

**Comment by jpkrohling** [comment]
No, and PRs are welcome! For v2, we'll use `kubebuilder` as the base, which would make it easier to have this, like we have for the opentelemetry-operator: https://github.com/open-telemetry/opentelemetry-operator/blob/master/config/default/kustomization.yaml

**Comment by iblancasa** [comment]
I think @rubenvp8510 worked on this as part of #1623, right? Probably, this issue can be closed

**Comment by pavolloffay** [comment]
This is done now after migrating to operator-sdk 1.13
