### ISSUE TITLE
console.openshift.io cluster role permission in cluster_role.yaml but not csv

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#1237]
Appears that the `console.openshift.io` permissions in `cluster_role.yaml`, added in #1177, is not being included in the manifest (clusterserviceversion yaml).

**Comment by jpkrohling** [comment]
May I assign this to you, @rubenvp8510 ?

**Comment by rubenvp8510** [comment]
Yes :) no problem
