### ISSUE TITLE
Unable to access Jaeger UI even after having the ingress IP

### ISSUE THREAD

**Issue by v1468k** [jaegertracing/jaeger-operator#1240]
Hi,
I am trying to setup Jaeger in my system. I followed all the instructions and everything went according to the instrcutions. But i am unable to access the UI even though the pods are all running and i have the ingress ip available as well. 
![image](https://user-images.githubusercontent.com/63405886/95417441-b1ce7d00-0952-11eb-85cb-6c8e853baa34.png)

I tried to logon to the UI on 10.61.62.222 aswell as with port 16686. 10.61.62.222:16686
Nothing helps.

Please help me figure out this issue

**Comment by jpkrohling** [comment]
That's strange, the UI should have been available at http://10.61.62.222 . Could you try doing a port-forward and try it again? Like this:

```console
$ kubectl port-forward deployments/simplest 16686
```

The UI should then be available at http://localhost:16686 .

**Comment by v1468k** [comment]
Hi @jpkrohling 
I tried port forwarding  Still not working. Browser says connection timed out.

**Comment by jpkrohling** [comment]
This sounds like a networking issue between you and your Kubernetes cluster then. Are you trying it locally with `minikube`, or are you using a remote cluster somewhere?

**Comment by v1468k** [comment]
I am using a remote cluster. But everything else works fine. I am able to access all the other apps deployed there (I am using dashboards like prometheus and grafana deployed there..works fine).

Thanks

**Comment by jpkrohling** [comment]
I'm afraid I can't help you much further: if you can reproduce the problem with `minikube`, it means that I can reproduce it as well and I'll be able to help you.

In any case, could you please paste the logs here? Perhaps there's something interesting there:

```console
$ kubectl logs deployments/simplest 
```

**Comment by pavolloffay** [comment]
Closing, not information provided

**Comment by pavolloffay** [comment]
feel free to reopen if the issue is still there
