### ISSUE TITLE
Should Jaeger 2.0 operator upgrade 1.x instances automatically?

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#1241]
Thought it would be worth starting a discussion, to see what the pros/cons might be.

For example, a pro would be continuous seamless operations of existing Jaeger instances. but a con may be that some Jaeger 1.x options are not supported/compatible with Jaeger 2.

Or should the upgrade be supported, but if some incompatibility is detected, then it skips that instance (current behaviour I believe) and logs a warning?

**Comment by jpkrohling** [comment]
Last I heard, there was only a minor flag with backwards compatibility problems. If that's still true, we can indeed offer an upgrade to v2.

**Comment by objectiser** [comment]
We should gather all the known changes and then decide. For example:

- #1227 indicates that some kafka producer flags are not supported (batch-linger/size/max-messages)
- Message encoding default - if jaeger 2 uses OTLP (which might be a good idea) then possibly existing instances could set the encoding to jaeger to remain compatible with existing messages in the kafka cluster - but this would then cause problems with new jaeger 2 instances. Probably needs discussion, as otherwise the default may need to remain jaeger encoding?

@pavolloffay would you be able to list any changes you think would need to be handled in the upgrade, or that make upgrade inadvisable?

**Comment by jpkrohling** [comment]
The first issue seems an oversight and perhaps should be added to the OpenTelemetry-based Jaeger. The second would be a real backwards compat problem.

**Comment by pavolloffay** [comment]
> #1227 indicates that some kafka producer flags are not supported (batch-linger/size/max-messages)

We had users that complained that some flags were noop even in the current Jaeger distros (e.g. span writer exposing reader configuration). I think there are more flags missing in the OTEL distribution not just for kafka.

> Message encoding default - if jaeger 2 uses OTLP (which might be a good idea) then possibly existing instances could set the encoding to jaeger to remain compatible with existing messages in the kafka cluster - but this would then cause problems with new jaeger 2 instances. Probably needs discussion, as otherwise the default may need to remain jaeger encoding?

The 2.0 config could still keep `jaeger` receiver and add OTLP `exporter` and `receiver`. Though it might cause custom kafka receivers stop working since there won't be new data. This might be fine to just document. IIRC Jaeger OTEL kafka uses Jaeger encoding and topic by default.
