### ISSUE TITLE
keeping metrics and servicemonitor

### ISSUE THREAD

**Issue by jjmengze** [jaegertracing/jaeger-operator#1249]
in this proposal #1201 we can saw that metrics and servicemonitor are have been removed.

because currently operator-sdk doesn't provide the metric library.

in my point of view we can the CreateMetricsService function by ourselves,so that we no longer rely on the methods provided by the operator sdk

**Comment by jpkrohling** [comment]
I think the main point there is that the operator shouldn't be creating resources that are related to itself, like its own services or service monitor objects. It should be part of the operator's provisioning tool (Helm, OLM, ...) instead, which I tend to agree.

**Comment by jpkrohling** [comment]
I do appreciate your comment, but I'm closing this issue here, as I think this discussion does belong to #1201.
