### ISSUE TITLE
Skip detectClusterRoles for Kubernetes

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1261]
Based on #1258, we should skip the execution of this function if we are *not* running on OpenShift:

https://github.com/jaegertracing/jaeger-operator/blob/619c92481921131da1af876b29b973ac6a6a4cdc/pkg/autodetect/main.go#L199-L221

**Comment by johanavril** [comment]
hi @jpkrohling , I would like to try working on this

**Comment by jpkrohling** [comment]
It's yours!
