### ISSUE TITLE
Allow service types to be configured

### ISSUE THREAD

**Issue by kevinjqiu** [jaegertracing/jaeger-operator#1263]
Currently, all services are created as `ClusterIP` type services.  This is adequate if everything is run inside the kubernetes cluster.  For our use case, we need to deploy the collector on a kube cluster but we have a variety of ways to deploy agents, e.g., directly on a VM outside of the cluster.

This means we need to expose the agent GRPC service so it can be reached by the agents outside of the cluster.  Since it's the GRPC service, we can't use ingress.  It'd be nice if we can configure the service for each individual component which allows us to specify `serviceType: NodePort` or even `LoadBalancer`.

Thanks,

**Comment by jpkrohling** [comment]
We've had a PR adding this to the query service. Exposing the collector to outside of the cluster should never be the default option, but I think it might be reasonable to align the collector's service with the query.

**Comment by jpkrohling** [comment]
This might be related as well: #1048

**Comment by kevinjqiu** [comment]
> This might be related as well: #1048

For HTTP thrift services, sure, but the GRPC service cannot be exposed by way of ingress, since ingresses are HTTP only.
