### ISSUE TITLE
Add documentation to write e2e tests

### ISSUE THREAD

**Issue by annanay25** [jaegertracing/jaeger-operator#127]
Would be nice to have documentation (possibly in the doc for contributing guidelines) on writing e2e tests.

**Comment by jpkrohling** [comment]
Do you need this for your current PRs, or did you figure it out already? If you need this, I'll bump the priority for this one, otherwise, I'll review your PR for document it :)

**Comment by annanay25** [comment]
@jpkrohling this is what I could come up with :) - https://github.com/jaegertracing/jaeger-operator/pull/114/commits/c352a4da73d08c8dcdfc20a3b32d841ae479c7c7

Not sure how to really query the deployed pod for its environment variables.

**Comment by jpkrohling** [comment]
You can get a deployment based on its name + namespace like this:

https://github.com/jaegertracing/jaeger-operator/blob/c576d56292cc7cb64f133d8dd2079de9cfc47827/pkg/controller/deployment/deployment_controller.go#L71-L72

The second line will populate the instance you created in the first line. Once you get that instance, you can just access the env vars as usual. Here's a code that is unrelated, but shows how to interact with env vars from pods:

https://github.com/jaegertracing/jaeger-operator/blob/08b45de096e6291dd7e7a5d53438518a236cc2ad/pkg/inject/sidecar.go#L116-L121

**Comment by annanay25** [comment]
Thanks!

**Comment by pavolloffay** [comment]
old issue closing, now tests are using kuttl.
