### ISSUE TITLE
No services list in the Jaeger UI for the Production Strategy deployment

### ISSUE THREAD

**Issue by chandu9333** [jaegertracing/jaeger-operator#1273]
I am not able to see any services like jaeger-query and Jaeger-operator (its own using tracing enabled at operator.yaml)  services in the dashboard. 

What could be the issue, can you please some one let me know? 
Thanks in advance

**Comment by objectiser** [comment]
@chandu9333 have you checked the jaeger-query and jaeger-operator logs to see whether there is anything (i.e. errors)?

**Comment by chandu9333** [comment]
I dont see any errors but jus see below logs under jaeger-query

2020/10/27 09:03:08 maxprocs: Leaving GOMAXPROCS=32: CPU quota undefined
{"level":"info","ts":1603789388.0329237,"caller":"flags/service.go:116","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1603789388.0333474,"caller":"flags/admin.go:120","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1603789388.0334482,"caller":"flags/admin.go:126","msg":"Starting admin HTTP server","http-addr":":16687"}
{"level":"info","ts":1603789388.0335026,"caller":"flags/admin.go:112","msg":"Admin server started","http.host-port":"[::]:16687","health-status":"unavailable"}
{"level":"info","ts":1603789388.198771,"caller":"config/config.go:179","msg":"Elasticsearch detected","version":7}
{"level":"info","ts":1603789388.1997435,"caller":"app/static_handler.go:180","msg":"watching","file":"/etc/config/ui.json"}
{"level":"info","ts":1603789388.1997778,"caller":"app/static_handler.go:188","msg":"watching","dir":"/etc/config"}
{"level":"info","ts":1603789388.1998744,"caller":"app/server.go:133","msg":"Query server started","port":16686,"addr":":16686"}
{"level":"info","ts":1603789388.199914,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1603789388.1999254,"caller":"app/server.go:148","msg":"Starting HTTP server","port":16686,"addr":":16686"}
{"level":"info","ts":1603789388.1999407,"caller":"app/server.go:161","msg":"Starting GRPC server","port":16686,"addr":":16686"}
{"level":"info","ts":1603789388.1999454,"caller":"app/server.go:171","msg":"Starting CMUX server","port":16686,"addr":":16686"}

**Comment by objectiser** [comment]
Have you taken a look at https://www.jaegertracing.io/docs/1.20/troubleshooting/ ?

**Comment by chandu9333** [comment]
Yes but no luck...Do we need to enable any sort of ports at Cluster level? 
I access UI by port-forwarding to localhost

**Comment by jpkrohling** [comment]
Are you able to reproduce it with minikube? If so, please list all the steps you did, including the CR you are deploying.

**Comment by chandu9333** [comment]
Able to see the traces.

**Comment by LuChenjing** [comment]
@chandu9333 Hi, how did you fix it? I tried all-in-one and production streagy, But none shown any services in UI. And there's no error logs from pods.
