### ISSUE TITLE
generator_test should not be using a specific image name

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#1278]
The generator test has a hard coded reference to the 1.13 all-in-one image: https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/generator_test.go#L59

This shouldn't be done anyway, but has caused problems when running with OTEL images on OpenShift.

**Comment by objectiser** [comment]
This test should work equally well without the `image` being explicitly defined in the CR. I think the main purpose is just to create a single deployment yaml to represent that an operator would generate.
