### ISSUE TITLE
Exposing OTLP port in collector and possibly agent

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#1287]
Currently we build OTEL variants of the Jaeger agent, collector,ingester and all-in-one - which can be used from the current Jaeger operator. However the OTLP port for the agent, collector and all-in-one are not exposed by the operator.

In the interim, before we have an official "Jaeger 2" operator, is there a way we can identify that an OTEL image is being used and include the OTLP port on the deployment/service definitions?

**Comment by jpkrohling** [comment]
We can "guess" based on the image names, but we won't know for sure. The status endpoint could return the type of the collector, but that would still require running the collector before we can infer this.
