### ISSUE TITLE
Could you please help me to understand or can you provide more details/reference that I can refer?

### ISSUE THREAD

**Issue by chandu9333** [jaegertracing/jaeger-operator#1295]
All Jaeger backend components expose Prometheus metrics by default (other metrics backends are also supported). Logs are written to standard out using the structured logging library zap.

I don't understand this as a newbie.

I have the Jaeger operator is running in my GKE cluster with Production Strategy using ElasticSearch as backend storage.
How can we enable/see prometheus metrics?

**Comment by jpkrohling** [comment]
Are you talking about the operator metrics, or the operand (Jaeger instance) metrics? In both cases, the metrics are on `/metrics` for the documented ports (8383 and 8686 for the operator, "admin" port for each component in the production strategy).

You'll need a Prometheus in your Kubernetes cluster that is able to scrape the metrics from those endpoints. If you are using the Prometheus Operator, you'll need a `Prometheus` CR. Until #1275 is ready and released, you'll need also to add `ServiceMonitor` CRs, which are detected by the Prometheus operator. The Jaeger Operator, at this moment, will generate a `ServiceMonitor` for its own endpoints.

Hope this helps.

**Comment by chandu9333** [comment]
I have jaeger operator running in one namespace in kubernetes cluster and Prometheus operator is running in different namespace. 
How can I trace Prometheus metrics from jaeger operator

**Comment by jpkrohling** [comment]
That's probably a question for the Prometheus operator folks.

**Comment by chandu9333** [comment]
Can’t we trace Prometheus using jaeger operator?

**Comment by jpkrohling** [comment]
Not sure I understand your question. Jaeger Operator is for managing Jaeger, which handles distributed tracing. The Prometheus Operator is for managing Prometheus, which handles metrics.

**Comment by chandu9333** [comment]
All jaeger backend components expose Prometheus metrics by default. 
What do you mean by that. 
I’m not clear on this yet. Sorry to bug you again and again. 
Please clarify me on that statement which I see in documentation.

**Comment by jpkrohling** [comment]
Those are for monitoring Jaeger itself: you can monitor the internal work queue, how long Jaeger is taking to persist things to disk, and so on. You then use Prometheus to scrap (ie: read) those metrics and store it in Prometheus database. You can then create alert rules (again, in Prometheus) in case your Jaeger instance starts acting weird: when saving a span takes too long, when the queue is never cleared, ...
