### ISSUE TITLE
I deployed sample app but not able to see in jaeger UI

### ISSUE THREAD

**Issue by chandu9333** [jaegertracing/jaeger-operator#1297]
I have applied the business-application-injected-sidecar.yaml file on my gke cluster where jaeger operator with all in one instance is already running, but I’m not able to see myapp as a service in jaeger UI(port forwarded using local host)

Btw, I can access sample app it shows as Hello from vert.x ! 

What could be the reason?  could some one help on it?

**Comment by chandu9333** [comment]
Sorry my bad, was able to do that using jaeger instance now. 
As I understand sample app is applicable to jaeger instance.
But can we apply that for production strategy?

**Comment by jpkrohling** [comment]
>  As I understand sample app is applicable to jaeger instance.

Not sure what you mean here. Could you please clarify? The example works with any instance of Jaeger, no matter the strategy.
