### ISSUE TITLE
Allow specific values for nodeport to be configured

### ISSUE THREAD

**Issue by CSP197** [jaegertracing/jaeger-operator#1307]
As a user of jaeger-operator, I would like to expose the jaeger-query service in my K8s VPC. 

As per #1263, I understand that a service type can be set via -
```
query:
      serviceType: NodePort
```
But it would be nice if a user could specify a constant value for the exposed nodeport as follows -
```
query:
      serviceType: NodePort
      nodePort: 3####
```

Thanks all,

**Comment by dogukanturan** [comment]
I guess we can't add NodePort and we can't make a static ClusterIP definition either.

**Comment by CSP197** [comment]
@jpkrohling - Can you pls review my PR: https://github.com/jaegertracing/jaeger-operator/pull/1394?

**Comment by jpkrohling** [comment]
@rubenvp8510 will take a look at this one
