### ISSUE TITLE
Existing apps with sidecar agent inject annotation not injected when first appropriate jaeger instance created

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#1315]
If an app has been deployed, before the Jaeger instance is created, the operator log shows:
```
"No suitable Jaeger instances found to inject a sidecar" deployment=myapp
```
However, when the Jaeger instance is created (and available), the operator does not rescan the apps to see whether an agent for that Jaeger instance can now be injected.

Reproduced on OCP4.5 with Jaeger 1.17 and 1.20.

**Comment by objectiser** [comment]
cc @jpkrohling @rubenvp8510 

Haven't tried on latest, as was not available in the operatorhub at the time, so might be fixed?

Also tried with app having injected sidecar, then removed the jaeger instance (which cleaned up the sidecar agent), and then created a new jaeger instance - and the agent doesn't get re-injected into the app.

BTW - the Jaeger instance and business app are deployed to different namespaces.

**Comment by jpkrohling** [comment]
There were quite a few changes made by @rubenvp8510 in the past on this logic, so, this might indeed be fixed already. But would be nice to get a confirmation from him.

**Comment by rubenvp8510** [comment]
I changed the logic to address the case of injection across namespaces. and IIRC I put some logic to scan apps for injection
I'll check this case and see if can reproduce it.
