### ISSUE TITLE
Pod recreation due to container.name tag missing in the jaeger.tags argument

### ISSUE THREAD

**Issue by lujiajing1126** [jaegertracing/jaeger-operator#1318]
We have observed Pod recreation events in the production cluster very similar to this issue https://github.com/jaegertracing/jaeger-operator/issues/1089

We find the following logs in the operator container,

```
...
time="2020-11-27T01:24:15Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=hera-alertgateway-ack-deploy jaeger=jaeger-ack jaeger-namespace=observability namespace=sqb
time="2020-11-27T01:24:15Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=kubernetes-ack-jack-ack-deploy jaeger=jaeger-ack jaeger-namespace=observability namespace=sqb
time="2020-11-27T01:24:15Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=merchant-dmp-datacenter-ack-deploy jaeger=jaeger-ack jaeger-namespace=observability namespace=sqb
time="2020-11-27T01:24:15Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=merchant-dmp-service-ack-deploy jaeger=jaeger-ack jaeger-namespace=observability namespace=sqb
```

These are the four deployments annotated with `sidecar.jaegertracing.io/inject: 'true'`, and these event repeatedly occur recently. In the meantime, we find the following events from kubernetes, the times exactly coincide.

![image](https://user-images.githubusercontent.com/2568208/100436666-9e31ce00-30da-11eb-8527-c9bea0c296fb.png)

Thus, we compared two replicaSets generated and found the arguments of two agent containers are different,

```
$ diff merchant-dmp-datacenter-ack-deploy-6d5dc79477 merchant-dmp-datacenter-ack-deploy-68b5cc4bd6
...(not related)
120c120
<         - --jaeger.tags=cluster=undefined,deployment.name=merchant-dmp-datacenter-ack-deploy,pod.namespace=sqb,pod.name=${POD_NAME:},host.ip=${HOST_IP:},container.name=merchant-dmp-datacenter-ack
---
>         - --jaeger.tags=cluster=undefined,deployment.name=merchant-dmp-datacenter-ack-deploy,pod.namespace=sqb,pod.name=${POD_NAME:},host.ip=${HOST_IP:}
``` 

I suppose it is related to https://github.com/jaegertracing/jaeger-operator/blob/f250749b7029cfe2c211a07b482e233a65496f47/pkg/inject/sidecar.go#L198-L202 since the agent container has already been injected.

**Comment by jpkrohling** [comment]
Thank you for finding the root cause and for the PR!
