### ISSUE TITLE
Latest release doesnt reflect real latest

### ISSUE THREAD

**Issue by daroga0002** [jaegertracing/jaeger-operator#1322]
In repo I see release:
![image](https://user-images.githubusercontent.com/20227477/100609926-1e407980-330f-11eb-91c3-9e9928377eb9.png)

in releases:
![image](https://user-images.githubusercontent.com/20227477/100609977-2ef0ef80-330f-11eb-840c-81b6fc21a346.png)

question does Latest Release shoudnt be moved to v1.21.2 ?

**Comment by jpkrohling** [comment]
Thanks for pointing it out! I just created a GitHub Release for the latest tag.
