### ISSUE TITLE
Unable to lock version for indirect dependency

### ISSUE THREAD

**Issue by lujiajing1126** [jaegertracing/jaeger-operator#1326]
As we have discussed in PR #1319, I tried to run `go mod tidy` on the master branch and the indirect version of `github.com/miekg/dns@v1.1.35` went away. This dependency is introduced in #1298 intended to fix a CVE issue.

I suppose as per https://github.com/golang/go/issues/40784#issuecomment-675161073, it is not possible to lock/pin an indirect dependency. So we have to be very careful with this indirect dep.

Just a comment. I am not sure what we can do now. Maybe add a git-hook to ensure? @jpkrohling

**Comment by jpkrohling** [comment]
Should it be part of the `replaces` section? I'm not quite sure what's the recommended approach for Go modules...

**Comment by lujiajing1126** [comment]
> Should it be part of the `replaces` section? I'm not quite sure what's the recommended approach for Go modules...

According to the official spec, I suppose it can be done with `replace`. https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive
