### ISSUE TITLE
Automatically detect platform

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#133]
At the moment jaeger-operator has to be configured with `--platform=openshift` to find out information about the platform: k8s, openshift. This leads to duplication of deployment files and docs. 

Maybe we can get the platform from the orchestration API and adjust behavior based on that.

**Comment by jpkrohling** [comment]
I opened a thread on the operator-sdk mailing list a couple of weeks ago on this topic:

https://groups.google.com/forum/#!msg/operator-framework/ls0-cNq0mmg/Rcm_or-HAgAJ

I believe this is something that should be provided by the SDK.

**Comment by pavolloffay** [comment]
There is no API in k8s which returns a distribution. However in case of creating openshift route we can query `api/routes.openshift.io/v1` to check whether routes are accessible and based on it create it.
