### ISSUE TITLE
jaeger-operator has root group 

### ISSUE THREAD

**Issue by UsaninMax** [jaegertracing/jaeger-operator#1336]
Hello, I use Jaeger with Kubernetes and our security doesn't allow us to use any pod/containers with root access
I am noticed that security context was parameterized for Agents https://github.com/jaegertracing/jaeger-operator/pull/1190/files  that's great.
Meanwhile the jaeger-operator itself has own user and by default root group 
https://github.com/jaegertracing/jaeger-operator/blob/master/build/Dockerfile#L28
the result is:
```
bash-4.4$ id
uid=1001 gid=0(root) groups=0(root)
```

Could you please help to run jaeger-operator as non root ?

**Comment by jpkrohling** [comment]
Interesting observation. I'm not sure I fully understand the attack vector this would open, but I don't see a problem in changing it either. Would you mind opening a pull request, perhaps linking a best practices doc reference or a link to a Dockerfile being used by some other operator/project?

**Comment by UsaninMax** [comment]
@jpkrohling 
https://kubernetes.io/docs/concepts/security/pod-security-standards/

> Non-root groups (optional) | Containers should be forbidden from running with a root primary or supplementary GID.

**Comment by jpkrohling** [comment]
Cool! Would you open a PR with the proposal?
