### ISSUE TITLE
How can I add service annotations in the Jaeger manifest?

### ISSUE THREAD

**Issue by herbguo** [jaegertracing/jaeger-operator#1338]
As the title say, How can I add service annotations in the Jaeger manifest ?
I want to add same annotations in the jaeger-query service , I install the jaeger through the jaeger-operator. 
the version is 1.20.0

The  jaeger offical document only have the sample to alter the deployment annotations.

I can not find how to alter the jaeger install manifest to add annotation in jaeger offical document. 

someone can help me! thanks!!!

**Comment by jpkrohling** [comment]
You can add annotations to components, but not directly to the underlying resources (deployments, services, ...). The annotation you add to the component is then propagated down to the resources.
