### ISSUE TITLE
jaeger query start with jaeger agent sidecar while agent strategy is daemonset

### ISSUE THREAD

**Issue by Creator1024** [jaegertracing/jaeger-operator#1350]
I have deployed jaeger-operator(v1.20.0) in kubernetes(v1.15.10), and start a jaeger instance with production strategy and the agent's strategy is DaemonSet.

```
jaeger-operator-dcc8d44f-sz4q6           1/1     Running   0          3h55m
jaeger-test-agent-daemonset-6j76r        1/1     Running   0          3h38m
jaeger-test-agent-daemonset-p9rpm        1/1     Running   0          3h38m
jaeger-test-agent-daemonset-x67rh        1/1     Running   0          3h38m
jaeger-test-agent-daemonset-xxm9q        1/1     Running   0          3h38m
jaeger-test-collector-78b95f5965-tvgsm   1/1     Running   1          123m
jaeger-test-query-5fd695b9d8-7h2hq       2/2     Running   0          38m
```

As shown above, pod collector was a single container but pod  query was injected a jaeger agent sidecar.
I think both  collector and  query can use the daemonset jaeger agent. there is no need to set annotation "sidecar.jaegertracing.io/injected" for query deployment by default.

**Comment by jpkrohling** [comment]
The strategy is to tell the operator what's the strategy to use with your workloads. The decisions for the Jaeger components themselves are up to the operator itself.

Do you have a reason to skip the sidecar for the query deployment?

**Comment by Creator1024** [comment]
IMO, the purpose of  choosing daemonset strategy for agent  is that I want any pods communicate with jaeger agent through node where the pod is scheduled.  In this way, I only need to concern about the agent daemonset but not other agent sidecar.

if it's possible disable `"sidecar.jaegertracing.io/injected"` , and config JAEGER_AGENT_HOST and JAEGER_AGENT_PORT env for query?
```
  - name: JAEGER_AGENT_HOST
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
  - name: JAEGER_AGENT_PORT
    value: "6831"
```

**Comment by jpkrohling** [comment]
That's true, for your own workloads. The query deployment is managed by the operator, making it an exception. The annotation wouldn't work, as we don't use the sidecar injection logic for this deployment, we add the sidecar manually to the deployment.

But I'm still curious at to why you really want to make the query spans to go through the DaemonSet.
