### ISSUE TITLE
Can you indicate the correspondence between jaeger-operator version and k8s version?

### ISSUE THREAD

**Issue by dylanyht** [jaegertracing/jaeger-operator#1352]
I installed jaeger-operator on master on k8s version 1.14 and got the following error when deploying jaegertracing.io_jaegers_crd.yaml

```
error: error validating "jaegertracing.io_jaegers_crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.agent.properties.imagePullSecrets): unknown field "x-kubernetes-list-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.agent.properties.tolerations): unknown field "x-kubernetes-list-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.agent.properties.volumeMounts): unknown field "x-kubernetes-list-type".........
```

**Comment by jpkrohling** [comment]
We strive to support as many versions as possible, but we test and support up to N-2 versions, where N is the latest.

**Comment by xichengliudui** [comment]
+1
I'm having the same problem, I'm using operator version 1.8 trying to deploy in the K8S 1.4 cluster, I'm having the same problem.
what is the corresponding kubernetes version of jaeger-operator 1.8?
@dylanyht excuse me, what version of K8S did you finally use？

**Comment by jpkrohling** [comment]
A good first step is to send a PR documenting the current support to the readme file, plus a change to the release document, so that we document this for every future release.

**Comment by dylanyht** [comment]
@xichengliudui  I used version 1.13, but I ended up using the new version deployed in the new cluster

**Comment by myc547** [comment]
+1
me too,I'm used operator version 1.21.2 trying to deploy in the Kubernetes 1.14 cluster.

**Comment by jpkrohling** [comment]
Unfortunately, I think it's clear by now that Kubernetes 1.14 isn't supported with the most recent version of the operator.

**Comment by myc547** [comment]
I suggest describing the version requirements of Kubernetes in the documentation

**Comment by jpkrohling** [comment]
Agree. Would you like to contribute by starting such a doc?

**Comment by myc547** [comment]
Thank you  very much for your invitation, I'm also happy to  contribute a doc, but due to my current work arrangements, i am sorry that i am not qualified for this great thing. However, I will try my best to discuss some issues.
