### ISSUE TITLE
PVC storage 

### ISSUE THREAD

**Issue by vinaymanne5** [jaegertracing/jaeger-operator#1357]
We have deployed  custom pvc volume in jaeger allinone strategy. we are not able to see the pvc after deployment success.
Could you please suggest here

      storage:
        type: jbod
        volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
          storageClassName: standard

**Comment by objectiser** [comment]
The [badger example](https://github.com/jaegertracing/jaeger-operator/blob/master/examples/with-badger-and-volume.yaml) shows that the volume/mounts are defined at the same level as the `storage` node.

I'll close - but reopen if still an issue.
