### ISSUE TITLE
error="no kind is registered for the type v1.Route"

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#136]
The OpenShift-specific feature of creating a Route for the Query deployment seems to be broken after the migration to the SDK 0.1.0:

```
ERRO[0009] failed to create                              error="no kind is registered for the type v1.Route"
ERRO[0009] failed to create                              error="no kind is registered for the type v1.Route" instance="&{{Jaeger io.jaegertracing/v1alpha1} {simplest  default /apis/io.jaegertracing/v1alpha1/namespaces/default/jaegers/simplest 13d08c78-f318-11e8-8426-525400eb2ad2 2518 1 2018-11-28 15:15:37 +0100 CET <nil> <nil> map[] map[] [] nil [] } {allInOne {jaegertracing/all-in-one:1.8 {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} { jaegertracing/jaeger-agent:1.8 {map[]} {[] [] map[] {map[] map[]}}} {{[]}} {memory {map[]} {<nil>   }} {<nil> oauth-proxy {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
```

**Comment by pavolloffay** [comment]
Any tips how to fix this?

**Comment by pavolloffay** [comment]
This seems to be the fix https://github.com/operator-framework/operator-sdk/issues/477, but the SDK changed so `k8sutil.AddToSDKScheme(route.Install)` has to be changed to the new API

**Comment by camilamacedo86** [comment]
It shows be deprecated since the k8sutil.AddToSDKScheme does no longer exist. Also, see https://github.com/operator-framework/operator-sdk/blob/c3a77eee021a1cc6a31861a0efd253dc23fbe591/doc/user-guide.md#register-with-the-managers-scheme

**Comment by camilamacedo86** [comment]
Hi folks, 

Could you help me with https://github.com/operator-framework/operator-sdk/issues/1365?
