### ISSUE TITLE
Jaeger Operator Expects Elasticsearch resource in logging.openshift.io/v1

### ISSUE THREAD

**Issue by jaitaiwan** [jaegertracing/jaeger-operator#1369]
Hey Folks,

I've been trying to get Jaeger Operator to work by default with the es-operator I've installed into the cluster. After a lot of debugging steps I've come across the error:
`no matches for kind "Elasticsearch" in version "logging.openshift.io/v1`

I found this after researching and finding that the `--es-provision` flag (which should be set to `yes` not `true`) is being set to no because the autodetection system couldn't find my ES operator. I suspect it does so by looking at the available resources in the cluster and trying to autodetect the Elasticsearch CRD in the logging.openshift.io/v1 api version but of course on a standard GKE cluster with a manually installed es-operator from https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-installing-eck.html the correct detection should use `elasticsearches elasticsearch.k8s.elastic.co/v1  Elasticsearch`.

This will also likely need to be updated when AWS begins doing releases for their fork of this as well.

**Comment by jpkrohling** [comment]
The auto-provisioning currently works only with the Elasticsearch operator that ships with OpenShift: https://github.com/openshift/elasticsearch-operator

We might change this in the future, but probably not before v2

**Comment by c4m4** [comment]
I am still waiting :)

**Comment by jpkrohling** [comment]
@c4m4, this is unlikely to happen without contributions from users interested in this feature.

**Comment by jaitaiwan** [comment]
@jpkrohling if you can point me to the relevant tests/code portion I might be able to do a PR to fix.

**Comment by jpkrohling** [comment]
First, you'll need to create the CRs to provision the ES cluster here, in this package: https://github.com/jaegertracing/jaeger-operator/tree/master/pkg/storage . You'd need to create another ES set of sources, as we don't want to remove the support for the existing ES operator. 

You'll probably also want to detect which ES operator is available and record this trait somewhere. The auto-detection is made here: https://github.com/jaegertracing/jaeger-operator/tree/master/pkg/autodetect

The controller should then verify which operator was detected in the cluster, and obtain the appropriate CRs. Look at the existing ES code there for reference.

It might be worth coming up with a proposal before working on the whole code, as this might potentially duplicate or make the current code way more complex. Perhaps a more generic way can be used here, abstracting away which operator is going to be used?

**Comment by jaitaiwan** [comment]
Thanks. I was wondering the same thing, especially if the CR's start to largely diverge from eachother and then also might need to account for AWS's fork of ElasticSearch as well.

**Comment by jaitaiwan** [comment]
My experience with Go is limited, so it's probably something that is getting beyond my skillset.

**Comment by pavolloffay** [comment]
At the moment there is no plan to add change auto-provisioning/integration with Elastic.co operator.
