### ISSUE TITLE
Failed not finding Kafka object

### ISSUE THREAD

**Issue by juanitomint** [jaegertracing/jaeger-operator#1371]
Hi guys Im trying to deploy a very simple test jaeger and operator fails with:

level=error msg="failed to apply the changes" error="no matches for kind \"Kafka\" in version \"kafka.strimzi.io/v1beta1\"" execution="2021-01-27 14:03:05.42255875 +0000 UTC" instance=jaeger-test namespace=jaeger

` helm install -n jaeger --version 2.18.0 jaeger-operator jaegertracing/jaeger-operator `

the jaeger deployed was:
`apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-test
spec:
  strategy: allInOne # <1>
  allInOne:
    image: jaegertracing/all-in-one:latest # <2>
    # options: # <3>
    #   log-level: debug # <4>
  storage:
    type: memory # <5>
    options: # <6>
      memory: # <7>
        max-traces: 100000
  ingress:
    enabled: true # <8>
  agent:
    strategy: DaemonSet # <9>
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: "" # <10>`
` kubectl get jaegers
NAME          STATUS   VERSION
jaeger-test   Failed  `

**Comment by objectiser** [comment]
Hi @juanitomint did you install the strimzi operator? https://strimzi.io/

**Comment by juanitomint** [comment]
yes the strimzi operator is installed...@objectiser

**Comment by objectiser** [comment]
@juanitomint  Could you run `kubectl get crds | grep strimzi` and provide the output?

@jpkrohling Any other suggestions - I've checked strimzi and it appears `kafka.strimzi.io/v1beta1` is still the most recent version - and as CRDs are cluster wide (so shouldn't be affected whether strimzi operator is namespaced/cluster scoped), the only reason I can see that this error would occur is if the CRD hasn't been installed?

**Comment by juanitomint** [comment]
sure 
`juanb@v8 ~ $ kubectl get crds | grep strimzi
kafkaconnects.kafka.strimzi.io               2019-05-03T17:26:37Z
kafkaconnects2is.kafka.strimzi.io            2019-05-03T17:26:36Z
kafkamirrormakers.kafka.strimzi.io           2019-05-03T17:26:37Z
kafkas.kafka.strimzi.io                      2019-05-03T17:26:30Z
kafkatopics.kafka.strimzi.io                 2019-05-03T17:26:35Z
kafkausers.kafka.strimzi.io                  2019-05-03T17:26:32Z
`

**Comment by Anna-Katona** [comment]
Not sure if it is still relevant...
What is the output of 
`kubectl get crd kafkas.kafka.strimzi.io -o jsonpath="{.spec.versions[*].name}"` ?
Does it have 'v1beta1' in the list?

In my case there was only v1beta2 because I installed too new kafka-operator. It was resolved after I removed CRDs and installed 0.19.0 for example

**Comment by bwand** [comment]
I am getting the same problem. Trying to install the simplest Jaeger with the operator and getting:
`time="2021-06-22T14:49:35Z" level=error msg="failed to apply the changes" error="no matches for kind \"Kafka\" in version \"kafka.strimzi.io/v1beta1\"" execution="2021-06-22 14:49:34.392092441 +0000 UTC" instance=simplest namespace=default`

I have Strimzi deployed in version 0.23.0 and do not want to go back to 0.19.0.

**Comment by jpkrohling** [comment]
@rubenvp8510, could you please take a look at this one?

**Comment by bwand** [comment]
Hi, could you give me any hint how I can get around that problem without downgrading Strimzi Kafka to an old outdated version?

**Comment by rubenvp8510** [comment]
Unfortunately the current version of jaeger-operator doesn't support newer versions of Strimzi , this is due changes on the CRD and the fact that the new version doesn't support `kafka.strimzi.io/v1beta1` anymore but only `kafka.strimzi.io/v1beta2`.

In order to support newer versions of Strimzi operator ( kafka.strimzi.io/v1beta2` ) there is some work in progress : https://github.com/jaegertracing/jaeger-operator/pull/1495

**Comment by rubenvp8510** [comment]
https://github.com/jaegertracing/jaeger-operator/pull/1495 fixes this. Closing the issue.
