### ISSUE TITLE
Request to release a minor version for the operator

### ISSUE THREAD

**Issue by lujiajing1126** [jaegertracing/jaeger-operator#1385]
In the past few months, I have opened two issues (#1318, #1360) which do have a large impact on our services in both production and beta clusters.

Since these issues are already resolved by PR #1319 and #1368 , I request for a minor release in order to apply these bug fixes in our environment as suggested by @jpkrohling in the private communication.

Thanks in advance.

**Comment by lujiajing1126** [comment]
I have closed #1360

**Comment by jpkrohling** [comment]
To clarify: the next minor release would include this fix, but we'll only release the next minor release once the next minor version of Jaeger is released. What we can do now is a patch release. See #1386.
