### ISSUE TITLE
add ability to indicate PriorityClass for agent in jaeger operator crd

### ISSUE THREAD

**Issue by elkh510** [jaegertracing/jaeger-operator#1387]
hi, 
please add ability to indicate [PriorityClass](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass) for agent(parameter in deployment or daemonset) in jaeger operator [crd](https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml).

**Comment by elkh510** [comment]
@jpkrohling pls review
https://github.com/jaegertracing/jaeger-operator/pull/1392

**Comment by romanp-lohika-tix** [comment]
@jpkrohling hi
pr #1392 was merged 
where can we expect the release?
thank you!

**Comment by elkh510** [comment]
@jpkrohling hi
pr #1392 was merged
where can we expect the release?
thank you!

**Comment by jpkrohling** [comment]
We should be having a new release in the next couple of weeks, following the next release of Jaeger itself.
