### ISSUE TITLE
Our k8s provider mandates the use of backoffLimit <=3.

### ISSUE THREAD

**Issue by arjuncreativo** [jaegertracing/jaeger-operator#1424]
How can I set backoffLimit for storage type elasticsearch under esIndexCleaner and dependencies

```
time="2021-04-05T08:05:30Z" level=error msg="failed to apply the changes" error="admission webhook \"xxxxxx.webhook\" denied the request: Job spec in CronJob must set 'backoffLimit' <= 3" execution="2021-04-05 08:05:30.031265563 +0000 UTC" instance=jaeger-tracing-prd namespace=xxxxxxxxx
```

**Comment by jpkrohling** [comment]
Seems like a good first issue. Would you like to send a PR for this? You'd need to change this struct to accommodate the new field:

https://github.com/jaegertracing/jaeger-operator/blob/65490e8fdc240b3bf9a25297dfc1627372134791/pkg/apis/jaegertracing/v1/jaeger_types.go#L603-L624

Make sure to add the same field to other places that also create cronjobs, such as the JaegerDependenciesSpec and JaegerCassandraCreateSchemaSpec.

You'll then be able to use it here:

https://github.com/jaegertracing/jaeger-operator/blob/65490e8fdc240b3bf9a25297dfc1627372134791/pkg/cronjob/es_index_cleaner.go#L48-L99

Make sure to add a test and docs for this.

**Comment by chasekiefer** [comment]
I'm giving this a try and am looking to finish up by modifying the docs. Should I open a separate PR into the documentation repository?

**Comment by jpkrohling** [comment]
Yes, please create a new PR for the docs repo, linking to this PR here. The changes there should be applied only to the `next-release` directory. Thanks!

**Comment by chasekiefer** [comment]
@jpkrohling So I've been working through writing the docs but it appears https://www.jaegertracing.io/docs/1.22/operator/ doesn’t dive very deep into the CRD options. It seems like only pretty high-level features are mentioned. Does this deserve a mention in the docs?

**Comment by jpkrohling** [comment]
Right, sorry, it should probably be kept only as a godoc in the relevant Go type. We'll eventually figure out a way to properly document the whole CRD based on that.

**Comment by chasekiefer** [comment]
I added the godoc but I had to open a new PR. It should be good to go now!
