### ISSUE TITLE
Update to Strimzi 0.23

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1428]
The next version of Strimzi might require updates on our side. The operator might then need to be updated to reflect that. This ticket is to both assess the impact and to prepare the code to handle it.

**Comment by jpkrohling** [comment]
@rubenvp8510 may I assign this to you?

**Comment by rubenvp8510** [comment]
Yes, I'll take care

**Comment by rubenvp8510** [comment]
I think we can close this one . It was addressed on https://github.com/jaegertracing/jaeger-operator/pull/1495
