### ISSUE TITLE
Default jaeger version set to 1.21.0 instead of 1.22.0 for operator 1.22.0

### ISSUE THREAD

**Issue by LeoHexspoor** [jaegertracing/jaeger-operator#1433]
I was expecting to see jaeger instances upgrading after upgrading to operator 1.22.0 but looking at the versions.txt the default jaeger version for operator 1.22.0 remains 1.21.0.

Give the following text in the docs I would expect operator 1.22 to use jaeger 1.22 as well:

> Each version of the Jaeger Operator follows one Jaeger version. Whenever a new version of the Jaeger Operator is installed, all the Jaeger instances managed by the operator will be upgraded to the Operator’s supported version. For example, an instance named simplest that was created with Jaeger Operator 1.12.0 will be running Jaeger 1.12.0. Once the Jaeger Operator is upgraded to 1.13.0, the instance simplest will be upgraded to the version 1.13.0, following the official upgrade instructions from the Jaeger project.

Can I use jaeger 1.22.0 with controller 1.22 and if so how do I overwrite the default version?

**Comment by rubenvp8510** [comment]
There is an issue in the latest release, the Jaeger version wasn't bumped.

This PR prepares a new release that should fix this issue: https://github.com/jaegertracing/jaeger-operator/pull/1432

**Comment by jpkrohling** [comment]
Once 1.22.1 is released, would you be willing to verify it?

**Comment by LeoHexspoor** [comment]
@jpkrohling Certainly!

**Comment by LeoHexspoor** [comment]
@jpkrohling I've rolled out 1.22.1 and it's working as expected. My jaeger instances were migrated to 1.22. Thanks!

**Comment by LeoHexspoor** [comment]
I was a bit quick to say everything was working as expected. This issue can be closed as Jaeger instances and sidecars got migrated properly to v1.22.0. But there was an issue with some lost configuration, I've logged a separate issue for this #1437.
