### ISSUE TITLE
Test examples

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#144]
examples in `deploy/examples` could be tested using a simple smoke test introduced in #143.

The goal is to avoid having broken examples. 

We could also reduce examples to let's say 3
- allinOne 
- prod elastic
- prod cassandra

**Comment by objectiser** [comment]
Agree examples should be tested - but might need more examples, as some features are independent of the strategy or storage type. For example, UI configuration, sampling, etc.

**Comment by jpkrohling** [comment]
As a consumer of this information, I find it easier to see an example containing only the feature I want to enable.

Agree that we do need to QE those examples from time to time, or automatically.

**Comment by jpkrohling** [comment]
@kevinearls is this something you'd be interested in doing?

**Comment by kevinearls** [comment]
@jpkrohling Sure, go ahead and assign it to me.

**Comment by pavolloffay** [comment]
@kevinearls can we close this? Is this one?

**Comment by kevinearls** [comment]
@pavolloffay The tests I wrote for #582 covered many but not all of the examples.  So I guess it depends on whether we think the other ones need to be added.  

deploy/examples/auto-provision-kafka may require some changes to the testing framework.

**Comment by pavolloffay** [comment]
I will close this then and we can add new tests when required.
