### ISSUE TITLE
Double check that the deprecated/removed options for 1.22 are migrated

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1442]
Jaeger v1.22 removed a few deprecated options, as seen in the release notes here: https://github.com/jaegertracing/jaeger/releases/tag/v1.22.0

At least one option wasn't properly migrated, as evidenced by #1441. This ticket is to assess whether any other properties are missing.

**Comment by jpkrohling** [comment]
Apparently, we had this in an old migration:

https://github.com/jaegertracing/jaeger-operator/blob/5e9b39e9e091bb171b27edd61d02c7273cf6f55f/pkg/upgrade/v1_18_0.go#L23-L48

It would then be worth investigating what went wrong with #1441 and check how we could have prevented it from happening.

**Comment by rubenvp8510** [comment]
This is the list of flags removed on 1.22

- [ ] `--cassandra.tls` is replaced by `--cassandra.tls.enabled`
- [ ] `--cassandra-archive.tls` is replaced by `--cassandra-archive.tls.enabled`
- [ ] `--collector.grpc.tls` is replaced by `--collector.grpc.tls.enabled`
- [ ] `--collector.grpc.tls.client.ca` is replaced by `--collector.grpc.tls.client-ca`
- [ ] `--es.tls` is replaced by `--es.tls.enabled`
- [ ] `--es-archive.tls` is replaced by `--es-archive.tls.enabled`
- [ ] `--kafka.consumer.tls` is replaced by `--kafka.consumer.tls.enabled`
- [ ] `--kafka.producer.tls` is replaced by `--kafka.producer.tls.enabled`
- [ ] `--reporter.grpc.tls` is replaced by `--reporter.grpc.tls.enabled`
- [ ] Replace` --query.port` and -`-query.host-port `with `--query.http-server.host-port` and `--query.grpc-server.host-port     `
- [ ] `--collector.http-port` is replaced by `--collector.http-server.host-port`
- [ ] `--collector.grpc-port` is replaced by `--collector.grpc-server.host-port`
- [ ] `--collector.zipkin.http-port` is replaced by `--collector.zipkin.host-port`
- [ ]  `--health-check-http-port` & `--admin-http-port`, replaced by--admin.http.host-port
- [ ]  `--es.max-num-spans` replaced by `--es.max-doc-count`
- [ ]  `--jaeger.tags` replaced by `--agent.tags`
- [ ] Remove `--cassandra.enable-dependencies-v2`, Jaeger will automatically detect the version of the dependencies table
- [ ] `--cassandra.tls.verify-host` is replaced by `--cassandra.tls.skip-host-verify` instead
- [ ] `--downsampling.hashsalt` removed from jaeger-query
- [ ] `--downsampling.ratio` removed from jaeger-query

Also need to verify where env vars are used, replace with properly names.

**Comment by rubenvp8510** [comment]
> Apparently, we had this in an old migration:
> 
> https://github.com/jaegertracing/jaeger-operator/blob/5e9b39e9e091bb171b27edd61d02c7273cf6f55f/pkg/upgrade/v1_18_0.go#L23-L48
> 
> It would then be worth investigating what went wrong with #1441 and check how we could have prevented it from happening.

The reason of this migrating failed is because we are using environment variables for zipkin port/host, not the flags. Those environment variables should be migrated on the first reconciliation, but we didn't renamed before release 1.22. My fault was to focus only on migrate the flags

May be it worth to add some e2e tests?

**Comment by jpkrohling** [comment]
>May be it worth to add some e2e tests?

Not sure, there was a bug in the tests as well, not sure we would have caught this with e2e tests.

**Comment by rubenvp8510** [comment]
@jpkrohling Can we close this one?

**Comment by jpkrohling** [comment]
Was there a PR as part of this?

**Comment by rubenvp8510** [comment]
> Was there a PR as part of this?

Yes, this one: https://github.com/jaegertracing/jaeger-operator/pull/1449 

Also, I put a check list here, and verified that each of the flags where migrated. =)
