### ISSUE TITLE
Streaming stretegy and kafka auth.

### ISSUE THREAD

**Issue by VincenzoDo** [jaegertracing/jaeger-operator#1453]
Hello,

I have a question regarding the streaming deployment strategy.

How, if possible, can I pass tls certificate and key as well as the CA certificate to use when authenticating to Kafka brokers? I could not find any examples in the documentation.

Thank you!

Vincenzo

**Comment by jpkrohling** [comment]
You can add the certs to a configmap or secret, mount them as volumes, and specify the CLI flags to the ingester/collector to use that.

This is how you can mount volumes:

https://github.com/jaegertracing/jaeger-operator/blob/03f5722996b4462c70cc21b3dfb972ef32073755/examples/simple-prod-with-volumes.yaml#L14-L19

This is how you can pass options to the underlying binary:

https://github.com/jaegertracing/jaeger-operator/blob/03f5722996b4462c70cc21b3dfb972ef32073755/examples/all-in-one-with-options.yaml#L9-L12

And here's a list of options that you can use with all the binaries: https://www.jaegertracing.io/docs/1.22/cli/#jaeger-collector-kafka

Of special mentions:

```
--kafka.producer.tls.ca
--kafka.consumer.tls.ca

--kafka.producer.tls.cert
--kafka.consumer.tls.cert
--kafka.producer.tls.key
--kafka.consumer.tls.key
```
