### ISSUE TITLE
cassandraCreateSchema job not support specify node to schedule

### ISSUE THREAD

**Issue by LuChenjing** [jaegertracing/jaeger-operator#1471]
## Requirement - what kind of business use case are you trying to solve?
I hope can set the `affinity` for `cassandraCreateSchema` job just like other jaeger components.

**Comment by jpkrohling** [comment]
Would you be willing to send a pull request?

**Comment by chasekiefer** [comment]
If there is still value in this I could take it on.

**Comment by LuChenjing** [comment]
Sorry for the late reply... 
@chasekiefer Appreciate it. Hope it been merged soon.
