### ISSUE TITLE
Service selector does not match custom Deployment labels

### ISSUE THREAD

**Issue by Gerrit-K** [jaegertracing/jaeger-operator#1479]
**Describe the bug**
When creating a `Jaeger` object with custom `labels`, they are propagated to the `Deployment` (and hence the `Pod`) correctly, but unfortunately not to the `Service`(s). This is especially causing issues if you (intentionally or by accident) try to override the default labels, such as `app.kubernetes.io/name`, because then the `Service`s do not match the `Pod` labels anymore.

It might be debatable that a user should be allowed to overwrite those default labels, but it should at least be consistent (i.e. either override them everywhere, including the `Service`s, or disallow that in the `Deployment` as well) in order to not break the overall application.

**To Reproduce**
1. Deploy a `Jaeger` instance with `spec: { labels: { "app.kubernetes.io/name": "jaeger-with-custom-name" } }` (be sure to  use a different name than for the `Jaeger` object itself)

**Expected behavior**
The `Service` selectors should match the respective `Deployment`, even when using custom labels.

**Version (please complete the following information):**
 - OS: Linux nodes on AKS
 - Jaeger version: 1.22.1 (Operator image version)
 - Deployment: Kubernetes

**Comment by jpkrohling** [comment]
The right behavior should to not allow reserved labels to be overridden. The operator relies on them in different places in the reconciliation.
