### ISSUE TITLE
Support Customization of Deployment Strategy

### ISSUE THREAD

**Issue by ethernoy** [jaegertracing/jaeger-operator#1480]
## Requirement - what kind of business use case are you trying to solve?

Customize deployment strategy of allinone/collector/query deployment (recreate/rollingupdate)

## Problem - what in Jaeger blocks you from solving the requirement?

Unable to customize deployment strategy of allinone, which is default to rollingupdate. I bind a pvc to jaeger allinone container to enable badger persistent storage. Due to platform restriction, this pvc can only allow one binding from pod simultaneously. When I update the jaeger CR, the deployment of jaeger allinone image is updated and it deploys another replicaset before terminating the original deployment and fails because of the pvc limitation. Allowing customization of deployment strategy should solve this issue.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a field deployment strategy in jaeger CRD and let jaeger operator update the related field in deployment accordingly.

**Comment by jpkrohling** [comment]
Would you like to send a PR with a fix for this? Should be relatively easy, let me know if you need references.

**Comment by ethernoy** [comment]
> Would you like to send a PR with a fix for this? Should be relatively easy, let me know if you need references.

Sure, I am glad to do that.

**Comment by jpkrohling** [comment]
Sure. Take a look at this PR, which did something similar (new field in the CRD, using it in the deployment for collector/query, tests, re-generated manifest files)

https://github.com/jaegertracing/jaeger-operator/pull/1413
