### ISSUE TITLE
Sidecar is not removed when annotation is changed to false

### ISSUE THREAD

**Issue by HannanSolo** [jaegertracing/jaeger-operator#1497]
**Describe the bug**
Operator doesn't remove sidecar based on annotation, only adds it.

**To Reproduce**
1. Create a deployment with sidecar.jaegertracing.io/inject set to true
2. Spin it up
3. Apply changed deployment with sidecar.jaegertracing.io/inject set to false

**Expected behavior**
Expect the operator to spin down the agent side car

**Version (please complete the following information):**
 - Jaeger version: 1.23
 - Deployment:  Kubernetes

**What troubleshooting steps did you try?**
I was able to make it work only when I completely delete the deployment and create it again with the false value. If I do a rollout or delete the pod, it will always spin up with a side car.

**Additional context**

Even when the annotation value is blank or the annotation is removed it still keeps the side car.
on https://www.jaegertracing.io/docs/1.23/operator/#install-modes It says 
"watch all deployments, to inject or remove sidecars based on the sidecar.jaegertracing.io/inject annotation"
It doesn't remove it, so I want my money back >:(

**Comment by mfz85** [comment]
can I work on this one?

**Comment by jpkrohling** [comment]
It's yours, @mfz85!
