### ISSUE TITLE
Outdated CONTRIBUTING.md

### ISSUE THREAD

**Issue by jan25** [jaegertracing/jaeger-operator#1498]
**Describe the bug**

I was trying to setup this repository for first time and found [CONTRIBUTING.md](https://github.com/jaegertracing/jaeger-operator/blob/master/CONTRIBUTING.md#developing) has outdated instructions:
- `make run` tries to install 0.18 version of operator-sdk which is quite old
- make commands needs fixes to use `examples/` instead of `deploy/`, this is missed during refactoring examples maybe

**To Reproduce**
```
make run
kubectl apply -f deploy/examples/simplest.yaml
kubectl get jaegers
kubectl get pods
```

**Expected behavior**
I would expect following above steps in CONTRIBUTING.md would create pods with all in one strategy.

**Version (please complete the following information):**
 - OS: darwin20.0

**Comment by jpkrohling** [comment]
Would you mind sending in a PR?

> make run tries to install 0.18 version of operator-sdk which is quite old

That's unfortunately correct. We need this specific version, as the next one brings a lot of breaking changes. We do plan on using a recent version of the operator-sdk for the v2.
