### ISSUE TITLE
spark dependencies missing image pull secrets or service account

### ISSUE THREAD

**Issue by snuggie12** [jaegertracing/jaeger-operator#1503]
## Requirement - what kind of business use case are you trying to solve?

Was trying to use my own docker image server for the spark dependencies, but upon changing the image I ran into image pull backoffs. Best I can tell, you can't set either `imagePullSecrets` (preferred) or a `serviceAccount` which could have that set.

## Problem - what in Jaeger blocks you from solving the requirement?

For compliance reasons we want to use our own image server.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add `imagePullSecrets` to https://github.com/jaegertracing/jaeger-operator/blob/a9cd80bf9def2d3a33f2522d701fc393af09013b/pkg/apis/jaegertracing/v1/jaeger_types.go#L598

**Comment by jpkrohling** [comment]
You actually can indeed set the service account: the struct you linked embeds `JaegerCommonSpec`, which does include the service account:

https://github.com/jaegertracing/jaeger-operator/blob/a9cd80bf9def2d3a33f2522d701fc393af09013b/pkg/apis/jaegertracing/v1/jaeger_types.go#L197-L231

And it seems like the spark dependencies job does take it into account:

https://github.com/jaegertracing/jaeger-operator/blob/a9cd80bf9def2d3a33f2522d701fc393af09013b/pkg/cronjob/spark_dependencies.go#L107

I'm closing this, as I believe what you requested should just work, but if you have further evidence that this is not the case, feel free to reopen.

**Comment by snuggie12** [comment]
Yeah, I just plane missed it; even looked for it.

`imagePullSecrets` would be better like there is for the agent, but I can make do.

If I was reading correct, you can't add `imagePullSecrets` to the `jaeger` sa? So it sounds like I have to make a duplicate sa and then make sure it gets the same rbac as `jaeger`?

**Comment by jpkrohling** [comment]
The `jaeger` SA is managed by the operator, if you change it to include a pull secret, it might (and likely will) be reverted by the operator. You are encouraged to duplicate the SA and use that one instead.
