### ISSUE TITLE
Write e2e tests for the case when injection annotation is false

### ISSUE THREAD

**Issue by rubenvp8510** [jaegertracing/jaeger-operator#1518]
This issue is to follow up the work started on  https://github.com/jaegertracing/jaeger-operator/pull/1508

That PR fixes https://github.com/jaegertracing/jaeger-operator/issues/1497 but we also need E2E tests. The test should be written using `kuttl`

**Comment by mfz85** [comment]
can I work on this one @jpkrohling, as accorded on the previous PR ?

**Comment by jpkrohling** [comment]
It's yours!
