### ISSUE TITLE
cannot create jaeger-collector using CR on separate NS from operator

### ISSUE THREAD

**Issue by oxeye-schmil** [jaegertracing/jaeger-operator#1532]
### k8s environment
minikube

### created operator with following commands

`kubectl apply -f observability_ns.yaml`
`kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml`
`kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml`
`kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml`
`kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml`
`kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml`
`kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role.yaml`
`kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role_binding.yaml`

### create all in one
```
kubectl apply -n myapp -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
EOF
```

### Result: no pods running
`~ kubectl -n myapp get jaegers`
`NAME       STATUS   VERSION   STRATEGY   STORAGE   AGE`
`simplest                                           13m`
`~ kubectl -n myapp get pods -l app.kubernetes.io/instance=simplest`
`No resources found in myapp namespace`

**Comment by jpkrohling** [comment]
By default, the operator will watch only for resources in the same namespace it's running. You can either create the CR in the same namespace (`kubectl apply -n observability ...`), or change the operator to watch for resources in all namespaces, which requires the cluster-wide permissions (which seems that you applied already).
