### ISSUE TITLE
Use random ports in port forward and smoketests

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#154]
We use port forward in smoke tests introduced in https://github.com/jaegertracing/jaeger-operator/pull/145.

The test forwards collector and query ports on host machine. However it uses standard ports (e.g. 16686) so the test might fail if there is jaeger server running locally.

Forwarder allows to use random port if it is specified as `:16686` or `0:16686`, however random ports are not exposed in the currently used version of go-client. Version 1.13.0 added API to get used ports.

**Comment by jpkrohling** [comment]
Is this still a goal?

**Comment by pavolloffay** [comment]
This was done in https://github.com/jaegertracing/jaeger-operator/pull/862
