### ISSUE TITLE
Add the ability to the KUTTL tests to be run in a real cluster

### ISSUE THREAD

**Issue by iblancasa** [jaegertracing/jaeger-operator#1556]
## Requirement - what kind of business use case are you trying to solve?
Add the ability to the [KUTTL](https://kuttl.dev/) tests to be run in a real cluster

## Problem - what in Jaeger blocks you from solving the requirement?
With the current automation in the `Makefile`, it is not possible to run the KUTTL tests in a real cluster. The KUTTL tests are run in a [kind](https://kind.sigs.k8s.io/) cluster but it would be really nice if we allow running them in other clusters like [OpenShift](https://www.redhat.com/es/technologies/cloud-computing/openshift) and [minikube](https://minikube.sigs.k8s.io/).

Some things to solve:
* Add a way to push the `asserts:e2e` Docker image to a Docker registry to allow the cluster to pull it
* Allow the modification of the `YAML` files that are part of the KUTTL tests to point to the correct images (for instance, point to the pushed `asserts:e2e` Docker image)
* Avoid running the `start-kind` `make` target when running the tests again a real cluster

## Proposal - what do you suggest to solve the problem or improve the existing situation?
It would be needed to add a new `make` target to push the `asserts:e2e` Docker image to a Docker registry.

Also, I think it would be a good idea to templatize the `KUTTL` test `YAML`
files. This can be really helpful because we have some situations where it can be interesting:
* Changing easily where the Docker images are hosted to pull them
* We run the same tests for different configurations. Since there is not a way to create "`functions`" in `YAML`, this solution would avoid duplicating `YAML` files
* Copy the files that are the same for all the configurations (like an Elasticsearch configuration, for instance)
* We can add logic to generate a test or not depending on the platform (`OpenShift`, `Kubernetes`, `minikube`). I was not able to find a way to implement this logic directly with KUTTL.

**Comment by iblancasa** [comment]
Please, I would like to work on this task :)

**Comment by jpkrohling** [comment]
kuttl does support running the tests in different envs:

https://kuttl.dev/docs/testing/test-environments.html

**Comment by iblancasa** [comment]
@jpkrohling I know but, currently, our automation doesn't. It is prepared to just run the test in the `kind` cluster. The idea is to allow easily to run in a different environment. One of the reasons is the `asserts:e2e` Docker image is not pushed anywhere and is loaded directly in the `kind` cluster. So, doing the modifications I suggest in the first comment, we can run the testes in all the environments supported by KUTTL.
