### ISSUE TITLE
Facing issues in getting the IP address to access Jaeger-UI on Linux platform

### ISSUE THREAD

**Issue by odidev** [jaegertracing/jaeger-operator#1568]
**Describe the bug**

Hi Team, 

I am working on jaeger deployment using jaeger-operators on the Ubuntu Linux/AMD64 machine using minikube. 

I have followed the [docs](https://github.com/jaegertracing/jaeger-operator#getting-started), addon ingress to minikube, installed operator using given yaml files, and activated extra features. Then created the jaeger instance once jaeger-operator is ready with namespace ‘observability’, following the above linked documentation. 

Below is the output of `kubectl get all -n observability`: 
~~~ 
$ kubectl get all -n observability 

NAME                                 READY   STATUS    RESTARTS   AGE 
pod/jaeger-operator-dbf5767c-8dgjf   1/1     Running   0          92m 
pod/simplest-5675c68699-c7wgp        1/1     Running   0          89m   

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                  AGE 
service/jaeger-operator-metrics       ClusterIP   10.97.208.223   <none>        8383/TCP,8686/TCP                        92m 
service/simplest-agent                ClusterIP   None            <none>        5775/UDP,5778/TCP,6831/UDP,6832/UDP      89m 
service/simplest-collector            ClusterIP   10.99.48.59     <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   89m 
service/simplest-collector-headless   ClusterIP   None            <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   89m 
service/simplest-query                ClusterIP   10.104.172.28   <none>        16686/TCP,16685/TCP                      89m 

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE 
deployment.apps/jaeger-operator   1/1     1            1           92m 
deployment.apps/simplest          1/1     1            1           89m 

NAME                                       DESIRED   CURRENT   READY   AGE 
replicaset.apps/jaeger-operator-dbf5767c   1         1         1       92m 
replicaset.apps/simplest-5675c68699        1         1         1       89m 
~~~ 

However, I am not getting the value of address, where Jaeger-UI is available. Below is the ingress information: 
~~~ 
$ kubectl get -n observability ingress 

NAME             CLASS    HOSTS   ADDRESS   PORTS   AGE 
simplest-query   <none>   *                 80      25h 
~~~ 

I have verified that ingress is addon to minikube.  

Can you please provide some pointers on what could be the issue here?    

**To Reproduce**

I have exactly followed the [getting started](https://github.com/jaegertracing/jaeger-operator#getting-started) document.

**Expected behavior**

Ingress should serve the Jaeger-UI and IP address must be returned.

**Screenshots**

NA

**Version (please complete the following information):**

 - OS: Linux
 - Jaeger version: master branch
 - Deployment: minikube

**What troubleshooting steps did you try?**

Checked that ingress is addon to minikube.

**Additional context**

NA

**Comment by odidev** [comment]
Hello Team, can you please review this issue?

**Comment by antoniomerlin** [comment]
Hi, did your cluster having Ingress controller to satisfy the ingress, merely creating the ingress resource will have no effect.

**Comment by antoniomerlin** [comment]
![Screenshot from 2024-02-05 16-35-53](https://github.com/jaegertracing/jaeger-operator/assets/4397319/a0a8a684-d01c-4a4b-a281-a54d06b829d5)
Refer this one https://kubernetes.github.io/ingress-nginx/deploy/
OR
i think try by adding this in simplest-query ingresses metadata after some time you'll get loadbalancer IP in status of this ingresses.
```
annotations:
    kubernetes.io/ingress.class: nginx
```
