### ISSUE TITLE
Migrate CronJob from batch/v1beta1 to batch/v1

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#1585]
```
W1018 09:49:01.504879 1398543 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1018 09:49:01.750729 1398543 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

https://kubernetes.io/releases/_print/#release-history

We should clarify since batch/v1 is supported in k8s and OCP.

**Comment by iblancasa** [comment]
@rubenvp8510 yes
We need to upgrade the `k8s` Golang package to v0.21.0 or newer. Is that ok?

**Comment by rubenvp8510** [comment]
I think is fine, eventually we will upgrade some dependencies here: https://github.com/jaegertracing/jaeger-operator/pull/1561

**Comment by iblancasa** [comment]
I gave a try but it seems the task is more complex than expected. Some dependencies require `k8s.io/api/batch/v2alpha1` but that is not longer available... One of those dependencies seems to be the `operator-sdk` so... that work seems to be part of #1561

**Comment by kevinearls** [comment]
I'm going to work on this
