### ISSUE TITLE
Cannot use HorizontalPodAutoscaling: injected agent lacks resource defs

### ISSUE THREAD

**Issue by sgmiller** [jaegertracing/jaeger-operator#160]
The kube-controller-manager can't autoscale our deployments with an injected Jaeger agent, as the injected container defines no CPU or Memory requests and/or limits.  

```
kube-controller-manager-ip-10-0-1-4.us-east-2.compute.internal kube-controller-manager E1205 19:17:47.410801       1 horizontal.go:188] failed to compute desired number of replicas based on listed metrics for Deployment/default/podredacted: failed to get cpu utilization: missing request for cpu on container jaeger-agent in pod default/podredacted
kube-controller-manager-ip-10-0-1-4.us-east-2.compute.internal kube-controller-manager I1205 19:17:47.410855       1 event.go:221] Event(v1.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"default", Name:"podredacted", UID:"c393ace0-cbd6-11e7-9783-021516797582", APIVersion:"autoscaling/v2beta1", ResourceVersion:"161801118", FieldPath:""}): type: 'Warning' reason: 'FailedGetResourceMetric' missing request for cpu on container jaeger-agent in pod default/podredacted
```

**Comment by jpkrohling** [comment]
Good catch!

What would be a suitable solution? Copy the values from the main pod? Inherit possible values from the JaegerSpec?

**Comment by jpkrohling** [comment]
Would you be interested in draft a PR with that? I think the most appropriate would be as a conf in the Operator's YAML (CR), instead of `ConfigMap` and I do like the idea of letting an application override it via annotations.

**Comment by annanay25** [comment]
I could give this a shot :) @jpkrohling

**Comment by annanay25** [comment]
Looking forward to this! :D

**Comment by jpkrohling** [comment]
@annanay25 do you have any news on this?

**Comment by jpkrohling** [comment]
I'm closing this, as we have a "resources" node in the injected container now. @sgmiller, please check it out and reopen this issue if you think there's still something to do here.

**Comment by sgmiller** [comment]
Nope, that should do it.

**Comment by igaskin** [comment]
I'm trying to configure this in my deployment, but it is not clear to me from the docs where these limits are added.  Can you add something to  https://www.jaegertracing.io/docs/1.13/operator/#auto-injecting-jaeger-agent-sidecars doc, or a snippet in this issue to help those who may have the same problem?

**Comment by jpkrohling** [comment]
Good catch about the operator not being able to update existing sidecars.

@rubenvp8510: the problem @igaskin reported is similar to #454 and #453. Would you be interested in working on it?

**Comment by rubenvp8510** [comment]
@jpkrohling Yes, I can start working on that .
