### ISSUE TITLE
AllInOne doesn't support priorityClass 

### ISSUE THREAD

**Issue by arminc** [jaegertracing/jaeger-operator#1601]
**Describe the bug**
The query, agent and collector allow us to set the `priorityClassName` but the AllInOne doesn't.

**To Reproduce**
AllInOne doesn't have the `priorityClassName` https://github.com/jaegertracing/jaeger-operator/blob/39bdf765d8cef2a81456111d3d9b88e2e7cf9509/pkg/apis/jaegertracing/v1/jaeger_types.go#L368

While the Collector for example does have it: https://github.com/jaegertracing/jaeger-operator/blob/39bdf765d8cef2a81456111d3d9b88e2e7cf9509/pkg/apis/jaegertracing/v1/jaeger_types.go#L441

**Expected behavior**
To be able to specify `priorityClassName` for the AllInOne.

**Version (please complete the following information):**
Latest

**Comment by pavolloffay** [comment]
thanks for submitting the issue. 

@arminc would you like to contribute this feature?

**Comment by arminc** [comment]
@pavolloffay I was planning to but very busy, will try to fix it when I can find some time.

**Comment by djsly** [comment]
@pavolloffay the esCleaner doesnt support priorityClass neither, I'm not sure if we should add that as a requirement to this issue @arminc  or if its best to create another issue just for the esCleaner job

**Comment by CSP197** [comment]
@pavolloffay 
if this issue is still pending, I can pick it up. It looks like an easy feature.

I can add the priorityClass option to the `JaegerAllInOneSpec` as well as the `JaegerEsIndexCleanerSpec` as needed

**Comment by sonofgibs** [comment]
@arminc @pavolloffay the above pr solves this issue and is ready for review thanks!
