### ISSUE TITLE
Update docs after operator-sdk version bump to 1.13

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#1624]
https://github.com/jaegertracing/jaeger-operator/pull/1623 updated operator SDK to 1.13. Now we should update readme and https://www.jaegertracing.io/docs/1.28/operator/#installing-the-operator-on-kubernetes how to install the operator.

**Comment by rubenvp8510** [comment]
Fixes with this PR: https://github.com/jaegertracing/jaeger-operator/pull/1635 now the installation steps points to Jaeger page.
