### ISSUE TITLE
No deploy directory

### ISSUE THREAD

**Issue by williamwang97** [jaegertracing/jaeger-operator#1630]
Kubernetes cannot be deployed using jaeger-operator because there is no deploy directory in the master branch

**Comment by wikilele** [comment]
Hi,
I have your same problem.
While waiting I think that we can reference a previous commit.
We can do like this
wget https://raw.githubusercontent.com/jaegertracing/jaeger-operator/863caeb028c54dbd92c86ad54f4fce14abee9784/deploy/crds/jaegertracing.io_jaegers_crd.yaml

**Comment by jpkrohling** [comment]
This is the PR that caused the problem: https://github.com/jaegertracing/jaeger-operator/pull/1623

**Comment by pavolloffay** [comment]
Folks in the meantime just to not depend on the master and use released version https://github.com/jaegertracing/jaeger-operator/tree/v1.28.0.

We had to make the cut and update the project to the latest operator-sdk. @rubenvp8510 will have a look at this and change the docs to use pinned version instead.

**Comment by jpkrohling** [comment]
The readme file should have been changed accordingly in the same PR. As of now, the getting started part of the readme still points people to the deploy directory.

**Comment by pavolloffay** [comment]
indeed, the readme is one place and the docs is the second place. It should be consolidated to a single location and use a tagged version in the first place.

**Comment by pavolloffay** [comment]
@jpkrohling FYI https://github.com/jaegertracing/documentation/pull/370

**Comment by rubenvp8510** [comment]
Fixes here: https://github.com/jaegertracing/jaeger-operator/pull/1635 and here: https://github.com/jaegertracing/documentation/pull/538

**Comment by venkataphaniv** [comment]
Try this:

https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.28.0/deploy/operator.yaml

Replace 1.28 with 1.27, 1.26... and it worked for me.
