### ISSUE TITLE
ServiceMonitor manifest breaks Kubernetes OLM install

### ISSUE THREAD

**Issue by rkukura** [jaegertracing/jaeger-operator#1683]
**Describe the bug**
When attempting to publish jaeger-operator v1.29.1 to the Operator Hub Community Operators repositories, the community-operators CI failed with "api-server resource not found installing ServiceMonitor jaeger-operator-metrics-monitor: GroupVersionKind monitoring.coreos.com/v1, Kind=ServiceMonitor not found on the cluster", while the community-operators-prod CI passed. I worked around the issue for the release by removing the monitoring-related manifests from the bundle. The monitoring functionality should be available on Kubernetes when the ServiceMonitor CRD is available.

**To Reproduce**
1. Push a release PR to an Operator Hub repository, as in step 7 of https://github.com/jaegertracing/jaeger-operator/blob/master/RELEASE.md.
2. See that the community-operators CI job fails.

**Expected behavior**
The Operator Hub CI job should pass and monitoring should be usable on Kubernetes.

**Comment by rubenvp8510** [comment]
As we decided to not include the ServiceMonitor resource on the community operator hub I think we can close this.

WDTY? @rkukura
