### ISSUE TITLE
Jaeger operator is spamming logs with "Waited for Xs due to client-side throttling, not priority and fairness"

### ISSUE THREAD

**Issue by rakesh-garimella** [jaegertracing/jaeger-operator#1684]
**Describe the bug**

I tried to upgrade the Jaeger operator to the version 1.29.1 on kubernetes. I used the deployment stratergy of `allinone`. When I check the logs of the jaeger operator I see that following logs appear almost evert second
```
I1217 12:10:20.274563       1 request.go:668] Waited for 1.540277s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/apiextensions.k8s.io/v1?timeout=32s
I1217 12:10:30.274983       1 request.go:668] Waited for 1.5175147s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/networking.k8s.io/v1?timeout=32s
I1217 12:10:40.325410       1 request.go:668] Waited for 1.577647s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/node.k8s.io/v1?timeout=32s
I1217 12:10:54.740491       1 request.go:668] Waited for 1.0375806s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/events.k8s.io/v1?timeout=32s
```

I am upgrading Jaeger operator from 1.18.1 to 1.29.1. This behaviour was not seen in jaeger operator 1.18.1.

I think the autodetect feature of jaeger operator is trying to look for all the crds present on the kubernetes cluster. May be this [PR](https://github.com/jaegertracing/jaeger-operator/pull/1608/files) might have caused the issue. 

Another difference to the charts I see is now jaeger [crd(version 1.29.1)](https://github.com/jaegertracing/helm-charts/blob/jaeger-operator-2.27.1/charts/jaeger-operator/crds/crd.yaml) is quite exhaustive (compared to [crd](https://github.com/jaegertracing/helm-charts/blob/jaeger-operator-2.16.0/charts/jaeger-operator/crds/crd.yaml) of 1.18) can this also lead to this issue ?

Is there someway to supress these messages as they dont look something serious.

**To Reproduce**
1. Install jaeger operator with 1.18.1 (strategy (`allinone`))
2. Upgrade to latest Jaeger operator (1.29.1)
3. Check the logs of the jaeger operator

**Expected behavior**
The operator logs should be clean.

**Screenshots**

**Version (please complete the following information):**
 - OS: k3d running on mac OS.
 - Jaeger version: Jaeger operator version 1.29.1
 - Deployment: Kubernetes on k3d and GCP

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by rubenvp8510** [comment]
I'll try to dig more into this tomorrow morning, my understanding is that this is not affecting the functionality right?

Anyway it will be good to know the root cause of this and see if we can suppress the logs or fix the underlying cause.
