### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#1685]
Jaeger main repo, ui and idl already switched to main.

**Comment by pavolloffay** [comment]
@iblancasa / @rubenvp8510 would you like to take this one?

**Comment by iblancasa** [comment]
@pavolloffay I don’t have admin permissions in this repo… so, I can not perform that change

**Comment by rubenvp8510** [comment]
I can do it :)

**Comment by pavolloffay** [comment]
The Github CI workflows were not updated for the main branch
