### ISSUE TITLE
How to add QUERY_BASE_PATH env var to query

### ISSUE THREAD

**Issue by pteroctopus** [jaegertracing/jaeger-operator#1686]
I don't see an option in jaeger-operator helm chart to add an additional environment variable to query.
I would like to run query ui on different context path.

Jaeger documentation says that for that QUERY_BASE_PATH environment variable needs to be set.

Where to set it?

This doesn't work:

      query:
        replicas: 1
        serviceType: ClusterIP
        env:
          - name: QUERY_BASE_PATH
            value: query

**Comment by pavolloffay** [comment]
Note that this is not helm chart repo. The query base path in the operator can be set in the CR `.spec.query.options.query.base-path`

**Comment by pteroctopus** [comment]
Thank you.
