### ISSUE TITLE
v1.29.0 and later fail to start with default allInOne strategy: ElasticsearchList missing

### ISSUE THREAD

**Issue by mrethers** [jaegertracing/jaeger-operator#1687]
**Describe the bug**
After upgrading to v1.29.0, my Jaeger CR fails when using all defaults (AllInOne, memory storage). The controller indicates the following error:

```
2021-12-22T00:40:02.243Z	ERROR	controller-runtime.manager.controller.jaeger	Reconciler error	{"reconciler group": "jaegertracing.io", "reconciler kind": "Jaeger", "name": "jaeger", "namespace": "perficient-operators", "error": "no kind is registered for the type v1.ElasticsearchList in scheme \"pkg/runtime/scheme.go:100\""}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214
```

**To Reproduce**
1. Install operator v1.29.0+ on Openshift
2. Create a default Jaeger CR
3. Observe the controller logs

**Expected behavior**
Operator should not care about Elasticsearch when the strategy is allInOne and continue with memory storage. I haven't tested when the strategy is Elasticsearch but I'm assuming it would also fail....

**Version (please complete the following information):**
 - Openshift 4.8
 - Jaeger Operator v.1.29.0

**What troubleshooting steps did you try?**
Downgrading to v1.28.0 worked

**Additional context**
Seems like the migration to operator-sdk 1.13 in commit 91e3b69ee5c8761bbda9d3cf431400a73fc1112a is missing the registration of the Elasticsearch kind?

There was a similar issue reported previously: https://github.com/jaegertracing/jaeger-operator/pull/366/files

**Comment by rubenvp8510** [comment]
HI thanks for catching this issue, I'll try to reproduce it,

It is strange that the e2e tests haven't cached this before.
