### ISSUE TITLE
Sidecar e2e tests are missing in the workflow

### ISSUE THREAD

**Issue by lujiajing1126** [jaegertracing/jaeger-operator#1692]
**Describe the bug**
Sidecar e2e tests are missing in the workflow

**To Reproduce**

**Expected behavior**

Run E2E for tests/e2e/sidecard.

Expect sidecar E2E tests for PR #1679 

**Screenshots**

**Version (please complete the following information):**

**What troubleshooting steps did you try?**

**Additional context**

**Comment by rubenvp8510** [comment]
@iblancasa Could you take a look please'

**Comment by iblancasa** [comment]
Yes, I'll work on this as soon as #1556 is finished
