### ISSUE TITLE
Jaeger operator default metrics port changed in the app, but not in the chart

### ISSUE THREAD

**Issue by skhalash** [jaegertracing/jaeger-operator#1697]
**Describe the bug**
In https://github.com/jaegertracing/jaeger-operator/pull/1647, the default metrics port was changed from 8383 to 8080. However, this change was not reflected in the Helm chart. The container port is still 8383 (for example, [here](https://github.com/jaegertracing/helm-charts/blob/jaeger-operator-2.27.1/charts/jaeger-operator/templates/deployment.yaml#L46) and [here](https://github.com/jaegertracing/helm-charts/blob/jaeger-operator-2.27.1/charts/jaeger-operator/templates/service.yaml#L17)). Generally speaking, from the PR's changelist it's not clear why the default port was changed at all.

**To Reproduce**
1. `helm install tracing jaegertracing/jaeger-operator`
2. `kubectl port-forward tracing-jaeger-operator-metrics 8383`
3. `curl localhost:8383/metrics`
4. `kubectl port-forward` throws the following error:
```
Forwarding from 127.0.0.1:8383 -> 8383
Forwarding from [::1]:8383 -> 8383
Handling connection for 8383
E0104 14:38:28.362665   31041 portforward.go:406] an error occurred forwarding 8383 -> 8383: error forwarding port 8383 to pod 18688a9a29c82e559ccbc0e518afb1860a12c9fff5685e92c2d13bc3c70a3def, uid : failed to execute portforward in network namespace "/var/run/netns/cni-b8444608-7fd3-db57-c89a-f9f75ae6fa13": failed to dial 8383: dial tcp4 127.0.0.1:8383: connect: connection refused
E0104 14:38:28.363151   31041 portforward.go:234] lost connection to pod
```

**Expected behavior**
Get a valid response with operator metrics.

**Screenshots**

**Version (please complete the following information):**
 - Jaeger Operator version: 1.29.1
 - Deployment: Kubernetes (k3d)
 - k3d version v5.1.0
 - k3s version v1.21.5-k3s2

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by rubenvp8510** [comment]
Sorry, this was happens when we migrated to the new SDK, which in the project structure has another default port, but there is no strong reason to change it, I'll set it to the previous default port to avoid breaking things again.

**Comment by skhalash** [comment]
Great, thanks!
