### ISSUE TITLE
Add METRICS_STORAGE_TYPE support

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger-operator#1700]
## Requirement - what kind of business use case are you trying to solve?

For context: https://cloud-native.slack.com/archives/CGG7NFUJ3/p1640003084352300

Add ability for jaeger-query to opt-into querying aggregated span metrics from prometheus.

## Problem - what in Jaeger blocks you from solving the requirement?

This is enabled by setting the `METRICS_STORAGE_TYPE` env var to `prometheus`.

However, it's not possible to define environment variables in jaeger-operator.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Follow a similar pattern to how `SPAN_STORAGE_TYPE` is defined in jaeger-operator via the `spec.storage.type` path, for example, [this is how jaeger-query defines it](https://github.com/jaegertracing/jaeger-operator/blob/91e3b69ee5c8761bbda9d3cf431400a73fc1112a/pkg/deployment/query.go#L138).

From a brief glance, the proposal is to support a `spec.metrics.type` path in both [query](https://github.com/jaegertracing/jaeger-operator/blob/91e3b69ee5c8761bbda9d3cf431400a73fc1112a/pkg/deployment/query.go#L136) and [all-in-one](https://github.com/jaegertracing/jaeger-operator/blob/91e3b69ee5c8761bbda9d3cf431400a73fc1112a/pkg/deployment/all_in_one.go#L146) that will assign this value to the `METRICS_STORAGE_TYPE` env var.

**Comment by JaredTan95** [comment]
and `PROMETHEUS_SERVER_URL ` also need to be added, right?

**Comment by albertteoh** [comment]
> and PROMETHEUS_SERVER_URL also need to be added, right?

_I think_ we won't need to from what I gather in [@jpkrohling's comment](https://cloud-native.slack.com/archives/CGG7NFUJ3/p1640595672034500?thread_ts=1640003084.352300&cid=CGG7NFUJ3):

> if this can't be configured via flags (which the operator does support), the operator has to be changed to support it

because we can configure this via the `--prometheus.server-url` flag.

**Comment by JaredTan95** [comment]
I am interested in this feature
