### ISSUE TITLE
Remote sampling strategy returns default instead of configured one

### ISSUE THREAD

**Issue by pteroctopus** [jaegertracing/jaeger-operator#1705]
Sampling strategy is defined in operator configuration:

      sampling:
        options:
          default_strategy:
            type: const
            param: 1

But clients are still getting default sampling configuration. Also agent and collector endpoints for configuration are returning default:

# Collector endpoint:
```
curl 'http:/10.202.47.202:14268/api/sampling?service=aaa'
{"strategyType":"PROBABILISTIC","probabilisticSampling":{"samplingRate":0.001}}
```

# Agent endpoint:
```
curl 'http://10.202.2.241:5778?service=aaa'
{"strategyType":0,"probabilisticSampling":{"samplingRate":0.001}}
```

Config map and collector file have the right configuration but they are returning the default:

#Configmap: jaeger-operator-jaeger-sampling-configuration
```
apiVersion: v1
data: 
  sampling: '{"default_strategy":{"param":1,"type":"const"}}'                                                                                                                               
kind: ConfigMap
```

# Collector file:
```
/ # uname -n
jaeger-operator-jaeger-collector-5ff45cdc9b-kkkwf
/ # cat /etc/jaeger/sampling/sampling.json 
{"default_strategy":{"param":1,"type":"const"}}
```

**To Reproduce**
1. Install jaeger operator and set sampling strategy as defined on top of the issue
2. Client will not get type: const, param: 1 configuration but the default one probabilistic, sampling rate: 0.001
3. Also curl 'http:/collector-host:14268/api/sampling?service=aaa' will retrurn the default probabilistic one instead of const

**Expected behavior**
Expected behaviour is that collector and agent endpoints will return the configured sampling strategy instead of default one.

**Version (please complete the following information):**
 - Jaeger operator helm chart version: 2.27.1
 - OS: Linux 
 - Kubernetes: v1.21.2
 - Deployment: Kubernetes

**Comment by pteroctopus** [comment]
I'm adding my values.yaml. Strategy is streaming. Agents are configured as daemonset:

jaeger-operator:
  image:
    repository: jaegertracing/jaeger-operator
    tag: 1.29.1
    pullPolicy: IfNotPresent
    imagePullSecrets: []

  crd:
    install: true

  jaeger:
    create: true
    namespace:
    spec:
      strategy: streaming
      collector:
        autoscale: true
        maxReplicas: 5
        minReplicas: 2
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        options:
          sampling:
            strategies-reload-interval: 30s
          kafka:
            producer:
              topic: internal.jaeger-spans
              brokers: REMOVED
              batch-size: 128000
              batch-linger: 1s
              batch-max-messages: 100
      ingester:
        autoscale: true
        maxReplicas: 8
        minReplicas: 2
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        options:
          kafka:
            consumer:
              topic: jaeger-spans
              brokers: REMOVED
          ingester:
            deadlockInterval: 60m0s
      storage:
        type: elasticsearch
        options:
          es:
            server-urls: REMOVED
            tags-as-fields:
              all: true
            tls:
              ca: /es/certificates/ca.crt
        secretName: jaeger-es-auth-secret
      volumeMounts:
        - name: certificates
          mountPath: /es/certificates/
          readOnly: true
      volumes:
        - name: certificates
          secret:
            secretName: jaeger-es-http-certs-public
      query:
        replicas: 1
        serviceType: ClusterIP
      agent:
        strategy: DaemonSet
      sampling:
        options:
          default_strategy:
            type: const
            param: 1
      ingress:
        enabled: false

  rbac:
    # Specifies whether RBAC resources should be created
    create: true
    pspEnabled: false
    clusterRole: true

  service:
    type: ClusterIP
    # Specify a specific node port when type is NodePort
    # nodePort: 32500
    # Annotations for service
    annotations: {}

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template
    name:
    # Annotations for serviceAccount
    annotations: {}

  # Specifies extra environment variables passed to the operator:
  #extraEnv: []
  extraEnv:
    # Specifies log-level for the operator:
    - name: LOG-LEVEL
      value: debug

  extraLabels: {}
    # Specifies extra labels for the operator deployment:
    # foo: bar

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  securityContext: {}

  priorityClassName:

**Comment by pteroctopus** [comment]
In collector logs I see this warning message:

 {"level":"warn","ts":1641896088.730515,"caller":"static/strategy_store.go:323","msg":"Failed to parse sampling strategy","strategy":{"type":"const","param":1}}

**Comment by pteroctopus** [comment]
Settings sampling to probabilistic doesn't cause the same problem. This works as expected.

```
      sampling:
        options:
          default_strategy:
            type: probabilistic
            param: 1
```

 But const: 1 doesn't as described in top post.

**Comment by rubenvp8510** [comment]
The only possible values for file sampling type are `probabilistic` and `ratelimiting`, This is for controlling the sampling configuration remotely, you can still use const sampling in your clients if you don't want to use the remote sampling feature.


https://www.jaegertracing.io/docs/1.30/sampling/#file-sampling


> service_strategies element defines service specific sampling strategies and operation_strategies defines operation specific sampling strategies. There are 2 types of strategies possible: probabilistic and ratelimiting which are described above (NOTE: ratelimiting is not supported for operation_strategies). default_strategy defines the catch-all sampling strategy that is propagated if the service is not included as part of service_strategies

**Comment by rubenvp8510** [comment]
@pteroctopus Does that works for you? Or is this still an issue ?

**Comment by pteroctopus** [comment]
This works for me. Thank you.
