### ISSUE TITLE
v1.30.0/jaeger-operator not found

### ISSUE THREAD

**Issue by JaredTan95** [jaegertracing/jaeger-operator#1710]
**Describe the bug**
as described from https://www.jaegertracing.io/docs/1.30/operator/,

```bash
kubectl create namespace observability # <1>
kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.30.0/jaeger-operator.yaml -n observability # <2>
```

but could not download it as it was not found.

**Comment by rubenvp8510** [comment]
This should be fixed in this PR: https://github.com/jaegertracing/jaeger-operator/pull/1711 

We still need to release the operator for 1.30.0 that is why the image was not found.

**Comment by JaredTan95** [comment]
got it.
