### ISSUE TITLE
Docs say 1.3 is latest, but github says its 1.29

### ISSUE THREAD

**Issue by leberknecht** [jaegertracing/jaeger-operator#1721]
**Describe the bug**
https://www.jaegertracing.io/docs/1.30/operator/ says to run `kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.30.0/jaeger-operator.yaml -n observability # <2>` which points to a non-existing release, github says `1.29.1` is latest.

Maybe im missing something here..?

**To Reproduce**
1. try to follow https://www.jaegertracing.io/docs/1.30/getting-started/
2.
3.

**Expected behavior**
Docs and github should be in sync

**Comment by rubenvp8510** [comment]
1.30.0 Is out,
https://github.com/jaegertracing/jaeger-operator/releases/tag/v1.30.0

That should fix this issue, I'm gonna close this ticket, but if this is still a problem we can open it again or open a new one.
