### ISSUE TITLE
Split the E2E tests into different GitHub Actions workflows

### ISSUE THREAD

**Issue by iblancasa** [jaegertracing/jaeger-operator#1726]
## Requirement - what kind of business use case are you trying to solve?
Make faster to recover from CI flaky E2E tests.

## Problem - what in Jaeger blocks you from solving the requirement?
Currently, when something fails in the E2E tests, it is needed to rerun the full set of E2E tests. The idea is to split the GitHub workflow in a way it is not needed to rerun tests that are working (or, at least, reduce the number of tests to rerun).

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Split the E2E test into different GitHub Actions workflows.

**Comment by frzifus** [comment]
Issue can be closed?

**Comment by iblancasa** [comment]
Yes
