### ISSUE TITLE
CRD validation does not catch invalid options

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#1733]
**Describe the bug**
Creating a Jaeger instance with Cassandra storage and setting an object as env key causes a panic.

**To Reproduce**
1. Add a Cassandra storage to a spec
2. Use an object as `ENV` key

**Expected behavior**
An error message when creating an instance with invalid parameters.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.28 and above
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
See: https://github.com/jaegertracing/jaeger-operator/issues/1649#issuecomment-1001271023

**Additional context**
See: https://github.com/jaegertracing/jaeger-operator/issues/1649

**Comment by pavolloffay** [comment]
Just a note, we should validate all options objects from the CR, not just for storage/cassandra but as well for query, collector etc.
