### ISSUE TITLE
add retry mechanism for e2e test workflows

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#1750]
## Requirement - what kind of business use case are you trying to solve?

It seems that the e2e sometimes fail. Instead of having to re-trigger the complete ci logic manually, an automatic retry behavior would be nice.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

So far, I have not dealt with it much. I found [this action](https://github.com/marketplace/actions/retry-step) online. Alternatively, someone [here](https://github.community/t/how-to-retry-a-failed-step-in-github-actions-workflow/125880) describes how to implement a retry logic itself.

## Any open questions to address

What are your thoughts?

---

// cc : @rubenvp8510 @iblancasa

**Comment by iblancasa** [comment]
Thanks for opening this issue! Yes, I agree we are having some problems related to the CI. 🤔  The most of the issues I've seen in the last days are related to downloading resources from the Internet like the Golang dependencies and pulling container images. I'm preparing a PR to speedup the build of the E2E environments and I think most of those problems will disappear. It is based on #1715. But yes, we need something extra. I'll take care of this. 😄 Thanks!

**Comment by frzifus** [comment]
if we can't download dependencies to build / test, maybe it would make sense to put them in a container image?
Our Build image could then call our make rules in the cl.
Just an idea:
```bash
make_ci_test_with_dep:
    docker run --rm -it build_img_with_deps bash -c "make test_with_dep"
---
make ci_test_with_dep 
```

Thanks for taking care :)

**Comment by iblancasa** [comment]
I added some retry mechanisms and I think we can close this issue. What do you think @frzifus?

**Comment by frzifus** [comment]
sure :+1:
