### ISSUE TITLE
Expose OTEL environment variables too

### ISSUE THREAD

**Issue by ctron** [jaegertracing/jaeger-operator#1754]
## Requirement - what kind of business use case are you trying to solve?

Expose (additionally) in deployments:

* `OTEL_SERVICE_NAME`
* `OTEL_PROPAGATORS`

Also see: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter

## Problem - what in Jaeger blocks you from solving the requirement?

Some implementations actually go for the (newer?) OpenTelemetry specification of these variables. And so adding the existing `JAEGER_*" variants get ignored. Exposing the `OTEL_*`  variants would bring back the out-of-box behavior.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Expose the variables listed above in addition to current variables.

**Comment by pavolloffay** [comment]
`OTEL_` env variables are used to configure OpenTelemetry clients - SDK or instrumentation. Jaeger-operator does not have any functionality that handles clients. 

Please take a look at https://github.com/open-telemetry/opentelemetry-operator and Instrumentation Kind which offers client side configuration.
