### ISSUE TITLE
 no matches for kind "Certificate" in version "cert-manager.io/v1" | no matches for kind "Issuer" in version "cert-manager.io/v1"

### ISSUE THREAD

**Issue by abhishekgoldypathak** [jaegertracing/jaeger-operator#1761]
Getting 2 errors while installing the k8 manifest. Looks like maybe a kubectl / k8 API version mismatch. I am not able to find this k8 API and kind in k8 API docs.

apiVersion: cert-manager.io/v1
kind: Certificate

Details of my error in the attached screenshots.

![Screenshot 2022-02-18 at 8 36 55 PM](https://user-images.githubusercontent.com/80172803/154709115-f09942de-f919-4395-9e90-21166a3fc62b.png)

![Screenshot 2022-02-18 at 8 39 59 PM](https://user-images.githubusercontent.com/80172803/154709106-002d56dd-7d2a-46d4-9662-2042e5b32267.png)

Should I delete this observability namespace and try an older version of jaeger manifest? Is there a compatibility matrix for kubectl to Jaeger manifest version mapping?

**Comment by frzifus** [comment]
hi @abhishekgoldypathak, thanks for your report. Seems [cert-manager](https://cert-manager.io/) is not installed. I'll revisit the documentation.

Could you try installing cert-manager and then deploying jaeger-operator again?
```bash
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/1.6.1/cert-manager.yaml
```

**Comment by abhishekgoldypathak** [comment]
1. this seems to be the working command not the one provided

kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/download/v1.6.2/cert-manager.yaml
![Screenshot 2022-02-20 at 4 56 04 PM](https://user-images.githubusercontent.com/80172803/154840254-c91ac26e-2907-4942-a7ec-b33f5b956777.png)

2. after this I get a couple of connection refused errors. I don't recognize this IP 10.107.102.190 - is this some sort of default / hardcoded value?

![Screenshot 2022-02-20 at 4 58 16 PM](https://user-images.githubusercontent.com/80172803/154840292-2a62484b-4fb6-4562-8476-0d6692e284c6.png)

please suggest

**Comment by ivanayov** [comment]
@abhishekgoldypathak I had the same issue and resolved it with canal:

```
kubectl apply -f https://projectcalico.docs.tigera.io/manifests/canal.yaml
```

You might also need some timeout, as cert-manager needs around 2 minutes to deploy successfully.

**Comment by abhishekgoldypathak** [comment]
my cert manager pods don't come up, looks like a wrong node-selector default setting (or something else)
![Screenshot 2022-02-21 at 7 26 36 PM](https://user-images.githubusercontent.com/80172803/154969056-0d8ae186-968c-46aa-b652-386e0a42c435.png)

**Comment by abhishekgoldypathak** [comment]
![Screenshot 2022-02-21 at 7 31 07 PM](https://user-images.githubusercontent.com/80172803/154969745-33518e40-2eb7-4711-8547-0a89c0907e97.png)

**Comment by frzifus** [comment]
mh... `Too many pods` doesnt sound right.

How many pods do you have up and running? e.g. `bc <<< "$(kubectl get pods --all-namespaces | wc -l) - 1"`
The number of pods available would be interesting too. `kubectl cluster-info dump | grep pods -A 10 -B 10`

**Comment by abhishekgoldypathak** [comment]
Interesting catch  - I had my application (product) running which has ~130 total pods - deleted those helm charts and now jaeger comes up..

but logically, what would jaeger trace if I start it with my application brought down :) 
![Screenshot 2022-02-21 at 8 21 52 PM](https://user-images.githubusercontent.com/80172803/154978824-308bc313-56ef-45a6-b690-8325f2346916.png)


however before I go there I don't see the Jaeger UI, no svc running on 16886 port

**Comment by frzifus** [comment]
> but logically, what would jaeger trace if I start it with my application brought down :)

it would trace itself ^^

Until here it looks like you only deployed the operator. You should be able to continue with the [quick-start deploying the allinone image](https://www.jaegertracing.io/docs/1.31/operator/#quick-start---deploying-the-allinone-image).

---
I used this a while ago
```
kubectl apply -n observability -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
EOF
```
then
```bash
kubectl port-forward -n observability svc/simplest-query 8080:16686
```

**Comment by pavolloffay** [comment]
The cert manager was added to docs
