### ISSUE TITLE
Custom ImagePullPolicy

### ISSUE THREAD

**Issue by edenkoveshi** [jaegertracing/jaeger-operator#1768]
## Requirement - what kind of business use case are you trying to solve?

Adding a new imagePullPolicy field to the CRD to allow custom imagePullPolicy value and not the default Kubernetes value.
This can be quite useful for environments with internal registery and it should be quite easy to implement
This is also quite popular in Kubernetes operators.

## Problem - what in Jaeger blocks you from solving the requirement?

The Jaeger operator does not allow custom imagePullPolicy and uses the Kubernetes default on its' Deployments.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add an imagePullPolicy field in the Jaeger CR (under allInOne.spec, query.spec,, etc.)
Propagate it to the Jaeger deployments (if not nil, else use Kubernetes default as it does now)

## Any open questions to address

I'll try and give it a shot but I'm not yet very familiar with the Jaeger operator

**Comment by frzifus** [comment]
Solved here: https://github.com/jaegertracing/jaeger-operator/pull/1798
