### ISSUE TITLE
Upgrade k8s.io/apimachinery from 0.21.3 to 0.23.4

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#1784]
The existing PR https://github.com/jaegertracing/jaeger-operator/pull/1760 is failing with these [errors](https://github.com/jaegertracing/jaeger-operator/actions/runs/1886000973):

![image](https://user-images.githubusercontent.com/10403402/155342260-c4daa824-b905-4a14-8b22-43d0a104caf2.png)

**Comment by frzifus** [comment]
seems appear here too [k8s.io/api #1759](https://github.com/jaegertracing/jaeger-operator/pull/1759)

**Comment by kevinearls** [comment]
@frzifus @rubenvp8510 This has been updated to 0.23.5, so this can be closed
