### ISSUE TITLE
Update Makefile so it installs a new version of controller-gen if needed

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#1814]
## Requirement - what kind of business use case are you trying to solve?

Update the Makefile so that it installs a new version of controller-gen if needed.  I was working on [updating the operator-sdk](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.17.0/) which requires updating controller-gen to v0.8 but the controller-gen target only re installs a new version if it does not find an installed instance.  I had 0,0,1 installed so it didn't do anything.

**Comment by frzifus** [comment]
mh... Can we solve the problem by including the version number in the binary name? like: `controller-gen_v0.8.0`, `controller-gen_v0.0.1`

**Comment by iblancasa** [comment]
Is this issue related to #1841 or something different?

**Comment by kevinearls** [comment]
@iblancasa Yes, I think #1841 fixes this so we can close it.

**Comment by frzifus** [comment]
> Update the Makefile so that it installs a new version of controller-gen if needed.

Since this pr we download a new controller-gen version on every build and not only when it is needed, right?

**Comment by iblancasa** [comment]
I think so. We can follow a similar approach to the one followed with kind, kuttl and other tools (installing them using the scripts from `hack/install`)

**Comment by frzifus** [comment]
sounds good to me. alternatively, we could put the versions name in the binary. as indicated here:
```Make
CONTROLLER_GEN_VER=v0.8.0
CONTROLLER_GEN = $(shell pwd)/bin/controller-gen-$(CONTROLLER_GEN_VER)
controller-gen: ## Download controller-gen locally if necessary.
	# TODO: check if $(CONTROLLER_GEN) exists
	$(VECHO) GOBIN=$(shell pwd)/bin go install -o $(CONTROLLER_GEN) sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_GEN_VER)
```
What do you think? (ps: i have no preference here. Just wanted to take it into consideration.)

**Comment by kevinearls** [comment]
@frzifus I don't know to be honest.  😕 There seems to be multiple different ways to install any tools.  Ideally we'd have something that checks whether you have all of the correct versions of all the tools you need, and if not installs them.   I don't have time to do that at the moment...

**Comment by iblancasa** [comment]
I'll do

**Comment by iblancasa** [comment]
I think we can close this task /cc @rubenvp8510
