### ISSUE TITLE
log line inconsistency

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#1817]
**Describe the bug**
Seems we use plain `logrus` in some places instead of the propagated `logr.Logger` wrapper. on one hand this leads to bad readability, on the other hand i had problems to change the log level in all places at once.

**To Reproduce**
1. Deploy Operator
2. Deploy Jaeger
3. View Operator logs

**Expected behavior**

- Seeing the same format of logs in every line.
- Being able to change log-levels globally.

**Screenshots**
![image](https://user-images.githubusercontent.com/10403402/158548313-ae5f7065-9702-409e-b3ff-f34047109294.png)

**Version (please complete the following information):**
 - Jaeger version: 1.32.0

**Comment by iblancasa** [comment]
What do you think about adding something to ensure the logging is not done using `logrus` directly (from the CI, for instance)? Is something I can work on.

**Comment by frzifus** [comment]
sure, what did you have in mind? Some kind of linting rule? I wouldn't prioritize it too highly, but it would certainly be helpful.

**Comment by iblancasa** [comment]
Yes. Something like looking for usages of `logrus.<Logging function>` and fail when something is found.
I know we first need to fix this but is to avoid new issues in the future. What do you think?

**Comment by frzifus** [comment]
I'm not sure if this will adequately address the issue. Imports are often renamed. Found this in [cmd/generate](https://github.com/jaegertracing/jaeger-operator/blob/main/pkg/cmd/generate/main.go#L105).

e.g.
```golang
	log "github.com/sirupsen/logrus"
```

**Comment by iblancasa** [comment]
Where is the `logr.Logger wrapper` located? I'm not able to find it
