### ISSUE TITLE
e2e test warning, ignoring previous --max-args value

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#1822]
**Describe the bug**
Noticed `xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value`

**To Reproduce**
1. make run-e2e-tests

**Expected behavior**
No ignored arguments (does not sound good)

**Version (please complete the following information):**
 - OS: linux
 - Jaeger version: 1.32

---

cc @iblancasa

**Comment by iblancasa** [comment]
Confirmed. This warning appears in GNU findutils >= 4.9.0

**Comment by iblancasa** [comment]
@frzifus, can we close this issue?
