### ISSUE TITLE
jaeger-operator helm chart option to mount a the cert

### ISSUE THREAD

**Issue by dirkckau** [jaegertracing/jaeger-operator#1859]
## Requirement - what kind of business use case are you trying to solve?

Helm chart

## Problem - what in Jaeger blocks you from solving the requirement?

I found an issue when I was installing Jager-operator 1.32.0 in my cluster using the default helm chart. 
I've cert manager 1.7.2 in my cluster, however, seems the jaeger-operator is missing a mount on the cert.
![image](https://user-images.githubusercontent.com/91056335/163310440-33c165b4-cbc3-481f-8853-6b9ca009b8c3.png)

In my case, I am ok to install the jaeger-operator after I manual created a cert and mount to the jaeger-operator.
But, there are no placeholder on the cert in the helm chart, and I couldn't see the mutation webhook in the cluster. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Add a placeholder of the cert volume in the helm chart.

**Comment by frzifus** [comment]
Hi @dirkckau, I can't say much about helm charts. But the best thing to do is to create an issue on the [helm repo](https://github.com/jaegertracing/helm-charts).

**Comment by avishefi** [comment]
Helm chart PR: https://github.com/jaegertracing/helm-charts/pull/368
