### ISSUE TITLE
Upgrade from 1.32.0 to 1.33.0 fails

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#1870]
**Describe the bug**
I tried to upgrade from Jaeger Operator v1.32.0 to 1.33.0 and it failed.

**To Reproduce**
1.  Start minikube
2. kubectl create observability
3. kubectl apply --namespace observability -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.32.0/jaeger-operator.yaml
4. Wait till the operator finishes deploying
5. kubectl apply --namespace observability -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.33.0/jaeger-operator.yaml

This gave me:

```
[validatingwebhookconfiguration.admissionregistration.k8s.io/jaeger-operator-validating-webhook-configuration](http://validatingwebhookconfiguration.admissionregistration.k8s.io/jaeger-operator-validating-webhook-configuration) configured
The Deployment "jaeger-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"[app.kubernetes.io/name](http://app.kubernetes.io/name)":"jaeger-operator", "name":"jaeger-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Expected behavior**
The operator should upgrade to 1.33.0

**Comment by frzifus** [comment]
thx for reporting, I'll try to take a closer look during the week.

**Comment by ivaske** [comment]
I get the same error but i'm upgrading from 1.31.0

**Comment by frzifus** [comment]
@ivaske did you use OLM or also just a deployment?

**Comment by jkandasa** [comment]
@frzifus root cause for this issue, we have introduced extra match selector label in deployment of the recent build. As per the k8s doc, Deployment's label selector is immutable

#### new selector label:
```
app.kubernetes.io/name: jaeger-operator
```
#### k8s doc
![image](https://user-images.githubusercontent.com/1004403/170920883-0e0fedce-42cb-4646-8165-77525a4ac990.png)
Source: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates

**Comment by frzifus** [comment]
But how do you add more labels via operator sdk? Maybe we want to add more common labels in the future. 

I expected that a deployment is replaced. Is there an csv option to overwrite deployments?

Found this in `kubectl`:
```bash
$ kubectl apply -h | grep overwrite
      --overwrite=true: Automatically resolve conflicts between the modified and live configuration by using values from the modified configuration
```

**Comment by jkandasa** [comment]
@frzifus I am fine with removing the label

**Comment by rubenvp8510** [comment]
I'm fine with removing the label too.

**Comment by frzifus** [comment]
Would like to briefly check if the problem also occurs with olm too. If not, we should extend the documentation that `kubectl apply ... --overwrite ...` is needed.
