### ISSUE TITLE
will jaeger-operator remove zipkin svc?

### ISSUE THREAD

**Issue by lixiangzzz2017** [jaegertracing/jaeger-operator#1871]
**Describe the bug**
jaeger-operator removed zipkin svc exceptedly

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**
this is the log from k8s apiServer
requestURI:/api/v1/namespaces/istio-system/services/zipkin
responseObject:{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Success","details":{"name":"zipkin","kind":"services","uid":"323ae62f-0a6a-421e-82eb-c61930531c60"}}
responseStatus:{"metadata":{},"status":"Success","code":200}
sourceIPs:["172.27.4.158"]
stage:ResponseComplete
stageTimestamp:2022-04-27T01:01:40.924251Z
user:{"username":"system:serviceaccount:observability:jaeger-operator","uid":"ade7b732-c270-4d36-849f-84cbd48e44c8","groups":["system:serviceaccounts","system:serviceaccounts:observability","system:authenticated"]}
userAgent:jaeger-operator/v0.0.0 (linux/amd64) kubernetes/$Format
verb:delete
And this log from stdout of jaeger-operator
1.6510213008411016e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-v1-deployment", "UID": "199690ad-18ad-46ee-8c4c-13d3555e205b", "kind": "apps/v1, Kind=Deployment", "resource": {"group":"apps","version":"v1","resource":"deployments"}}
time="2022-04-27T01:01:40Z" level=info msg="injecting Jaeger Agent sidecar" jaeger=jaeger jaeger-namespace=istio-system namespace=istio-system
1.6510213008462358e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-v1-deployment", "code": 200, "reason": "", "UID": "199690ad-18ad-46ee-8c4c-13d3555e205b", "allowed": true}
1.6510213009332972e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-v1-deployment", "UID": "2d99b7c7-c836-4649-b9dc-21e6885b1076", "kind": "apps/v1, Kind=Deployment", "resource": {"group":"apps","version":"v1","resource":"deployments"}}
time="2022-04-27T01:01:40Z" level=info msg="injecting Jaeger Agent sidecar" jaeger=jaeger jaeger-namespace=istio-system namespace=istio-system
1.651021300934585e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-v1-deployment", "code": 200, "reason": "", "UID": "2d99b7c7-c836-4649-b9dc-21e6885b1076", "allowed": true}
1.6510213009420476e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-v1-deployment", "UID": "3121ae9c-374e-4e1b-b288-225870858dcc", "kind": "apps/v1, Kind=Deployment", "resource": {"group":"apps","version":"v1","resource":"deployments"}}
1.6510213009424481e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-v1-deployment", "code": 200, "reason": "is jeager deployment, we do not touch it", "UID": "3121ae9c-374e-4e1b-b288-225870858dcc", "allowed": true}
1.6510213010242481e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-jaegertracing-io-v1-jaeger", "UID": "5abd7058-e7da-4c37-bec5-8403ffbf5ce7", "kind": "jaegertracing.io/v1, Kind=Jaeger", "resource": {"group":"jaegertracing.io","version":"v1","resource":"jaegers"}}
1.651021301024528e+09	INFO	jaeger-resource	default	{"name": "jaeger"}
1.6510213010250723e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-jaegertracing-io-v1-jaeger", "code": 200, "reason": "", "UID": "5abd7058-e7da-4c37-bec5-8403ffbf5ce7", "allowed": true}
1.6510213010355482e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-jaegertracing-io-v1-jaeger", "UID": "bbdd006a-9ce9-4a28-9e57-5b057917030e", "kind": "jaegertracing.io/v1, Kind=Jaeger", "resource": {"group":"jaegertracing.io","version":"v1","resource":"jaegers"}}
1.6510213010359693e+09	INFO	jaeger-resource	validate update	{"name": "jaeger"}
1.6510213010360072e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-jaegertracing-io-v1-jaeger", "code": 200, "reason": "", "UID": "bbdd006a-9ce9-4a28-9e57-5b057917030e", "allowed": true}

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.33.0
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by iblancasa** [comment]
I just created one Jager deployment and I can see the Zipkin port exposed:
```sh 
$ kubectl get services | ggrep 9411
simple-prod-collector            ClusterIP   10.96.4.148     <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP,4317/TCP,4318/TCP   21s
simple-prod-collector-headless   ClusterIP   None            <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP,4317/TCP,4318/TCP   22s
```

Are you still able to reproduce the problem? Can you provide more information?

**Comment by lixiangzzz2017** [comment]
thank you.It didn't happen any more

**Comment by iblancasa** [comment]
@lixiangzzz2017 awesome!
