### ISSUE TITLE
make run-openshift does not work

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#189]
`make run-openshift` does not deploy jaeger services.  ` oc get jaeger` returns jaeger instances but nothings get deployed.

To reproduce:
```
oc cluster up
oc login -u system:admin
make run-openshift
oc create -f deploy/examples/simple-prod.yaml
oc get all | grep jaeger 
```

**Comment by jpkrohling** [comment]
Is this because of the route problem?

**Comment by pavolloffay** [comment]
I don't think so

**Comment by jpkrohling** [comment]
I'll take a look, thanks for reporting!

**Comment by jpkrohling** [comment]
In which namespace are you on? If you are on `my-project`, could you try switching to `default`? I don't get anything "wrong", except for the problem reported in #136.
