### ISSUE TITLE
Add service for agent daemonset

### ISSUE THREAD

**Issue by nmiculinic** [jaegertracing/jaeger-operator#192]
The title says it all, currently agent doesn't deploy service for the agent daemonset.

**Comment by jpkrohling** [comment]
What's your use case for that? When the agent is deployed as a daemon set, it should be available on all nodes on a given port, so, clients would just send the spans to the node's IP instead of to a "host" (service).

**Comment by nmiculinic** [comment]
Because it's simpler to deploy traefik via helm. It's quicker for quick-start since it needs to know only one serviceIP and I can experiment further. I've tried side-car but for some reason pod annotation didn't work for me. Traefik crashed when it cannot find agent on localhost:port.

In looking over jaeger logs I find it correctly located pod needed for sidecar injection but for some reason, it doesn't perform it. No errors or anything.

**Comment by nmiculinic** [comment]
https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/opentracing/#jaeger

or for example, what's the easiest way to get node's IP into nginx ingress controller?

**Comment by jpkrohling** [comment]
I'm closing this, as I don't think we want services in front of daemonsets. IMO, it kinda defeats the purpose of having agents as daemonsets, as clients would *always* be directed to an instance defined by whatever the service returned, instead of the local node's daemonset. In that case, it's more appropriate to go directly to the collector instead.

**Comment by jpkrohling** [comment]
That said, I'm really open to consider this feature if there's a use case justifying it.

**Comment by nmiculinic** [comment]
I agree with you. This is just traefik helm chart configuration

**Comment by haf-afa** [comment]
> It looks like this controller uses Jaeger Collector, not Agent. For the collector, we do have services already.

No, it uses port 6831; the agent's thrift-udp port. https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/third-party-addons/opentracing.md
