### ISSUE TITLE
Installation instructions link to non-existent Operator yaml

### ISSUE THREAD

**Issue by uberscott** [jaegertracing/jaeger-operator#1934]
**Bad Install Link**
The README.md references [THIS](https://www.jaegertracing.io/docs/1.35/operator/) page used to install the jaeger-operator: (https://www.jaegertracing.io/docs/1.35/operator/)[https://www.jaegertracing.io/docs/1.35/operator/]

Which in turn shows this command to install the operator:
```bash
kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.35.0/jaeger-operator.yaml -n observability
```
Notice that this link does not resolve to anything: [kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.35.0/jaeger-operator.yaml -n observability](kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.35.0/jaeger-operator.yaml -n observability)

**Comment by frzifus** [comment]
Duplicate https://github.com/jaegertracing/jaeger-operator/issues/1927

**Comment by rubenvp8510** [comment]
Yeah, the thing here is that we haven't release yet jaeger operator 1.35.0

**Comment by iblancasa** [comment]
I create an issue in the Jaeger documentation repository: https://github.com/jaegertracing/documentation/issues/580. @rubenvp8510, could you close this issue?

**Comment by rubenvp8510** [comment]
Closing,  moving to documentation repository
