### ISSUE TITLE
Is there a way to add agent service in production strategy 

### ISSUE THREAD

**Issue by ssharma2089** [jaegertracing/jaeger-operator#1941]
When we want to install as a production strategy with elasticsearch as the storage type. Except for the agent service, it only deploys the collector, query, and associated services. I am unable to define an agent address in Traefik setup to trace the application due to the jaeger agent.
I tried to define the agent service as a different deployment under the same namespace, however it remained for couple of hours before disappearing.

I am deploying jaeger as kubernetes deployment not as helm chart.

Below is the yaml for jaeger

apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch 
    options:
      es:
        server-urls: http://elasticsearch-service:9200
        index-prefix: my-prefix
    secretName: jaeger-secret
    
If I change the strategy to ALLINONE, then it work as expected. 

Could you please help me in adding the agent service to the production strategy so that it can be deployed?

**Comment by pavolloffay** [comment]
> When we want to install as a production strategy with elasticsearch as the storage type. Except for the agent service, it only deploys the collector, query, and associated services.

This is expected the production strategy deploys only collector and query. The agent can be deployed as a sidecar or daemonset 

 * https://www.jaegertracing.io/docs/1.35/operator/#installing-the-agent-as-daemonset 
 * https://www.jaegertracing.io/docs/1.35/operator/#auto-injecting-jaeger-agent-sidecars

Please re-open if there are still issues.

**Comment by ssharma2089** [comment]
@pavolloffay Thank you for clarifying. 
But why does the agent service object disappear after a few hours? I have been unable to get trace result due to your disappearing. 
When I choose Traefik service in the Jaeger UI and click on Find Traces, an error appears **"no trace result. Try another query "**
It will work if I create an agent service and then click on find trace in UI.

Below is the deployment for agent service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: simple-prod
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simple-prod-agent
    app.kubernetes.io/part-of: jaeger
  name: simple-prod-agent
  namespace: observability
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: zk-compact-trft
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: http-config-rest
    port: 5778
    protocol: TCP
    targetPort: 5778
  - name: jg-compact-trft
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jg-binary-trft
    port: 6832
    protocol: UDP
    targetPort: 6832
  selector:
    app: jaeger
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: simple-prod
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simple-prod-agent
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP
