### ISSUE TITLE
Trying to install jaeger-operator version 1.35.0 doesn't work due to the release not being present

### ISSUE THREAD

**Issue by soenkeliebau** [jaegertracing/jaeger-operator#1945]
**Describe the bug**
In the latest version of the documentation the [installation section](https://www.jaegertracing.io/docs/1.35/operator/#installing-the-operator-on-kubernetes) states to run the following command to install the operator:

`kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.35.0/jaeger-operator.yaml -n observability`

**To Reproduce**
1. Get an empty k8s cluster (or at least one without the jaeger operator deployed already)
2. Run `kubectl create namespace observability`
3. Run `kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.35.0/jaeger-operator.yaml -n observability`

Note: The steps leave out the installation of cert-manager, because for this exact error that is irrelevant.

**Expected behavior**
The Jaeger operator should be installed and started, instead step 3 fails with the following error:

> error: unable to read URL "https://github.com/jaegertracing/jaeger-operator/releases/download/v1.35.0/jaeger-operator.yaml", server reported 404 Not Found, status code=404

This is probably due to the 1.35.0 release not yet having been created in the operator repository. 
This may be intentional, I am not sure of release policy here.

**Screenshots**
![image](https://user-images.githubusercontent.com/1070361/172828783-4cfb0f40-39df-4dd3-855b-59b512fc057f.png)

**Version (please complete the following information):**
 - OS: Arch Linux
 - Jaeger version: 1.35.0 (not really applicable here, as the installation never starts)
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
Went to https://github.com/jaegertracing/jaeger-operator/releases and checked for the existance of the referenced release.

**Comment by frzifus** [comment]
Duplicate https://github.com/jaegertracing/jaeger-operator/issues/1927, https://github.com/jaegertracing/documentation/issues/580

**Comment by soenkeliebau** [comment]
Apologies, I'll close this.
