### ISSUE TITLE
Add username/password support to es index cleaner job

### ISSUE THREAD

**Issue by gregoryfranklin** [jaegertracing/jaeger-operator#196]
Related to https://github.com/jaegertracing/jaeger/issues/1317

The supplied es index cleaner cronjob is unable to run against elasticsearch clusters that require authentication.

I propose populating ES_USERNAME and ES_PASSWORD using the storage secret (assuming https://github.com/jaegertracing/jaeger/pull/1318 gets accepted as is).

**Comment by gregoryfranklin** [comment]
This is the proposed change: https://github.com/gregoryfranklin/jaeger-operator/commit/865ef67f87813f89105153be1fce8f6616c212b9
depending on https://github.com/jaegertracing/jaeger/pull/1318

**Comment by jpkrohling** [comment]
@gregoryfranklin feel free to send the PR and add "WIP" in the title, removing it when it's ready to be merged.
