### ISSUE TITLE
Upgrade otel packages to the latest version

### ISSUE THREAD

**Issue by iblancasa** [jaegertracing/jaeger-operator#1966]
## Requirement - what kind of business use case are you trying to solve?
Upgrade the otel dependency packages to the latest version.

Current used version of the otel packages is v0.20.0. This version was published Apr 23, 2021. We should upgrade this dependency to the latest version (v1.7.0 when this issue was opened)

**Comment by frzifus** [comment]
Maybe that [reference](https://github.com/frzifus/jaeger-otel-test/commit/96a352b4a181ff43213c7ffc578b39ca1cfe2451) can help.

**Comment by MdSahil-oss** [comment]
@iblancasa I'd like to work on this issue.

**Comment by frzifus** [comment]
Its yours :)

**Comment by frzifus** [comment]
@MdSahil-oss are you still working on #2031 ?

**Comment by MdSahil-oss** [comment]
Yes! I have a PR with this Issue

**Comment by volmedo** [comment]
@frzifus @iblancasa I'm looking for projects to contribute to as part of Hacktoberfest 2022. Do you think it would be interesting for me to work on this issue?

**Comment by frzifus** [comment]
Hi @volmedo, i cant say if its `interesting`. You will learn a bit about the recent API change. But it would definitely be valuable and shoudnt be too much effort.

**Comment by volmedo** [comment]
@frzifus sorry I expressed it badly 😅. What I wanted to say was in the line of it being interesting to the project, so if you say it'd be valuable, that answers my question. I'll work on it!
