### ISSUE TITLE
autoscale E2E tests are flaky because the number of replicas is not the expected one

### ISSUE THREAD

**Issue by iblancasa** [jaegertracing/jaeger-operator#1968]
Those tests depend on the number of replicas. Sometimes, the platform is strong enough to start less replicas than 5 (the expected ones).

We should include some logic to avoid this kind of random issues but check the autoscalability works properly.

**Comment by iblancasa** [comment]
@frzifus could you assign this issue to me? Thanks!

**Comment by frzifus** [comment]
Sure :)
