### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by sta-szek** [jaegertracing/jaeger-operator#1983]
**Describe the bug**
The error happens sometimes, i guess some process triggers that.
Please ignore `This field was missing!!!!!!!!` as it is our internal message.

Please find attached file with surrouding logs 

[On_demand_report_2022-07-05T10_54_28.180Z_d7538140-fc50-11ec-84ba-cf7f04fb0981.csv](https://github.com/jaegertracing/jaeger-operator/files/9045750/On_demand_report_2022-07-05T10_54_28.180Z_d7538140-fc50-11ec-84ba-cf7f04fb0981.csv)

**Comment by frzifus** [comment]
hi @sta-szek what Operator version are you running?

**Comment by iblancasa** [comment]
I think he is using 1.34.x because the `viper` and `controller-runtime` versions are the same as the ones used for that release.

**Comment by sta-szek** [comment]
@frzifus sorry for late response, at the time being we used:

```
version: 2.32.2
appVersion: 1.34.1
```

but the issue also occured with latest:

```
version: 2.35.0
appVersion: 1.37.0
```

two days ago

**Comment by DodgeCamaro** [comment]
faced with the same error
version: 2.39.0
appVersion: 1.39.0

**Comment by iblancasa** [comment]
@DodgeCamaro could you provide some kind of reproducer?
