### ISSUE TITLE
Reverse io.jaegertracing apiGroup

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#201]
The API groups are usually in the following form:
* `monitoring.coreos.com`
* `rbac.authorization.k8s.io/v1`
* `route.openshift.io`

and we use `io.jaegertracing`

we should reconsider and change to `jaegertracing.io`

**Comment by jpkrohling** [comment]
I wonder if this pattern/convention is documented somewhere

**Comment by pavolloffay** [comment]
Not sure if directly documented but all the examples use the `sub-resource.resource.domain` group: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

**Comment by jpkrohling** [comment]
Done as part of #265
