### ISSUE TITLE
[Bug]: Can't use ES_USE_ALIASES with spark-dependencies in jaeger operator

### ISSUE THREAD

**Issue by ksponomarev** [jaegertracing/jaeger-operator#2016]
### What happened?

Hello
I can't enable `ES_USE_ALIASES` with 
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
```
for `dependencies`
I think I need it [here](https://github.com/jaegertracing/jaeger-operator/blob/main/pkg/cronjob/spark_dependencies_test.go#L68)

### Steps to reproduce

1. Install jaeger-operator
2. Install jaeger
3. Set `use-aliases: true`
4. Run spark-dependencies job

### Expected behavior

Spark-dependencies use aliases

### Relevant log output

```shell
22/08/03 11:29:23 INFO ElasticsearchDependenciesJob: Running Dependencies job for 2022-08-03T00:00Z, reading from dtv-kaas-jaeger-span-read index, result storing to dtv-kaas-jaeger-dependencies-write
```

### Pipeline

Application->OTEL Collector->Jaeger->Elasticsearch

### Stogage backend

Elasticsearch

### Operating system

Linux

### Deployment model

Kubernetes

### Deployment configs

```shell
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  imagePullSecrets:
      - name: artifactory
  storage:
    type: elasticsearch
    dependencies:
      image: docker.io/jaegertracing/spark-dependencies:latest
      successfulJobsHistoryLimit: 1
      backoffLimit: 2
      schedule: "55 23 * * *"
      javaOpts: "-Djavax.net.ssl.trustStore=trust.store -Djavax.net.ssl.trustStorePassword=1111111111"
      resources:
        requests:
          memory: 4096Mi
        limits:
          memory: 4096Mi
    esRollover:
      image: docker.io/jaegertracing/jaeger-es-rollover:1.36.0
      conditions: "{\"max_age\": \"14d\"}"
      readTTL: 168h
      imagePullPolicy: Always
      imagePullSecrets:
        - name: artifactory
      backoffLimit: 2
      successfulJobsHistoryLimit: 1
      schedule: "55 22 * * *"
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
    esIndexCleaner:
      image: docker.io/jaegertracing/jaeger-es-index-cleaner:1.36.0
      enabled: true
      backoffLimit: 2
      numberOfDays: 1
      successfulJobsHistoryLimit: 1
      schedule: "55 21 * * *"
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
    options:
      es:
        server-urls: https://elsticsearch:9200
        tls:
          enabled: true
        username: admin
        password: pass
        index-prefix: dtv-kaas
        index-rollover-frequency-services: day
        index-rollover-frequency-spans: day
        use-aliases: true
        create-index-templates: false
  agent:
    image: docker.io/jaegertracing/jaeger-agent:1.36.0
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    imagePullSecrets:
        - name: artifactory
    options:
      log-level: info
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: vaultpki-clusterissuer
    tls:
      - hosts:
        - jaeger.example.com
        secretName: jaeger.example.com
    hosts:
      - jaeger.example.com
  collector:
    maxReplicas: 5
    minReplicas: 1
    image: docker.io/jaegertracing/jaeger-collector:1.36.0
    imagePullPolicy: Always
    options:
      es:
        use-aliases: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  query:
    replicas: 3
    image: docker.io/jaegertracing/jaeger-query:1.36.0
    tracingEnabled: true
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
    options:
      prometheus:
          server-url: http://prometheus-stack-prometheus.prometheus-stack:9090
      es:
        use-aliases: true
    metricsStorage:
      type: prometheus
  ui:
      options:
        dependencies:
          menuEnabled: true
```

**Comment by avdeevi** [comment]
I have same problem.  
jaegertracing/spark-dependencies  ignore environment variable ES_USE_ALIASES=true

**Comment by ksponomarev** [comment]
I fixed this with rebuilding container with `ENV ES_USE_ALIASES=true`
But it's note cool

**Comment by brentmjohnson** [comment]
not sure if the operator eventually reconciles resources and overwrites this, but you can also patch the cronjob as a workaround like the following:

````
kubectl patch CronJob/jaeger-spark-dependencies -n observability --type json -p='[
  {"op": "add", "path": "/spec/jobTemplate/spec/template/spec/containers/0/env/-", "value": { "name": "ES_USE_ALIASES", "value": "true" }}
]'
````

**Comment by frzifus** [comment]
Seems the `ES_USE_ALIAS` option is simply ignored. Compare it with `ES_INDEX_PREFIX`.
```yaml
    options:
      es:
        use-aliases: true
        index-prefix: dtv-kaas
```

Here the v1.37 source.

https://github.com/jaegertracing/jaeger-operator/blob/58f91556e182a4fd929f1abbd0522b1e560e51b3/pkg/cronjob/spark_dependencies.go#L167-L183

---

Would any of you like to work on a patch? :)

**Comment by frzifus** [comment]
@miyunari, are you interested in working on this?

**Comment by miyunari** [comment]
yes I would be happy to work on this :)

**Comment by yakimba** [comment]
We are facing the same issue without jaeger-operator. 
We have installed spark-dependencies as cronjob in kubernetes. But spark with env ES_USE_ALIASES: true tries to use index jaeger-span-dd-mm-yyyy, but we don't have such indexes. We only have indexes with names like jaeger-span-00000XX.
As a result spark always tolds that 0 dependencies found

**Comment by oncipriani** [comment]
> We are facing the same issue without jaeger-operator. We have installed spark-dependencies as cronjob in kubernetes. But spark with env ES_USE_ALIASES: true tries to use index jaeger-span-dd-mm-yyyy, but we don't have such indexes. We only have indexes with names like jaeger-span-00000XX. As a result spark always tolds that 0 dependencies found

Exactly the same issue here. Installed using the Helm Chart.
