### ISSUE TITLE
[Feature]: Release 1.37.0

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#2017]
### Requirement

Jaeger core 1.37.0 has been released https://github.com/jaegertracing/jaeger/releases/tag/v1.37.0.

### Problem

Jaeger Operator 1.37 is documented, but not accessible.

### Proposal

Release the Jaeger-Operator 1.37.0.

**Comment by iblancasa** [comment]
We can close this task https://github.com/jaegertracing/jaeger-operator/releases/tag/v1.37.0
