### ISSUE TITLE
[Bug]: Missing GRPC port on jaeger-query deployment

### ISSUE THREAD

**Issue by avishefi** [jaegertracing/jaeger-operator#2041]
### What happened?

There is no grpc port on the jaeger-query deployment created by the operator using the production strategy.

### Steps to reproduce

1. Create a Jaeger instance
2. There is a grpc-query port 16685 on the jaeger-query service
3. There is no grpc-query port on the jaeger-query deployment and pod

### Expected behavior

There should be a grpc-query port 16685 on jaeger-query

**Comment by iagosrodrigues** [comment]
I was troubleshooting just right now, and I saw this error, took me some time to figure out that this port is missing in production strategy.
