### ISSUE TITLE
Revisit CR

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#207]
Before going into details we should establish conceptual objectives for jaeger-operator. For me the most important objectives of jaeger CR are:
* simple deployment - keep the number of required options minimal
* robust configuration - do not repeat the same conf props for multiple components
* fine tuning - operator should know what are the best defaults for a given configuration - e.g. we increase queue sizes, ES batch, correctly set number of shards and replicas.

**Comment by pavolloffay** [comment]
Now I would like to highlight a couple of inconsistencies:
* archive storage - we might automatically configure archive storage based on the flags provided to the main storage.
* storage auth - the same auth is used for C* and ES - we might move it from options map to normal properties under storage
* `JaegerDependenciesSpec` should not expose `CassandraUseSsl` - it could be found out from storage flags or see the previous point
* secretName
* `JaegerCassandraCreateSchemaSpec` could  derive datacenter, mode from storage options map
* if the archive storage is configured operator should make the archive button in UI visible.

```
      --cassandra.tls                                             Enable TLS
      --cassandra.tls.ca string                                   Path to TLS CA file
      --cassandra.tls.cert string                                 Path to TLS certificate file
      --cassandra.tls.key string                                  Path to TLS key file
      --cassandra.tls.server-name string                          Override the TLS server name
      --cassandra.tls.verify-host                                 Enable (or disable) host key verification (default true)
      --cassandra.username string                                 Username for password authentication for Cassandra
      --cassandra.password string                                 Password for password authentication for Cassandra


      --es.tls                                                    Enable TLS
      --es.tls.ca string                                          Path to TLS CA file
      --es.tls.cert string                                        Path to TLS certificate file
      --es.tls.key string                                         Path to TLS key file
      --es.token-file string                                      Path to a file containing bearer token. This flag also uses CA if it is specified
      --es.username string                                        The username required by ElasticSearch
      --es.password string                                        The password required by ElasticSearch


      --cassandra.consistency string                              The Cassandra consistency level, e.g. ANY, ONE, TWO, THREE, QUORUM, ALL, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE (default LOCAL_ONE)
      --cassandra.keyspace string                                 The Cassandra keyspace for Jaeger data (default "jaeger_v1_test")
      --cassandra.local-dc string                                 The name of the Cassandra local data center for DC Aware host selection


```

**Comment by objectiser** [comment]
Agree it would be nice to simplify the CR configuration for majority of users, but provide a mechanism whereby advanced users could change values not exposed by specific properties in the CR.

So one approach would be to define a set of common properties (e.g. tls) and derive values where possible - but if a user specifies the same parameter in the options field, then that should override.

**Comment by pavolloffay** [comment]
Also some operators provide a `unmanaged` flag which tells the operator to not override manually modified deployments/configmaps.

**Comment by pavolloffay** [comment]
TODOs after meeting:

- [ ] rename `Size` to `Replicas`
- [ ] change operator's flags `--image` to `--registry`? It's related to jira MAISTRA-203. What happens if the registry with productized images does not contain all images - eg. spark-dependencies.
- [ ] `JaegerDependenciesSpec` should not expose `CassandraUseSsl`
- [ ] `JaegerCassandraCreateSchemaSpec` - remove datacenter and mode - derive from storage flags

**Comment by pavolloffay** [comment]
I am closing this. All items are fixed or cannot be fixed.
