### ISSUE TITLE
[Feature]: release Jaeger-Operator 1.38.1

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#2082]
### Requirement

Today Jaeger [1.38.1](https://github.com/jaegertracing/jaeger/releases/tag/v1.38.1) released.

### Problem

Missing a Operator release.

**Comment by mjnagel** [comment]
Would like to see this as well! More general question - it seems to generally be the case that you should be using equivalent versions of Jaeger and the operator. Is that a strict rule, or do you just need to match minor versions?

**Comment by sereneshikari** [comment]
Hey @mjnagel, I think [this section](https://github.com/jaegertracing/jaeger-operator/blob/b003836ceeec14a313e1e528316efd0403a0b74a/README.md#jaeger-operator-vs-jaeger) of the README answers your question

**Comment by frzifus** [comment]
thanks @sereneshikari !
