### ISSUE TITLE
[Bug]: Jaeger operator cannot reconcile in non-cluster-wide mode

### ISSUE THREAD

**Issue by sereneshikari** [jaegertracing/jaeger-operator#2085]
### What happened?

I am trying to install the Jaeger operator in non-cluster-wide mode to watch a specific namespace (its own) but it is unable to reconcile the `Jaeger` custom resources created in the same namespace

### Steps to reproduce

Follow the steps in the [documentation](https://www.jaegertracing.io/docs/1.38/operator/#installing-the-operator-on-kubernetes) to install the Jaeger operator to watch a specific namespace:
1. > `kubectl create namespace jaeger`
2. Label the namespace for Istio sidecar injection: `kubectl label ns jaeger istio-injection=enabled` (I don't think this is relevant)
3. Download the [Kubernetes installation manifest for the Jaeger operator](https://github.com/jaegertracing/jaeger-operator/releases/tag/v1.38.0) to a file `jaeger-operator.yaml`
4. > [E]dit the deployment files to change `observability` to the desired namespace value
5. > [C]hange the `ClusterRole` and `ClusterBindingRole` of the operator manifest to `Role` and `RoleBinding`, also set the `WATCH_NAMESPACE` environmebt variable on the jaeger operator Deployment.
6. Remove `Role` and `(Cluster)RoleBinding` resources related to OpenShift metrics (I don't think this is relevant)
7. > `kubectl create -f jaeger-operator.yaml -n jaeger`
(see complete manifest in "Deployment configs" section)
8. Create a simple `Jaeger` CR:
  ```console
  kubectl apply -n jaeger -f - <<EOF
  apiVersion: jaegertracing.io/v1
  kind: Jaeger
  metadata:
    name: simplest
  EOF
  ```

### Expected behavior

As per the [documentation](https://www.jaegertracing.io/docs/1.38/operator/#quick-start---deploying-the-allinone-image):
> In a few seconds, a new in-memory all-in-one instance of Jaeger will be available, suitable for quick demos and development purposes.

### Relevant log output

Logs from the Jaeger operator pod. Please see the "Additional context" section for log "highlights"

[`jaeger-operator-logs.txt`](https://github.com/jaegertracing/jaeger-operator/files/9744354/jaeger-operator-logs.txt)

### Additional context

Environment context:
- The operator is installed into a [Rancher RKE2](https://github.com/rancher/rke2) cluster (`v1.24.6+rke2r1`)
- `cert-manager` (`v1.9.0`) is installed in the cluster
- Istio (`1.14.1`) is installed in the cluster and the namespace in which the Jaeger operator is installed is labelled for Istio sidecar injection
- Elasticsearch (ECK) operator (`v2.2.0`) is installed in the cluster
- Strimzi operator is _not_ installed in the cluster

From the logs, the Jaeger operator understands that it _doesn't_ run in cluster-wide scope:
```
1.665385903185044e+09	INFO	Consider running the operator in a cluster-wide scope for extra features
```

It also disables the namespace controller accordingly:
```
1.6653859055759609e+09	INFO	could not get a list of namespaces, disabling namespace controller. reason: namespaces is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "namespaces" in API group "" at the cluster scope
```

However, after it detects the `simplest` `Jaeger` CR, it still requests for cluster-scope permission:
```
1.665386343996404e+09	INFO	jaeger-resource	default	{"name": "simplest"}
1.6653863440157018e+09	INFO	jaeger-resource	validate create	{"name": "simplest"}
1.6653863440157602e+09	INFO	jaeger-resource	validate update	{"name": "simplest"}
1.6653863440272865e+09	INFO	Reconciling Jaeger	{"namespace": "jaeger", "instance": "simplest", "execution": 1665386344.027283}
1.665386344034854e+09	ERROR	Reconciler error	{"controller": "jaeger", "controllerGroup": "jaegertracing.io", "controllerKind": "Jaeger", "Jaeger": {"name":"simplest","namespace":"jaeger"}, "namespace": "jaeger", "name": "simplest", "reconcileID": "b1270208-4b3e-44f8-9a4d-ea5e8ed1ab6a", "error": "deployments.apps is forbidden: User \"system:serviceaccount:jaeger:jaeger-operator\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234
```

Another strange issue is that it tries to verify a deployment in _another_ namespace (`pf`) when `WATCH_NAMESPACE` is set only to `jaeger`:
```
1.665386318303846e+09	INFO	verify deployment	{"namespace": "pf"}
[...]
W1010 07:18:41.791624       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "namespaces" in API group "" at the cluster scope
E1010 07:18:41.791674       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "namespaces" in API group "" at the cluster scope
1.6653863253456182e+09	INFO	Determining whether we should enable the Elasticsearch Operator integration
1.665386325346376e+09	INFO	Determining whether we should enable the Kafka Operator integration
1.6653863253475988e+09	INFO	found the cronjobs api in batch/v1
1.6653863253488421e+09	INFO	found the horizontalpodautoscalers api in autoscaling/v2
1.6653863253488717e+09	INFO	detecting orphaned deployments.
W1010 07:18:47.073794       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "namespaces" in API group "" at the cluster scope
E1010 07:18:47.073852       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "namespaces" in API group "" at the cluster scope
1.6653863283031425e+09	ERROR	failed to get the namespace for the deployment, skipping injection based on namespace annotation	{"namespace": "pf", "error": "Timeout: failed waiting for *v1.Namespace Informer to sync"}
github.com/jaegertracing/jaeger-operator/controllers/appsv1.(*deploymentInterceptor).Handle
	/workspace/controllers/appsv1/deployment_webhook.go:84
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/webhook/admission/webhook.go:169
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/webhook/admission/http.go:98
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:56
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2084
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:142
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2084
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:104
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2462
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2916
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1966
```

### Jaeger backend version

v1.38.0

### SDK

N/A

### Pipeline

N/A

### Stogage backend

Memory

### Operating system

CentOS Linux 7

### Deployment model

Kubernetes

### Deployment configs

[`jaeger-operator.txt`](https://github.com/jaegertracing/jaeger-operator/files/9744324/jaeger-operator.txt)

**Comment by sereneshikari** [comment]
I'm not familiar with Go (let alone the SDK and libraries written for K8s operators 😅) but from GitHub searches through the codebase and reading related documentation, here's what I could find...

The `Reconciling Jaeger ...` logs appear to come from here:
https://github.com/jaegertracing/jaeger-operator/blob/5c272f39e2144075e004e5d27e5d2f3eb75f991e/pkg/controller/jaeger/jaeger_controller.go#L71-L76

and further down, we have this function:
https://github.com/jaegertracing/jaeger-operator/blob/5c272f39e2144075e004e5d27e5d2f3eb75f991e/pkg/controller/jaeger/jaeger_controller.go#L95

which seems to be the one listing the deployments:
https://github.com/jaegertracing/jaeger-operator/blob/5c272f39e2144075e004e5d27e5d2f3eb75f991e/pkg/controller/jaeger/jaeger_controller.go#L406-L412

Comparing with [the documentation for the `client.Reader` interface](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.13.0/pkg/client#Reader), there don't seem to be any [`ListOptions`](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.13.0/pkg/client#ListOptions) passed to `rClient.List(...)` to restrict the namespaces to search for. Could this be the reason for the error I'm seeing?

**Comment by frzifus** [comment]
> Could this be the reason for the error I'm seeing?
Good question. But i found something else. Looking on the error (`failed to get the namespace for the deployment, skipping injection based on namespace annotation	{"namespace": "pf", "error": "Timeout: failed waiting for *v1.Namespace Informer to sync"}`) look, i assume the issue should be somehow here:
https://github.com/jaegertracing/jaeger-operator/blob/5c272f39e2144075e004e5d27e5d2f3eb75f991e/controllers/appsv1/deployment_webhook.go#L79-L86


Any idea @rubenvp8510 ?

**Comment by sereneshikari** [comment]
Hi @frzifus, thanks for taking a look! I think there are two errors:
1. `ERROR	failed to get the namespace for the deployment, skipping injection based on namespace annotation	{"namespace": "pf", "error": "Timeout: failed waiting for *v1.Namespace Informer to sync"}`
2. `Reconciler error	{"controller": "jaeger", "controllerGroup": "jaegertracing.io", "controllerKind": "Jaeger", "Jaeger": {"name":"simplest","namespace":"jaeger"}, "namespace": "jaeger", "name": "simplest", "reconcileID": "b1270208-4b3e-44f8-9a4d-ea5e8ed1ab6a", "error": "deployments.apps is forbidden: User \"system:serviceaccount:jaeger:jaeger-operator\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope"}`

For error (1), a quick online search returns this GitHub issue [external-dns#1202](https://github.com/kubernetes-sigs/external-dns/issues/1202) where the discussion indicates that the error is due to missing RBAC permissions. I guess that makes sense because I have only used `Role`s and `RoleBinding`s so listing namespaces is forbidden.

So ultimately both errors (1) and (2) are due to missing RBAC permissions.

For error (1) do we know what creates the Informer for `*v1.Namespace`?
For error (2), maybe following the same approach below in the `syncOnJaegerChanges` function would be correct, namely checking if we are not running in cluster-wide mode and adjusting the client options accordingly:
https://github.com/jaegertracing/jaeger-operator/blob/5c272f39e2144075e004e5d27e5d2f3eb75f991e/pkg/autodetect/main.go#L290-L330

**Comment by sereneshikari** [comment]
I also see there a few open GitHub issues that are related to Jaeger operator in non-cluster-wide mode so I'm listing them here for better context on the situation we're dealing with (please note that this list may not be exhaustive):
- #1431 
- #929 
- jaegertracing/helm-charts#241
