### ISSUE TITLE
[e2e] make cassandra broken on minikube v0.33.1

### ISSUE THREAD

**Issue by annanay25** [jaegertracing/jaeger-operator#211]
`make cassandra` seems to be failing with -

```
WARN  [main] 2019-02-14 04:59:40,369 SimpleSeedProvider.java:60 - Seed provider couldn't lookup host cassandra-0.cassandra
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: The seed provider lists no seeds.
The seed provider lists no seeds.
ERROR [main] 2019-02-14 04:59:40,374 CassandraDaemon.java:708 - Exception encountered during startup: The seed provider lists no seeds.
```
.. on minikube v0.33.1 / docker v18.09.1~ce (perhaps broken on more recent releases as well). 

Just verified that it works with minikube v0.30.0 / docker v18.06.1~ce (This is on an Ubuntu 18.04 machine).

**Comment by jpkrohling** [comment]
I smell problems in the future :(

**Comment by jpkrohling** [comment]
I'm running minikube `v0.34.1` and it's working fine. Could you try with this latest minikube version and reopen if it's still an issue?
