### ISSUE TITLE
Wait for ES deployment to be ready and then deploy jaeger

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#216]
Now operator creates ES CR and jaeger objects (deployments) at the same time. This is causing jaeger pods to fail multiple times until Elasticsearch is up.

**Comment by pavolloffay** [comment]
I think this one of the most important features for ES deployment. 

Thinking about how to tackle it. Maybe the best would be to use k8s client and wait until ES deployment is up - readiness probe responds positively.

**Comment by jpkrohling** [comment]
I'd say that the cleanest would be to create a `Job` that blocks until it can make a connection to ES. This `Job` can be added to the list of `Dependencies`, similar to how the `CassandraCreateSchema` works.

https://github.com/jaegertracing/jaeger-operator/blob/401ef74cda6fe5b470616d9cbfcedd1f7bc840aa/pkg/storage/dependency.go#L12-L18

https://github.com/jaegertracing/jaeger-operator/blob/401ef74cda6fe5b470616d9cbfcedd1f7bc840aa/pkg/storage/cassandra_dependencies.go#L15

**Comment by pavolloffay** [comment]
I was thinking about this but - it seems more complicated and harder to maintain. 

With job we need a separate docker image with code which calls ES - this will require mounting secrets etc.

I would rather use operator to do this using the similar way how it looks for dependencies jobs to be finished.

**Comment by pavolloffay** [comment]
Dependencies for C* makes sense - it initializes schema. Whereas in this case we just wait until deployment is ready.

For rollover support using dependencies makes sense - as we need to initialize mappings and create indices. The rollover image would fail if the ES is not up.

**Comment by jpkrohling** [comment]
Then probably something like: 

https://github.com/jaegertracing/jaeger-operator/blob/401ef74cda6fe5b470616d9cbfcedd1f7bc840aa/pkg/controller/jaeger/deployment.go#L53-L62

and 

https://github.com/jaegertracing/jaeger-operator/blob/401ef74cda6fe5b470616d9cbfcedd1f7bc840aa/pkg/controller/jaeger/deployment.go#L74-L95
