### ISSUE TITLE
Upgrade Operator-SDK to v1.27

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#2177]
### Requirement

We would like to update k8s apis.

### Problem

There are a few broken 
- https://github.com/jaegertracing/jaeger-operator/pull/2152
- https://github.com/jaegertracing/jaeger-operator/pull/2154
- https://github.com/jaegertracing/jaeger-operator/pull/2160
- https://github.com/jaegertracing/jaeger-operator/pull/2168
- https://github.com/jaegertracing/jaeger-operator/pull/2171

### Proposal

Updating Operator-sdk to the latest version.

**Comment by iblancasa** [comment]
I can do it
