### ISSUE TITLE
Use better service account names

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#218]
We are not creating service accounts for jaeger if they are not needed. We do create ones for oauth proxy (for query) and then one for collector if we deploy elasticsearch. 

* the oauth proxy as name `fmt.Sprintf("%s-ui-proxy", jaeger.Name)`
* the collector one has name `return fmt.Sprintf("%s", jaeger.Name)`

It seems that we might need different service accounts for different deplyments/pods. I would reconsider names and derive the name mased on jaeger and component name e.g. `simplest-query`.

**Comment by jpkrohling** [comment]
We create one for the whole Jaeger instance and use it across all components:

```console
$ kubectl get deployment simple-prod-collector -o=jsonpath="{.spec.template.spec.serviceAccount}{'\n'}"
simple-prod
$ kubectl get deployment simple-prod-query -o=jsonpath="{.spec.template.spec.serviceAccount}{'\n'}"
simple-prod
$ kubectl get deployment simplest -o=jsonpath="{.spec.template.spec.serviceAccount}{'\n'}"
simplest
```

By now, we also support overriding each component's service account via the Jaeger CR. This means that we have a simple default setup, while being flexible for more complex cases.

I'm closing this, but feel free to reopen if you think we still should have a goal of having one service account per component by default.
