### ISSUE TITLE
[Bug]: Compatibility matrix is missing v1.36

### ISSUE THREAD

**Issue by shazib-summar** [jaegertracing/jaeger-operator#2219]
### What happened?

Not exactly an application bug but the compatibility matrix is missing v1.36

### Steps to reproduce

1. Open the compatibility matrix
2. Look for version 1.36

### Expected behavior

Compatibility matrix to have v1.36

### Additional context

I would be happy to make a PR for this. I assume v1.36 will have the same supported Kubernetes | Strimzi Operator | Cert-Manager versions as 1.37 and 1.35. Kindly correct me if this assumption is wrong.

| Jaeger Operator |   Kubernetes   | Strimzi Operator | Cert-Manager |
|:---------------:|:--------------:|:----------------:|:------------:|
|     v1.37.x     | v1.19 to v1.24 |       v0.23      |    v1.6.1    |
|     v1.36.x     | v1.19 to v1.24 |       v0.23      |    v1.6.1    |
|     v1.35.x     | v1.19 to v1.24 |       v0.23      |    v1.6.1    |

**Comment by shazib-summar** [comment]
Apologies if this is the wrong template to use, but the only options I had were bug/feature request.

**Comment by shazib-summar** [comment]
Update:

Just realised its missing v1.45 and v1.43 as well. If the compatibility data is provided, I'll be happy to make a PR here.

**Comment by frzifus** [comment]
Thanks for reporting, are you willing to submit a pr? :)

**Comment by shazib-summar** [comment]
Yes @frzifus, I would be happy to. I just need the version mapping to add in the matrix.


| Jaeger Operator |   Kubernetes   | Strimzi Operator | Cert-Manager |
|:---------------:|:--------------:|:----------------:|:------------:|
|     v1.45.x     | ..... |       .....      |    .....    |
|     v1.44.x     | ..... |       .....      |    .....   |
|          |  |           |      |
|     v1.36.x     | ..... |       .....      |    .....    |

**Comment by iblancasa** [comment]
@shazib-summar you can move to the tags from the versions and get the information:

- `Kubernetes`: you can check the K8s versions tested
- `Strimzi Operator`: there is one variable in the `Makefile` with the version used to test
- `Cert-Manager`: there is one variable in the `Makefile` with the version used to test

**Comment by shazib-summar** [comment]
Apologies for creating a duplicate bug. I forgot I had created one earlier. Made a PR to address this issue.
