### ISSUE TITLE
[Feature]: Release operator with jaeger 1.46.0

### ISSUE THREAD

**Issue by iblancasa** [jaegertracing/jaeger-operator#2228]
### Requirement

Create the Jaeger Operator release 1.46.0 based on Jaeger 1.46.0: https://github.com/jaegertracing/jaeger/releases/tag/v1.46.0

### Problem

.

**Comment by lghinet** [comment]
still no release . .

**Comment by iblancasa** [comment]
@lghinet I was on vacation. I just created the tag https://github.com/jaegertracing/jaeger-operator/releases/tag/v1.46.0
