### ISSUE TITLE
kubectl get pods and logs commands in README don't work because of label changes

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#224]
The README includes the following commands

kubectl get pods -l jaeger=simplest
kubectl logs -l jaeger=simplest 

Currently neither of these work as the jaeger label doesn't exist.  As a workaround we can do:

kubectl get pods -l app.kubernetes.io/instance=simplest
kubectl logs -l app.kubernetes.io/instance=simplest 

NOTE: On Openshift the kubectl logs command also requires that the container name be specified.

**Comment by jpkrohling** [comment]
The question is whether we want to add a label "jaeger" again, to make it easier to query the objects related to `simplest`. The same can be done by querying based on the label `app.kubernetes.io/instance`, but that's a lot more work than just typing `jaeger`.

**Comment by jpkrohling** [comment]
Done as part of #225, we won't be re-adding the `jaeger` entry for now.
