### ISSUE TITLE
[Bug]: Jaeger Operator Compatibility table is missing data for versions 1.44, 1.45, 1.46

### ISSUE THREAD

**Issue by shazib-summar** [jaegertracing/jaeger-operator#2247]
### What happened?

The compatibility table at https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md is outdated. Jaeger Operator v1.46 was released a few days ago but the table only goes till v1.43

### Steps to reproduce

Visit the provided link and observe the table.

### Expected behavior

The table to have rows and compatibility data for versions 1.44, 1.45 and 1.46.

### Screenshot

<img width="1317" alt="image" src="https://github.com/jaegertracing/jaeger-operator/assets/27294025/32924466-769c-4581-94c5-6d8eb35a2f90">

### Additional context

This isnt really a bug but the most applicable category was either this or a feature request. I ended up choosing bug, apologies if this confuses anyone.

I would also be more than happy to make a PR once the information regarding compatibility with K8s versions is provided 😄

**Comment by iblancasa** [comment]
Duplicated #2219

**Comment by QuirkyMarc** [comment]
Hmm... I didn't think I had the information to do that.. but looking again at issue https://github.com/jaegertracing/jaeger-operator/issues/2219 , maybe I do... let me see...
