### ISSUE TITLE
[Bug]: When increasing the release version, the replaces field contains an invalid value.

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#2267]
### What happened?

In [step 2 of the release instructions](https://github.com/jaegertracing/jaeger-operator/blob/main/RELEASE.md#releasing), we perform `OPERATOR_VERSION=x.xx.x make prepare-release`. This increases the versions in `CSV`. However, the version to be `replaces` field (indicating the version that should be replaced by this release) is also set to the current version.

### Steps to reproduce

https://github.com/jaegertracing/jaeger-operator/pull/2263/files#r1261498696

### Expected behavior

.

**Comment by iblancasa** [comment]
It seems this is somehow breaking the CI now:
```
+++ b/bundle/manifests/jaeger-operator.clusterserviceversion.yaml
@@ -19,7 +19,7 @@ metadata:
     categories: Logging & Tracing
     certified: "false"
     containerImage: quay.io/jaegertracing/jaeger-operator
-    createdAt: "2023-08-28T13:47:27Z"
+    createdAt: "2023-08-30T01:06:00Z"
     description: Provides tracing, monitoring and troubleshooting for microservices-based
       distributed systems
     operators.openshift.io/infrastructure-features: '["disconnected"]'
@@ -515,7 +515,7 @@ spec:
   maturity: alpha
   provider:
     name: CNCF
-  replaces: jaeger-operator.v1.47.0
+  replaces: jaeger-operator.v1.48.0
   selector:
     matchLabels:
```

**Comment by iblancasa** [comment]
@frzifus please, could you take a look into this? All the CI is currently broken after doing the release.
