### ISSUE TITLE
e2e tests do not work on OpenShift

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#227]
The e2e tests does not work on openshift bc:
* https://github.com/jaegertracing/jaeger-operator/blob/610d415ca5dfe2f14b2f06f4a3bef3fa5520457b/test/e2e/daemonset.go#L143
* personally on minishift I could not select default namespace and our tests depend on services (es, cassandra) deployed in default namespce

**Comment by jpkrohling** [comment]
cc @kear

**Comment by kevinearls** [comment]
Most of the work here is done.  There are two small bugs left, #326 which is a fix to get the all-in-one-with-ingress test working on OpenShift, and #327 for the DaemonSet test, which is currently blocked by #322.  I think this can be closed.
