### ISSUE TITLE
[Bug]: Missing container image 1.48.0 on quay.io

### ISSUE THREAD

**Issue by lewapek** [jaegertracing/jaeger-operator#2317]
### What happened?

Hey,
It looks like the image:
```
quay.io/jaegertracing/jaeger-operator:1.48.0
```
is missing.

I tried to follow the installation instructions (https://www.jaegertracing.io/docs/1.48/operator/#installing-the-operator-on-kubernetes). After execting `kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.48.0/jaeger-operator.yaml -n observability # <2>` the operator pod fails to start, and complains about the missing image.

I then tried to pull the image (`docker pull quay.io/jaegertracing/jaeger-operator:1.48.0`) and indeed it seems to be missing. I contrast I can pull `1.47.0` or `1.48` (without `.0` at the end) versions

It may be connected with https://github.com/jaegertracing/jaeger-operator/issues/2309 (seems to be solved but maybe some images skipped publishing)

### Steps to reproduce

`docker pull quay.io/jaegertracing/jaeger-operator:1.48.0`  
Above is the easy one - you can alternatively try to install operator on k8s followingthe isntructions (https://www.jaegertracing.io/docs/1.48/operator/#installing-the-operator-on-kubernetes)

### Expected behavior

The image 1.48.0 tag is published (to make https://github.com/jaegertracing/jaeger-operator/releases/download/v1.48.0 working).

### Relevant log output

```shell
Error response from daemon: manifest for quay.io/jaegertracing/jaeger-operator:1.48.0 not found: manifest unknown: manifest unknown
```
```


### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

_No response_

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

_No response_

### Deployment configs

_No response_

**Comment by iblancasa** [comment]
Related to #2309.

Try with `1.48.1`.

**Comment by lewapek** [comment]
Thx - `1.41.1` exists and probably words. Still the docs can be misleading as they point to `1.48.0`: https://www.jaegertracing.io/docs/1.48/operator/#installing-the-operator-on-kubernetes
