### ISSUE TITLE
[Bug]: Documentation version early release than operator

### ISSUE THREAD

**Issue by Roiocam** [jaegertracing/jaeger-operator#2349]
### What happened?

Jaeger latest version documentation not correctly work for newcomer, because it has been release 1.50, but operator not release yet.

https://www.jaegertracing.io/docs/1.50/operator/#installing-the-operator-on-kubernetes

### Steps to reproduce

1. open: https://www.jaegertracing.io/docs/1.50/operator/#installing-the-operator-on-kubernetes
2. follow the step to install jaeger operator
3. A 404 error occurred on the kubernetes CLI.

### Expected behavior

why documentation has been released 1.50 and jaeger operator not?

**Comment by iblancasa** [comment]
This should be fixed as part of the doc repository: https://github.com/jaegertracing/documentation/issues/580

**Comment by Roiocam** [comment]
> This should be fixed as part of the doc repository: [jaegertracing/documentation#580](https://github.com/jaegertracing/documentation/issues/580)这应该作为文档存储库的一部分进行修复：jaegertracing/documentation#580

Didn't notice that, Thanks.
