### ISSUE TITLE
Continue on reconciliation error?

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#236]
Currently, if there's an error while applying changes for a given object in the reconciliation loop, further objects aren't processed, as the routine just returns.

This causes a situation like #235: a failure in the Elasticsearch updates made the reconciliation logic to abort, preventing updates to the cronjob schedule.

We should decide whether it's a good idea to continue on error, or if the current behavior is acceptable.

cc @objectiser, @pavolloffay

**Comment by pavolloffay** [comment]
If the operator gets into even more undefined states then I would rather not continue on errors.

If there are dependencies on correct behavior during processing the continuation can cause problems.

**Comment by jpkrohling** [comment]
I would say that whatever remediation we *can* take, should be taken during the `apply` methods (or even before, like `normalize()`).  

So, a failure at this level is something that the operator doesn't know how to recover from. Similarly, we can't tell whether the state is now sane or not.

**Comment by objectiser** [comment]
Is there any way to build a "transaction log" of changes being applied, that could be rolled back if a failure occurs? So also means the previous state mustn't be torn down until the updated state is successful.

**Comment by jpkrohling** [comment]
This is certainly something to think about.

**Comment by jpkrohling** [comment]
Another aspect to this problem that happened recently: failures in `Routes` object caused the reconciliation to be ended prematurely, preventing more important objects from being created/synchronized.

I think we should review the current `apply` methods and judge one by one which ones are important enough to prevent the reconciliation from continuing, and which failures can be simply logged (perhaps in the `Status`?)
