### ISSUE TITLE
[Bug]: Regression introduced by PR #2277 with deployment.spec.selector.matchLabels field which is an immutable field

### ISSUE THREAD

**Issue by secat** [jaegertracing/jaeger-operator#2370]
### What happened?

Custom labels are configured on `production` strategy. Upgrading the `jaeger-operator` from version `v1.46.0` to `v1.49.0` results in errors since a `deployment.spec.selector.matchLabels` field is immutable.

This resgression was introduced by PR #2277

### Steps to reproduce

1. Install jaeger-operator version v1.46.0
2. Deploy a jaeger custom resource with custom labels and `production` strategy
3. Upgrade the jaeger-operator to version v1.49.0

### Expected behavior

Upgrading the `jaeger-operator` should not endup in reconciliation errors and immutable fields on resources should not be updated.

### Jaeger backend version

v1.49.0

**Comment by secat** [comment]
Here is a proposed solution to apply on the `pkg/inventory/deployment.go` file to fix the bug:

```diff
// ForDeployments builds a new Deployment inventory based on the existing and desired states
func ForDeployments(existing []appsv1.Deployment, desired []appsv1.Deployment) Deployment {
	update := []appsv1.Deployment{}
	mcreate := deploymentMap(desired)
	mdelete := deploymentMap(existing)

	for k, v := range mcreate {
		if t, ok := mdelete[k]; ok {
			tp := t.DeepCopy()
			util.InitObjectMeta(tp)

			// if we have a nil value for the replicas in the desired deployment
			// but we have a specific value in the current deployment, we override the desired with the current
			// as this might have been written by an HPA
			if tp.Spec.Replicas != nil && v.Spec.Replicas == nil {
				v.Spec.Replicas = tp.Spec.Replicas
			}

			// we can't blindly DeepCopyInto, so, we select what we bring from the new to the old object
			tp.Spec = v.Spec
			tp.Spec = inject.PropagateOAuthCookieSecret(t.Spec, v.Spec)

+			// Deployment.Spec.Selector is an immutable field: we can't update
+			// this field with a new value, we MUST keep the old field value
+			tp.Spec.Selector = t.Spec.Selector

			tp.ObjectMeta.OwnerReferences = v.ObjectMeta.OwnerReferences

			for k, v := range v.ObjectMeta.Annotations {
				tp.ObjectMeta.Annotations[k] = v
			}

			for k, v := range v.ObjectMeta.Labels {
				tp.ObjectMeta.Labels[k] = v
			}

			update = append(update, *tp)
			delete(mcreate, k)
			delete(mdelete, k)
		}
	}

	return Deployment{
		Create: deploymentList(mcreate),
		Update: update,
		Delete: deploymentList(mdelete),
	}
}
```

**Comment by secat** [comment]
If the proposed solution is fine, I can contribute a PR to resolve this issue

**Comment by iblancasa** [comment]
I think it should be fine.

**Comment by secat** [comment]
Also, it is the solution that was used over the `opentelemetry-operator`, see [code here](https://github.com/open-telemetry/opentelemetry-operator/blob/main/internal/manifests/mutate.go#L289)
