### ISSUE TITLE
Enable provisioning of Elasticsearch only when the ES operator is available

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#238]
Currently, the Jaeger Operator attempts to provision an Elasticsearch cluster even when the Elasticsearch Operator isn't available. It should work similar to the Routes, where it's enabled/disabled via a flag, with the default being the automatic detection.

**Comment by pavolloffay** [comment]
I am not sure if adding complexity like a flag for this is necessary. It does not buy is anything.

But I would certainly say we should/could log an error where we expect es-operator to be there and it isn't.

**Comment by jpkrohling** [comment]
We should always allow the operator users to override any automatic decisions we make. It's easy to introduce a bug in an automatic detection routine or to have assumptions change (like the group API for the ES operator changing).

**Comment by pavolloffay** [comment]
There is nothing automatic. If they configure URL we know they want to use an external ES cluster. The most important is to let them know the cluster won't create ES bc there is no ES operator.

**Comment by jpkrohling** [comment]
> If they configure URL we know they want to use an external ES cluster

This won't change. This is not per-CR, this is per-Operator.

> The most important is to let them know the cluster won't create ES bc there is no ES operator.

Right now, we just fail whenever there's no URL for ES in the Jaeger CR and the ES operator isn't available. With this per-operator setting, we won't be attempting to provision an ES cluster when we can't :-)

**Comment by jpkrohling** [comment]
A good side-effect and the main reason to get this one done now is that the e2e tests are now passing, as the controller won't try to query the list of existing ES clusters during the reconciliation logic.
