### ISSUE TITLE
[Feature]: Support Jaeger-v2 Operator

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-operator#2411]
### Requirement

Once Jaeger-v2 (https://github.com/jaegertracing/jaeger/issues/4843) reaches production readiness and feature parity, we should support it in the operator.

### Problem

Jaeger-v2 is based on OpenTelemetry Collector and uses completely different configuration mechanism:
  * all configuration is done via config files, not CLI flags or env vars (although some env vars are supported by telemetry SDKs)
  * it is a single binary that can be deployed into different roles (collector, query, etc.) also based on configuration, but in this case with structural config changes, not just tweaking parameters

### Proposal

I would like to hear what maintainers of this repo think about the best approach. Can we come up with a roadmap of how jaeger-v2 will be supported by the operator? Is there some common approach we can use with the OTEL operator?

### Open questions

* Is it worth maintaining both helm charts and operator?

**Comment by dipankardas011** [comment]
not sure if we actually need helm charts as we have to deploy via the kubernetes operator method

still need to have a discussion with otel operator folks

**Comment by yurishkuro** [comment]
Closing as a duplicate of #2717 (which was moved from Jaeger repo)
