### ISSUE TITLE
release jaeger-operator 1.55.0

### ISSUE THREAD

**Issue by frzifus** [jaegertracing/jaeger-operator#2498]
Release Jaeger Operator 1.55.0.

https://github.com/jaegertracing/jaeger/releases/tag/v1.55.0

**Comment by frzifus** [comment]
We may want to wait until https://github.com/jaegertracing/jaeger-operator/pull/2497 is in.

**Comment by QuirkyMarc** [comment]
Maybe still a bit premature to remove jaeger-agent from the operator? (that https://github.com/jaegertracing/jaeger-operator/pull/2497)

There are some that haven't quite gotten off the agent yet and are still using the it [ed: guilty as charged, your honors], and the agent is still in jaegertracing code itself, even up to latest v1.55.0, and the image still being built ( [jaegertracing/jaeger-agent:1.55.0](https://hub.docker.com/layers/jaegertracing/jaeger-agent/1.55.0/images/sha256-3946f9da4a30c1b3dcbca0130107500ecea5f034904f44bf79962f5422a5b6ab?context=explore) ).

**Comment by iblancasa** [comment]
#2513
