### ISSUE TITLE
[Documentation]: Compatibility Matrix is missing beyond v1.49

### ISSUE THREAD

**Issue by QuirkyMarc** [jaegertracing/jaeger-operator#2506]
### What happened?

Looking at the compatibility matrix, hasn't been updated since Sep 2023, last entry is v1.49.   

Current operator version is v1.54.  Seems to be missing a few entries.   ;)

### Steps to reproduce

1. Open the Compatibility Matrix: https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md
2. Look for versions v1.50 through, at time of this writing, v1.54

### Expected behavior

Compatibility Matrix should contain all releases up to the latest one

### Screenshot

Live screenshot of Compatibility Matrix as of Mar 14 2024

![Screenshot of compatibility Matrix](https://github.com/jaegertracing/jaeger-operator/assets/9660180/af71e7ec-7466-4f83-b3bf-4fe7cac08568)

**Comment by iblancasa** [comment]
@QuirkyMarc would you like to send a PR?

**Comment by QuirkyMarc** [comment]
@iblancasa   Hmm... I didn't think I had the information to do that.. but looking again at issue https://github.com/jaegertracing/jaeger-operator/issues/2219 , maybe I do... let me try...

**Comment by mooneeb** [comment]
Hey @QuirkyMarc were you able to make time to make progress on this PR? If not, I'll be glad to lend a hand and help contribute

**Comment by mooneeb** [comment]
@iblancasa I've created the PR to update the documentation :) Please have a look whenever you are able to
