### ISSUE TITLE
[Documentation]: Compatibility Matrix outdated

### ISSUE THREAD

**Issue by mooneeb** [jaegertracing/jaeger-operator#2574]
### What happened?

Last week, Jaeger Operator v1.57.0 was released. However, the [following compatibility matrix](https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md) has not been updated as of yet.

I'm very happy to submit a PR to update the documentation - I just created this issue following the contribution guidelines to get the maintainers' approval before doing so.

### Steps to reproduce

Visit: https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md

### Expected behavior

The compatibility map to include the following table:

| Jaeger Operator | Kubernetes      | Strimzi Operator   | Cert-Manager |
|-----------------|-----------------|--------------------|--------------|
| v1.57.x         | v1.19 to v1.28  | v0.32              | v1.6.1       |

**Comment by iblancasa** [comment]
@mooneeb would you like to send a PR?

**Comment by mooneeb** [comment]
> @mooneeb would you like to send a PR?

I'll send a PR as soon as I find some time
