### ISSUE TITLE
JaegerStatus object

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#259]
This is a follow-up issue from #248, to determine how the `JaegerStatus` object should look like. As seen in the Operator Framework mailing list, here's a resource that may help determine what should and what should not be there:

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

**Comment by pavolloffay** [comment]
Could you please a link to operator ML thread?

**Comment by jpkrohling** [comment]
The most relevant part is this:

> The status summarizes the current state of the object in the system, and is usually persisted with the object by an automated processes but may be generated on the fly. At some cost and perhaps some temporary degradation in behavior, the status could be reconstructed by observation if it were lost.

...

> When a new version of an object is POSTed or PUT, the "spec" is updated and available immediately. Over time the system will work to bring the "status" into line with the "spec".

...

> Historical information status (e.g., last transition time, failure counts) is only provided with reasonable effort, and is not guaranteed to not be lost.

**Comment by jpkrohling** [comment]
> Could you please add a link to operator ML thread?

https://groups.google.com/d/msg/operator-framework/m27X0aif_OI/AkK-EIO2CQAJ

**Comment by jpkrohling** [comment]
I'm closing this, as we have status already. Any extra fields can be added on demand, as required.
