### ISSUE TITLE
Incorporate rbac, crd and operator yaml into one file

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#26]
Not sure if it is convention, but wondering if there is a real benefit to having the rbac, crd and operator yaml content in separate files.

It means users have to perform three operations instead of one. Same operations are performed on both kubernetes and openshift - so just thinking it may be better to have a single `jaeger-operator.yaml` file with all content?

**Comment by jpkrohling** [comment]
I believe this is a convention, as this is how the SDK generates them. I would keep them separate for now, until we understand better the ups and downs.

**Comment by jpkrohling** [comment]
There was an update to the SDK and they are still split. I think this is the recommended approach. Should we still consider having the yaml as one file?

**Comment by objectiser** [comment]
I guess if that is the convention/recommended approach, we should leave - but seems pointless when can be deployed in a single step.
