### ISSUE TITLE
A way to find jaeger version

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#261]
Sometimes it's useful to know the version of the components being deployed. This is useful for handling breaking changes but also new features.

For example Jaeger 1.9 introduced GRPC communication between agent and collector. The operator should preferably use GRPC if it is possible but still use thrift for older versions see #260 

The version could be derived from the image string but not always -e.g. missing tag. Perhaps we could spin up the image and invoke version command before deploying.

**Comment by jpkrohling** [comment]
Or via the status endpoint?

**Comment by pavolloffay** [comment]
That should work too I thought that running an `exec` command might be easier. Then just get output and parse the result. IIRC the returned string by endpoint and command is the same.

`{"gitCommit":"","GitVersion":"","BuildDate":""}`

**Comment by jpkrohling** [comment]
Running an exec *before* the container comes up might delay the startup of the pod. Getting the version information after it's running is less invasive, IMO.

**Comment by pavolloffay** [comment]
There is no difference - we first have to run the container with no flags and then create an appropriate configuration. Also, more importantly, running the command is faster than waiting for http server to come up.

We could do this if the tag is missing.

**Comment by jpkrohling** [comment]
I think I missed a key part of this:

> The operator should preferably use GRPC if it is possible but still use thrift for older versions

You are right: we have no other way than running the container first.

**Comment by jpkrohling** [comment]
I'm closing this, as we the picture is clearer now: there's only one Jaeger version being managed per Jaeger Operator version. We store the operand's version in the CR's Status object, and only change during the upgrade mechanism.

**Comment by AhHa45** [comment]
so how to see the version?
