### ISSUE TITLE
Do not allow deploying es with 2 nodes

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#268]
It can cause split brain https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#split-brain

**Comment by objectiser** [comment]
Rather than not allow, should we just report a warning that references the above URL? And possibly this type of warning could be included in the JaegerStatus - so the operator warns that system is not running with an optimal configuration.

**Comment by jpkrohling** [comment]
I'd be consistent with the ES operator here: if they allow this sort of configuration, we should as well.

**Comment by pavolloffay** [comment]
It depends on how "smart" we want to make our operator and if we want to protect users against creating clusters which can eventually get into inconsistent state.

**Comment by jpkrohling** [comment]
We should be smart to make some decisions on behalf of the user, but the user always has the final word. If they say "2 nodes", we should say: "here you are: 2 nodes! *but*, did you know that it might lead to an inconsistent state?"

**Comment by pavolloffay** [comment]
I did more reading on this topic. Two nodes is actually a valid configuration if it is configured properly. I have check with ECL and it seems they do it right. However if one node of these 2 fails the whole cluster is automatically in the down state.

I would not recommend using two nodes but we can certainly allow this configuration.
