### ISSUE TITLE
Rename `Size` to `Replicas`

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#270]
From https://github.com/jaegertracing/jaeger-operator/issues/207#issuecomment-463234778

**Comment by jpkrohling** [comment]
Should we keep `Size` for backwards compatibility? 

cc @objectiser, @pavolloffay

**Comment by objectiser** [comment]
I guess as the apiGroup has changed, then we could make this a breaking change? Although in general if it doesn't complicate code too much, it would be easier to deprecate.

**Comment by jpkrohling** [comment]
It requires both options to co-exist. Right now, the migration path from the old `apiGroup` to the new one is changing from `io.jaegertracing` to `jaegertracing.io` in the CR files.
