### ISSUE TITLE
e2e tests for update scenarios

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#276]
Most (all?) of our current e2e tests are related to the deployment of CRs. We recently added support for instance updates and we do not have e2e tests for that.

Scenarios that would be nice to have as e2e tests:

- [ ] Simple replica size update -- deploy a `simple prod` (Elasticsearch) with the collector's replica size to 2, check that spans can be stored/retrieved, update the replica size to 3, wait for the available replica size to be 3, and check again that spans can be stored/retrieved
- [ ] Same as above, but deploying first a `simplest` (in memory) and then a `simple-prod` (ES).
- [ ] Add volumes
- [ ] Change operand's image (ie, custom jaeger-query)
- [ ] Enable/disable ingress
- [ ] Update the UI config map

**Comment by kevinearls** [comment]
@jpkrohling I may have time to work on this shortly, so I was wondering if you could:

1. Update the list of scenarios?  I can probably come up with some but would love more ideas than just changing the number of replicas.
2. Let me know what you think of combining things in test cases.  Ideally it would be nicer to have separate tests to say, test the simple-prod deployment, and then test changing the number of replicas in the simple-prod deployment.  However, this could end up adding to the time required to do PR builds.  (Although I suppose this depends on how many instances of minikube Github actions will let us run at a time.
)

**Comment by jpkrohling** [comment]
I added a few extra cases to the list.

**Comment by kevinearls** [comment]
@iblancasa  Don't we have update tests now?

**Comment by iblancasa** [comment]
No, we haven't. This is something I have to work on

**Comment by iblancasa** [comment]
**Update**.

Covered scenarios right now:

- [x] *Simple replica size update -- deploy a simple prod (Elasticsearch) with the collector's replica size to 2, check that spans can be stored/retrieved, update the replica size to 3, wait for the available replica size to be 3, and check again that spans can be stored/retrieved*: covered in the `elasticsearch` E2E test suite.
- [x] *Same as above, but deploying first a simplest (in memory) and then a simple-prod (ES)*: covered in the `elasticsearch` E2E test suite.
- [x] *Add volumes*: covered in the `examples` E2E test suite.
- [ ] Change operand's image (ie, custom jaeger-query)
- [x] Enable/disable ingress: covered as part of the `ui` E2E test suite.
- [x] Update the UI config map: covered as part of the `ui`  E2E test suite.
