### ISSUE TITLE
Block until objects have been created and are ready

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#277]
In some parts of the controller, during the reconciliation logic, we check for existing objects, such as deployments. A timing condition might cause the check for the state of a object to fail, as the object might not have been created yet. Ideally, we would wait until the object has been created *and* available, instead of just available.

https://github.com/jaegertracing/jaeger-operator/blob/898bb4312ff74f829f01b1c1c0440a722aaf90bc/pkg/controller/jaeger/deployment.go#L48-L52

https://github.com/jaegertracing/jaeger-operator/blob/898bb4312ff74f829f01b1c1c0440a722aaf90bc/pkg/controller/jaeger/deployment.go#L74-L76

**Comment by pavolloffay** [comment]
In ES we wait for exact number of available replicas to be sure ES cluster is in ready state.

https://github.com/jaegertracing/jaeger-operator/blob/898bb4312ff74f829f01b1c1c0440a722aaf90bc/pkg/controller/jaeger/elasticsearch.go#L68

**Comment by jpkrohling** [comment]
True, but it will fail before that in case there are no objects matching the List criteria:

https://github.com/jaegertracing/jaeger-operator/blob/898bb4312ff74f829f01b1c1c0440a722aaf90bc/pkg/controller/jaeger/elasticsearch.go#L64

**Comment by jpkrohling** [comment]
Basically, we need to check if the error is a "not found" and ignore the failure (`return true, nil`)

The `IsNotFound` function can be used for that:

https://github.com/jaegertracing/jaeger-operator/blob/898bb4312ff74f829f01b1c1c0440a722aaf90bc/pkg/controller/jaeger/jaeger_controller.go#L84

**Comment by pavolloffay** [comment]
> True, but it will fail before that in case there are no objects matching the List criteria:

In general case yes. In ES case I know the expected number of ES nodes so I can loop until they are not there.

**Comment by jpkrohling** [comment]
One example of this situation can be seen in the logs recorded for #279, especially this snippet here:

```
DEBU[0075] creating deployment                           deployment=simple-prod-query instance=simple-prod namespace=default
DEBU[0075] Deployment doesn't exist yet.                 name=simple-prod-query namespace=defaul
```

The deployment was passed to the `create` method but wasn't yet available via the `get` operation.
