### ISSUE TITLE
Docker image is close to 100mb

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#282]
The current Docker image for the operator is close to 100MB at [DockerHub](https://cloud.docker.com/u/jaegertracing/repository/docker/jaegertracing/jaeger-operator/tags). It looks like the change in #191 is the one that caused the biggest bump. Reverting it locally caused the image to go down to the initial levels.

![image](https://user-images.githubusercontent.com/13387/53972686-93155e00-40ff-11e9-920a-e1115e2886da.png)

```
$ docker images jaegertracing/jaeger-operator:1.10.0
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
jaegertracing/jaeger-operator   1.10.0              806a4530248d        7 days ago          266MB


$ docker images jpkroehling/jaeger-operator:latest
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
jpkroehling/jaeger-operator   latest              dcfed8ef97cc        30 seconds ago      44.9MB
```

I'm not sure this is a problem right now, but it's something to keep an eye on.

**Comment by pavolloffay** [comment]
in #191 we switched to centos base image because we needed openssl to generate certs for ES. The whole approach is a bit nasty we run shell script to do that. I would prefer to generate the certs from go if it is possible.

**Comment by jpkrohling** [comment]
So, all we need is a couple of cert files? If so, we should be able to just re-declare the base image.

**Comment by jpkrohling** [comment]
By the way, looks like it's not that hard to generate from Go. I was looking at it during #473 and generating a cert is actually quite easy with go. Basically, [rsa.GenerateKey()](https://golang.org/pkg/crypto/rsa/#GenerateKey) for the private key, and [x509.CreateCertificateRequest()](https://golang.org/pkg/crypto/x509/#CreateCertificateRequest) / [x509.CreateCertificate()](https://golang.org/pkg/crypto/x509/#CreateCertificate) for the certificate.

I assume we would still need this code after we remove some of the duplicate code from the ES Operator, right?

**Comment by jpkrohling** [comment]
I'm closing this, as it's unlikely that we'll ever generate the certs from Go in the foreseeable future.
