### ISSUE TITLE
Unable to get metrics for status spec

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#284]
It seems that jaeger is not able to get metrics from the collector: 

```
DEBU[0077] failed to obtain the metrics from pod         error="Get http://172.17.0.9:14268/metrics: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" instance=simple-prod namespace=myproject url="http://172.17.0.9:14268/metrics"
```

I get the same result for all-in-one

```
minishift v1.31.0+cfc599c
make run WATCH_NAMESPACE=myproject
```

**Comment by jpkrohling** [comment]
Do you have the Jaeger instance in a different namespace as the operator? I think inter-project network is blocked by default in OpenShift.

**Comment by pavolloffay** [comment]
I will double check, but should at least add docs and know how to enable it

**Comment by pavolloffay** [comment]
I have retested it it happens when operator and jaeger instance are running in the same namespace. I have run the operator using `make run`

**Comment by pavolloffay** [comment]
I see the same behaviour on minikube. I think it can be related to how I run the operator e.g. via `make run`. It just does not see pod's network. 

However we should verify that operator will be able to get metrics from different namespaces on OCP

**Comment by jpkrohling** [comment]
> It just does not see pod's network.

Yes, that's the case. When using `make run`, your operator is not running in the cluster.

**Comment by pavolloffay** [comment]
@kevinearls would you be able to test it?

**Comment by kevinearls** [comment]
@pavolloffay  I can take a look, although I'm not sure I have enough information to reproduce this.

**Comment by pavolloffay** [comment]
1. Deploy jaeger operator in a project A. 
2. Then create a simplest instance in namespace B.
3. Generate some tracing data - e.g. open jaeger UI and it should generate spans for itself
4. `oc get jaeger simplest -o yaml` 

The last step should show metrics in Status spec.

Note that you have to deploy jaeger operator via resource files not via `make run` goal.

**Comment by kevinearls** [comment]
@pavolloffay I think this is working properly for me.  I did the following:

- minikube start
- minikube addons enable ingress
- kubectl create namespace observability
- The 5 kubectl create statements from the jaeger-operator readme
- kubectl create namespace issue224
- oc project issue224
- kubectl apply -f deploy/examples/simplest.yaml
- Went to the Jaeger UI in a browser and hit refresh multiple times
- oc get jaeger simplest -o yaml

The output for the last command ended with:

  status:
    collectorSpansDropped: 0
    collectorSpansReceived: 14

Please let me know if there's anything else I can do here.

**Comment by pavolloffay** [comment]
@kevinearls We need to test this on openshift not minikube

**Comment by kevinearls** [comment]
@pavolloffay Sorry, I didn't see the OpenShift requirement.  In any case, I repeated the steps with minishift, and still get collectorSpansDropped and CollectorSpansReceived in the output from oc get jaeger simplest -o yaml

Is this the correct behavior ?

**Comment by jpkrohling** [comment]
I'm closing this, as we don't have this logic anymore. Note however that `make run` will start the operator outside of the cluster, so, similar issues might happen and that's "expected".
