### ISSUE TITLE
Could agent sidecar injection specify service name

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#29]
Wondering if, when an agent sidecar is injected, whether it could also specify the JAEGER_SERVICE_NAME environment variable on the service?

This would avoid user having to manually add it, and also means that we could define the convention - e.g. <name>.<namespace>, if we wanted to support multitenancy.

As a side issue - should the injection be dependent upon an annotation? Similar to Istio sidecar injection which can be enabled on the namespace (so all deployments) or individually? Just so that users have some control, and not everything automatically gets a jaeger agent sidecar.

**Comment by jpkrohling** [comment]
> should the injection be dependent upon an annotation

Yes. Not sure how it works in Istio yet, but I assume it would work in a similar manner.
