### ISSUE TITLE
Revisit Elasticseach spec

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#290]
At the moment our ES spec allows specifying a number of nodes and resources. Based on the number of nodes we create a preferred topology. We should allow users to create more advanced topologies - e.g. with hot and warm nodes https://www.elastic.co/blog/hot-warm-architecture-in-elasticsearch-5-x.

We could embed the whole ES spec from es-operator which is very flexible but requires some ES knowledge to use it appropriatelly. The other approach is to keep our ES spec and for more advanced users allow to use es-operator directly - in this case our operator would just create secrets and inject current configuration.

**Comment by objectiser** [comment]
Could you provide an example of the current ES spec (I guess from your description this is Jaeger specific), and a copy of a simple and complex ES-operator CR, so we can assess the impact on users of exposing the ES-operator CR directly?

**Comment by pavolloffay** [comment]
There are two ES specs - one part of Jaeger spec and second ES spec used by ES operator.

Jaeger CR embeds this: 

```go
type ElasticsearchSpec struct {
	Image            string                            `json:"image"`
	Resources        v1.ResourceRequirements           `json:"resources"`
	NodeCount        int32                             `json:"nodeCount"`
	NodeSelector     map[string]string                 `json:"nodeSelector,omitempty"`
	Storage          v1alpha1.ElasticsearchStorageSpec `json:"storage"`
	RedundancyPolicy v1alpha1.RedundancyPolicyType     `json:"redundancyPolicy"`
}

type ElasticsearchStorageSpec struct {
	StorageClassName string             `json:"storageClassName,omitempty"`
	Size             *resource.Quantity `json:"size,omitempty"`
}
```

Based on these properties we create ES CR which is defined in https://github.com/jaegertracing/jaeger-operator/blob/401ef74cda6fe5b470616d9cbfcedd1f7bc840aa/pkg/storage/elasticsearch/v1alpha1/types.go#L52 (I will not copy it here).

**Comment by objectiser** [comment]
I think for initial release we should just use the ES CR within the Jaeger CR, and not have a simplified version. Once we know things are stable, we may then want to produce a more concise alternative, but might be better to do that based on consultation/real world usage at a later date?

**Comment by pavolloffay** [comment]
> Once we know things are stable, we may then want to produce a more concise alternative, but might be better to do that based on consultation/real world usage at a later date?

We have currently taken the same approach as in cluster logging operator CLO. Generally speaking the component which uses ES storage should know the best how to use it. The goal is to abstract users from ES details and expose just a simple configuration. If you look at ES CR it's very detailed compared to what is in Jaeger. I think we should align with CLO and provide a similar ES configuration abstracting users from ES details - but at the same time allow them to use modify things if needed.


> and a copy of a simple and complex ES-operator CR, so we can assess the impact on users of exposing the ES-operator CR directly?

Simple and complex CR can vary a lot. I think there are a lot of possible configurations and topologies of ES clusters and we should be thinking about the ones which are the most likely to be used. From the top of my head I can think of 

1. single node - covered
2. HA - 3 and more nodes. E.g. 3 master/client/data nodes or 3 master and N client/data nodes - covered
3. hot-warm deployment. E.g. 3 master nodes HOT 3 data/client and 3 WARM data/client.

The master, HOT and WARM nodes use different HW in order fullfil their purpose. The HOT/WARM nodes are configured at init time via `./bin/elasticsearch -Enode.attr.box_type=hot`

Then the current daily index has the following settings which tell ES on which nodes the index should live:
```
PUT /logs_2016-12-26
{
  "settings": {
    "index.routing.allocation.require.box_type": "hot"
  }
}
```

Or on index template:
```
{
  "template" : "indexname-*",
  "version" : 50001,
  "settings" : {
             "index.routing.allocation.require.box_type": "hot"
 ...
```

Once the operator decides the index is old enough it can change `index.routing.allocation.require.box_type` to `warm`. Perhaps this can be done via curator or editing the index mappings/templates directly. 

As we see there is also an index management involved in 3. If we want to support hot/warm topology in ES operator we will probably need a curator component to manage index migration and perhaps conpression etc. So perhaps we will need a flag saying use hot/warm topology. 

To support hot/warm we would need:
* we cannot set `-Enode.attr.box_type=warm` on the ES node
* don't curator for moving indices from hot to warm

**Comment by objectiser** [comment]
Ok, if the Jaeger CR is based on experience gained in the cluster logging operator to provide a simpified CR, then should be ok. Looks like supporting hot/warm config would be a longer term goal.

**Comment by pavolloffay** [comment]
Abstracting ES spec in Jaeger also allow us to change underlying ES storage. So there are two benefits:
* abstracting users from ES configuration
* allows migration to different ES deployment

I think all we need right now is to tell jaeger-operator just to create secrets and inject configuration but do not create ES CR. The CR would be created by more advanced users.

**Comment by objectiser** [comment]
Sounds good. Just to clarify

> tell jaeger-operator just to create secrets and inject configuration 

what secrets? and what configuration is being injected?

**Comment by pavolloffay** [comment]
We create secrets(certs) for secure communication between jaeger and ES. Then we inject flags to tell Jaeger use those secrets. Have a look at storage package to `elasticsearch_*` files

**Comment by pavolloffay** [comment]
I am closing this for now as we don't have this requirement now. More advanced users could connect to an external ES cluster. 

This might not be possible with ECL ES, once we have this requirement we will provide a solution.
