### ISSUE TITLE
add placement hints

### ISSUE THREAD

**Issue by casualjim** [jaegertracing/jaeger-operator#292]
Currently there is no way to get the jaeger pods deployed on nodes that are selected through the nodeSelector and tolerations.
It would be nice if we could get jaeger placed on specific nodes.

**Comment by objectiser** [comment]
Would it be better to just support node affinity, as node selectors will [eventually be deprecated](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity) in favour of it?

**Comment by shamil** [comment]
Also interested in this feature. If operator setups DaemonSet there should be an options to add tolerations so the pods will be started not only on untainted nodes

**Comment by jpkrohling** [comment]
@shamil via node affinity, or node selectors? Or "placement hints" in general, independent of the implementation?
