### ISSUE TITLE
no matches for kind "Jaeger" in version "io.jaegertracing/v1alpha1"

### ISSUE THREAD

**Issue by bysnupy** [jaegertracing/jaeger-operator#293]
I've installed the operator on `OpenShift` through creating the `yaml` files provided from the steps, but the operator back off with `CrashLoopBackOff` as follows.

~~~
# oc get pod
NAME                              READY     STATUS             RESTARTS   AGE
jaeger-operator-97dd6d757-xphlp   0/1       CrashLoopBackOff   8          21m
~~~

And the operator's pod logs are here.
~~~
# oc logs jaeger-operator-97dd6d757-xphlp
time="2019-03-11T12:38:29Z" level=info msg=Versions arch=amd64 jaeger-operator=1.10.0 operator-sdk=v0.4.1 os=linux version=go1.11.1
time="2019-03-11T12:38:29Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-03-11T12:38:29Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=false
time="2019-03-11T12:38:29Z" level=fatal msg="no matches for kind \"Jaeger\" in version \"io.jaegertracing/v1alpha1\""
~~~

What is it wrong in my installation steps for the operator ? It looks like `v1alpha1` API version is not including the `Jaeger` resources, the documentation is based on `v1` API version, so it's not matched API version with it.  If you have any workaround to fix it ?

My env is `OpenShift` `v3.11.82`. Thanks

**Comment by objectiser** [comment]
Apologies but looks like the readme is describing the installation instructions for the current master branch, which has changed apiGroup from `io.jaegertracing/v1alpha1` to `jaegertracing.io/v1`, but the `operator.yaml` is referring to the `1.10` version of the operator.

If you are intending to deploy a CR using the new `jaegertracing.io/v1` apiGroup, then probably the easiest fix is to change the [operator image](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/operator.yaml#L19) to use the `master` tag.

**Comment by bysnupy** [comment]
Thank you @objectiser ! It work for me ! I'll close this issue.
