### ISSUE TITLE
grpc: addrConn.createTransport failed to connect when deploying operator as a daemonset on OpenShift

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#321]

**Comment by kevinearls** [comment]
If I deploy the operator as a daemonset using deploy/examples/agent-as-daemonset.yml I get the following error in the log for the pod:

WARNING: 2019/03/15 13:54:45 grpc: addrConn.createTransport failed to connect to {127.0.0.1:14250 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:14250: connect: connection refused". Reconnecting...

I get the same error in the daemonset e2e test

**Comment by kevinearls** [comment]
I'm going to close this as I see this on Kubernetes too.  I think there is a problem deploying as a daemonset but I don't think this is it.

**Comment by ranetkaSt** [comment]
> m going to clo

Did you receive this problem? I've got the same error...

**Comment by Asisranjan** [comment]
I am also getting this issue when i installed jaeger-kubernetes in minikube. Could you please help me if one resolve this.

**Comment by objectiser** [comment]
@ranetkaSt @Asisranjan Could one of you open a new issue related to kubernetes and provide information specific to your use cases / versions - and preferrable with instructions on how we can reproduce. Thanks.

**Comment by yhyddr** [comment]
i have same trouble but not this application.
for me , it's  firewall's problem to refused connection
