### ISSUE TITLE
Deploying as a daemonset fails on OpenShift

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#322]
Using minishift, I did "oc create -f deploy/examples/agent-as-daemonset.yml".  Once the daemonset deployed, oc describe gave me the following error:

Warning  FailedCreate  4s (x14 over 45s)  daemonset-controller  Error creating: pods "agent-as-daemonset-agent-daemonset-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 5775: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 5778: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 6831: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 6832: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 5775: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 5778: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 6831: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 6832: Host ports are not allowed to be used]

**Comment by objectiser** [comment]
@kevinearls Just to clarify - did you mean "Using minikube" or was it on minishift?

**Comment by kevinearls** [comment]
@objectiser Sorry, I meant minishift.

**Comment by objectiser** [comment]
@jpkrohling Any thoughts?

I was able to reproduce and tried deploying the jaeger instance as `system:admin` user which has privileged scc, so should allow access to host ports.

I also tried:
```
adm policy add-user-to-scc hostaccess system:admin
```
but that didn't seem to help.

**Comment by jpkrohling** [comment]
I thought we had it working and documented for jaegertracing/jaeger-openshift, but looks like there's nothing in the readme about it. I'll try it out and share my findings.

**Comment by jpkrohling** [comment]
Looks like I got it working. Instead of granting `privileged` to the user who is creating the daemonset (which I think is the service account), we can instead create a `scc` that allows daemon host ports to be open for the user.

Once @kevinearls validates the following instructions, I'll update the readme.

First, store the following in a file called `hostport-scc-daemonset.yaml`:
```yaml
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: daemonset-with-hostport
  annotations:
    kubernetes.io/description: 'Allows DaemonSets to bind to a well-known host port'
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
allowHostPorts: true
```

Then, load this CR:
```console
$ oc apply -f hostport-scc-daemonset.yaml
```

Give the users in the namespace privilege to this new security context and load the `agent-as-daemonset` example:
```console
$ oc adm policy add-scc-to-user daemonset-with-hostport -z default
$ kubectl apply -f deploy/examples/agent-as-daemonset.yaml
```

Eventually, it becomes available:
```console
$ kubectl get daemonsets
NAME                                 DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
agent-as-daemonset-agent-daemonset   1         1         1         1            1           <none>          1m
```

**Comment by objectiser** [comment]
@jpkrohling Does this mean that the user creating the jaeger instance has to do this? Or is it the user that is deploying the operator?

If the user creating the jaeger instance, that could be a security problem.

**Comment by jpkrohling** [comment]
A cluster-admin has run all the permission-related commands (the `oc` commands from my previous comment)

**Comment by jpkrohling** [comment]
@kevinearls I think you mentioned on IRC that the instructions here work. Once you confirm that's the case, I'll document it in the readme and send a PR.

**Comment by kevinearls** [comment]
@jpkrohling Yes, you are correct, the instructions work.  Sorry for the delay.
