### ISSUE TITLE
Support providing certificates for self provisioned Elasticsearch

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#330]
At the moment Jaeger operator creates certificates and secrets for secure communication between ES and Jaeger components (query, collector, index cleaner, rollover).

The cert creation is done by https://github.com/jaegertracing/jaeger-operator/blob/master/scripts/cert_generation.sh. The certs are stored on FS, in case of operator restart the certs are loaded back from secrets. The script also regenerates certs if they are expired. 

Note that script sets `CN` which have to match searchguard configuration:
https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/sgconfig/sg_roles_mapping.yml#L15
https://github.com/jaegertracing/jaeger-operator/blob/master/scripts/cert_generation.sh#L260

**Comment by objectiser** [comment]
Just to clarify - the previous work has been to create/manage certificates when using the ES cluster setup by the es-operator?

This PR is about enabling users to specify certificates when using an independently setup ES cluster? If so, can't that just be done by deploying the certificates/secrets and providing the relevant ES command line options?

**Comment by pavolloffay** [comment]
@jpkrohling do you think users would provide all secrets or just CA with the key? To generate clients certs they have to know what CN, OU, O https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/sgconfig/sg_roles_mapping.yml#L26.

**Comment by pavolloffay** [comment]
> This PR is about enabling users to specify certificates when using an independently setup ES cluster? If so, can't that just be done by deploying the certificates/secrets and providing the relevant ES command line options?

This is all related to self-provisioned ES. you are correct is they use external ES instance it's up to them to configure certificates and authorization.

**Comment by jpkrohling** [comment]
> do you think users would provide all secrets or just CA with the key?

I assume secrets are self-sufficient, in that they contain the cert and the key to use, possibly a CA cert to used to verify the counterpart. In other words: a user cannot provide just the client cert or just the key: they have to provide the entire secret.

I do *not* expect people to provide the CA's key at all.

**Comment by pavolloffay** [comment]
I meant secret with all necessary content: 

```var masterSecret = secret{
	name: "master-certs",
	keyFileNameMap: map[string]string{
		"ca":     "ca.crt",
		"ca-key": "ca.key",
	},
}
```

If we do not expect people providing the CA key - then they would have to:
* provide secrets for all components - es, jaeger, curator 
* generate the certs with appropriate settings so SG auhorizes access to resources e.g.  `'CN=system.logging.curator,OU=OpenShift,O=Logging'`
* handle expiration

@ewolinetz do you allow users to provide secrets in CLO? (We pretty much do the same as in CLO.)

**Comment by ewolinetz** [comment]
@pavolloffay no, we don't. We keep it a closed loop at this time.

**Comment by jpkrohling** [comment]
@pavolloffay is this a documentation issue only, or would something be required in the operator's code?

**Comment by pavolloffay** [comment]
No it's not a documentation issue.

**Comment by jpkrohling** [comment]
What's the action then for this issue? Should it be closed as "won't fix", or do you still plan on working on this, despite ECL not directly supporting this?
