### ISSUE TITLE
"cronjob-es-index-cleaner" is what options are available ?

### ISSUE THREAD

**Issue by bysnupy** [jaegertracing/jaeger-operator#331]
Can I refer the documentation for `cronjob-es-index-cleaner` ?
I want to know how can I manage the indices size periodically.

Thanks.

**Comment by jpkrohling** [comment]
Perhaps @pavolloffay can give you a more precise answer, but you can find some information here:

https://www.jaegertracing.io/docs/1.10/deployment/#elasticsearch 
https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/README.md

**Comment by pavolloffay** [comment]
hi @bysnupy 

The best docs are probably in jaeger repo https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/esCleaner.py#L13
 and then for operator https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/apis/io/v1alpha1/jaeger_types.go#L193

**Comment by bysnupy** [comment]
Thank you for your information guys!! 
I’ll check it. Thanks again! My issue has  resolved, I’ll close thi issue. :)
