### ISSUE TITLE
Changing "sidecar.jaegertracing.io/inject" annotation to be more generic

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#351]
Currently the agent sidecar injection mechanism relies on the deployment including an annotation `sidecar.jaegertracing.io/inject` with value either `true` or the name of the jaeger instance it is associated with.

As well as injecting the agent, it also adds a couple of environment variables (service name and propagation) to automatically configure the tracer used by the service.

When the agent strategy is set to `DaemonSet`, the user becomes responsible for configuring the environment variables.

Wondering if we could make the annotation more generic - so not associated with the concept of "inject" and "sidecar", and instead be related to just indicating the deployment should be instrumented (or observed).

Then the operator can use knowledge of whether a sidecar or daemonset agent is being used, and configure the deployment accordingly - along with the relevant environment variables for the selected strategy.

**Comment by jpkrohling** [comment]
The agent strategy isn't an "and/or" decision: there can be a daemon set for for most applications and sidecars dedicated to certain applications. One further argument in favor of the current naming is that its outcome is similar to the similarly named annotation from Istio.

But we could certainly consider a second, non-sidecar/inject related annotation, that will enhance the pod with env vars such as `JAEGER_SERVICE_NAME`.

**Comment by objectiser** [comment]
Is the sidecar injection "always on"? If so, then I think we need to update the documentation to make this clear, as the implication currently is that strategy default is `inject` but can be changed to `daemonset` - i.e. either or.

If that is the case, then possibly a separate annotation would be good - whether the `sidecar.jaeger.io/inject` implies this other annotation or not is a separate question.

**Comment by jpkrohling** [comment]
Need to check the code, but IIRC, the only difference when the strategy is set to `DaemonSet` is that we deploy the daemon set.

**Comment by pavolloffay** [comment]
Closing, the agent component of the Jaeger deployment might get replaced with OpenTelemetry.
