### ISSUE TITLE
Disable ingress (on k8s) by default when strategy not 'allInOne'

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#359]
Having the ingress (on kubernetes) enabled by default when using the 'allInOne' strategy is convenient as it makes it easy to access the Jaeger UI for demos and testing.

However it is not suitable in a production environment (e.g. 'production' or 'streaming' strategies) where secure access will be required. It would also be necessary for an organisation to determine how best to expose the Jaeger UI amongst other endpoints it exposes outside of its cluster - therefore this is best managed outside of the operator.

When running on OpenShift, this will still work as is - as when doing a "production" deployment the "route" used to expose the Jaeger UI is protected by the OAuthProxy, and the route is named.

As there is a difference, depending upon the platform being used, we need to clearly document the defaults.

**Comment by objectiser** [comment]
@jpkrohling Just wondering if this could become confusing for users. Possibly a simpler approach would be to just disable ingress/routes by default - so a CR must explicitly enable with appropriate customisation when required?

**Comment by jpkrohling** [comment]
> Just wondering if this could become confusing for users

Good point. Technically, we are considering disabling the ingress by default because it's will probably be wrong most of the time. I believe the secure route will be right most of the time, and I think "secure by default" is a good strategy.

How about we disable the ingress, enable the secure route, and watch for incoming issues/comments? If users are indeed confused, or if we learn that having the secure route is an annoyance most of the time, we change the default.

**Comment by objectiser** [comment]
Sounds reasonable - will leave for a few days to see if there are any other thoughts before doing a PR.

**Comment by samheutmaker** [comment]
I'm currently running into this problem. Is there a work around to disable the ingress in the meantime?

**Comment by jpkrohling** [comment]
You can disable it by setting the property `enabled` to `false` in the `ingress` node. Look at the ["Creating a new Jaeger instance"](https://github.com/jaegertracing/jaeger-operator#creating-a-new-jaeger-instance) documentation, or the [`disable-ingress.yaml`](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/disable-ingress.yaml) example.

**Comment by samheutmaker** [comment]
@jpkrohling Thanks!

**Comment by Darren-wh** [comment]
@samheutmaker Can you describe the steps? I can't find the parameter. How to disable ingress (on k8s) by default? thanks

**Comment by jpkrohling** [comment]
@Darren-wh, we have an example for that: https://github.com/jaegertracing/jaeger-operator/blob/4b2f557fa84038f018a2b863a3b693b8be13ea3f/examples/disable-ingress.yaml

**Comment by Darren-wh** [comment]
@jpkrohling Thanks./:strong
