### ISSUE TITLE
Set image pull policy to Always

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#370]
At the moment our container specs do not define image pull policy - so the default is used `IfNotPresent`.

We should consider changing the pull policy to `Always` to enable updates.

**Comment by jpkrohling** [comment]
Unless we have specific requirements to set it to `Always`, I'd leave the default behavior enabled. The cluster admin can then change it if they see fit.

**Comment by objectiser** [comment]
@jpkrohling How would the cluster admin change it? We don't currently enable the pull policy to be set in the operator or CR?

**Comment by jpkrohling** [comment]
The common practice is to make use of the [AlwaysPullImages admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages)

**Comment by jpkrohling** [comment]
I don't think we heard any requests from the community in this front. I'm closing this, as I think we should keep whatever the default cluster behavior is. If we have community feedback requesting this to be set on a per-component basis, we can reopen this.
