### ISSUE TITLE
Per-namespace inject annotation

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#373]
Looking at the istio documentation, I learned that we can annotate namespaces (seems obvious in hindsight). The operator could then support looking at the namespace's annotations to determine whether auto-injection should happen or not.

https://istio.io/docs/setup/kubernetes/install/kubernetes/

**Comment by pavolloffay** [comment]
Istio uses labels and not annotations for sidecar injection:

> When you deploy your application using kubectl apply, the Istio sidecar injector will automatically inject Envoy containers into your application pods if they are started in namespaces labeled with istio-injection=enabled:
