### ISSUE TITLE
Gosec "out of memory" issue in travis

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#379]
The `gosec` command is having out of memory problems when running in travis. For example:

https://travis-ci.org/jaegertracing/jaeger-operator/jobs/524976175
https://travis-ci.org/jaegertracing/jaeger-operator/jobs/524973760 (using `./...` instead of `$(PACKAGES)`

**Comment by jpkrohling** [comment]
Was this fixed already by #381?

**Comment by objectiser** [comment]
Yep - sorry for got to link back to issue.
