### ISSUE TITLE
Fix race condition in e2e SmokeTest

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#380]
The smoketest can fail here if the first span has not been flushed by the time the test does the http get.

https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/smoketest.go#L46-L52

**Comment by pavolloffay** [comment]
The whole block is in `wait.Pool` so if the spans is not there the request to query service is repeated.

**Comment by kevinearls** [comment]
@pavolloffay I think the problem is that if you don't find the span you're looking for on the first try, this line returns an error, so the test terminates.  https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/smoketest.go#L50

**Comment by pavolloffay** [comment]
I see that one should return `nil`
