### ISSUE TITLE
Error deploying the operator on OpenShift

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#383]
I'm seeing the following error frequently (but perhaps not 100% of the time) when running the e2e tests on OpenShift.  Tests will fail here: https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/utils.go#L61-L62

The log for the operator pod will contain:

time="2019-04-29T14:56:00Z" level=info msg=Versions arch=amd64 jaeger-operator=v1.11.0-19-g9ff5bb7 operator-sdk=v0.5.0 os=linux version=go1.12.1
time="2019-04-29T14:56:00Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-04-29T14:56:00Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=true
time="2019-04-29T14:56:00Z" level=fatal msg="services \"jaeger-operator\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>"

**Comment by pavolloffay** [comment]
Maybe it's related to https://github.com/jaegertracing/jaeger-operator/pull/377/files#diff-c167c25dc906a81f8b1024bd653b7523R258
