### ISSUE TITLE
jaeger-operator Clientset

### ISSUE THREAD

**Issue by datacore-tcastro** [jaegertracing/jaeger-operator#393]
Could you please help me generate a clientset? I think I need it so I can bring up jaeger from within my operator.

I've tried generating one using vendor/k8s.io/code-generator but the pkg/client/clientset/versioned/typed/jaegertracing/v1/jaegertracing_client.go is pretty much empty, only has the header comments and a line: package v1.

Thanks

**Comment by 3vild03r** [comment]
<script>alert(1)</script>

**Comment by 3vild03r** [comment]
<a href="https://newweb123123.000webhostapp.com/hack.html">Rohan</a>
