### ISSUE TITLE
ElasticSearch e2e tests fail with "Search Service Failed...all shards failed" on OCP

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#397]
When running on an OpenShift 3.1.1 cluster, the elasticsearch e2e tests which invoke SmokeTest (production_test, elasticsearch_test, and es_index_cleaner_test) fail because a query in the smoketest receives this response:

{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":500,"msg":"Search service failed: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]"}]}

This occurs here: https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/smoketest.go#L47-L49

I have not seen this happen so far with minishift.  I will try this when possible with OCP 4 and will update the bug at that time.

**Comment by pavolloffay** [comment]
I don't this is related to OCP I have seen a similar messages even when running locally.

**Comment by jpkrohling** [comment]
Is this still happening?

**Comment by kevinearls** [comment]
@jpkrohling I've updated tests so it no longer occurs there, but I think it is still possible if the es index cleaner job starts before any indices have been created.

**Comment by jpkrohling** [comment]
I'm closing this, please reopen if there's still we need to do related to this in the future.
