### ISSUE TITLE
E2E Tests fail at startup on OCP 4 with Failed to create resource(s) in global resource manifest

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#398]
When trying to run e2e tests (in this case the e2e elasticsearch tests, but I assume this would apply to all tests) on OCP4, the tests fail at startup with:

```
E0507 09:30:33.789947   44431 memcache.go:126] couldn't get current server API group list; will keep using cached value. (Get https://192.168.64.76:8443/api?timeout=32s: dial tcp 192.168.64.76:8443: i/o timeout)
time="2019-05-07T09:31:03+02:00" level=fatal msg="Failed to create resource(s) in global resource manifest: Post https://192.168.64.76:8443/api/v1/namespaces: dial tcp 192.168.64.76:8443: i/o timeout"
```

I'm not certain if the memcache statement is relevant, but the second line results in a test failure.  It is from here:  https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/main_entry.go#L131

**Comment by jpkrohling** [comment]
Was this fixed already?

**Comment by kevinearls** [comment]
@jpkrohling I haven't seen this in a long time, so I'm going to close it.
