### ISSUE TITLE
Add a helm chart

### ISSUE THREAD

**Issue by pavelnikolov** [jaegertracing/jaeger-operator#4]
So far, awesome job @jpkrohling! However I think that the operator needs a helm chart.
In the `README.md` you show how to set this up using the `kubectl --apply ...` command. This is helpful but in a production environment, chances are that we wouldn't install things manually using `kubectl`. This is why I believe that there needs to be a helm chart for installing the operator. WDYT?

**Comment by jpkrohling** [comment]
Absolutely, the operator works best with a Helm chart. Do you think we could change the existing Jaeger Helm chart to use this operator?

https://github.com/helm/charts/tree/master/incubator/jaeger

**Comment by cpanato** [comment]
@pavelnikolov we can create a new chart to host the operator.
if you agree i can work on that

**Comment by pavelnikolov** [comment]
I agree of course. I’d be happy to help.

**Comment by cpanato** [comment]
@pavelnikolov @jpkrohling PR is here: https://github.com/helm/charts/pull/8107

**Comment by jpkrohling** [comment]
This is really great @cpanato! As I'm not an expert regarding Helm, I can't provide a good review, but I'm looking forward to seeing it merged :)

One question I have, though: how would it work for someone to get a Jaeger instance then? Would one need to install the operator via `helm` and then "kubectl apply [simplest.yaml](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/simplest.yaml)"? How about the backing storage?

It would be nice to get some examples (via README?), showing how to get from a clean Kubernetes cluster to an installation with the production strategy using with Elasticsearch. So far, this is the most complex scenario we have (ignoring Kafka for the moment), so, if we could show how people can get this scenario running, it would be really helpful.

**Comment by cpanato** [comment]
@jpkrohling, after you install the operator using helm chart the process to get jaeger running, is the same if you installed that manually using the manifests you need to run the `kubectl apply simplest.yaml` for example

can you provide some example to me? then I can add in the readme 😄

**Comment by jpkrohling** [comment]
Ideally, there would be two examples:

1. the first would be the simplest and would just have an in-memory instance like https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/simplest.yaml
1. the second would show how to install Elasticsearch + Jaeger. I understand there's an ES chart as well, so, it would be nice to demonstrate Helm dependency management capabilities: https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/simple-prod.yaml

**Comment by jpkrohling** [comment]
@cpanato do you have news about this one?

**Comment by cpanato** [comment]
@jpkrohling I will add the items you requested this week

**Comment by jpkrohling** [comment]
Going back to this issue, I see that it's done. Great to see that! 

Would one of you be interested in sending a PR changing the README to include info about how to install the Operator via Helm?

I'm closing this issue in the meantime, as I believe this has been done, but do feel free to open a new issue if there's anything else missing.
