### ISSUE TITLE
Add a mechanism to clean completed/failed jobs triggered by the jaeger-operator

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#406]
At this moment there is no mechanism to delete completed/failed jobs(pods) from the namespace.

We can keep the last job [or] provide an option(number of jobs to be retained) in the CR file.

![image](https://user-images.githubusercontent.com/1004403/57519485-070af700-7339-11e9-82f3-83251e033855.png)

**Comment by jpkrohling** [comment]
Isn't this the same as #418 ?

**Comment by jkandasa** [comment]
@jpkrohling No, This ticket to clean completed/failed jobs.
#418: if a job triggered on a schedule if that failed, multiple jobs/pods created on the same schedule.
Example: triggers a job every day @ 9 AM, if the job fails, creates another pod. if newly created pod fails, creates the next one. This cycle continuing multiple times.

**Comment by jpkrohling** [comment]
Doesn't Kubernetes clean them up? I would expect it to at least cleanup the completed jobs?

**Comment by jkandasa** [comment]
@jpkrohling I think it should do.
Maybe by default we have, long TTL.

@objectiser working on #407 to support user specified TTL
