### ISSUE TITLE
How can I keep my ingress hosts configuration after jaeger operator pod restart

### ISSUE THREAD

**Issue by sunyl527** [jaegertracing/jaeger-operator#408]
Hello, I found the ingress configuration would be revert after the pod  of jaeger operator restarted.
How can I keep my configuration while jaeger operator pod restart?
e.g. 
I create a Jeager instance named `jeager`, it will create a ingress with the hosts `*`, 
then I edit the ingress host.
While I delete the jaeger-operator pod, the ingress will revert in some seconds.
````
[root@test1-istio ~]# kubectl get ing -n devops | grep jaeger
jaeger-query                           *                                       80        36m
[root@test1-istio ~]# kubectl patch ingress jaeger-query -n devops -p "spec:
>  rules:
>    - host: jaeger.dew.ms
>      http:
>        paths:
>          - backend:
>              serviceName: jaeger-query
>              servicePort: 16686
>            path: /"
ingress.extensions/jaeger-query patched
[root@test1-istio ~]# kubectl get ing -n devops | grep jaeger
jaeger-query                           jaeger.dew.ms                           80        37m
[root@test1-istio ~]# kubectl delete po -n devops jaeger-operator-79d67565fc-q6gt6 
pod "jaeger-operator-79d67565fc-q6gt6" deleted
[root@test1-istio ~]# kubectl get ing -n devops | grep jaeger
jaeger-query                           jaeger.dew.ms                           80        38m
[root@test1-istio ~]# kubectl get ing -n devops | grep jaeger
jaeger-query                           *                                       80        38m
````

**Comment by objectiser** [comment]
> I create a Jeager instance named jeager, it will create a ingress with the hosts *,
then I edit the ingress host.

The operator is responsible for all of the resources that it creates - so manually applying any changes to those resources will eventually be reverted by the operator. You need to create a feature/enhancement request to ensure that the operator creates the required configuration on your behalf.

**Comment by sunyl527** [comment]
> The operator is responsible for all of the resources that it creates - so manually applying any changes to those resources will eventually be reverted by the operator. You need to create a feature/enhancement request to ensure that the operator creates the required configuration on your behalf.

Thanks for your reply.
Is there anyway for me to set ingress host with Jaeger instance?
I find the only way is to set ingress disable with 
```
  ingress:
    enabled: false
```
so that I can create a new ingress with my custom configuration.

**Comment by objectiser** [comment]
Not currently - this is the ingress definition: https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/apis/jaegertracing/v1/jaeger_types.go#L125-L129

So it would be worth creating a separate enhancement request - and would also be great if you could contribute a PR :)

**Comment by sunyl527** [comment]
Thanks.  :) I am sorry that my coding is poor.Hope it would be supported in the future.

**Comment by objectiser** [comment]
@sunyl527 Its not a problem if you are unable to provide a PR - just did a quick search and found there is already an issue requesting this feature: https://github.com/jaegertracing/jaeger-operator/issues/135

Hopefully someone will implement it soon.
