### ISSUE TITLE
Enable specifying serviceAccount and securityContext

### ISSUE THREAD

**Issue by mwieczorek** [jaegertracing/jaeger-operator#421]
When we create a new Jaeger resource, new serviceAccount with the same name is created and all jaeger components are run with this SA.
It's not possible to set securityContext for the Jaeger components

Enable specifying serviceAccount and securityContext in jaeger CR (top-level and on each component separately).

**Comment by jpkrohling** [comment]
Would you be interested in contributing this feature?

**Comment by mwieczorek** [comment]
I don’t do golang day to day, but I can try.
Of course if someone else from the community finds this „good first issue” and would like to do it - Please comment here and go ahead.
