### ISSUE TITLE
Deploying as sidecar - what should be local_agent / reporting_host?

### ISSUE THREAD

**Issue by pzheng64** [jaegertracing/jaeger-operator#422]
I'm using Kubernetes cluster and I'd like to deploy Jaeger operator and instance.
I've followed the steps in this block.
https://github.com/jaegertracing/jaeger-operator#auto-injection-of-jaeger-agent-sidecars

- `observability`: Namespace where Jaeger operator has been deployed
- `jx-staging`: Namespace where my client app (dev-hub-server) which will be traced using Jaeger client.

By the way, what should be local_agent / reporting_host in the config array?  `localhost` or `jaeger`?
```# OpenTracing settings

# default tracer is opentracing.Tracer(), which does nothing
OPENTRACING_TRACER_CALLABLE = __name__ + '.tracer'

def tracer():
    install_all_patches()
    config = Config(
        config={
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'local_agent': {
                'reporting_host': 'jaeger',
                'reporting_port': '6831',
            },
            'logging': True,
        },  
        service_name='devhubserver',
        validate=True,
        metrics_factory=PrometheusMetricsFactory(namespace='devhubserver')
    )
    return config.initialize_tracer()


# default is False
OPENTRACING_TRACE_ALL = True

# default is []
OPENTRACING_TRACED_ATTRIBUTES = ['path', 'method', 'META', 'body', 'path_info', 'content_type', 'content_params', 'GET', 'POST', 'COOKIES', 'FILES', 'headers']```

**Comment by objectiser** [comment]
When deploying the agent as a sidecar, it will be referenced at `localhost`.

**Comment by pzheng64** [comment]
@pavolloffay Great, it worked! Thank you so much.  One more question.  How can I define `ingress` inside all-in-one.yaml? Can I define like this?
```apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne # (1)
  allInOne:
    image: jaegertracing/all-in-one:latest # (2)
    options: # (3)
      log-level: debug # (4)
  ingress:
    metadata:
      annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-jaeger
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      labels:
        app: jaeger
        app.kubernetes.io/component: query-ingress
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/managed-by: jaeger-operator
        app.kubernetes.io/name: jaeger-query
        app.kubernetes.io/part-of: jaeger
      name: jaeger-query
      namespace: {{ .Values.namespace }} # Need to define namespace here: e.g. jx-staging
    spec:
    backend:
      serviceName: jaeger-query
      servicePort: 16686```

**Comment by objectiser** [comment]
@pzheng64 Ingress is enabled by default for the allInOne. Further information on accessing the UI can be found here: https://github.com/jaegertracing/jaeger-operator#kubernetes-1

**Comment by pzheng64** [comment]
@objectiser But I need to define domain name.

**Comment by objectiser** [comment]
@pzheng64 Best thing currently would be to disable the ingress in the CR and deploy your own. If you could then create a new issue identifying what is missing in the current ingress.

**Comment by jpkrohling** [comment]
I'm closing this, as it seems that the questions have been answered. Feel free to reopen if there's still something pending.
