### ISSUE TITLE
Automatically scale components based on metrics

### ISSUE THREAD

**Issue by atmosx** [jaegertracing/jaeger-operator#428]
Hello!

It is not clear to me how to horizontally scale single components. Is this something we need to handle ourselves based on exported metrics or does the operator manage this somehow?

Are there any known best practices from people with high volume of traces?

Thanks!

**Comment by pavolloffay** [comment]
Hi, right now it is not automatic and you should scale the components manually via created CR.

**Comment by jpkrohling** [comment]
We do have auto-scaling in the roadmap, though.

**Comment by mumrau** [comment]
#856 added support for autoscaling on the collector. 
Stop me if I'm wrong, but I suppose this is groundwork for other components as well? I'm particularly thinking about the ingester, obviously.
I'll use autoscaling on the 1.17 release, and will be very happy to provide feedback, if anything doens't go the way expected.

**Comment by jpkrohling** [comment]
That's absolutely right. If HPA works as expected, we can apply the same idea to the ingester.

**Comment by objectiser** [comment]
This has now been implemented in #856 (for collector) and #1006 (for ingester). Feel free to reopen if something is missing.
