### ISSUE TITLE
Image for 1.12.0 not available in dockerhub

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#429]
Although the build completed successfully in travis, there is only a tag for `1.12`, but not for `1.12.0`: https://hub.docker.com/r/jaegertracing/jaeger-operator/tags

Problem is that the operator instructions reference an `operator.yaml` that refers to the `1.12.0` image. So we either need to:

- Find a way to tag the image with `1.12.0`, or
- Update the `operator.yaml` to reference `1.12` for now - which will be replaced when the next version is release.

@pavolloffay @jpkrohling Thoughts?

**Comment by pavolloffay** [comment]
Why there is no tag 1.12.0? Did we decide to not publish it or is the build flaky?

**Comment by cfontes** [comment]
I had the same issue today on our daily env creation tests Jaeger operator failed, changing to 1.12 worked

But since it's an operator there is no way to make sure tomorrow it will work too unless you guys commit the change to this https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml

**Comment by objectiser** [comment]
@pavolloffay According to the [build log](https://travis-ci.org/jaegertracing/jaeger-operator/jobs/535813628) it pushed 1.12.0.

**Comment by jpkrohling** [comment]
Interesting, the build on Travis apparently did upload 1.12.0: 

```
...
Successfully tagged jaegertracing/jaeger-operator:1.12.0
Pushing image jaegertracing/jaeger-operator:1.12.0...
The push refers to repository [docker.io/jaegertracing/jaeger-operator]
...
```

https://travis-ci.org/jaegertracing/jaeger-operator/jobs/535813628#L344

**Comment by objectiser** [comment]
Yes, its a strange - just disappeared within dockerhub :(

In the end I just pushed it manually.
