### ISSUE TITLE
Inject sidecar if a deployment has a specific annotation

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#43]
Investigate the possibility of injecting an agent sidecar in case a deployment contains a given label. See how the annotations for istio's auto injection are and try to follow the same naming pattern.

**Comment by thedodd** [comment]
Would definitely be awesome to see this land. Just curious ... the README states that this functionality is already there and available for usage, but it definitely doesn't seem to be working. Perhaps we should include some information in the README that this is unimplemented?

**Comment by jpkrohling** [comment]
Which version of the Operator are you using? The feature has been merged, but was released just this week. Make sure you are using the Operator version 1.8:

https://github.com/jaegertracing/jaeger-operator/blob/effbb55faf0f2dc8302d3683b961e577892ec7c7/deploy/operator.yaml#L17

If you need a reference, I use the following project when developing (which is also used in the e2e tests):

https://gitlab.com/jpkroehling/vertx-create-span/blob/master/deployment-sidecar.yaml

https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/sidecar.go#L74

**Comment by jpkrohling** [comment]
I'm closing this issue, but feel free to reopen if you have trouble using this feature.
