### ISSUE TITLE
Operator capability level 3

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#438]
The high-level issue to bring operator to level 3 based on https://github.com/operator-framework/operatorhub-docs/blob/master/building-operators/building-operators/types-of-operators.md#operator-maturity-model

Based on the https://operatorhub.io/operator/jaeger-operator jaeger-operator is level our current level is 2:

> Supports patch and manor version upgrades

Level 3 is
> App lifecycle, storage lifecycle (backup, failure recovery)

Apart from the storage, I think we should be already level 3.

**Comment by jpkrohling** [comment]
What's the action item here? Tell Operator Hub that we are level 3? Or work on the storage lifecycle? I believe the storage part would belong to the storage operator, no?

**Comment by pavolloffay** [comment]
If we think there is no action on our side we can just ask them to bump the level.

Storage concerns belong to storage operator, except schema migrations which we own.

**Comment by jpkrohling** [comment]
> schema migrations which we own

We are doing this already, right?

**Comment by pavolloffay** [comment]
I cannot recall any migrations we do.

**Comment by jpkrohling** [comment]
For Cassandra, we do have a schema script that is supposed to handle this.

**Comment by pavolloffay** [comment]
Not quite see migrations steps here https://github.com/jaegertracing/jaeger/blob/master/CHANGELOG.md#1100-2019-02-15.

Jaeger 1.10 automatically uses schema V2, however we did a patch to storage layer which automatically recognizes which schema has been created. but it does not migrate any data.

We don't do any schema migrations explicitly in the operator. If I am wrong please correct me.

**Comment by jpkrohling** [comment]
> Run plugin/storage/cassandra/schema/migration/v001tov002part1.sh which will copy dependencies into a csv, update the dependency UDT, create a new dependencies_v2 table, and write dependencies from the csv into the dependencies_v2 table.

I missed that, but that's exactly the case that should be handled by the operator.

**Comment by jpkrohling** [comment]
Related to #42

**Comment by pavolloffay** [comment]
Based on https://operatorhub.io/operator/jaeger we are already level 4- deep insights.
