### ISSUE TITLE
Make run is broken

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#441]
Make run fails with the following error:

```
INFO[0000] Versions                                      arch=amd64 jaeger-operator=v1.11.1-5-ged370cf operator-sdk=v0.5.0 os=linux version=go1.11.1
INFO[0000] Auto-detected the platform                    platform=kubernetes
INFO[0000] Automatically adjusted the 'es-provision' flag  es-provision=false
FATA[0000] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined 
exit status 1
make: *** [Makefile:106: run] Error 
```

Running git bisect indicates that this commit https://github.com/jaegertracing/jaeger-operator/commit/ed370cf4fa5559d284f885420586293cd0229c80 introduced the problem cc) @objectiser.

**Comment by pavolloffay** [comment]
I am looking at a fix. The problem is that we create a new client with the assumption we are running inside a k8s pod https://github.com/jaegertracing/jaeger-operator/commit/ed370cf4fa5559d284f885420586293cd0229c80#diff-c167c25dc906a81f8b1024bd653b7523R231

Maybe a better is to reuse the client from the manager.

**Comment by pavolloffay** [comment]
The client from the manager could not find the operator deployment. Also the metrics package from operator SDK is using the rest client with the same creation as we do.

**Comment by jpkrohling** [comment]
> Also the metrics package from operator SDK is using the rest client with the same creation as we do.

Would be worth creating an issue upstream about it. I don't see a reason why we would want to prevent the metrics service from being used outside of a cluster context.
