### ISSUE TITLE
Scan deployments for agent injection

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#442]
When a Jaeger instance is installed via a given CR and the operator is then stopped, new deployments with the auto-injection annotation are ignored until the deployment has an update.

To solve this, the operator should check for all deployments when it first starts, injecting an agent when needed.

**Comment by jpkrohling** [comment]
From #427

**Comment by jpkrohling** [comment]
@rubenvp8510 I think this case here is covered, right?

**Comment by rubenvp8510** [comment]
@jpkrohling yes!
