### ISSUE TITLE
QQ about jaeger-operator standard deployment

### ISSUE THREAD

**Issue by atmosx** [jaegertracing/jaeger-operator#457]
Dear all,

I want to make sure I understand the available deployment solutions. There are currently two ways to deploy jaeger on a kubernetes cluster:

1. Run the entire set in every namespace and have the operator dynamically deploy the agents
1. Run as a daemonSet

From the documentation and tests I made, the ideal solution here is to deploy each component (operator, web-ui, collector & cronjobs) on every namespace. Is this correct or am I missing something?

Thanks!

**Comment by jpkrohling** [comment]
Hey @atmosx,

You should have only one operator for your whole cluster. Apart from that, it's possible to have one "instance" per namespace, or one "instance" for your whole cluster. It depends on your specific requirements and tenancy model.

"Instance" is a "Jaeger instance" (represented by a Custom Resource, CR) and contains a collector, query, batch jobs, ...

Note that the only component that might run as a daemon set is the agent. In that case, you should have only one Jaeger instance with the agent strategy set to "Daemon Set", as it binds to a well-known port: if you install a second instance also set to use agents as daemon set, it will try to bind to the same port as the first instance and will therefore fail. 

I'm closing this issue, hoping that my answer clarified things for you. If you still have questions, feel free to reopen.
