### ISSUE TITLE
failed to create or get service for metrics

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#461]
Currently, the Jaeger Operator fails to start in OpenShift due to the following message:

```
time="2019-06-05T12:29:54Z" level=fatal msg="failed to create or get service for metrics: services \"jaeger-operator\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"
```

This log message is recorded with `fatal` level, making the operator to simply exit upon this failure. Operators created with newer versions of the SDK have this set to `info` instead. This of course doesn't fix the underlying problem, but I think we should not crash the operator because of this failure.

**Comment by LiliC** [comment]
@jpkrohling Hello, you need to add the following to your role.yaml file, and it should fix this problem, as we are putting the Deployment of the operator as the owner to the OwnerRef of the Service object on creation:
```
  resources:
  - deployments/finalizers
```
 Docs [on this in operator-sdk](https://github.com/operator-framework/operator-sdk/tree/master/doc/user/metrics#garbage-collection). See full role.yaml file here -> https://github.com/operator-framework/operator-sdk-samples/blob/bd30254f3a7e3943fdbae33e9b6992bce1e07755/memcached-operator/deploy/role.yaml

 Let me know if this doesn't work for you!

**Comment by jpkrohling** [comment]
Spot on, @LiliC! Would you be open to review the PR that reinstates the metrics service?
