### ISSUE TITLE
build docker images

### ISSUE THREAD

**Issue by arnitolog** [jaegertracing/jaeger-operator#463]
What is the proper way to build a set of docker images from the master? 
Does the operator itself and all components use the same image? I want to test this fix https://github.com/jaegertracing/jaeger-operator/pull/445. But it is not clear for me which images I need to build and use

**Comment by objectiser** [comment]
If you are looking to test the latest version of the operator (including that fix), then you can use the https://hub.docker.com/r/jaegertracing/jaeger-operator/tags `master` tag here.

The operator only has a single image, the jaeger components that are being managed have their own docker images built from the https://github.com/jaegertracing/jaeger repo.

Will close - reopen if you have further questions.

**Comment by arnitolog** [comment]
thanks a lot

чт, 6 июн. 2019 г. в 00:18, Gary Brown <notifications@github.com>:
