### ISSUE TITLE
Lint OLM files

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#470]
OLM configuration files can be linted with
```bash
operator-courier verify --ui_validate_io /home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger-operator/deploy/olm-catalog
```

This should be added to our CI/makefile to assure the configuration is correct. Now it fails on
```
ERROR:operatorcourier.identify:Courier requires valid input YAML files
Courier requires valid input YAML files
```

It fails because `_generated.concat_crd.yaml` contains two `crd`s. 

@objectiser how were the files in `olm-catalog` generated? There are no instructions on what has to be updated on a new operator version.

**Comment by jpkrohling** [comment]
At least for the newest operator SDK versions, we should be able to generate the CSV files via `operator-sdk olm-catalog gen-csv`. We just need to get the right `deploy/olm-catalog/csv-config.yaml` :-)

**Comment by jpkrohling** [comment]
This might not be relevant anymore, as the CSV files are automatically generated based on certain input files, like CRD and roles/role bindings.
