### ISSUE TITLE
Cassandra Create schema with TLS config

### ISSUE THREAD

**Issue by Demonian** [jaegertracing/jaeger-operator#474]
HI,

There is ability to configure Cassandra storage with automatic schema creation through `jaeger-operator`, but there is no ability to use this if Cassandra is configured with TLS, because there is no ability to mount volume to Job.

This ability has been already implemented in `jaeger`: [Link to Jaeger Cassandra TLS configs for Create Schema](https://www.jaegertracing.io/docs/1.12/deployment/#tls-support)

**Expected Result**
There should be ability to use `createSchema` with TLS configs if there is ability to use Cassandra Storage with TLS.

**Proposal**
To fix this we can use volume mounts that are created through `Jaeger` manifest. 
E.g. in collector:

```
...
baseCommonSpec := v1.JaegerCommonSpec{
		Annotations: map[string]string{
			"prometheus.io/scrape":    "true",
			"prometheus.io/port":      strconv.Itoa(int(adminPort)),
			"sidecar.istio.io/inject": "false",
		},
		Labels: labels,
	}

	commonSpec := util.Merge([]v1.JaegerCommonSpec{c.jaeger.Spec.Collector.JaegerCommonSpec, c.jaeger.Spec.JaegerCommonSpec, baseCommonSpec})
...
VolumeMounts: commonSpec.VolumeMounts

```

**Comment by jpkrohling** [comment]
@Demonian, do you mean, here?

https://github.com/jaegertracing/jaeger-operator/blob/ce0ab28c64b8582f6db615e37ad10a668aa6aad2/pkg/storage/cassandra_dependencies.go#L84-L108

**Comment by Demonian** [comment]
@jpkrohling I mean that we should mount all secrets from main jaeger deployment to jobs also, or allow to configure specific volume mounts for job.
