### ISSUE TITLE
Support sidecar injection for Pods, ReplicaSets, and/or CRDs

### ISSUE THREAD

**Issue by jessesuen** [jaegertracing/jaeger-operator#475]
Can `sidecar.jaegertracing.io/inject` be done at a ReplicaSet or even Pod level? Or does must it only be a Deployment?

Allowing injection to happen at the lower level constructs would make it possible for jaeger-operator to integrate with CRDs (such as the [Argo Rollout CRD](https://github.com/argoproj/argo-rollouts)) which users would use in lieu of a Deployment. For example, istio follows this model.

Based on https://github.com/jaegertracing/jaeger-operator/pull/473, it appears that jaeger-operator now uses mutating webhooks to perform injections, which means Pod level injection would work for everyone.

**Comment by jpkrohling** [comment]
That's great feedback, @jessesuen! We decided to add support only for `Deployments` at first, to see if the approach would work. Apart from a couple of annoying things, it does work, so, we could certainly expand to other known types, like `Pods`.

That said, we are experimenting with a more standard approach, as described in the PR you linked. There are a couple of problems with that approach as well, such as setup complexity. Take a look at the changes to the `README.adoc` file in that PR, as it has an outline of all the steps required to get the automatic injection to work when using mutating webhooks.

For the record, @objectiser recently mentioned that Istio is moving away from webhooks, replacing their sidecar with a CNI plugin. This is also on our radar, but no work has started on that front yet.

**Comment by jpkrohling** [comment]
I'm closing this issue, as I don't think there's any action we need to take here other than collect your feedback, but feel free to reopen if you think there's something else we should be doing.
