### ISSUE TITLE
Ability to add extra annotations to OAuth Service Account

### ISSUE THREAD

**Issue by jwendell** [jaegertracing/jaeger-operator#479]
Our use case is that we want to add another annotation in here: https://github.com/jaegertracing/jaeger-operator/blob/13a53f753030688b58c79a3532e75d236af78172/pkg/account/oauth-proxy.go#L32

So that we can have a second route pointing to this service.

Because we just want to add another route, our annotation would be similar to https://github.com/jaegertracing/jaeger-operator/blob/13a53f753030688b58c79a3532e75d236af78172/pkg/account/oauth-proxy.go#L53

Meaning that just having a field like `extraRouteNames: []string` would work for us.

**Comment by jpkrohling** [comment]
Sorry, this is a bit confusing: do you need to customize the OAuth Redirect Reference, or do you need extra annotations to the `ServiceAccount`?

**Comment by jwendell** [comment]
What we need is to have a second OpenShift route to reach the Jeager pod (protected by OAuth). In order to achieve that we need to add a second annotation to the `jaeger-ui-proxy ServiceAccount`. This annotation is very similar to the one you already have, the only change is in the route name.

How you are going to implement this we leave to you. Perhaps you don't want to expose the whole `annotation` field so that users can append things there. If that's the case, you might want to expose a field where users can specify extra OpenShift route names to be used, like my suggestion above, or use Rob's:
```yaml
ingress:
  enabled: true
  defaultRoute: jaeger-query
  additionalRoutes:
  - tracing
```

**Comment by jwendell** [comment]
Two notes:
1. The value of that annotation can be a domain or (like we are using) a reference to an OpenShift route: https://docs.openshift.com/online/architecture/additional_concepts/authentication.html#redirect-uris-for-service-accounts
1. By letting users add any extra annotations they want, you give more flexibility. Not sure if this is what you want though.

**Comment by objectiser** [comment]
The `IngressSpec` already allows annotations to be specified, they are just not added to the route, so that looks like the best approach.

**Comment by jwendell** [comment]
@objectiser Note that those annotations we need are for the `jaeger-ui-proxy ServiceAccount`.

**Comment by jpkrohling** [comment]
We discussed this via IRC and there are a few things to consider:

- For the usual case, the operator should manage its route
- For the edge cases, the operator should allow users to manage this route externally (`enabled: false`)

The consensus seems to be that we don't need two routes (`jaeger-query` + `tracing`). @objectiser suggested having only the one we already have, skipping the `tracing` one. Should there be a need for an extra route, users can create it and manage externally.

As we don't know whether there's demand for this case yet, the question that remains is whether we want to do any changes to the operator to support it. If so, should we allow custom annotation entries to be specified for the `service-account-oauth-proxy` service account? Should we allow the service account used by the deployment containing the OAuth Proxy to be overridden?

**Comment by jpkrohling** [comment]
I'm closing this, as we decided to go with only one route.
