### ISSUE TITLE
simple-prod-deploy-es.yaml example fails on OCP 4.1.2

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#481]
The simple-prod-deploy-es.yaml example, as well as the self_provisioned_elasticsearch_test fail on OCP 4.1.2 because the elasticsearch pod never comes out of Pending state.

When this condition occurs I get the following message in the OCP 4.1.2 admin console: "Unschedulable: 0/5 nodes are available; 5 node(s) didn't match node selector "

**Comment by pavolloffay** [comment]
@kevinearls could you please report this in ES operator repository https://github.com/openshift/elasticsearch-operator? 

To help them debug just get the ES CR jaeger operator created - `oc get elasticsearch ....`

**Comment by kevinearls** [comment]
@pavolloffay I've opened https://github.com/openshift/elasticsearch-operator/issues/166

**Comment by objectiser** [comment]
@kevinearls - could you add to that ticket that you found the problem with OCP4.1.2, and also whether it worked with earlier versions of OCP 4.x?

**Comment by objectiser** [comment]
Sorry, 4.1.2 is in the title - but meant if you had tested it on previous versions of 4.0 or 4.1, and whether it had worked then.

**Comment by kevinearls** [comment]
@objectiser I've updated that bug.

**Comment by pavolloffay** [comment]
I don't think this is related to OCP version. I get the same error even running locally on 3.11. 

We should be running ES self-provisioned test on every PR on travis to catch the issues early. I have booked an issue for it https://github.com/jaegertracing/jaeger-operator/issues/484

**Comment by kevinearls** [comment]
NOTE: When this is fixed please remove the SKIP added in this PR

**Comment by jpkrohling** [comment]
Is this still happening?

**Comment by kevinearls** [comment]
@jpkrohling  Yes, I can still reproduce this.

**Comment by objectiser** [comment]
@kevinearls Just to clarify - is this using 4.1.x of the elasticsearch operator? The error seems related to the node label @jkandasa identified as being required by the es-operator master, but shouldn't be required for 4.1.x version of es-operator?

**Comment by kevinearls** [comment]
@objectiser No, things work correctly with version 4.1.x of the elasticsearch operator.  It still fails with the master though.

**Comment by pavolloffay** [comment]
I have talked to @objectiser the solution to this is to add label `kubernetes.io/os=linux`  to node. It was added in this PR https://github.com/openshift/elasticsearch-operator/pull/164.

I have submitted a PR #535 which adds this label to all nodes. 

I am not sure if we can do something more about this behavior other than set the required label on the nodes.

**Comment by pavolloffay** [comment]
I am closing this as it is not an issue or our side. See the comment above.
