### ISSUE TITLE
Run self es-self provisioned test on travis

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#484]
Run `make e2e-tests-self-provisioned-es` on travis. The motivation is to catch issues early.

For example https://github.com/jaegertracing/jaeger-operator/issues/481 is not related to OCP version but to change in ES operator.

@kevinearls would you be interested in this issue?

**Comment by pavolloffay** [comment]
Side note. self provisioned ES needs openshift to run. It does not run on plain k8s so we will need OCP on travis. I propose to use `oc cluster up` (3.9 is the lightest), we have done it here https://github.com/RHsyseng/docker-rhel-elasticsearch/blob/master/tests/prepare.sh to test other ES image.

**Comment by jpkrohling** [comment]
Perhaps we could add a suite for OpenShift (`// +build openshift`) and run it as a separate job?
