### ISSUE TITLE
Limit label values to 63 chars

### ISSUE THREAD

**Issue by bertpersyn** [jaegertracing/jaeger-operator#487]
**Description**

When an operator is defined, the length of the jaeger resource name isn't checked:

In the code, there is no check on the 63 char limit for [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/). (Is this correct?)

> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

**Question**

When deploying an operator that exceeds this limit, is there a trace of the failure?
Is there a way to fail the operator installation?
Maybe fix this problem in these ways:

* the length of the resource name is what the official specs are saying, but the operator code trims referencing labels to the label spec length?
* limit the length of the operator resource name?

**Comment by jpkrohling** [comment]
I'm probably missing something here, but is the limit of 63 chars also applied to the resource name? Or only to labels? If it's only to labels, how are you getting affected by the resource name being bigger than 63 chars? I believe it might be because of a code like the one below, but would be nice to confirm:

https://github.com/jaegertracing/jaeger-operator/blob/fe53dbb8804ae931b1ca76c21daf149e17f81f19/pkg/deployment/all-in-one.go#L198-L205

**Comment by bertpersyn** [comment]
> "app.kubernetes.io/instance": a.jaeger.Name,

I think this is indeed a violation of this [spec](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)

Maybe a first class citizen could be something like this:

```
type LabelMap struct {
	labels map[string]string
}

func NewLabelMap () *LabelMap {
	return &LabelMap {
		labels : make(map[string]string),
	}
}
func (lm *LabelMap) Store(label, value string) error {
   if len(label) + len(value) + 2 > 63 {
	return errors.New("a label cannot be longer than 63 chars")
   }
   lm.labels [label] = value
   return nil
}

func (lm *LabelMap) GetAll() map[string]string {
  targetMap := make(map[string]string)

  for key, value := range lm.labels {
    targetMap[key] = value
  }
  return targetMap 
}
```

[Playground](https://play.golang.org/p/YTHcfxrFrWb)

**Comment by jpkrohling** [comment]
Do we really want to fail because we can't add the full instance name to a label? Can't we just truncate it? I think we are not using this label for anything "serious".

**Comment by bertpersyn** [comment]
Truncation is a valid option I think

**Comment by jpkrohling** [comment]
Sounds like a "good-first-issue" ;-)

**Comment by bhavin192** [comment]
I would like to work on this one.

**Comment by objectiser** [comment]
@bhavin192 Its yours.

**Comment by bharaththiruveedula** [comment]
@objectiser @bhavin192 if no one working on this, can I take it up?

**Comment by bhavin192** [comment]
Sorry for complete silence on this. Wasn't having proper cluster setup on my machine. Now I have it, so I'm working on this. I think it's possible to solve this and #226 in one PR.

**Comment by bhavin192** [comment]
I wrote a simple function which truncates the value of a label if it's length is more than 63 characters. After doing that change now there is issue with Service name being > 63 characters.

**Comment by jpkrohling** [comment]
I think we wrap most service names in functions, so, you can change them to truncate at 63 chars as well.
