### ISSUE TITLE
Document how to disable the index cleaner job

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#489]
See #488 for context. This probably belongs to the Elasticsearch section of the readme.

**Comment by jpkrohling** [comment]
@cfontes, want to give this a try?

**Comment by cfontes** [comment]
@jpkrohling Sure, I will.

**Comment by cfontes** [comment]
here it is https://github.com/jaegertracing/jaeger-operator/pull/490

**Comment by jpkrohling** [comment]
@cfontes, are you still interested in working on this one?

**Comment by jpkrohling** [comment]
Sorry, the PR is there: #491!

**Comment by pavolloffay** [comment]
done in #491
