### ISSUE TITLE
Reconsider the strategy setting

### ISSUE THREAD

**Issue by pavelnikolov** [jaegertracing/jaeger-operator#5]
I like that `all-in-one` is the default value for the `strategy` setting. However, for new starters with Jaeger it might not be immediately obvious what the difference between `all-in-one` and `production` is. I would suggest a different point of view here. Instead of changing the functionality based on `strategy`, change it based on `storage`. Consider renaming the `strategy` option to `storage` and allow the following values: `memory`, `elasticsearch`, `cassandra`, etc.
The default `storage` option might be `memory`. The operator would chose the `all-in-one` image for that storage type. The user will still have the option to override the image for advanced users but in most cases you can preselect the default jaeger docker images - only request the users to select the version (tag) and image pull policy.
The other benefit of this approach is that if you change functionality based on storage type you can also add some functionality for managing retention. For example, you can delete Elasticsearch indices when they get out of retention. Alternatively, you can have per-service/operation retention and the operator can delete the traces for some busy services from Cassandra after a week but keep others for a month.
I am not saying that this is the best approach, I just wanted to give you a different point of view.

**Comment by jpkrohling** [comment]
I'm not sure this should be done right now. I'd rather leave this item open and wait for feedback from users.

The reason is that the "all-in-one" is suitable for pretty much all use cases, as it can be used with the same storage backends as the `production`. It's the default strategy if nothing is provided at all.

The only advantage of the production strategy for most users is that it can be individually scaled and it's used only if it's explicitly set (ie, the user has read about it).

**Comment by jpkrohling** [comment]
It is decoupled already:

https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/simple-prod.yaml

**Comment by jpkrohling** [comment]
I see the confusion now. The thing is: right now, the `storage.options` object goes directly to the `args`, just like the `all-in-one.options`. It makes sense to specify the `options` for the storage as a top-level object, as it's shared among the query and collector, but it doesn't really matter that much for the `all-in-one`.

For now, I'll then just change the example to use a different configuration switch than `memory-max-traces`.

**Comment by jpkrohling** [comment]
Has anyone given any further thoughts about this? We now have the storage options decoupled from the component nodes (allInOne, collector, ...). I like the simplicity that a strategy based on the storage brings, but at the same time, it deviates from what is done with Jaeger proper: all-in-one can be used with, say, Kafka.

**Comment by objectiser** [comment]
I think having the strategy, independent of the configuration of any specific aspect of the system, gives us greater flexibility (e.g. to add `streaming` strategy - and potentially others in the future).

**Comment by jpkrohling** [comment]
I'm closing this, as it seems there's value in having strategy *and* storage as independent constructs. The storage might be chosen based on the strategy (and vice-versa), but the end user should be able to decide how the jaeger instance is deployed in terms of components (production/streaming/all-in-one) and storage (cassandra/es/kafka).
