### ISSUE TITLE
Add annotation: linkerd.io/inject: disabled

### ISSUE THREAD

**Issue by tarvip** [jaegertracing/jaeger-operator#500]
Hi

at the moment sidecar injection is disabled in cronjobs for istio, would be cool to support linkerd2 as well.

**Comment by objectiser** [comment]
Feel free to submit a PR :)

**Comment by wscheele** [comment]
why hardcode that for all components?
should that not be configurable? it makes sense for the cronjobs, but i don't see why for instance query should have hardcoded "disabled".
