### ISSUE TITLE
Provide smart approach to determine redundancy policy with self provisioned ES

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#502]
As discussed in #501, it would be good to provide a smart way to determine a default redundancy policy. Currently will default to ZeroRedundancy.

**Comment by pavolloffay** [comment]
See https://github.com/jaegertracing/jaeger-operator/pull/501#discussion_r304001869.

The redundancy policy cannot be determined just from the node count. The node count and redundancy policy are used to calculate replica shards. 

I have submitted https://github.com/jaegertracing/jaeger-operator/pull/531 to use single redundancy by default. I don't know any way we could optimize the current approach, it seems this could be closed if nobody knows a better way to handle this.

**Comment by objectiser** [comment]
Agree, thanks.
