### ISSUE TITLE
Verify that the operator can inject sidecars from instances in other namespaces

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#505]
See https://github.com/jaegertracing/jaeger-operator/issues/60#issuecomment-508341067 for context.

**Comment by jpkrohling** [comment]
cc @christianhuening

**Comment by objectiser** [comment]
I deployed the jaeger-operator based on an image of the latest master - the operator in "observability" namespace, the `deploy/example/simplest.yaml` CR in a `monitoring` namespace and finally an example in the `example` namespace - the deployment including the `sidecar.jaegertracing.io/inject: "true"` annotation.

**Comment by christianhuening** [comment]
@objectiser oh cool! How did you deploy the jaeger-operator? Did you use the helm chart?
If not, what did you set the WATCH_NAMESPACE variable to?

**Comment by objectiser** [comment]
@christianhuening I used the instructions in this section of the readme: https://github.com/jaegertracing/jaeger-operator#kubernetes, but updated the `operator.yaml` to use an image built from the current master. So it is using WATCH_NAMESPACE="". 

I'll be doing a patch release shortly, so should be available soon.

**Comment by christianhuening** [comment]
@objectiser you release 1.13.1, but I cannot find/get an image with that tag. Is that pending in CI?

**Comment by christianhuening** [comment]
Ok thanks, it's there now. 
Now finally the RBAC settings in the helm chart only use Roles and RoleBinding, instead of a ClusterRole and ClusterRole binding. Will open a PR then.

**Comment by jpkrohling** [comment]
> Ok thanks, it's there now.

I had to push it manually, as we had the same problem as with the latest releases (only one tag gets pushed).

**Comment by christianhuening** [comment]
so it indeed is working, but for the helm chart version the RBAC files require updates to use ClusterRole and ClusterRoleBinding instead of namespace local versions. I tested that in then it is working. The kubernetes deployment files from the main jaeger repo are working out of the box across namespaces. I think we can close this issue.

**Comment by jpkrohling** [comment]
Thanks for verifying, @christianhuening
