### ISSUE TITLE
Automatic smoke testing of examples

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#513]
As discussed in https://github.com/jaegertracing/jaeger-operator/pull/511#issuecomment-509547349, it would be good if the examples could be automatically tested - deploy the CR, run smoke test to send/query spans.

**Comment by kevinearls** [comment]
@objectiser There is already an issue open for this, it's #144

**Comment by objectiser** [comment]
@kevinearls Ok thanks
