### ISSUE TITLE
Test operator deployment/update via OLM

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#552]
OLM repository contains instructions how to test operator deployment and update via OLM https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md#testing-operator-deployment-on-kubernetes

The instructions work for plain k8s but also for OCP 4.1. The test requires quay app registry where the operator has to be published.

**Comment by jpkrohling** [comment]
@kevinearls should this be assigned to you? I think this is a great goal to have, but not sure we can even start that as CI, as OpenShift is too heavyweight to be executed in GitHub CI's machines...

**Comment by jpkrohling** [comment]
Talking to @kevinearls on IRC, it sounds unlikely that we'll be able to get this done in the near future. The biggest road block is getting OpenShift enabled as part of our CI. If we ever get it working again, we can come up with the extra cases that we want to cover.
