### ISSUE TITLE
How to add badger as backend storage 

### ISSUE THREAD

**Issue by nomis-rzp** [jaegertracing/jaeger-operator#564]
Im using all-in-one. How to use badger as backend storage with operator ? Does the below one works ?

```
storage:
    type: badger
    options:
      badger:
        directory-key: /badger/key
        directory-value: /badger/value
        ephemeral: true
```

Also is it possible to create a PVC separately and add as a volume mount to the pod via service "Jaeger" yaml and use it as the config directory for badger?

**Comment by jpkrohling** [comment]
It *should* work, and you should be able to specify a [`volumeMount` and `volume`](https://www.jaegertracing.io/docs/1.13/operator/#finer-grained-configuration) both at the top-level (applying to all child nodes), or at individual components. 

I think badger as storage for Jaeger isn't supported for production setup (ie, query and collector in different pods/hosts), but @burmanm can confirm that.

If you do get an example working, please do consider sharing it here. Or, bonus points, send a PR adding a new example to our examples directory.

https://github.com/jaegertracing/jaeger-operator/tree/master/deploy/examples

**Comment by burmanm** [comment]
No, query and collector must reside in the same process with badger the query isn't integrated to the collector in any way (they use external process as the integration point - and there's no external process with badger). An external application such as gRPC server could work as query and collector both have integration to it.

**Comment by nomis-rzp** [comment]
@burmanm I think since im using all-in-one with the operator(both query and collector runs on the same pod), i should be able to use badger as storage backend.. right? Please correct me if im wrong.

Also if the above assumption holds true, i should be able to use a PVC to store the badger data and use it inside the service Jaeger yaml ?

**Comment by burmanm** [comment]
I'm not aware of any limitations why it shouldn't work with persistent volumes. Badger shouldn't know any difference as long as the disk behaves like it's a real disk (regardless how it is implemented). NFS backed disks might be slow, but even they should in most cases (unless improperly mounted) behave correctly.

**Comment by nomis-rzp** [comment]
Ok. I will try persistent volume inside below file and give it a try
https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/simplest.yaml

**Comment by zerda** [comment]
@burmanm "badger" is not a valid storage type in operator
https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/storage/types.go#L8

When I run with the simplest example, I got `time="2019-08-22T20:28:04Z" level=info msg="The provided storage type is unknown. Falling back to 'memory'" instance=simplest known-options="[memory kafka elasticsearch cassandra]" namespace=default storage=badger
`
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  storage:
    type: badger
```

**Comment by objectiser** [comment]
Correct, not supported as a storage at the moment - will work on a fix today.

**Comment by vinaymanne5** [comment]
We need to implement the PVC in jaeger production strategy. Could you please suggest us to deployment process.
