### ISSUE TITLE
Two operators managing the same instance

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#567]
We need to build a mechanism to ensure that only one operator is managing a given instance at the same time. When there are two operators watching the same namespaces, both will start a reconciliation logic for new instances and will concurrently start creating objects. Eventually, one will fail and the logs won't help figure out what's going on:

```
DEBU[0017] Reconciling Jaeger                            execution="2019-07-30 12:30:04.554052274 +0000 UTC" instance=simplest namespace=default
DEBU[0017] Adding finalizer                              instance=simplest namespace=default
INFO[0017] Storage type not provided. Falling back to 'memory'  instance=simplest namespace=default
DEBU[0017] Strategy chosen                               instance=simplest namespace=default strategy=allInOne
DEBU[0017] Creating all-in-one deployment                instance=simplest namespace=default
DEBU[0017] Assembling the Sampling configmap             instance=simplest namespace=default
DEBU[0017] Assembling an all-in-one deployment           instance=simplest namespace=default
DEBU[0017] skipping agent daemonset                      instance=simplest namespace=default strategy=
DEBU[0017] creating service account                      account=simplest instance=simplest namespace=default
ERRO[0017] failed to apply the changes                   error="serviceaccounts \"simplest\" already exists" execution="2019-07-30 12:30:04.554052274 +0000 UTC" instance=simplest namespace=default
```

One idea is to:

1. Add a `ManagedBy` property in the `Status` object with the `namespace.name` of the operator that is managing it, similar to the labels `app.kubernetes.io/managed-by` that we add to other lower level objects
1. When a new CR is seen, the very first thing the operator should do is set this `ManagedBy` field and persist it if it's empty, returning without further processing. This will trigger a new reconciliation logic, and the reconciliation logic will continue only if the `ManagedBy` matches the operator's identity

**Comment by jpkrohling** [comment]
cc @kevinearls, @jkandasa: I think we need a test case for this

**Comment by objectiser** [comment]
> When a new CR is seen, the very first thing the operator should do is set this ManagedBy field and persist it if it's empty, returning without further processing. This will trigger a new reconciliation logic, and the reconciliation logic will continue only if the ManagedBy matches the operator's identity

@jpkrohling Is there potential for two or more operators, watching the same namespace, to concurrently retrieve and set an empty ManagedBy field and try to write it back? What happens in this case?

**Comment by jpkrohling** [comment]
I believe only one wins, as Kubernetes has a `revision` field used with a pessimistic locking mechanism. The second will fail to persist the object.
