### ISSUE TITLE
Finalizer blocks the deletion of CRs if the operator isn't running

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#568]
A side effect of adding a finalizer to the Jaeger CRs is that the same operator instance that created the CR has to be running when the CR is deleted, otherwise the `kubectl delete` command blocks indefinitely and will end up not removing the CR:

How to reproduce:

In the first console:
```console
$ make run
INFO[0000] Versions                                      arch=amd64 jaeger=1.13.1 jaeger-operator=v1.13.1-36-g5ade023b operator-sdk=v0.8.1 os=linux version=go1.12.5
INFO[0000] Auto-detected the platform                    platform=kubernetes
INFO[0000] Automatically adjusted the 'es-provision' flag  es-provision=false
INFO[0000] The service account running this operator has the role 'system:auth-delegator', enabling OAuth Proxy's 'delegate-urls' option 
```

In a second console:
```console
$ kubectl apply -f /tmp/simplest.yaml 
jaeger.jaegertracing.io/simplest2 created
$ kubectl get jaegers
NAME        AGE
simplest2   9s
```

Then kill the operator from the first console. On the second console:

```console
$ kubectl delete jaeger simplest2
jaeger.jaegertracing.io "simplest2" deleted
^C
$ kubectl get jaegers
NAME        AGE
simplest2   102s
```

cc @rubenvp8510

**Comment by jpkrohling** [comment]
@rubenvp8510 instead of executing the update inside the `handleFinalizer`, can't it just change the CR and return it to the reconciliation loop? This way, the CR is persisted only once per reconciliation loop, avoiding another problem that I'm seeing:

```
ERRO[0015] failed to store back the current CustomResource  error="Operation cannot be fulfilled on jaegers.jaegertracing.io \"simplest3\": the object has been modified; please apply your changes to the latest version and try again" execution="2019-07-30 12:54:56.916884586 +0000 UTC" instance=simplest3 namespace=default
```

**Comment by rubenvp8510** [comment]
I can try what you are proposing in your comments

On the other hand if you delete the CR when the operator is not running, the sidecar of the deployments asociated with that CR will be orphaned, pointing to an non-existing Jaeger instance, without a posibility of delete it  unless we implement something with auto-detect feature.

**Comment by jpkrohling** [comment]
>  unless we implement something with auto-detect feature

That's the right approach. We cannot assume the operator will be up and running for the whole lifecycle of all managed CRs.
