### ISSUE TITLE
Add example application(s)

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#57]
As seen on https://github.com/jaegertracing/jaeger-operator/pull/52#issuecomment-428474043 , we need a simple application that generates traces. This application can then be used in the different deployment scenarios and e2e tests.

**Comment by annanay25** [comment]
Could we use the HOTRod application here?

**Comment by pavolloffay** [comment]
depends for what we need it. If it's to showcase operator then yes. If it's for e2e tests I would rather have something simpler. The hotrod can change and it would break tests.

We could even use more sophisticated app to generate spans like - https://github.com/jaegertracing/jaeger/pull/1245 or https://github.com/yurishkuro/microsim

**Comment by jpkrohling** [comment]
The main goal of this application is to provide users with a simple application to assess their environment is sane. Similarly, we'll use it for our e2e tests. I'd rather not use Hot ROD, but rather, something that generates a fixed number of spans/traces per request, so that we can ensure all the expected data was received by the collector.

**Comment by jpkrohling** [comment]
We have a sample CR based on the image we use for e2e tests. This might be sufficient for now.

**Comment by jpkrohling** [comment]
https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/business-application-injected-sidecar.yaml
