### ISSUE TITLE
Which Kubernetes versions are supported?

### ISSUE THREAD

**Issue by giorgio076** [jaegertracing/jaeger-operator#583]
## Issue on creating jaeger-operator

I'm working on K8s version:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.15", GitCommit:"c2bd642c70b3629223ea3b7db566a267a1e2d0df", GitTreeState:"clean", BuildDate:"2018-07-11T17:52:15Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
From `master` branch, I created CRD using `jaegertracing_v1_jaeger_crd.yaml`, then `service_account` , `role` , `role_binding`.

Creating `operator` I got this error:
```
# kubectl create -f operator.yaml 
error: unable to recognize "operator.yaml": no matches for kind "Deployment" in version "apps/v1"
```

So, edited `operator.yaml` :

```
--- apiVersion: apps/v1
+++ apiVersion: extensions/v1beta1
```
and `operator` Deployment has been crated:

```
# kubectl create -f operator.yaml 
deployment.extensions "jaeger-operator" created
```

Now issue is about starting POD, `kubectl logs` reports:

```
time="2019-08-08T08:03:51Z" level=info msg=Versions arch=amd64 jaeger-operator=1.13.1 operator-sdk=v0.8.1 os=linux version=go1.12.5
time="2019-08-08T08:03:51Z" level=info msg="Auto-detected the platform" platform=kubernetes
time="2019-08-08T08:03:51Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=false
time="2019-08-08T08:03:51Z" level=fatal msg="no matches for kind \"Deployment\" in version \"apps/v1\""
```

How can I deploy the `jaeger-opertor` so I'll be able to deploy `simplest.yaml` on my K8s Cluster?

Thanks in advance.

**Comment by jpkrohling** [comment]
That's a great question, @giorgio076. I don't think we have a written policy about which Kubernetes versions we support.

In any case, your server is 1.8.x, and the latest version as of now is 1.15 . I don't think it's reasonable for us to support all versions all the way back to 1.8.

**Comment by mane** [comment]
@jpkrohling considering that we can't upgrade kubernetes up to the latest version (1.15) from which one do you recon we could start using jaeger?

Cheers.

**Comment by jpkrohling** [comment]
Looking at Kubernetes' documentation, it looks like 1.10 already was using `apps/v1` for `Deployment`. I don't really know what else might not work on that version, though. Would you be willing to try it out and report back?

**Comment by pavolloffay** [comment]
We are using OCP 3.9  in tests which is based on k8s 1.9 https://docs.openshift.com/container-platform/3.9/architecture/infrastructure_components/kubernetes_infrastructure.html#overview.

However, we don't say we officially support OCP 3.9 it just happens to work for the use case in the tests. 3.9 is used bc of the quick start and low resources use on TravisCI.

**Comment by mane** [comment]
Thanks guys, much appreciated!

**Comment by jpkrohling** [comment]
@objectiser, @pavolloffay, should we write down our policy? For OpenShift, it's latest + previous 2 versions. Should we have the same for Kubernetes? Should it be "automatic", meaning that we should support a new version as soon as it's released? Or perhaps it should be `latest-[1|2|3]`, under the assumption that we'll need some time to make sure it works with `latest`? What about the patch versions, should we support only the latest (1.17.3 instead of 1.17.0)? Do we want to enforce it somehow (CI jobs? Pre-release tests? Nightly builds?)

Suggestion based on the current latest versions (OpenShift 4.3, Kubernetes 1.17), where `.x` means `latest`:

* OpenShift `4.3.x`, `4.2.x`, `4.1.x`
* Kubernetes [`v1.16.7`](https://github.com/kubernetes/kubernetes/releases/tag/v1.16.7), [`v1.15.10`](https://github.com/kubernetes/kubernetes/releases/tag/v1.15.10), [`v1.14.10`](https://github.com/kubernetes/kubernetes/releases/tag/v1.14.10)

**Comment by objectiser** [comment]
@jpkrohling For openshift agree, but for k8s we may end up having to follow the policy associated with the operator sdk upon which we are based?

**Comment by jpkrohling** [comment]
The `operator-sdk` would provide a base requirement, but I would expect it to support far older versions than what we might want to. For instance, the Operator SDK might still work with Kubernetes 1.11, but we'd need to do some extra effort on our side to support that version (see #938) based on the types of objects we manipulate.

**Comment by ncthbrt** [comment]
Would it not make sense to examine the different cloud operator policies on supported versions (e.g. aws, gcp, azure, etc) and try and find a compromise between maintenance effort and broad support on the biggest cloud providers.

**Comment by objectiser** [comment]
@ncthbrt Sounds like a good idea - do you have such info from any of the providers?

**Comment by ncthbrt** [comment]
Azure policy can be found here:
https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions
From the text:

AKS aims to certify and release new Kubernetes versions within 30 days of an upstream release, subject to the stability of the release.
...
Azure AKS supports three minor versions of Kubernetes:
-  The current minor version that is released in AKS (N)
-  Two previous minor versions. Each supported minor version also supports two stable patches.

This is known as "N-2": (N (Latest release) - 2 (minor versions)).

**Comment by pavolloffay** [comment]
Readme now documents which versions are supported
