### ISSUE TITLE
Problem using Operator 1.13: no image tag jaeger-collector:1.12.0 and jaeger-query:1.12.0 on registry.redhat.io/distributed-tracing-tech-preview

### ISSUE THREAD

**Issue by alekonko** [jaegertracing/jaeger-operator#589]
Hi,
 we have installed Jaeger Operator v1.13.1 and Maistra 0.12 on Openshift Cluster v 3.11.

We followed the instruction [https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html#installing-jaeger-operator](url)

`$ oc new-project observability # create the project for the jaeger operator
$ oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/crds/jaegertracing_v1_jaeger_crd.yaml
$ oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/service_account.yaml
$ oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/role.yaml
$ oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/role_binding.yaml
$ oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/operator.yaml
`

When we try to create a new instance of Jeager through CRD
`apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: installa-istio-11

  threeScale:
    enabled: false

  istio:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      multitenant: true

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: false

    mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
     dashboard:
        user: admin
        passphrase: admin
    tracing:
      enabled: true`

The jeager collector and query pod was created but with a not existant image tag  ( i look into rh registry on web) and go in Back-off pulling image.

This are we path of image:

- "registry.redhat.io/distributed-tracing-tech-preview/jaeger-collector:1.12.0" 
- "registry.redhat.io/distributed-tracing-tech-preview/jaeger-query:1.12.0"

There is a way to ovvrride image version ?

bye
Alessandro

**Comment by objectiser** [comment]
@alekonko This is an issue with the Maistra operator/CR incorrectly overriding the images that Jaeger should use - you will need to create an issue in their jira: https://issues.jboss.org/projects/MAISTRA.

Closing this issue - but feel free to reopen if you feel there is an issue with Jaeger.
