### ISSUE TITLE
Support TLS for Elasticsearch index cleaner and rollover jobs

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#592]
Derive TLS env vars from storage options map for index cleaner and rollover jobs. https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/es/esCleaner.py#L22-L25

- [x] Documentation  https://github.com/jaegertracing/documentation/pull/324/files

Related to https://github.com/jaegertracing/jaeger-operator/issues/471#issuecomment-520397430 and https://github.com/jaegertracing/jaeger-operator/issues/591

**Comment by FelixRodriguezJara** [comment]
Hello @pavolloffay. 

I have merged your changes into my code and it seems to be working fine for the index clenar. Please see below index cleaner job logs. It says there are no indexes, which is aligned with what I have got in my local at the moment, I need to run a test with data inside ES, anyway, it looks good so far, as it seems that certificate is not a problem anymore.

```
[root@devvm jaeger]# kubectl logs jaeger-index-cleaner-tbxm9 -n tracing
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
Elasticsearch has no indices
```

Regarding Spark dependencies and rollover Cronjobs, shouldn´t have they been created as well? I don´t see them among the cronjobs...

```
[root@devvm jaeger]# kubectl get cronjob -n tracing
NAME                                SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
pubsub-streaming-es-index-cleaner   55 23 * * *   False     0        <none>          4m51s

```

Thank you very much!

**Comment by pavolloffay** [comment]
@FelixRodriguezJara thanks for testing it.

The warnings in the log are intentional. Insecure should not be used in production environments. If you find any other issues please let us know.

Rollover is used when rollover is enabled to read more about it read our blog post https://medium.com/jaegertracing/using-elasticsearch-rollover-to-manage-indices-8b3d0c77915d.

Spark dependencies job does not support TLS at all - therefore in my PR I have disabled it if TLS is enabled  and the job is not enabled explicitly.

**Comment by FelixRodriguezJara** [comment]
Alright, thank you very much for your input, @pavolloffay!

Yes, I have enabled spark explicitly and it gets created, I just wanted to test. So, regarding spark job, isn´t it required by Jaeger at all and we can run without it?

On the other hand, thank you very much for the pointer to the es rollover documentation, very useful. I will check and see if it fits.

Thank you very much.

**Comment by pavolloffay** [comment]
It is optional please read about it our docs.

**Comment by FelixRodriguezJara** [comment]
Alright, thank you very much for your input, @pavolloffay!

Yes, I have enabled spark explicitly and it gets created, I just wanted to test. 

On the other hand, thank you very much for the pointer to the es rollover documentation, very useful. I will check and see if it fits.

Thank you very much.

**Comment by pavolloffay** [comment]
Done in #758
