### ISSUE TITLE
Resource limits for spark dependencies cronjob

### ISSUE THREAD

**Issue by harshal-shah** [jaegertracing/jaeger-operator#598]
The [spark dependencies cronjob](https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/cronjob/spark_dependencies.go#L36) does not have resources populated. It would be nice to be able to specify requests and limits for the pods created by this cronjob.
Right now the pods created by this cronjob do not have any resources defined and they consume a substantial amount of CPU / memory causing resource starvation on the node and all pods on it.

**Comment by antimack** [comment]
+1 to this, we have default requests and limits per namespace and spark dependencies OOM killed all the time

**Comment by harshal-shah** [comment]
@antimack as a workaround, you can add a `LimitRange` object to the namespace where jaeger is installed.

**Comment by antimack** [comment]
@harshal-shah Yeah, that’s what we do but we have default limitrange same for all the namespaces and we are trying to keep it low so spark dependencies failing to start. I just tweaked limitrange a bit but having the ability to specify resources in crd would be way much better :)

**Comment by harshal-shah** [comment]
Yes, Totally agree with that.

**Comment by jpkrohling** [comment]
@rubenvp8510 is this something you'd want to work on?

**Comment by harshal-shah** [comment]
We removed the limitrange and instead used the following [helmfile hook](https://github.com/roboll/helmfile#hooks) to patch the cronjob

~~~
    hooks:
    - events: ["postsync"]
      showlogs: true
      command: "kubectl"
      args: ["patch", "cronjob", "jaeger-spark-dependencies", "-n", "tracing", "--type", "merge", "--patch", "{ \"spec\": { \"jobTemplate\": { \"spec\": { \"template\": { \"spec\": { \"containers\": [ { \"name\": \"jaeger-spark-dependencies\", \"image\": \"jaegertracing/spark-dependencies\", \"resources\": { \"requests\":{ \"cpu\": \"2000m\", \"memory\": \"4Gi\" }, \"limits\":{ \"cpu\": \"2500m\", \"memory\": \"6Gi\" } } } ] } } } } } }"]
~~~

**Comment by harshal-shah** [comment]
Above patch gets overwritten by the operator 

~~~
W0826 08:33:55.753589       1 reflector.go:256] pkg/mod/k8s.io/client-go@v0.0.0-20190507014756-65905f29c17c/tools/cache/reflector.go:93: watch of *v1beta1.CronJob ended with: too old resource version: 198112976 (198121115)
~~~
