### ISSUE TITLE
Configure secure connection between agent and collector (TLS)

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#599]
Configure secure connection (TLS) between agent and collector when gRPC reporter is used (it's used by default).

The operator could automatically setup TLS, not requiring users to mess around with certs.

**Comment by annanay25** [comment]
Working on this one.

**Comment by jpkrohling** [comment]
The biggest problem is *how* to provision the cert. Ideally, it would:

1. check whether the operator is running on openshift
1. check whether the cert manager is available

For OpenShift, there's an annotation that can be used in the collector deployment that automatically generates a service certificate. See https://docs.openshift.com/container-platform/4.3/authentication/certificates/service-serving-certificate.html

For Cert Manager, it might need admin intervention to approve/sign the CSR. That's kinda what's blocking us from using webhooks for injecting the agent, though... We don't want to delay the deployment of the instance because an admin hasn't signed a cert.

**Comment by annanay25** [comment]
Is it an option to provision a self signed cert through the operator?

**Comment by annanay25** [comment]
If we use the same `RootCA` to create both client and server certs, we could provision them from the operator without the need of an external CA .. self signed but secure.

**Comment by annanay25** [comment]
We could then directly mount these as secrets on each of the agent and collector containers.

**Comment by jpkrohling** [comment]
No, let's try to avoid self-signed certs: confidence in the certificate authority that signed the cert is one of part of the trust model of TLS. Personally, I'd rather *not* have auto-TLS than to have it with self-signed certs, as it would send the wrong message to end-users.

We have OpenShift-specific code in the operator already, and we auto-detect some other features. We can easily detect both situations and act accordingly, either by adding an annotation on the Collector + using the cert that *should* be mounted automatically, or by requesting a cert with cert manager and updating the collector once the cert has been provisioned by the admin.

**Comment by annanay25** [comment]
We should keep this open to track TLS for a k8s setup.

**Comment by prashanthga** [comment]
Hello,  does TLS work between jaeger-agent and jaeger-collector ?   We are not using the HTTP Sender but rely on the UDPSender.  Is it possible to have a secure connection in such case ? Please advise.

**Comment by pavolloffay** [comment]
The TLS is supported only between agent and collector via gRPC

**Comment by prashanthga** [comment]
OK, does it mean UDP Senders not suite for security.
ALso, how we configure GRPC Sender using Java client ?   Does it support Authentication using Basic Auth or Oauth?  For e.g. a HTTP Sender allows setting username, password or token.  How do we do this using GRPC sender

**Comment by pavolloffay** [comment]
There is no support for the gRPC sender in Java at the moment. 

HTTP sender cannot be configured with secure connections either. :/

**Comment by prashanthga** [comment]
Jager documentation suggests configuring username, password and token for Http sender. So are you suggesting they are not supported in case of java client?
What's the recommendation for configuring security for jaeger

**Comment by pavolloffay** [comment]
1. can be done via gRPC, there we support mTLS
2. Jaeger itself does not provide auth, however this article will help you to set it up with auth proxy https://dzone.com/articles/protecting-the-collection-of-spans

**Comment by prashanthga** [comment]
gRPC supported for which clients ?

**Comment by pavolloffay** [comment]
Sorry its between agent and collector. I am not sure if it is supported in any clients.

**Comment by prashanthga** [comment]
You mentioned there is no support for gRPC Sender for Java in the comment above. So Im wondering is it supported for Python, Go etc .

**Comment by pavolloffay** [comment]
Each client has it's own maintainers. Have a look directly in those repositories.

**Comment by Zhuce123456789** [comment]
> The TLS is supported only between agent and collector via gRPC

Hello, could you let me know how to configure mTLS between agent and collector via gRPC?
