### ISSUE TITLE
Incorporate 'generate csv' in the release process

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#604]
In newer versions of the operator framework, it's possible to generate CSVs using a template, which is suitable for usage during the release process.

This issue is to investigate what we need to do in order to get the new CSVs automatically generated at release time.

**Comment by pavolloffay** [comment]
Would this also close https://github.com/jaegertracing/jaeger-operator/issues/470?

**Comment by jpkrohling** [comment]
Not sure -- that one is about linting the OLM files. I could try to add the linting command to the checks, but I'll leave it out in case it requires more work than just running the command you mentioned there.

**Comment by jpkrohling** [comment]
This has been done already.
