### ISSUE TITLE
Inject sidecar in properly in annotated Statefulsets

### ISSUE THREAD

**Issue by cfontes** [jaegertracing/jaeger-operator#62]
I am testing out Jaeger as a distributed tracing solution, Jaeger-Operator sounded like the easiest way to do it, and here I am ( I also checked the helm chart, but this looks like the preferred way currently )

Operator worked great, but I can't use the very handy annotation below

>   annotations:
>     inject-jaeger-agent: "true"

Our system is an actor based system with sharded local state, and we use Statefulsets to maintain local state and instances together.

Of course I can use the side car in my YAML and I did that, but this annotation is a lot easier to maintain.

That is it!

**Comment by mathspanda** [comment]
Is there anyone working on this issue? I would like to resolve this issue.

**Comment by jpkrohling** [comment]
I don't think @cfontes is working on it, so, feel free to get started! Use the current logic for the `Deployment` as base, perhaps using this commit as reference: https://github.com/jaegertracing/jaeger-operator/commit/fb56b311b787a68fd26db17f395b0aaa728f1b84

**Comment by pavolloffay** [comment]
Will be done https://github.com/jaegertracing/jaeger-operator/pull/1804
