### ISSUE TITLE
Use index mapping for ES 7.x when ES 6.8 is being used

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#634]
Elasticsearch 6.8 allows to use ES 7.x and 6.x/5.x compatible mappings. The operator could automatically configure Jaeger to use `--es.version=7` when ES 6.8 is being used this will result in using new mappings, so later when user switches to ES 7.x it will not have to do any data migration.

**Comment by pavolloffay** [comment]
I think nobody is working on this.

I would maybe prefer if the logic would be done directly in Jager collector. In jaeger there is already a logic which gets ES version from ping API and decides which template to use https://github.com/jaegertracing/jaeger/blob/67243904eebe9ac8ef3b9183c8715f55d075644a/pkg/es/config/config.go#L164

**Comment by jan25** [comment]
Thats useful, Thanks @pavolloffay 
I'll read a bit of code to get more context of this and good way to solve this, and I will open a PR(WIP) to discuss further

**Comment by pavolloffay** [comment]
Great @jan25, feel free to ping me if you run into any issues.

**Comment by pavolloffay** [comment]
This is not needed. ES7 indices can read indices created by ES6 by default.
