### ISSUE TITLE
mismatch between yaml and tag in docker hub

### ISSUE THREAD

**Issue by martinbrook** [jaegertracing/jaeger-operator#643]
Recent release has pushed v1.14.0 tag but yaml files call up tag 1.14.0

**Comment by martinbrook** [comment]
https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/operator.yaml#L19

https://hub.docker.com/r/jaegertracing/jaeger-operator/tags

**Comment by jpkrohling** [comment]
Sorry, some parts of this release were done manually. I just pushed another tag, conforming with the previous versions.

I'm closing this as I think it should be solved, but feel free to reopen if you are still having problems.
