### ISSUE TITLE
gRPC port is missing

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#654]
I might be missing something, but looks like we are not currently adding the gRPC port (14250) to the all-in-one nor collector deployments:

https://github.com/jaegertracing/jaeger-operator/blob/a059701671aba3b097dda1ecde16b110b9fbb071/pkg/deployment/all-in-one.go#L128-L168

https://github.com/jaegertracing/jaeger-operator/blob/a059701671aba3b097dda1ecde16b110b9fbb071/pkg/deployment/collector.go#L145-L162

**Comment by jpkrohling** [comment]
The agent in sidecar is using gRPC:

https://github.com/jaegertracing/jaeger-operator/blob/a059701671aba3b097dda1ecde16b110b9fbb071/pkg/inject/sidecar.go#L111

Also, the service does use expose the gRPC port:

https://github.com/jaegertracing/jaeger-operator/blob/a059701671aba3b097dda1ecde16b110b9fbb071/pkg/service/collector.go#L71-L74

At this point, I'm sure I'm missing something, just not sure what.

**Comment by dm03514** [comment]
Thank you for the link, I should be able to look at this sometime this week (before Saturday) unless someone else wants to take a look sooner :)

**Comment by yeya24** [comment]
I will take this

**Comment by yeya24** [comment]
So I guess we just need to add port 14250?

**Comment by jpkrohling** [comment]
Yes, but before, I'd like to understand why it's apparently working :-) Could you try removing the port 16686 and attempting to access the UI?

**Comment by yeya24** [comment]
> Yes, but before, I'd like to understand why it's apparently working :-) Could you try removing the port 16686 and attempting to access the UI?

Yes, if I remove 16686 in all-in-one container port, it still works. I think the only thing matters is the ports in Service. It will still set up proxy rules for 16686 if I configure it in Service, no matter whether you set 16686 in your container port.

**Comment by bhavin192** [comment]
@yeya24 yes, you are right. From API reference docs,

> List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network. Cannot be updated.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#container-v1-core

**Comment by jpkrohling** [comment]
Wonderful, thanks for digging that up, @bhavin192! @yeya24 you may go ahead and add the missing port
