### ISSUE TITLE
Should CI workflow for particular ES operator version trigger all e2e tests

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#657]
Related to discussion https://github.com/jaegertracing/jaeger-operator/pull/631#discussion_r323154287.

Reason for question - if we are going to have a workflow for multiple versions of the elasticsearch operator - then potentially only the self provisioned es e2e tests should be invoked. Essentially to avoid duplicate tests running when they are no affected by the es-operator.

**Comment by jpkrohling** [comment]
All the cases that we "support" should be tested. If we expect people to bring their own Elasticsearch, then there should be a test for it.

**Comment by objectiser** [comment]
Sorry will close - on closer inspection it is just running the es self provisioned tests due to the test group.
