### ISSUE TITLE
Add commonSpec to JaegerCassandraCreateSchemaSpec

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#659]
The only component within the CRD that does not support the common spec at the moment is the CassandraCreateSchema job.

**Comment by jpkrohling** [comment]
And Ingress (#574)?

Also, fixing this might also close #474.

**Comment by haanhvu** [comment]
I'll work on this

**Comment by haanhvu** [comment]
> And Ingress (#574)?
> 
> Also, fixing this might also close #474.

@frzifus I think #474 can be closed too
