### ISSUE TITLE
Elasticsearch port not set correctly for the jaeger-es-index-cleaner

### ISSUE THREAD

**Issue by alexnederlof** [jaegertracing/jaeger-operator#662]
I've configured my Jaeger operator to use ES (hosted by Amazon):

```yaml
storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://vpc-es-logging-xxx.zone.es.amazonaws.com:443
    dependencies:
      enabled: true
      elasticsearchNodesWanOnly: true
```

As you can see I configured it to use http*s* on port `443`. However, the clean job tries to use the standard port 9200.

```
Caused by: org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[https://vpc-es-logging-xxx.zone.es.amazonaws.com:9200]] 
        at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:152)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:424)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:388)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:392)
        at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:168)
        at org.elasticsearch.hadoop.rest.RestClient.mainInfo(RestClient.java:735)
        at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:330)
```

This is on Jaeger operator version: 1.13.1

Is there any way for me to specify the port correctly? Or is this feature misisng.

**Comment by alexnederlof** [comment]
I see the pod is initialized with the following environment variables (notice how the port is missing)

```yaml
containers:
  - env:
    - name: STORAGE
      value: elasticsearch
    - name: ES_NODES
      value: https://vpc-es-logging-xxx.zone.es.amazonaws.com
    - name: ES_CLIENT_NODE_ONLY
      value: "false"
    - name: ES_NODES_WAN_ONLY
      value: "true"
```

**Comment by alexnederlof** [comment]
Digging a bit further, I inspected the operator that resulted from applying the above config, and found that `es.server-urls` appeared twice, but the second entry "lost" its port.

```
options:
      es:
        server-urls: https://vpc-es-logging-xxx.zone.es.amazonaws.com:443
      es.server-urls: https://vpc-es-logging-xxx.zone.es.amazonaws.com
```

It could be a remnant from a previous config (before I added the `443` port) but I would expect the operator to clear those out. 

I've now updated my config to:

```
storage:
    type: elasticsearch
    options:
      # No more sub fields
      es.server-urls: https://vpc-es-logging-xxx.zone.es.amazonaws.com:443
```

And it seems the port is set correctly. So in the end, I guess the bug is that this config is not read (nor cleaned up) properly.

**Comment by jpkrohling** [comment]
@alexnederlof are you able to consistently reproduce it? Is it sufficient to set the `es.server-urls` to a given value when creating the CR, and later update the CR with a new value?

cc @kevinearls, @pavolloffay

**Comment by alexnederlof** [comment]
Strange, I created a new `jaeger` to give a reproducable example, but sets the URL correctly, regardless of which way you config it. For my other config it didn't 🤔. 

As this was probably just a glitch in the matrix, and I cannot reproduce it outside the original config, I'll close the issue.

**Comment by jpkrohling** [comment]
Thanks for trying it out, and do reopen if you face this issue again. It does sound like there's a loose end somewhere, as the operator should have updated the cronjob once the CR was updated.

**Comment by pavolloffay** [comment]
Didn't this happen when you run `kubectl apply -f` on the CR file?
