### ISSUE TITLE
Document CR with all the options

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#671]
Users often don't know what are all the options exposed in Jaeger CR, or alternativelly they don't know how to format nested nodes in the CR.

I think we should generate and publish CR with all the options. The values could be just empty or default. 

We could make this automatic during the build process. The generate yaml file could contain godoc comments on the fields and nodes. 

Related to https://github.com/jaegertracing/jaeger-operator/issues/668#issuecomment-534448280

**Comment by objectiser** [comment]
Would this include the freeformat options? Would it expand (for example) all of the storage options?

It would be great if we could have tabs or some checkbox/menu approach that only shows the CR parts relevant for selected strategy and storage.
