### ISSUE TITLE
How to deal with deprecated options

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#683]
Options for the various Jaeger components may become deprecated and eventually removed over time.

How should these be handled when a user specifies them in a CR? Especially if existing Jaeger instances are just upgraded through subsequent versions automatically by the operator?

Ideally we need the operator to:
(1) inform the user that the CR now includes deprecated or removed options, so needs to be updated
(2) until the updates are applied, where possible have the ability to modify the supplied configuration to one that is supported, before being applied to the underlying jaeger components (whether creating or updating).

**Comment by jpkrohling** [comment]
There are two situations:

1. CR is created for Jaeger 1.1 and the operator gets upgraded version by version until, say, 1.10. 
1. User creates a CR using a deprecated/removed option.

In the first case, the operator should change the CR whenever it's upgraded and a deprecated version is used. When the migration path isn't known, we should log and return an error (the upgrade mechanism should already abort on error).

For the second option, I think we should follow the same policy as Jaeger itself, keeping the option in the deprecated state for so long as the default underlying Jaeger version keeps it.

**Comment by objectiser** [comment]
Not sure we should treat the situations differently, as it may complicate the logic. So even if the user themselves specify a deprecated option, the upgrade logic could still be used to identify a new option - but log the fact, so users may be informed (if they check the logs).

**Comment by jpkrohling** [comment]
From the code's perspective, those are two different places. In one, we might use the current "normalize" function, while the upgrade logic would be on its version-specific source.
