### ISSUE TITLE
Adding Monitoring Port to collector, query and agent services

### ISSUE THREAD

**Issue by ronakladhar** [jaegertracing/jaeger-operator#688]
1. In the current jaeger operator installation, there is no provision for adding monitoring port to collector, agent and query services and they are also not present in default installation.
When i tried manually adding these ports, configuration is reverted back by Jaeger Operator.

  - Document Referred:
     https://www.jaegertracing.io/docs/1.14/monitoring/

2. Also there is no provision to expose query service on node port.

If this configuration are already present please update the documentation.

**Comment by jpkrohling** [comment]
About 1., the Operator adds annotations to the deployments/daemonsets/... that can be used by tools like Istio to build the monitoring configuration for Prometheus. 

https://github.com/jaegertracing/jaeger-operator/blob/54f74a5bececad40024a501ee596824edbe43828/pkg/deployment/all_in_one.go#L46-L49

If you are not using Istio, and if you are using the Prometheus Operator, you can create extra regular Kubernetes `Service` resources + a `ServiceMonitor`. Neither this extra `Service` nor the `ServiceMonitor` will be touched (changed/removed) by the Jaeger Operator. A very detailed blog post using `PodMonitor` instead of `ServiceMonitor` was published here: https://developers.redhat.com/blog/2019/08/28/build-a-monitoring-infrastructure-for-your-jaeger-installation/

About 2, the query service can be exposed to the public via regular Kubernetes means, such as `Ingress`, or `Routes` when running in OpenShift.

**Comment by jpkrohling** [comment]
I'm closing this issue, as I think this answers your questions, but feel free to reopen if that's not the case.

**Comment by ronakladhar** [comment]
https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/service/collector.go
It's service file doesn't have an entry for 14269/TCP port 

Similarly for query service too.

**Comment by ronakladhar** [comment]
I am installing it out of Istio and trying to integrate with Prometheus comes with default Istio installation using config file containing Kubernetes service discovery for searching targets.

At least collector and query service should have monitoring port exposed in their Kubernetes service.

**Comment by objectiser** [comment]
@ronakladhar Which version of Istio are you using?

**Comment by ronakladhar** [comment]
> @ronakladhar Which version of Istio are you using?
Istio-1.3.1

**Comment by jpkrohling** [comment]
>  It's service file doesn't have an entry for 14269/TCP port

The service doesn't need to expose the metrics port, as Istio will contact the pod directly.

**Comment by ronakladhar** [comment]
But since it is outside the istio, i am using service discovery over collector and query service.
Attaching snippet of my prometheus configuration:
`- job_name: jaeger-collector-monitoring
  scrape_interval: 
  scrape_timeout: 
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - role: service
    namespaces:
	  names:
	  - observability
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: jaeger-collector;http-monitoring
    replacement: $1
    action: keep`

**Comment by jpkrohling** [comment]
>  Attaching snippet of my prometheus configuration:

Is that a working configuration with a custom `Service` resource, or the one that isn't working because the `Service` has no monitoring port exposed? If you are using the Prometheus Operator, it's probably easier (better?) to use `ServiceMonitor` and/or `PodMonitor` resources.

**Comment by ronakladhar** [comment]
It's one which is not working as there is no monitoring port exposed. 
I agree that using prometheus operator would be a better option but currently it has no integration with istio installation and it will require additional configuration for adding istio resources as well.
For testing purposes i am doing this integration.
In my opinion there should be a provision for exposing monitoring port with jaeger operator CRD.

**Comment by jpkrohling** [comment]
The monitoring port shouldn't be exposed in the same service that exposes ports to external consumers. Our plan is to add extra services exposing *only* the monitoring ports. This will also be a step in the direction of having the Jaeger Operator to create `ServiceMonitor` resources when the Prometheus Operator exists.

We'd certainly welcome a PR that creates an extra `Service` exposing only the monitoring ports.

**Comment by ronakladhar** [comment]
Thanks for your support and suggestions. I will certainly try using prometheus operator.
