### ISSUE TITLE
Check whether the thrift configuration for the injected sidecar is correct

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#691]
When testing on OpenShift (crc) with Maistra, the injected sidecar to the `business-application-injected-sidecar.yaml` looks like this: 

```
      - args:
        - --collector.host-port=jaeger-collector:14267
        - --reporter.grpc.host-port=dns:///jaeger-collector-headless.istio-system:14250
        - --reporter.type=grpc
```

The `collector.host-port` seems to missing the namespace.

**Comment by pavolloffay** [comment]
I think `--collector.host-port` will be ignored because grpc reporter is used `--reporter.type=grpc`. Better would be to not set the `--collector.host-port` at all as it is deprecated.

**Comment by objectiser** [comment]
The `--collector.host-port` was being added by the Maistra template - that should be removed in the next release so I think this can be closed?

**Comment by jpkrohling** [comment]
I opened this one so that I wouldn't lose track of it, but I later figured out that it was added by the Maistra template. Closing this.
