### ISSUE TITLE
Watch resources created by the operator

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#694]
Newer versions of the Operator SDK allow the operator to watch resources that it has created as part of a CR that it manages. For instance, the Jaeger Operator can watch for `Service` objects that were created when a given `Jaeger` object was created.

The code would look like this in the `pkg/controller/jaeger/jaeger_controller.go`:

```go
err = c.Watch(&source.Kind{Type: &corev1.Pod{}}, &handler.EnqueueRequestForOwner{
	IsController: true,
	OwnerType:    &v1.Jaeger{},
})
if err != nil {
	return err
}
```

**Comment by pavolloffay** [comment]
The idea is to reset the objects if they are modified.
