### ISSUE TITLE
Enable auto-provision of Kafka when using "streaming" strategy

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#698]
When provisioning the Elasticsearch storage, if the server url is not defined (and running on OpenShift), the Jaeger operator will attempt to auto-provision the Elasticsearch storage using the elasticsearch-operator.

The same capability should be provided when the "streaming" strategy has been selected, and the Kafka topic (and/or broker) has not been configured for both consumer and producer.

Unlike the ES auto-provisioning - it may be possible to also perform this when running on K8S - we need to confirm that the same CRD is used in upstream strimzi and downstream AMQ.

**Comment by jpkrohling** [comment]
AMQ documentation shows this as a CR example:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
```

**Comment by objectiser** [comment]
> Kafka topic (and/or broker) has not been configured for both consumer and producer.

My preference would be just based on the broker - as this is equivalent to the ES server URL. We should still enable the user to specify the topic they wish to use, regardless of how the kafka cluster is provisioned.

**Comment by objectiser** [comment]
Implemented in https://github.com/jaegertracing/jaeger-operator/pull/713
