### ISSUE TITLE
Update the version at build time

### ISSUE THREAD

**Issue by pavelnikolov** [jaegertracing/jaeger-operator#7]
I think that the version should be injected into the binary at build time. This way you don't risk to end up with two binaries with different code with the same version. Unless I'm missing something.

**Comment by jpkrohling** [comment]
I was planning on adding a flag to the binary, so that uses can override it by changing the operator's deployment.

https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/operator.yaml#L22

**Comment by jpkrohling** [comment]
I just realized that you might have meant the Operator's version, not Jaeger's. I'm +1 to setting the version at build time.
