### ISSUE TITLE
Add configurable option on resource requirements for jaeger componenets

### ISSUE THREAD

**Issue by mathspanda** [jaegertracing/jaeger-operator#70]
We need to make resource requests and limits configurable for all jaeger pods.

**Comment by jpkrohling** [comment]
How would that work? Would you define one set of resource limits and it would be applied to all pods? Would that apply also for agents that are injected as sidecars? Or would you need a more granular configuration, so that the collector has one set of limits, the query another and so on?

**Comment by mathspanda** [comment]
A more granular configuration. The collector and the query have different set of requests and limits.

**Comment by jpkrohling** [comment]
How about the agent? Should the agent as sidecar have different constraints as an agent running as daemonset?

**Comment by jpkrohling** [comment]
> Even so, one Jaeger CR cannot have two different deployment strategy of the agent at the same time

That's not entirely true. IIRC, if the strategy is "DaemonSet", we deploy the agent as daemonset, but we still inject agent sidecars if the appropriate annotation is in place. So, while I probably wouldn't call it "best practice", it's possible to have both daemonsets and sidecars for the same Jaeger instance.

**Comment by jpkrohling** [comment]
Not really, I'm open to hear about concrete use cases :) My feeling is that the sidecar indeed should require far less resources than a daemon set, but every new configuration switch we add is potentially more complexity for the end user (and to maintain/test/document).

**Comment by mathspanda** [comment]
I agree with you. And more use cases and discussion on this issue are needed.

**Comment by jpkrohling** [comment]
I'm marking this as "question" for now, until we know what we need :)

**Comment by pavolloffay** [comment]
Has this been resolved? 

`JaegerCommonSpec` contains `Resources v1.ResourceRequirements` which is part of every jaeger spec - query, collector, agent. 

However, the `Resources`are not applied to the agent sidecar. 

cc @killcity

**Comment by killcity** [comment]
An issue we are running into with sidecar injection is that there is no way to set requests/limits on the sidecar agent, so any deployments/statefulsets, etc that require a certain QoS (we require `Guaranteed`) get changed to `Burstable`. I will have to manually add the sidecars until this feature is added. Thanks for all the hard work on this project!

**Comment by jpkrohling** [comment]
@killcity, @mathspanda, I believe this is supported for some time already. I'm closing this, but please check it out and reopen if there's still something missing.
