### ISSUE TITLE
Can't access UI after port-forward using simplest jaeger instance

### ISSUE THREAD

**Issue by satyajituk** [jaegertracing/jaeger-operator#700]
I am running **jaeger-operator** and **simple jaeger instance** as per the readme file here: https://github.com/jaegertracing/jaeger-operator

If I do `kubectl logs -l app.kubernetes.io/instance=simplest` I can see that the http server is running among other things: 
`{"level":"info","ts":1571139333.5400417,"caller":"app/server.go:112","msg":"Starting HTTP server","port":16686}`

I can see the pod running when I do `kubectl get pods -n observability`: 
`jaeger-operator-6d6cc86d89-577rr   1/1     Running   0          3h16m`

Now I want to see UI which is supposed to be included in the **simplest jaeger instance**: https://www.jaegertracing.io/docs/1.14/operator/#quick-start-deploying-the-allinone-image

I try doing this by doing a **port-forward**: 
`kubectl -n observability port-forward jaeger-operator-6d6cc86d89-577rr 16686:16686`

But when I go to `localhost:16686` it doesn't work. 

Where am I going wrong?

**Comment by jpkrohling** [comment]
Your `port-forward` is trying to attach to the port 16686 of the _operator_. It should attach to the port on the _instance_. Something like:

```console
$ kubectl -n observability port-forward service/simplest-query 16686
```

**Comment by satyajituk** [comment]
Thanks @jpkrohling ! This works now. I was unaware of the service `simplest-query`.
