### ISSUE TITLE
Add a custom filter to jaeger collector

### ISSUE THREAD

**Issue by christine-gong** [jaegertracing/jaeger-operator#701]
Is it possible to have a custom filter to filter out unwanted information in the tracing spans.
e.g. the request could have user id as part of query url, which we want to reduct before sending to kafka/elasticsearch. 
What is the best practice to do that? Thanks!!!

**Comment by objectiser** [comment]
It is not currently supported in Jaeger's collector, but this capability is being developed in the [OpenTelemetry collector](https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor) - but not sure how mature it is currently. So you could have an OpenTelemetry collector with Jaeger receiver, the attribute processor and then a Jaeger exporter to push data to the actual Jaeger collector?

If deploying on Kubernetes, you might want to try out the [operator](https://github.com/open-telemetry/opentelemetry-collector/issues/274) currently in development, to help deploy/configure the collector, and give us feedback on it?

**Comment by christine-gong** [comment]
@objectiser thanks for the information! If I want to add my own implementation, should be something similar to https://github.com/jaegertracing/jaeger/blob/master/cmd/collector/app/sanitizer/service_name_sanitizer.go ?

**Comment by jpkrohling** [comment]
Yes, that's an example of a filter (sanitizer in Jaeger terms). Note however that you need to assemble your own collector binary to make use of that.

**Comment by yurishkuro** [comment]
Neither is a good solution due to the lack of pluggability in Go. Only if the sanitizer is something standard and heavily configurable, then I don't think it matters where to put it.

**Comment by jpkrohling** [comment]
True. Or the agent should contain such sanitizers, but that kinda breaks the premise that agents are just "smarter pipes" between the client and collector.

**Comment by objectiser** [comment]
Just for reference, the opentelemetry collector already appears to have the capability based on per services rules: https://github.com/open-telemetry/opentelemetry-collector/blob/master/processor/attributesprocessor/testdata/config.yaml#L125-L137

**Comment by yurishkuro** [comment]
yeah, that's the type of complex configuration I was referring to. Better not to reimplement it in Jaeger.

**Comment by jpkrohling** [comment]
I guess we have consensus then and I'm closing this issue. 

@christine-gong: I encourage you to try the OpenTelemetry Collector out. If you need any assistance, let me know!

**Comment by christine-gong** [comment]
@jpkrohling @objectiser @yurishkuro thanks for the suggestion! i'll try OpenTelemetry Collector when i have some spare time. For now, i just want to add our customized zipkin span sanitizer in the collector. 

The stupid question is, how to develop and debug zipkin sanitizer locally? More specifically, how to generate zipkin spans but send those to jaeger collector locally? Since we configured our jaeger collector endpoint in Envoy tracing with zipkin tracer. 
e.g.
```
tracing:
      http:
        name: envoy.zipkin
        config:
          collector_cluster: jaeger
          collector_endpoint: "/api/v1/spans"
```

**Comment by objectiser** [comment]
@christine-gong I think you just need to specific `localhost` or `127.0.0.1` in the socket address, e.g. https://github.com/envoyproxy/envoy/blob/master/examples/jaeger-tracing/service1-envoy-jaeger.yaml#L97-L101

**Comment by christine-gong** [comment]
@objectiser thanks for your suggestion! 
Actually localhost/127.0.0.1 does not work, but ip of my laptop works! Also running a demo https://github.com/openzipkin/pyramid_zipkin-example locally pointing to `localhost:9411/api/v1/spans` works as well! 
Hope it would be useful to other people who check this issue~~
