### ISSUE TITLE
Support username and password in spark dependencies

### ISSUE THREAD

**Issue by haf-afa** [jaegertracing/jaeger-operator#703]
So we should make it recognise secretName, so that the cluster doesn't get lots of failed spark-dependencies runs.

Also, would the maintainers consider doing a spark-dependencies run immediately upon installation (or five minutes after, possibly?) so that the operator (me in this case) knows something is wrong?

Please assign me to this issue, I would like to fix this.

**Comment by jpkrohling** [comment]
> Also, would the maintainers consider doing a spark-dependencies run immediately upon installation (or five minutes after, possibly?) so that the operator (me in this case) knows something is wrong?

That would be like a dry-run, right? I'm certainly fine with changing it to run immediately.

**Comment by pavolloffay** [comment]
Username and password are consumed from storage options or from storage secret.
