### ISSUE TITLE
Publish latest/master images for every master build

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#715]
Created from https://github.com/jaegertracing/jaeger-operator/pull/705#issuecomment-543809611

Each merge to master should publish a new image - either latest/master. The use-case is to allow users to try latest operator features. We do the same in Jaeger - every build publishes a new latest image.

One thing to consider, the latest image could also by default use the latest Jaeger components.

**Comment by jpkrohling** [comment]
Seems to be working now:

Docker Hub:
![image](https://user-images.githubusercontent.com/13387/67204881-c39bd500-f40e-11e9-8314-41f1c0f47864.png)

Quay:
![image](https://user-images.githubusercontent.com/13387/67204909-d7473b80-f40e-11e9-8687-e02b268c0a3f.png)
