### ISSUE TITLE
Remove 'ingester.options.ingester.deadlockInterval' from examples

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#717]
The default value for the property `ingester.deadlockInterval` [has been changed](https://github.com/jaegertracing/jaeger/pull/1868) to `0` for Jaeger 1.15. After Jaeger 1.15 is released but before the Operator 1.15 is released, we should consider removing the option that sets this value to `0`, as will be just noise by then. 

Example:
https://github.com/jaegertracing/jaeger-operator/blob/01e39a38e95e6edb1dbc5c0edf042d6ed9df0c0e/deploy/examples/simple-streaming.yaml#L15-L22

**Comment by jpkrohling** [comment]
Note that a new example using the same flag is part of #713.

**Comment by amila-ku** [comment]
i would like to work on this.

**Comment by jpkrohling** [comment]
Thank you for your interest in this one, but it isn't ready to be done right now, given that it requires Jaeger 1.15, which hasn't been released yet. I can assign it to you anyway if you want, but we should have quite a few other issues that are suitable as a good-first-issue, in case you are interested.

**Comment by amila-ku** [comment]
then i will checkout other ones.

**Comment by jpkrohling** [comment]
@amila-ku, would you still be interested in sending a PR for this one?
