### ISSUE TITLE
Is there a recommended file to start running Jaeger instance with everything customizable?

### ISSUE THREAD

**Issue by satyajituk** [jaegertracing/jaeger-operator#729]
I am running jaeger operator according to the [getting started](https://github.com/jaegertracing/jaeger-operator) recommendation.
I am currently facing the issue where my pod is getting evicted: 
```
simplest-74c568c497-62hsz     0/1     Evicted     0          23h
simplest-74c568c497-7t9mm     0/1     Evicted     0          10d
simplest-74c568c497-ds752     0/1     Evicted     0          22h
simplest-74c568c497-qt26r     1/1     Running     0          17h
```

If I do a `kubectl describe pod simplest-74c568c497-7t9mm` I get the below reason: 
```
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: memory. Container jaeger was using 23009920Ki, which exceeds its request of 0.
```

As a first thing I want to be able to increase the memory available to more than the default ones. But I am not sure what's a recommended file to start with so that I can customize the default settings of all-in-one option.

**Comment by jpkrohling** [comment]
What's your Kubernetes environment (minikube? Google? OpenShift?). Are you using the in-memory storage, or are you a permanent storage mechanism, like badger, Elasticsearch or Cassandra?

**Comment by satyajituk** [comment]
Google i.e. GKE. 
I haven't set up anything extra apart from the getting started info given in the link. So currently it is in-memory. 
I plan to use a permanent storage mechanism, can you point me in right direction in this as well?

**Comment by jpkrohling** [comment]
Could you try it out on `minikube`? Do you know whether GKE *requires* the resources requests/limits to be set? For the time being, you can set the resources requests/limits like this:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
spec:
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
```

This is the official documentation for the operator: https://www.jaegertracing.io/docs/1.14/operator/ 
It includes information about how to use more permanent storage mechanisms.

**Comment by satyajituk** [comment]
Thanks. I will look into GKE then. And will use the above way of setting resources. 
Just to be clear, if it is running on in-memory, then if the pod restarts then the data will be lost right? This might be a reason why I am not seeing anything in my UI.

**Comment by satyajituk** [comment]
Is there any general advice on how to debug things? Right now, even though everything is running fine (i.e. services, jaeger instance, my own apps) I can't see traces in my UI. It is tricky to know where to start looking.

**Comment by objectiser** [comment]
Have you looked at https://www.jaegertracing.io/docs/1.14/troubleshooting/ ?

**Comment by jpkrohling** [comment]
@satyajituk I'm closing this, as I think @objectiser answered your question already, but feel free to reopen if you are still having troubles.
