### ISSUE TITLE
Docker images missing for 1.13.2 1.13.3 and 1.13.4

### ISSUE THREAD

**Issue by harshal-shah** [jaegertracing/jaeger-operator#735]
While there are 1.13.2,3,4 releases on github, there are no docker images on dockerhub

![image](https://user-images.githubusercontent.com/16479600/67755608-bd25e280-fa38-11e9-83dd-bcf5637a8aa2.png)

**Comment by objectiser** [comment]
@harshal-shah There are no Jaeger releases for version 1.13.2/3/4, see https://github.com/jaegertracing/jaeger/releases. The only releases are 1.13.0, 1.13.1 and most recently 1.14.0.

**Comment by harshal-shah** [comment]
I got confused with the `release/` releases on github 

![image](https://user-images.githubusercontent.com/16479600/67757482-2e1ac980-fa3c-11e9-8c98-89d57c640ba2.png)

**Comment by jpkrohling** [comment]
Based on the dates, I assume this has to do with testing the release script.
