### ISSUE TITLE
Agent only deployment

### ISSUE THREAD

**Issue by omerlh** [jaegertracing/jaeger-operator#748]
See discussion on jaegertracing/jaeger#833

Basically, I would like to have one cluster running Jaeger collector and agents, and the other cluster running only the agents, and configure those agents to ship the traffic to the collector on the other cluster. I don't think this is possible today with the operator - unless I'm missing something. What I need is:
 - Deploy only agents daemonset
 - Configure the collector host and port

Can you help with that?

**Comment by objectiser** [comment]
Sounds like a valid use case.

One suggestion would be the introduction of a new `strategy`, possibly `agents` or `agent-only`?

Would you be interested in submitting a PR for this?

**Comment by omerlh** [comment]
I might be able to do that... not sure if I'll have time :)

**Comment by jpkrohling** [comment]
Why only "agent daemonsets"? Wouldn't it work with agents in sidecars as well?

**Comment by omerlh** [comment]
It will, but I prefer working with daemonset instead of injecting sidecars

**Comment by jpkrohling** [comment]
Alright. I think the proposed name `agent-only` is appropriate then, as it covers both daemonsets and sidecars.

**Comment by omerlh** [comment]
Done :)

**Comment by pavolloffay** [comment]
This feature is provided by OpenTelemetry operator. There are no plans to implement this in Jaeger operator.
