### ISSUE TITLE
Add schema to CRD

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#763]
To move from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`, a schema needs to be defined in the CRD.

**Comment by jpkrohling** [comment]
The base for the schema, including the validation, should be possible to generate via `operator-sdk gen k8s|openapi` and alike. I faced a couple of problems in earlier versions, but we could give it a try again.

**Comment by jpkrohling** [comment]
Blocked by operator-framework/operator-sdk#2285
