### ISSUE TITLE
Replace base image to ubi

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#767]
The current CentOS base image seems to have some vulnerabilities, according to Quay:

![image](https://user-images.githubusercontent.com/13387/68947092-e6729c80-07b4-11ea-8933-bb4c80bfc069.png)

https://quay.io/repository/jaegertracing/jaeger-operator/manifest/sha256:0f33e0ea725448c52f74cb47a27391749868c888ad4a1f3d553c7bc31a8a28a7?tab=vulnerabilities

Changing the base image to `registry.access.redhat.com/ubi8/ubi` seems to be a valid fix:

![image](https://user-images.githubusercontent.com/13387/68947126-03a76b00-07b5-11ea-8149-63cc3b8f2766.png)

https://quay.io/repository/jpkroehling/jaeger-operator/manifest/sha256:e46a408f7496618b8923cf996dbad37d8b9c52b646eb0a97195ca01600f26226?tab=vulnerabilities

The `ubi-minimal` seems to be the default base image for new operators. 

@pavolloffay: we started using the `centos` image because of the TLS cert generation as part of the ES provisioning. I think we talked about replacing that with regular Go code, instead of relying on openssl. Do you still want to do that? If so, this change here could come after your change, so that we use `ubi-minimal`, which lacks `dnf`. Otherwise, we could just use `ubi` instead.

**Comment by objectiser** [comment]
+1 , although can you use `registry.redhat.io` instead of `registry.access.redhat.com`.

**Comment by pavolloffay** [comment]
+1 on using `ubi`. 

I would like to keep the scrip until ECL switches to golang based solution.

**Comment by jpkrohling** [comment]
> I would like to keep the scrip until ECL switches to golang based solution.

Are they switching to golang at all?

**Comment by pavolloffay** [comment]
I don't think that will happen any time soon.

**Comment by amila-ku** [comment]
@jpkrohling would like to work on this. If it is agreed to use ubi will start to work on this.

**Comment by jpkrohling** [comment]
I think there's nothing preventing us from using `ubi` instead of `centos`, so, it's yours, @amila-ku!
