### ISSUE TITLE
Reuse inject update loop from deployment controller into autodetect.

### ISSUE THREAD

**Issue by rubenvp8510** [jaegertracing/jaeger-operator#774]
This Issue was created to address remainding comments of PR: https://github.com/jaegertracing/jaeger-operator/pull/454

**Comment by jpkrohling** [comment]
Should I assign this to you, @rubenvp8510 ?

**Comment by rubenvp8510** [comment]
IIRC, this is not necessary any more.

**Comment by jpkrohling** [comment]
I think I've seen the same logic being repeated two (or even three) times:

https://github.com/jaegertracing/jaeger-operator/blob/c3adb529955979203ed99caa104d74792cfb46c2/pkg/controller/namespace/namespace_controller.go#L125-L159

https://github.com/jaegertracing/jaeger-operator/blob/c3adb529955979203ed99caa104d74792cfb46c2/pkg/controller/deployment/deployment_controller.go#L112-L143

**Comment by rubenvp8510** [comment]
Ha, sorry the code was changed due the introduction to namespace controller. and now is required again , Ok, assign  it to me.

**Comment by jpkrohling** [comment]
Thanks!

**Comment by kevinearls** [comment]
@rubenvp8510 Is this still relevant?

**Comment by pavolloffay** [comment]
It is going to be resolved as part of https://github.com/jaegertracing/jaeger-operator/issues/171
