### ISSUE TITLE
Build image for the Operator

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#781]
To speed up the builds, we could use a builder image to build the operator. I started this already locally, but started facing too many problems to get it working quickly. Here's the base `Dockerfile` that can be used to setup a basic image:

```Dockerfile
FROM fedora:31

ENV OPERATOR_SDK_VERSION v0.11.0

# see https://github.com/operator-framework/operator-sdk/issues/1854
ENV GOROOT /usr/lib/golang

RUN dnf update -y && dnf clean all

# mercurial is needed as there's at least one dependency that is managed with it instead of git, https://bitbucket.org/ww/goautoneg
RUN dnf --setopt=install_weak_deps=False --best -y install buildah podman git golang make mercurial

RUN curl -sLo /usr/local/bin/minikube https://github.com/kubernetes/minikube/releases/download/v1.5.2/minikube-linux-amd64
RUN curl -sLo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/latest/bin/linux/amd64/kubectl
RUN curl -sLo /usr/local/bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu

RUN chmod +x /usr/local/bin/minikube /usr/local/bin/kubectl /usr/local/bin/operator-sdk
RUN ln -s /bin/podman /usr/local/bin/docker

# build a relatively recent cache of the go mod
RUN git clone https://github.com/jaegertracing/jaeger-operator.git /tmp/jaeger-operator && \
    cd $_ && \
    go mod download && \
    cd && \ 
    rm -rf /tmp/jaeger-operator
```

Running the container in interactive mode works, but the build has test failures for Elasticsearch:

```
time="2019-11-21T11:44:19Z" level=info msg="Datacenter not specified. Using 'test' for the cassandra-create-schema job." instance=my-instance namespace=
time="2019-11-21T11:44:19Z" level=info msg="Mode not specified. Using 'prod' for the cassandra-create-schema job." instance=my-instance namespace=
time="2019-11-21T11:44:19Z" level=info msg="Cassandra hostname not specified. Using 'cassandra' for the cassandra-create-schema job." instance=my-instance namespace=
time="2019-11-21T11:44:19Z" level=info msg="Datacenter not specified. Using 'test' for the cassandra-create-schema job." instance=my-instance namespace=
time="2019-11-21T11:44:19Z" level=info msg="Mode not specified. Using 'prod' for the cassandra-create-schema job." instance=my-instance namespace=
time="2019-11-21T11:44:19Z" level=info msg="Cassandra hostname not specified. Using 'cassandra' for the cassandra-create-schema job." instance=my-instance namespace=
time="2019-11-21T11:44:19Z" level=info msg="Datacenter not specified. Using 'test' for the cassandra-create-schema job." instance=TestCassandraCreateSchemaEnabled namespace=
time="2019-11-21T11:44:19Z" level=info msg="Mode not specified. Using 'prod' for the cassandra-create-schema job." instance=TestCassandraCreateSchemaEnabled namespace=
time="2019-11-21T11:44:19Z" level=info msg="Cassandra hostname not specified. Using 'cassandra' for the cassandra-create-schema job." instance=TestCassandraCreateSchemaEnabled namespace=
time="2019-11-21T11:44:19Z" level=info msg="Datacenter not specified. Using 'test' for the cassandra-create-schema job." instance=TestCassandraCreateSchemaEnabledNil namespace=
time="2019-11-21T11:44:19Z" level=info msg="Mode not specified. Using 'prod' for the cassandra-create-schema job." instance=TestCassandraCreateSchemaEnabledNil namespace=
time="2019-11-21T11:44:19Z" level=info msg="Cassandra hostname not specified. Using 'cassandra' for the cassandra-create-schema job." instance=TestCassandraCreateSchemaEnabledNil namespace=
time="2019-11-21T11:44:19Z" level=info msg="Datacenter not specified. Using 'test' for the cassandra-create-schema job." instance=TestCassandraDependencies namespace=
time="2019-11-21T11:44:19Z" level=info msg="Mode not specified. Using 'prod' for the cassandra-create-schema job." instance=TestCassandraDependencies namespace=
time="2019-11-21T11:44:19Z" level=info msg="Cassandra hostname not specified. Using 'cassandra' for the cassandra-create-schema job." instance=TestCassandraDependencies namespace=
time="2019-11-21T11:44:19Z" level=error msg="Failed to create certificates" out="bash: /foo: No such file or directory\n" script=/foo
--- FAIL: TestExtractSecretsToFile_Err (0.00s)
    elasticsearch_secrets_test.go:114: 
        	Error Trace:	elasticsearch_secrets_test.go:114
        	Error:      	An error is expected but got nil.
        	Test:       	TestExtractSecretsToFile_Err
--- FAIL: TestWriteToWorkingDir (0.00s)
    elasticsearch_secrets_test.go:164: 
        	Error Trace:	elasticsearch_secrets_test.go:164
        	Error:      	Error message not equal:
        	            	expected: "mkdir /foo: permission denied"
        	            	actual  : "open /foo: is a directory"
        	Test:       	TestWriteToWorkingDir
    elasticsearch_secrets_test.go:164: 
        	Error Trace:	elasticsearch_secrets_test.go:164
        	Error:      	An error is expected but got nil.
        	Test:       	TestWriteToWorkingDir
FAIL
coverage: 91.5% of statements
FAIL	github.com/jaegertracing/jaeger-operator/pkg/storage	1.353s
ok  	github.com/jaegertracing/jaeger-operator/pkg/strategy	1.048s	coverage: 99.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/upgrade	0.020s	coverage: 84.4% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/util	0.026s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/version	0.030s	coverage: 57.1% of statements
FAIL
make: *** [Makefile:81: unit-tests] Error 1
Failed to build the operator.
```

Removing the test source file allows me to move forward and the basic build works.

For the e2e tests, minikube fails with:

```
# ./.ci/start-minikube.sh
+ sudo apt-get update
sudo: apt-get: command not found
+ export MINIKUBE_VERSION=v1.0.0
+ MINIKUBE_VERSION=v1.0.0
+ export KUBERNETES_VERSION=v1.14.0
+ KUBERNETES_VERSION=v1.14.0
++ command -v minikube
+ MINIKUBE=/usr/local/bin/minikube
+ sudo mount --make-rshared /
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
mount: /: permission denied.
```

**Comment by jpkrohling** [comment]
cc @kevinearls

**Comment by jpkrohling** [comment]
Just came across this, which might help us while we don't have a builder image: 
https://github.blog/changelog/2019-11-04-github-actions-adds-dependency-caching/

**Comment by jpkrohling** [comment]
The new caching mechanism isn't for us, apparently:

> ##[warning]Cache size of ~3342 MB (3504734861 B) is over the 400MB limit, not saving cache.

**Comment by rashmi-ibm** [comment]
I am trying to build jaegar-operator on a Power ppc64le system. The build is successful but I am getting the same error as above for test failure.

time="2020-02-04T03:42:29-05:00" level=info msg="Cassandra hostname not specified. Using 'cassandra' for the cassandra-create-schema job." instance=TestCassandraCreateSchemaInvalidTimeout namespace=
time="2020-02-04T03:42:29-05:00" level=info msg="Cassandra keyspace not specified. Using 'jaeger_v1_test' for the cassandra-create-schema job." instance=TestCassandraCreateSchemaInvalidTimeout namespace=
time="2020-02-04T03:42:29-05:00" level=error msg="Failed to parse cassandraCreateSchema.timeout to time.duration. Using '120s' by default." error="time: unknown unit mm in duration 3mm" instance=TestCassandraCreateSchemaInvalidTimeout namespace= timeout=3mm
time="2020-02-04T03:42:29-05:00" level=info msg="Datacenter not specified. Using 'test' for the cassandra-create-schema job." instance=TestCassandraDependencies namespace=
time="2020-02-04T03:42:29-05:00" level=info msg="Mode not specified. Using 'prod' for the cassandra-create-schema job." instance=TestCassandraDependencies namespace=
time="2020-02-04T03:42:29-05:00" level=info msg="Cassandra hostname not specified. Using 'cassandra' for the cassandra-create-schema job." instance=TestCassandraDependencies namespace=
time="2020-02-04T03:42:29-05:00" level=info msg="Cassandra keyspace not specified. Using 'jaeger_v1_test' for the cassandra-create-schema job." instance=TestCassandraDependencies namespace=
time="2020-02-04T03:42:29-05:00" level=error msg="Failed to create certificates" out="bash: /foo: No such file or directory\n" script=/foo
--- FAIL: TestExtractSecretsToFile_Err (0.00s)
    elasticsearch_secrets_test.go:114:
                Error Trace:    elasticsearch_secrets_test.go:114
                Error:          An error is expected but got nil.
                Test:           TestExtractSecretsToFile_Err
--- FAIL: TestWriteToWorkingDir (0.00s)
    elasticsearch_secrets_test.go:164:
                Error Trace:    elasticsearch_secrets_test.go:164
                Error:          Error message not equal:
                                expected: "mkdir /foo: permission denied"
                                actual  : "open /foo: is a directory"
                Test:           TestWriteToWorkingDir
    elasticsearch_secrets_test.go:164:
                Error Trace:    elasticsearch_secrets_test.go:164
                Error:          An error is expected but got nil.
                Test:           TestWriteToWorkingDir
FAIL
coverage: 92.5% of statements
FAIL    github.com/jaegertracing/jaeger-operator/pkg/storage    1.808s
ok      github.com/jaegertracing/jaeger-operator/pkg/strategy   0.087s  coverage: 97.8% of statements
?       github.com/jaegertracing/jaeger-operator/pkg/tracing    [no test files]
ok      github.com/jaegertracing/jaeger-operator/pkg/upgrade    0.086s  coverage: 84.3% of statements
ok      github.com/jaegertracing/jaeger-operator/pkg/util       0.046s  coverage: 93.7% of statements
ok      github.com/jaegertracing/jaeger-operator/pkg/version    0.069s  coverage: 57.1% of statements
FAIL
make: *** [unit-tests] Error 1
[ jaeger-operator]#

**Comment by jpkrohling** [comment]
Looks like you are running the tests as root, which might explain why the test is succeeding in creating the directory and thus, failing the test.

**Comment by jpkrohling** [comment]
I'm closing this, an experiment has shown that this wouldn't bring a huge benefit, as GitHub seems to be caching the go modules already.
