### ISSUE TITLE
Defining podAntiAffinity for Jaeger Collector

### ISSUE THREAD

**Issue by shubhanshus** [jaegertracing/jaeger-operator#784]
I am looking for correct place where I can define the podAntiAffinity for the Jaeger Collector and Jaeger Ingester. Normally this is defined with the deployment strategy. But, I am unable to figure out where would my antiAffinity code fit in with the Jaeger Operator. Can someone point me to the correct location. Thanks in advance. 

Sample Jaeger Collector podAntiAffinity config 
```
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - jaeger-collector

**Comment by jpkrohling** [comment]
This is documented here:
https://www.jaegertracing.io/docs/1.15/operator/#finer-grained-configuration
