### ISSUE TITLE
Provide the ability to disable specific deployments with a Jaeger-operator based deployment

### ISSUE THREAD

**Issue by trogo** [jaegertracing/jaeger-operator#785]
The jaeger-operator accepts a set of strategies and spins up deployments based on some assumptions.   It is possible that in the case of multi-tenant deployments, there will be parts of the deployment that happen in one K8s cluster and some parts in another K8s cluster.  The ability to disable some deployments would be useful.
Example with Streaming strategy.  

`Cluster1:  Agent, Collector `--> ` (Kafka Broker) `-->`Cluster2: -->Ingester, Query Engine`

In this instance there's no need for the Query engine and Ingester to run in Cluster1 and for collector or agent to run in Cluster 2.  
Right now the workaround is to set replicas to 0 for deployments that are not needed.  The deployment still shows up but no resources are allocated.   Example below

```
 NAME                                         DESIRED   CURRENT   READY   AGE

replicaset.apps/jaeger-operator-6d6cc86d89    1         1         1       14d
replicaset.apps/pmonit-collector-7f6f7f575b   1         1         1       6d8h
replicaset.apps/pmonit-ingester-69bdf975b7    0         0         0       6d8h
replicaset.apps/pmonit-query-84dd6d75f6       0         0         0       6d8h
```

However it would be useful if the yaml provided a single line `disable: true` to disable a specific deployment.  
```apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: pmonit
  namespace: monitoring
spec:
  strategy: streaming
  agent:
    replicas: 0
    strategy: DaemonSet
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 1
  collector:
    replicas: 0 <----------- Used as workaround
    disable: true <--------- New field
    image: jaegertracing/jaeger-collector:latest
    imagePullPolicy: Always```

**Comment by objectiser** [comment]
Although individual `enabled` properties could be added to each component, wondering whether different `strategy` values might work?

For example, if someone wants agent injection in a particular cluster, but referencing a collector in another cluster, that could be achieved using an `agent` strategy. Similarly for your streaming scenario, we could offer the variants `streaming-producer` and `streaming-consumer`?

It might avoid a user having to understand the implications of enabling/disabling the individual components.

**Comment by trogo** [comment]
It would work but it might lead to proliferation of strategies and as the deployments evolve and possibly get more complex i'm not sure if the number of strategies can keep up with the desired deployment models.

**Comment by jpkrohling** [comment]
@trogo, I think your workaround is actually clever and simple enough for people to figure out what's going on if they see no pods running for a given deployment. Is the existence of the deployment causing you any troubles?

**Comment by objectiser** [comment]
@trogo Beyond the three I've mentioned, could you list other scenarios that you think would need to be handled?

**Comment by trogo** [comment]
> @trogo, I think your workaround is actually clever and simple enough for people to figure out what's going on if they see no pods running for a given deployment. Is the existence of the deployment causing you any troubles?

@jpkrohling   
No functional issues from it but i would still call it a workaround and a bit of an eyesore to see deployments with 0 replicas.

**Comment by trogo** [comment]
> Although individual `enabled` properties could be added to each component, wondering whether different `strategy` values might work?
> 
> For example, if someone wants agent injection in a particular cluster, but referencing a collector in another cluster, that could be achieved using an `agent` strategy. Similarly for your streaming scenario, we could offer the variants `streaming-producer` and `streaming-consumer`?
> 
> It might avoid a user having to understand the implications of enabling/disabling the individual components.

@objectiser 
1.  `streaming-producer` and `streaming-consumer` - discussed
2.  `collectorless` K8S - discussed
3.   `collector-only` . (Run the collector in an independent K8S cluster and push to backend storage.   Here also we could use Kafka as a streaming to push into storage or a direct elasticsearch)
4.   `agentless` (Clients directly sending to a collector)
5.  `agentless and collectorless` (Clients directly sending to a kafka stream) -> This has been discussed on some threads here but not implemented yet.

**Comment by jpkrohling** [comment]
>  i would still call it a workaround and a bit of an eyesore to see deployments with 0 replicas.

Not quite sure about that: a deployment with 0 desired replicas is a very explicit decision and keeps all other parts simple: one doesn't need to read the docs to understand what `streaming-producer` means and how it differs from `streaming`. There's no room for inconsistencies as well: if you specify `collectorless` as the strategy, but then you go on to specify some `collector` options like `Replicas: 1`, what should happen?

`agentless` is also kinda strange, as you can achieve an "agentless" deployment by leaving the agent strategy with `sidecar` but leaving your deployments without the annotation that tells the Operator to inject an agent.

To the best of my knowledge, there's no client out there that can send spans directly to Kafka. You can certainly do so by yourself, but it's not something we even document, so, not sure we should consider it.

All in all, I have the feeling that this is an edge case with a simple workaround. I'll leave this issue open so that other people can give their opinions as well. If more people are interested in this, we should certainly consider implementing it.

**Comment by jpkrohling** [comment]
I'm closing this, as we haven't heard any further requests about disabling components individually and I still think that setting `Replicas` to `0` is a valid solution. In fact, I've since seen it elsewhere in a different context. @aditya-konarde could probably confirm that :-)
