### ISSUE TITLE
Exec command for jaeger Pod (all-in-one)

### ISSUE THREAD

**Issue by emailtovamos** [jaegertracing/jaeger-operator#786]
Can someone give me an example `exec` command for a jaeger Pod (all-in-one)? 
I tried doing `kubectl exec <pod-name> df` according to [this](https://stackoverflow.com/questions/53200828/how-to-identify-the-storage-space-left-in-a-persistent-volume-claim) but got response: 
```
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"df\": executable file not found in $PATH"
```

No matter what variety of the command I give I always get error. I just want to exec into the Pod and see the storage space.

**Comment by objectiser** [comment]
Hi @emailtovamos - the docker images are derived [from scratch](https://github.com/jaegertracing/jaeger/blob/master/cmd/all-in-one/Dockerfile#L4), so do not provide a shell.

**Comment by jpkrohling** [comment]
@emailtovamos, the Jaeger pods do not make use of local storage other than when using the badger as the storage backend. In that case, you should be using a volume that is managed externally. In that case, you can probably obtain the free space information from the actual storage provider or, in the worst case, mount the volume in a second pod in read-only mode.
