### ISSUE TITLE
BadRequest on container name in operator log  on fresh install

### ISSUE THREAD

**Issue by treyhyde** [jaegertracing/jaeger-operator#787]
I'm trying to figure out why my DaemonSet agents are not actually starting which may or may not be related to this issue.   Noticed in the operator logs this BadRequest.   This is 

>> $ kubectl logs jaeger-operator-6fbb5db94c-6crsm  -n observability
Error from server (BadRequest): a container name must be specified for pod jaeger-operator-6fbb5db94c-6crsm, choose one of: [jaeger-operator jaeger-agent]

``  Image:       jaegertracing/jaeger-agent:1.15.1``

If this is referring to the container-name of the DaemonSet that operator is trying to create ....
```Pod Template:
  Labels:           app=jaeger
                    app.kubernetes.io/component=agent
                    app.kubernetes.io/instance=es-production
                    app.kubernetes.io/managed-by=jaeger-operator
                    app.kubernetes.io/name=es-production-agent
                    app.kubernetes.io/part-of=jaeger
  Annotations:      linkerd.io/inject: disabled
                    prometheus.io/port: 14271
                    prometheus.io/scrape: true
                    sidecar.istio.io/inject: false
  Service Account:  es-production
  Containers:
   jaeger-agent-daemonset:
    Image:       jaegertracing/jaeger-agent:1.15.1
    Ports:       5775/UDP, 5778/TCP, 6831/UDP, 6832/UDP, 14271/TCP
    Host Ports:  5775/UDP, 5778/TCP, 6831/UDP, 6832/UDP, 14271/TCP
    Args:
      --reporter.grpc.host-port=dns:///es-production-collector-headless.observability:14250
      --reporter.type=grpc
    Liveness:     http-get http://:14271/ delay=5s timeout=1s period=15s #success=1 #failure=5
    Readiness:    http-get http://:14271/ delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
```

**Comment by jpkrohling** [comment]
You should specify `-c jaeger-operator` to the `kubectl logs` command. We now have two containers as part of the Jaeger Operator deployment, one being the Jaeger Agent as a sidecar, to receive traces from the operator itself.

If you find a documentation place that needs updating, let us know!

**Comment by treyhyde** [comment]
well, darn, that wasn't the log from the pod, that was a warning from the kube... totally went right over my head, sorry.
