### ISSUE TITLE
Is all-in-one with badger recommended for production cases?

### ISSUE THREAD

**Issue by emailtovamos** [jaegertracing/jaeger-operator#795]
I have had problems with using badger mainly it not cleaning data well enough. You can see it here: https://github.com/jaegertracing/jaeger/issues/1916

It is mentioned in the website that it is `experimental`. So does that mean it is not recommended in production systems yet? 

I am going for production soon and wondering if I should explore more of the other options and leave badger behind? Thanks.

**Comment by objectiser** [comment]
Hi @emailtovamos, as you have indicated there are still some areas that need further work, so it is probably best not to use in production yet.

**Comment by emailtovamos** [comment]
Ok thanks. Which one should I use for production then? Elasticsearch or Cassandra? I have no experience in either of these and just want to go for the one which is easier to implement/maintain if all other things are similar.

**Comment by jpkrohling** [comment]
Both are good choices, we typically recommend to go with the one you are more comfortable in maintaining. Both require maintenance work, so, we do recommend learning about one of them. Right now, the community seems to prefer Elasticsearch over Cassandra.

**Comment by emailtovamos** [comment]
Thanks! 
So there is `external` and `self-provisioned` Elasticsearch options described [here](https://www.jaegertracing.io/docs/1.15/operator/#elasticsearch-storage). 
Which one is easier to setup? None of them seem straight forward to me.

**Comment by pavolloffay** [comment]
Self provisioned is only for OpenShift. Not sure if you are on OpenShift :)

**Comment by jpkrohling** [comment]
Looks like this has been answered already. Closing.
