### ISSUE TITLE
(minor) In `main.go` use proper context.

### ISSUE THREAD

**Issue by pavelnikolov** [jaegertracing/jaeger-operator#8]
Use `context.Background()` in https://github.com/jaegertracing/jaeger-operator/blob/master/cmd/jaeger-operator/main.go#L37
instead of `context.TODO(). 
The TODO context is almost never the right context to use.

**Comment by bhavin192** [comment]
I think this got solved by commit https://github.com/jaegertracing/jaeger-operator/commit/764e981334120c402b2c2e9d61c425ed62c0432a

**Comment by jpkrohling** [comment]
Good catch, @bhavin192! I'm closing this one as a result.
