### ISSUE TITLE
Kafka auto provisioning is not working on OpenShift

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#815]
The deploy/examples/auto-provision-kafka.yaml example does not work on OpenShift. After deployment the zookeeper pods fail to start with the error:

```
Detected Zookeeper ID 1
mkdir: cannot create directory '/var/lib/zookeeper/data': Permission denied
/opt/kafka/zookeeper_run.sh: line 25: /var/lib/zookeeper/data/myid: No such file or directory
Starting Zookeeper with configuration:

    the directory where the snapshot is stored.
    dataDir=/var/lib/zookeeper/data
    clientPort=21810

```

**Comment by jpkrohling** [comment]
Reported by @kevinearls. Blocked by https://github.com/strimzi/strimzi-kafka-operator/issues/2281

**Comment by jpkrohling** [comment]
Looks like this happens only when running in the `default` namespace. @kevinearls I just tried deploying in the `observability` namespace, and I got all Kafka components to deploy correctly, but got some Elasticsearch problems, as I couldn't get a proper configuration to make the collector to talk to an Elasticsearch. Would you be able to give it a try ?

**Comment by pavolloffay** [comment]
I am closing this as it works except `default` namespace. 

Feel free to reopen if we think that we should fix it - however it seems more like an OCP issue.
