### ISSUE TITLE
Jaeger Operator not deploying Jaeger components

### ISSUE THREAD

**Issue by arugifa** [jaegertracing/jaeger-operator#818]
I recently noticed that my Jaeger Operator (version **1.14.0**) doesn't deploy my Jaeger CRD definition anymore, i.e., no Jaeger components are created (collector, query). However, the Cassandra pods get created, and the Cassandra Schema job get executed.

Having a look into the operator's logs, I can see a lot of lines looking like that:

```
time="2019-12-05T16:14:53Z" level=error msg="failed to apply the changes" error="failed to handler dependencies: timed out waiting for the condition" execution="2019-12-05 16:12:53.593407803 +0000 UTC" instance=jaeger namespace=tracing
```

Looking inside the operator's source code, I couldn't find out where this error was coming from. Would you have an idea of what is happening?

I deploy Jaeger Operator with the official Helm chart (version **2.10.2**). And here is my Jaeger CRD:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  labels:
    app.kubernetes.io/name: jaeger
    helm.sh/chart: jaeger-0.1.0
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
spec:
  collector:
    image: jaegertracing/jaeger-collector:1.14
    replicas: 1
    resources:
      limits:
        cpu: 1
        memory: 154Mi
      requests:
        cpu: 1
        memory: 128Mi
    tolerations:
      - effect: NoSchedule
        key: CriticalAddonsOnly
        operator: Exists
  ingress:
    enabled: false
  query:
    image: jaegertracing/jaeger-query:1.14
    replicas: 1
    resources:
      limits:
        cpu: 0.1
        memory: 128Mi
      requests:
        cpu: 0.01
        memory: 64Mi
    tolerations:
      - effect: NoSchedule
        key: CriticalAddonsOnly
        operator: Exists
  storage:
    cassandraCreateSchema:
      datacenter: dc1
      mode: test
    options:
      cassandra:
        keyspace: jaeger_v1_dc1
        servers: jaeger-cassandra.tracing.svc.cluster.local
    type: cassandra
  strategy: production
```

Once created on Kubernetes, it then looks like that (`kubectl get jaeger jaeger -o yaml`):

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  creationTimestamp: "2019-12-05T15:35:18Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jaeger
    helm.sh/chart: jaeger-0.1.0
    jaegertracing.io/operated-by: tracing.jaeger-operator
  name: jaeger
  namespace: tracing
  resourceVersion: "269092844"
  selfLink: /apis/jaegertracing.io/v1/namespaces/tracing/jaegers/jaeger
  uid: d75eeec1-1774-11ea-a962-0a82c62d427e
spec:
  agent:
    options: {}
    resources: {}
  allInOne:
    options: {}
    resources: {}
  collector:
    image: jaegertracing/jaeger-collector:1.14
    options: {}
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: 154Mi
      requests:
        cpu: "1"
        memory: 128Mi
    tolerations:
    - effect: NoSchedule
      key: CriticalAddonsOnly
      operator: Exists
  ingester:
    options: {}
    resources: {}
  ingress:
    enabled: false
    openshift: {}
    resources: {}
  query:
    image: jaegertracing/jaeger-query:1.14
    options: {}
    replicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    tolerations:
    - effect: NoSchedule
      key: CriticalAddonsOnly
      operator: Exists
  resources: {}
  sampling:
    options: {}
  storage:
    cassandraCreateSchema:
      datacenter: dc1
      mode: test
    dependencies:
      resources: {}
    elasticsearch:
      storage: {}
    esIndexCleaner:
      resources: {}
    esRollover:
      resources: {}
    options:
      cassandra:
        keyspace: jaeger_v1_dc1
        servers: jaeger-cassandra.tracing.svc.cluster.local
    type: cassandra
  strategy: production
  ui:
    options: {}
status:
  version: ""
```

**Comment by jpkrohling** [comment]
@arugifa, this error is being returned from this code:

https://github.com/jaegertracing/jaeger-operator/blob/bfd54b350b5f7b933066bc3c26f4ea6d02d49df7/pkg/controller/jaeger/jaeger_controller.go#L285-L288

And here are the dependencies related to Cassandra:

https://github.com/jaegertracing/jaeger-operator/blob/bfd54b350b5f7b933066bc3c26f4ea6d02d49df7/pkg/storage/cassandra_dependencies.go#L56-L115

The Operator will wait for a success condition from all the dependencies before allowing the remaining of the components to be created. In this case, the condition is the batch job to be in "succeeded" state:

https://github.com/jaegertracing/jaeger-operator/blob/bfd54b350b5f7b933066bc3c26f4ea6d02d49df7/pkg/controller/jaeger/dependencies.go#L98-L104

If you start your operator with the logging set to debug, you should be able to see which specific dependency is blocking the execution. You can set the log level via the `--log-level=debug` flag here:

https://github.com/jaegertracing/jaeger-operator/blob/bfd54b350b5f7b933066bc3c26f4ea6d02d49df7/deploy/operator.yaml#L23

If you can't figure out why the dependency isn't succeeding, let us know and post both the debug log from the step above, as well as the log from the pod that is being waited for.

**Comment by arugifa** [comment]
Thanks for your quick and detailed answer @jpkrohling 🙌 

After activating debug logs on the Operator, I was able to see A LOT of lines like:

```shell
time="2019-12-06T16:45:25Z" level=debug msg="Waiting for dependency to complete" name=jaeger-cassandra-schema-job namespace=tracing
```

Which was making sense after your answer.

I then looked at the logs inside the Cassandra Schema job, and saw lot of errors like:

```python
Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 2443, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/usr/bin/cqlsh.py", line 2421, in main
    encoding=options.encoding)
  File "/usr/bin/cqlsh.py", line 485, in __init__
    load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/policies.py", line 417, in __init__
socket.gaierror: [Errno -2] Name or service not known
Cassandra is still not up at jaeger-cassandra.tracing.svc.cluster.local. Waiting 1 second.
```

At this point, I noticed that deployment of Jaeger components (collector + query) was SOMETIMES working. And looking into the Cassandra Schema job, I could see the job needed up to **119s** to complete:

```shell
$ kub describe job jaeger-cassandra-schema-job
Name:                     jaeger-cassandra-schema-job
...
Duration:                 119s
Active Deadline Seconds:  120s
...
```

My Cassandra nodes seem to need more than **120s** to bootstrap sometimes, which is causing the Cassandra Schema job to fail. Which is blocking creation of Jaeger components (as you said).

I see this value is hardcoded:

https://github.com/jaegertracing/jaeger-operator/blob/bfd54b350b5f7b933066bc3c26f4ea6d02d49df7/pkg/storage/cassandra_dependencies.go#L53-L54

I will propose a Pull Request next week to be able to configure this value :)

Thanks again. And have a nice weekend 👍
