### ISSUE TITLE
change jaeger-collector from tcp to udp

### ISSUE THREAD

**Issue by jdambly-ns** [jaegertracing/jaeger-operator#821]
I'm using the jaegar operator on baremetal in conjunction with metallb, and I want to use UDP instead of the default TCP, but I don't see a way to do this. Is this supported in the operator?

**Comment by jpkrohling** [comment]
I have a few questions for you:

1. did you mean "Agent" instead of "Collector"? There's no support for listening via UDP ports in the Collector, only in the Agent.
1. what do you mean "using Jaeger Operator on bare metal"?

**Comment by jpkrohling** [comment]
> MetalLB is a load-balancer implementation for bare metal Kubernetes clusters, using standard routing protocols.
https://metallb.universe.tf/

Makes more sense now, forget the second question :)

**Comment by jdambly-ns** [comment]
> I have a few questions for you:
> 
> 1. did you mean "Agent" instead of "Collector"? There's no support for listening via UDP ports in the Collector, only in the Agent.

I'm confused because when I fire up the jaegar agent it's trying to connect to udp port 6831 and 6832, but I don't see these ports open on any k8s serivce, any idea what I am doing wrong here?

here is what my agent looks like
![image](https://user-images.githubusercontent.com/23508331/70572613-f7fd5900-1b54-11ea-93b5-8e6da8cd03ee.png)

**Comment by jpkrohling** [comment]
The Agent indeed uses UDP, the Collector doesn't. Perhaps the illustration on https://www.jaegertracing.io/docs/1.15/architecture/ could help you understand what is used where.

**Comment by jdambly-ns** [comment]
that has cleared thing up thanks
