### ISSUE TITLE
Unable to set KEYPSPACE environment in cassandraCreateSchema 

### ISSUE THREAD

**Issue by ssoerensen** [jaegertracing/jaeger-operator#822]
The create cassandra schema supports setting a KEYSPACE environment variable, it seems logical that this can be done in the `cassandraCreateSchema`. However it does not have any affect. this could be nice to have if for example datacenter name contains dashes instead of underscore

**Comment by jpkrohling** [comment]
Would you like to contribute this feature? It's probably just a matter of changing this func:

https://github.com/jaegertracing/jaeger-operator/blob/4ae96a01e18b1c3d1122cde66d8995992a3f5765/pkg/storage/cassandra_dependencies.go#L14-L116

**Comment by arpitjindal97** [comment]
I have created a Pull Request for the same #837
