### ISSUE TITLE
Error cleaning orphaned deployment

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#823]
While running the e2e tests in OpenShift, I noticed that some errors related to the cleaning of orphaned deployments (ie, deployments with an Agent pointing to a non-existing Jaeger Collector). I was able to reproduce it on an OpenShift 4.2 cluster using the manifests generated by a previous e2e test:

```
$ kubectl apply -f deploy/test/namespace-manifests.yaml
rolebinding.rbac.authorization.k8s.io/jaeger-operator created
role.rbac.authorization.k8s.io/jaeger-operator created
serviceaccount/jaeger-operator created
deployment.apps/jaeger-operator created
```

Once the operator's pod is up, the following can be seen:
```
time="2019-12-10T09:31:12Z" level=error msg="error cleaning orphaned deployment" error="deployments.apps is forbidden: User \"system:serviceaccount:orphaneddeployment:jaeger-operator\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope"
time="2019-12-10T09:31:12Z" level=error msg="error cleaning orphaned deployment" error="jaegers.jaegertracing.io is forbidden: User \"system:serviceaccount:orphaneddeployment:jaeger-operator\" cannot list resource \"jaegers\" in API group \"jaegertracing.io\" at the cluster scope"
```

The full logs are here: https://paste.centos.org/view/70ba245f

This might be an issue only in the `role.yaml` used by the tests, meaning that it might not be affecting real operator deployments.

cc @kevinearls, @rubenvp8510

**Comment by jpkrohling** [comment]
I think we fixed this one already, right @rubenvp8510  ?

**Comment by rubenvp8510** [comment]
Yes
