### ISSUE TITLE
Removing sidecar container on annotations removal

### ISSUE THREAD

**Issue by mumrau** [jaegertracing/jaeger-operator#833]
Hello,

I might have missed out on such documentation, but I haven't found anything for the automatic removal of the innjected sidecar, is there such a feature? 
Would we like to have it implemented or not?

I am talking on the operator reacting to the removal of an annotation, not on the Jaeger CRD removal.

Looking forward to a discussion!

**Comment by jpkrohling** [comment]
It *should* work, done as part of #443 (or any of the follow-up PRs). If it's not working as intended, please run the operator with debug-level logging and report back.

cc @rubenvp8510

**Comment by mumrau** [comment]
It didn't work properly on our end. I didn't see any documentation, that's why I didn't dig further. I'll do so, and come back with debug logs later on, after the christmas break.
Thank you for the reactivity by the way!

**Comment by jpkrohling** [comment]
Alright! I'm adding "needs-info", as we can't proceed without some debug logs, or some more information on how to reproduce.

**Comment by mumrau** [comment]
I upgarded since then, but I bleieve this is working as intended, I don't have the logs from back then, but I sadly couldn't reproduce.
