### ISSUE TITLE
How can I get all the span data in the memory for the jaeger all in one back end

### ISSUE THREAD

**Issue by liuzijuan123** [jaegertracing/jaeger-operator#834]
I need get all the span  data in the memory for the jaeger all in one back end, How can I get that? 
Thank you very much.

**Comment by jpkrohling** [comment]
You can use the Jaeger Query for that: https://www.jaegertracing.io/docs/1.16/apis/#trace-retrieval-apis

**Comment by jpkrohling** [comment]
I'm closing this issue as I think the link above answers your question, but feel free to reopen if you have further questions.
