### ISSUE TITLE
Document that `--config-file` shouldn't be used with the operator

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#84]
Using an external configuration file mean that the Jaeger instance has to be manually restarted, instead of letting the operator handle the configuration change.

We need to document this behavior and recommendation, but also point out that this might change soon, once on-the-fly updates are supported.

See https://github.com/jaegertracing/jaeger/issues/1058

**Comment by yurishkuro** [comment]
@jpkrohling do we still need this given that #2188 implements time-based reloading?

**Comment by jpkrohling** [comment]
Good question. I think the basic idea is still valid ("a config file shouldn't be used with the operator"), as the Operator will add configuration options as flags based on the environment (mTLS when possible, ES URL for auto-provisioned storage, ...) and using `--config-file` might cause confusion when trying to figure out the effective configuration for an instance.
