### ISSUE TITLE
CreatedAt date/time not correct in csv

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#843]
For example, the [1.16. csv](https://github.com/jaegertracing/jaeger-operator/blob/90b4053280fb230f99da4a6be5b40091d754ae43/deploy/olm-catalog/jaeger-operator/1.16.0/jaeger-operator.v1.16.0.clusterserviceversion.yaml#L68) has a createdAt date in September, while the release was made in December.

**Comment by kevinearls** [comment]
@pavolloffay This can be closed.  This file doesn't even exist anymore.
