### ISSUE TITLE
Add support for TLS on ingress

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#85]
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

**Comment by objectiser** [comment]
> So, we would basically just need to accept a secretName?

Yes that is my understanding.

> Question: should it be service-name (as the other key names in this CRD), or serviceName, to follow the naming scheme for the Ingress object?

I think it is better to stick with one convention in the operator CRD - so `secret-name`. However, if the general convention for CRDs is lower camel case, then we should switch to that asap.

**Comment by objectiser** [comment]
From a quick look it appears lower camel case is the more common - can't actually find examples using hyphens - so we should consider changing.

**Comment by jpkrohling** [comment]
What a rookie mistake on my part :(

**Comment by cedrickring** [comment]
I'll grab this one 👍

**Comment by jpkrohling** [comment]
Go ahead, @cedrickring. It's yours!
