### ISSUE TITLE
Jaeger tags for injected agent are only added if a single container is present

### ISSUE THREAD

**Issue by TBBle** [jaegertracing/jaeger-operator#863]
I'm specifically looking at `func container` in https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/inject/sidecar.go.

The flow *appears* to be intended to inject a bunch of tags from the pod info, and *if a single container is present*, include a tag about the container.

However, the entire set of tags is only added in a single-container setup.

This looks like a trivial mistake in #648.

**Comment by TBBle** [comment]
I don't have an immediate fix for it, but I suspect the 'only one container' logic will also fail if called from `UpdateSidecar`, as it the jaeger-agent side-car will be seen as a second container.

**Comment by jpkrohling** [comment]
Nice catch!
