### ISSUE TITLE
Inject sidecar agent with true breaks if Jaeger name changes

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#899]
Jaeger operator uses annotation `sidecar.jaegertracing.io/inject: true`  to inject an agent to a deployment. After the first loop (if the Jaeger instance is found) it changes `true` to `<jaeger-instance-name>`. Therefore if the jaeger instance name is changed the sidecars will not be injected.

**Comment by jpkrohling** [comment]
I think @rubenvp8510 has/had a fix for it, in that he'd look for orphaned deployments from time to time.

**Comment by rubenvp8510** [comment]
I have a routine that checks for orphaned, used autodetect loop for that. I'll check this case.
