### ISSUE TITLE
Jaeger agent can be injected into jaeger instance

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#900]
Jaeger agent can be injected into Jaeger agent or all-in-one deployment which causes deployment failures due to port collisions.

This is not a problem when the inject annotation (`sidecar.jaegertracing.io/inject=true`) is added on deployments, but it can be problematic when the inject annotation is applied on a namespace (https://github.com/jaegertracing/jaeger-operator/pull/897) and the namespace contains Jaeger instance.

**Comment by jpkrohling** [comment]
This is not a problem now, but will become a problem once #897 is merged, right?

**Comment by pavolloffay** [comment]
It is if somebody would use the inject annotation on Jaeger all-in-one deployment or agent deployment.

**Comment by rubenvp8510** [comment]
Is this still an issue? or it was fixed in PR #897 ?

**Comment by pavolloffay** [comment]
It hasn't been. I will be looking into this. 

As part of this ticket I will have some thoughts on how we could exclude specific deployments when the annotation is used on a namespace.
