### ISSUE TITLE
Agent sidecars are not cleared when annotation is deleted from namespace

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#906]
Related to https://github.com/jaegertracing/jaeger-operator/pull/897

Steps to reproduce:
```
# go to default namespace
oc create -f deploy/examples/simplest.yaml
oc create deployment vertx --image=jaegertracing/vertx-create-span:operator-e2e-tests

oc annotate namespace default sidecar.jaegertracing.io/inject=true
oc annotate namespace default sidecar.jaegertracing.io/inject-
```

After these steps the agent is vertx deployment is still injected.

cc) @rubenvp8510

**Comment by pavolloffay** [comment]
Maybe related to https://github.com/jaegertracing/jaeger-operator/issues/905?

**Comment by jpkrohling** [comment]
@rubenvp8510 has this been fixed?

**Comment by jpkrohling** [comment]
@rubenvp8510 has this been fixed?

**Comment by rubenvp8510** [comment]
IIRC yes, I'll verify and let you know so we can close this.
