### ISSUE TITLE
Upstream connect error or disconnect/reset before headers. reset reason: connection termination 

### ISSUE THREAD

**Issue by mooperd** [jaegertracing/jaeger-operator#907]
Hi,

When I try and expose Jaeger via Istio ingress gateway I get the following problem - I thought someone watching here would have an explanation. It's sure confusing the hell outta me! 

https://discuss.istio.io/t/upstream-connect-error-or-disconnect-reset-before-headers-reset-reason-connection-termination/4434

Cheers,

Andrew

**Comment by pavolloffay** [comment]
Moving this to Jaeger operator repository.

**Comment by pavolloffay** [comment]
cc @jpkrohling

**Comment by andye2004** [comment]
> I assume you are deploying jaeger via Jaeger operator right?

@pavolloffay, thanks for responding so quickly. I am using the operator but looking at the official helm charts it's the same issue there so I would assume that this would need fixing in both if the operator is not just pulling the helm charts into its build for distribution?

**Comment by pavolloffay** [comment]
We don't use helm chars in the operator. 

@andye2004 is istio upstream using helm chart to install jaeger? 

Do we know if the issue has been fixed in envoy?

**Comment by andye2004** [comment]
As best I can tell the issue remains open.
