### ISSUE TITLE
Disable Jaeger agent injection via annotation

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#910]
Created from https://github.com/jaegertracing/jaeger-operator/pull/903#discussion_r378925226

PR https://github.com/jaegertracing/jaeger-operator/pull/897 added per namespace injection support for Jaeger agent. 

```
oc annotate namespace project sidecar.jaegertracing.io/inject=true
```

It means that all deployments in that namespace will get jaeger agent injected. 

I am proposing to define a special semantics for annotation `sidecar.jaegertracing.io/inject=false` applied on deployment to disable agent injection. Hence the `false` value means do not inject agent.

Currently a similar behavior could be achieved by a workaround   `sidecar.jaegertracing.io/inject=non-existing-jaeger-instance` on a deployment. This will result in a log entry `No suitable Jaeger instance has been found`.

**Comment by jpkrohling** [comment]
I should have documented this when I first implemented, but I'm quite sure I thought about `false` when the sidecar injection feature was implemented.

On one hand, I think it's great to have an explicit value for `false`, but other than the log message, there's really no difference between what we have today vs. having a special conditional in the code to skip the `#Select()` logic.

One corner case is when having a Jaeger instance named `false`: currently, the Operator will inject a sidecar for the instance `false`. With the special value for `false`, the instance would be able to exist, but no sidecars would be possible to be injected. This case is so improbable to ever exist that I don't even want to spend energy thinking about what's the right thing to do... As @pavolloffay mentioned in IRC, when someone names a Jaeger instance `false`, we can just assume that the internet simply implodes.

**Comment by jpkrohling** [comment]
@jkandasa, @kevinearls, @objectiser, @rubenvp8510, @annanay25, what's your opinion on this? Should we have a special `false` value for the annotation, or is the current behavior good enough? In summary, here are the differences:

1. when having a special value for `false`, we can have better targeted log messages
1. `false` requires documentation and test
1. the current code already assumes the `false` semantics when the annotation's value isn't `true` and the specified value doesn't map to an existing Jaeger instance

**Comment by objectiser** [comment]
@jpkrohling I think it is better to properly support `false`, as otherwise someone could mess things up by creating a Jaeger CR with name `false`.

**Comment by jpkrohling** [comment]
What should we do when someone does create a Jaeger CR with the name `false`? Should we silently delete the CR?

**Comment by kevinearls** [comment]
@jpkrohling I think I agree with @objectiser although I'm not quite sure how to handle the unlikely event someone tries to create a jaeger instance named false?  Do we do anything now if someone uses an invalid name, or does that never actually make it to the operator?

**Comment by objectiser** [comment]
If we handle `false` as an explicit value, before checking for Jaeger instances with the specified name, then it shouldn't matter if someone create a Jaeger instance named false - it wouldn't change the behaviour of the agent sidecar injection.

**Comment by jkandasa** [comment]
@jpkrohling I too support the `false` option.
Istio is also using a similar approach. https://istio.io/docs/setup/additional-setup/sidecar-injection/
They have an additional option too, [More control: adding exceptions](https://istio.io/docs/setup/additional-setup/sidecar-injection/#more-control-adding-exceptions)

**Comment by jpkrohling** [comment]
> it wouldn't change the behaviour of the agent sidecar injection.

If a Jaeger instance is named `false`, then the annotation value is ambiguous, as it may mean "do not inject" or "inject the instance 'false'".

But in all honesty, if someone names their instance `false`, they deserve every pain inflicted on them...
