### ISSUE TITLE
Investigate replacing Routes with Ingress

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#918]
Looking at some OpenShift 4.x docs, I got the impression that regular Kubernetes `Ingress` resources are recognized by OpenShift and used as base for new routes. If that confirms to be true, we can just get rid of the `Route` resource in the Jaeger Operator, keeping `Ingress` for both OpenShift and Kubernetes.

**Comment by objectiser** [comment]
Would need to be sure the upgrade mechanism handled it, so routes were then converted into equivalent ingresses.

**Comment by xmj** [comment]
This would probably also help with the issue that on Openshift, routes ignore the hostnames set for Ingress controllers per https://github.com/jaegertracing/jaeger-operator/issues/135.

**Comment by iblancasa** [comment]
> This would probably also help with the issue that on Openshift, routes ignore the hostnames set for Ingress controllers per #135.

Could you please create a new issue explaining your issue?
