### ISSUE TITLE
Provide client-gen generated code to be used by other Operators

### ISSUE THREAD

**Issue by rareddy** [jaegertracing/jaeger-operator#920]
Working on my operator and trying to enable the support to find available Jaeger instances, I did not find readily usable go client code that Get, List etc. This code can be auto-generated using the `[client-gen](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md)` tool. Locally I did the same to generate some code, however it would be nice have available as part of the Jaeger Operator code.

**Comment by jpkrohling** [comment]
I think it's a great idea. Would you like to give this a try? The OpenTelemetry Operator has a similar structure as Jaeger's and I added this there some time ago. Here's what I think would be required:

Install `client-gen`:
https://github.com/open-telemetry/opentelemetry-operator/blob/4593927867598681b2a13d30012c15ba98b5749c/Makefile#L95-L101

Add the command to `generate.sh`:
https://github.com/open-telemetry/opentelemetry-operator/blob/4593927867598681b2a13d30012c15ba98b5749c/.ci/generate.sh#L43-L55

**Comment by rareddy** [comment]
Yes, I will contribute a PR for this.

**Comment by rareddy** [comment]
https://github.com/jaegertracing/jaeger-operator/pull/921

**Comment by jpkrohling** [comment]
Addressed by #920
