### ISSUE TITLE
Should Jaeger operator CI be testing against jaeger latest?

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#930]
Currently the Jaeger operator CI builds the PR against the most recent stable release of Jaeger.

This protects the Jaeger operator PRs from any issues caused in the Jaeger repo, but also means any changes (intentional or otherwise) are not picked up until doing a release of the operator currently.

Options:
1) Change the `versions.txt` to use `latest` tag for Jaeger repo for all tests.
2) Provide some additional test examples that override the Jaeger images to use the latest tag.

**Comment by pavolloffay** [comment]
+1 on using `latest` in master.

**Comment by jpkrohling** [comment]
I appreciate the idea, but it means that PRs to the operator might fail because someone just merged a PR in Jaeger, breaking existing tests of ours.

IMO, it would probably be better to run nightly builds against `latest`: the job would change versions.txt and run the full suite.

**Comment by objectiser** [comment]
Sounds like a good approach - is it possible to do in GitHub actions, or do we need to setup in jenkins?

**Comment by jpkrohling** [comment]
It should be possible to trigger jobs on schedule:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

**Comment by pavolloffay** [comment]
I understand Juca's concern, but on the other hand using the latest version might have more benefits for us.

It would be good to get `latest` builds more exposed and tested by the community before the release tag pushed to avoid scenarios like this and fix as many issues as possible. It can cause some problems, but it is still much better than release breaking version which was not intended to be breaking. Ultimately we do not want to break APIs so these issues should not occur _often_.

I would be in favor of using `latest` tags in master for both: the operator and jaeger. Our docs on the website (starting with https://github.com/jaegertracing/documentation/pull/370) use tagged versions  but we might still get users experimenting with the latest builds.

**Comment by jpkrohling** [comment]
Let's start with `latest` and see how it goes. I'm afraid applying `latest` to all the PRs will cause uncertainty in our CI builds. If we see that the stability of `latest` is good and that we can easily determine what `latest` is when analyzing a build failure, then I'd be OK in changing everything to use `latest`.

**Comment by pavolloffay** [comment]
Closing, the operator is tested only against tagged version. We don't have use-case to test against Jaeger main/latest.
