### ISSUE TITLE
Operator cannot create resources in other namespaces even in cluster-wide mode

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger-operator#931]
After PR #928 I have not been able to install an operator that works cluster-wide.  It's possible I am not following the updated instructions correctly, but here is what I did:

```
kubectl create namespace observability
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml

kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role.yaml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role_binding.yaml

kubectl create -n observability -f https://gist.githubusercontent.com/kevinearls/0da613ed3c580c5a82d9b2399600bb11/raw/a6b8b684398f8d69e1e38ed62b8d6bebd8b26586/operator.yaml
```

(Note the last line uses my modified version of operator.yaml)

The operator appears to install correctly, but when I do the following:

```
kubectl create namespace simple
kubectl create -f deploy/examples/simplest.yaml --namespace simple
```

I get the following errors in the jaeger operator log.  (Actually I get them repeatedly, as in 1 a second.)

```
E0228 09:04:35.171558       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:observability:jaeger-operator" cannot list resource "secrets" in API group "" at the cluster scope
```

This occurs both on minikube and on Openshift

**Comment by jpkrohling** [comment]
I have a workaround for this, but looks like the problem is underneath our operator, either at the SDK, controller-runtime or perhaps even client-go.

**Comment by jpkrohling** [comment]
There are actually a couple of problems happening here:

1. the cluster role does not include the rules from the regular role, meaning that a role binding has to be created for each namespace in which the operator should create resources
1. when this permission doesn't exist, we hit a problem like #2608

The problem you reported is most likely the first item, so, I'll change the title back to that and create a new one to track the second problem.

**Comment by majidazimi** [comment]
The issue still exists in latest version. I'm using chart 2.21.1 with image 1.22.1, I've set the following options:
```yml
rbac:
  create: true
  clusterRole: true
```
But I still see this log message:
`E0525 08:30:16.437023       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:jaeger-operator:jaeger-operator" cannot list resource "namespaces" in API group "" at the cluster scope`

But when I add `namespaces` to api groups `""`, everything works.
