### ISSUE TITLE
Cannot create crd in v1.17.0

### ISSUE THREAD

**Issue by william-tran** [jaegertracing/jaeger-operator#938]
`kubectl create -n jaeger -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.17.0/deploy/crds/jaegertracing.io_jaegers_crd.yaml`
fails with
...`Example:(*apiextensions.JSON)(nil)}: must only have "properties", "required" or "description" at the root if the status subresource is enabled`

Doing the same with v1.16.0 succeeds.

**Comment by objectiser** [comment]
What version of kubernetes are you running on?

**Comment by julienvey** [comment]
Same problem here, Kubernetes version `v1.11.8`

It looks like the same problem as https://github.com/jetstack/cert-manager/issues/2200

**Comment by jpkrohling** [comment]
@julienvey you might want to use an older version of the Jaeger Operator or, preferable, use a newer version of Kubernetes. Version 1.11 is now 6 versions behind the current (1.17).

**Comment by jpkrohling** [comment]
I'm closing, as this is probably only happening with "old" Kubernetes versions. We do not have an official policy yet about which versions we support, but that's being tracked by #583.
