### ISSUE TITLE
Elasticsearch --es.tags-as-fields.all

### ISSUE THREAD

**Issue by mimol91** [jaegertracing/jaeger-operator#939]
Is it possible to configure ES storage to keep tags as fields? This same way as it's done in AllInOne?

**Comment by pavolloffay** [comment]
Hi @mimol91 yes it is possible. Just supply the option to the storage options https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/all-in-one-with-options.yaml#L10

> This same way as it's done in AllInOne?

IIRC Elasticsearch storage is supported only for production deployment (separate query, collector components). 


I am closing this as it is a question. If there are any issues please re-open.

**Comment by mimol91** [comment]
@pavolloffay Its what I mean, there is no way to set `--es.tags-as-fields.all` for production deployment as ES storage do not accept this param (See: https://github.com/jaegertracing/jaeger-operator/blob/b7ce28f171a416945d881cf7c018280baa4aae01/pkg/storage/elasticsearch.go)

Is it possible to configure ES storage with `--es.tags-as-fields.all`  (Currently its only possible using AllInOne image)

**Comment by pavolloffay** [comment]
Elasticsearch is not supported with `allInOne` strategy. More docs are here https://www.jaegertracing.io/docs/1.17/operator/#production-strategy.

The `--es.tags-as-fields.all` should with Elasticsearch in `production` strategy. The configuration has to be supplied to storage options as I pointed out in my previous comment.

**Comment by pavolloffay** [comment]
Sorry @mimol91 my bad, actually Elasticsearch should work in `allInOne` strategy. This CR shows an example configuration with tags as fields

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: allInOne
  storage:
    type: elasticsearch
    options:
      es:
        # Note: This assumes elasticsearch is running in the "default" namespace.
        server-urls: http://elasticsearch.default.svc:9200
        tags-as-fields:
          all: true
```

**Comment by mimol91** [comment]
Hey.
I dont want to use **allInOne**.
I just miss-interpreted that `tags-as-fields:` can be only used with `allInOne` strategy, but it is working fine with production too.

**Comment by pavolloffay** [comment]
It's working with all strategies which support Elasticsearch storage.

If a backend is supported in a strategy it's fully supported - all options
