### ISSUE TITLE
Expose operator-specific metrics

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#943]
The operator could expose some metrics reflecting the current state of the managed instances. For instance:

```
jaeger_operator_instances_by_strategy{strategy=".spec.strategy"}
jaeger_operator_instances_by_storage{storage=".spec.storage.type"}
jaeger_operator_instances_by_version{version=".status.version"}
jaeger_operator_instances_replicas{component="collector|ingester|query", size=1}
```

The version should always be the same as the operator's, but a discrepancy in this field should help understand whether there was a problem with the upgrade mechanism.

Those gauges should be gathered periodically, as part of the background process launched by the auto-detect mechanism.

**Comment by objectiser** [comment]
@jpkrohling Just a naming comment - as they are related to the jaeger instances, rather than the operator, should they be `jaeger_instances_by_...`?

**Comment by jpkrohling** [comment]
I think the convention is to have the first part to be the "system namespace". In a Prometheus with Jaeger Collector, Jaeger Query and Agent metrics, having the prefix `jaeger_operator` helps to quickly understand where the metric is coming from.

**Comment by objectiser** [comment]
@jpkrohling Sounds reasonable.

**Comment by pavolloffay** [comment]
Can the operator expose operand's metric? For instance the number of collected spans?

**Comment by jpkrohling** [comment]
I think nothing prevents the operator from being a proxy for the operand's metrics, but I think the target audience might be different enough to keep them separated.

What we should do is to create a `ServiceMonitor` for each component, like it's being done by the [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-operator/blob/4593927867598681b2a13d30012c15ba98b5749c/pkg/controller/opentelemetrycollector/reconcile_servicemonitor.go#L43-L70).
