### ISSUE TITLE
Move example e2e tests into a separate CI check

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#967]
Move example e2e tests into a separate CI check so it can be restarted without restarting the whole test suite.

The main motivation is that example tests are sometimes flaky. It should also decrease CI time as examples e2e will be executed in parallel.

https://github.com/jaegertracing/jaeger-operator/blob/master/.github/workflows/e2e-kubernetes.yaml#L9

**Comment by pavolloffay** [comment]
@kevinearls is this something interesting to you?

**Comment by kevinearls** [comment]
@pavolloffay I'd be interested, but I'm not sure what you mean here.  Examples are already split into two parts, do you want to split them into more or is there something else you're looking for?

btw, there is also at least one other issue open on this: #945

**Comment by pavolloffay** [comment]
I want to move them to a different github ACTION file so they can be restarted separately from other job - e2e and basic checks.

**Comment by kevinearls** [comment]
@jpkrohling what do you think?   These test failures on github have certainly been very frustrating and hard to analyze.

**Comment by jpkrohling** [comment]
This means creating 6 different files with pretty much the same contents, right? Sounds wrong, but might be a reasonable compromise. I was really hoping that GitHub would implement the ability to restart individual elements of the matrix...

**Comment by pavolloffay** [comment]
Why 6 files? Could you please list them? 

If we do it right we might need only one additional workflow file like https://github.com/jaegertracing/jaeger-operator/blob/master/.github/workflows/e2e-kubernetes.yam but for only running the examples.

**Comment by jpkrohling** [comment]
Oh, you mean to only move the examples target? I thought you wanted to have each e2e target on its own action. Right now, the problem might be with `examples1`, but last week it was `examples2`, and `cassandra` before that. I'd even dare to say that we had problems with all targets at a given point :-)

**Comment by pavolloffay** [comment]
A finer granularity would be welcome but perhaps we can start with just moving the examples to a separate workflow.

**Comment by iblancasa** [comment]
I think this issue can be closed now, right? :relaxed:

**Comment by pavolloffay** [comment]
thanks @iblancasa
