### ISSUE TITLE
End to end test for examples1 does not pass on CI

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#974]
PR showing failing CI https://github.com/jaegertracing/jaeger-operator/pull/973

@kevinearls would you like to have a look?

**Comment by kevinearls** [comment]
@pavolloffay Sure, please assign this to me

**Comment by pavolloffay** [comment]
Other failures can be seen here https://github.com/jaegertracing/jaeger-operator/actions?query=workflow%3A%22Kubernetes+end-to-end+tests%22

**Comment by kevinearls** [comment]
@pavolloffay This should now be fixed with PR #995
